sonata-project/SonataAdminBundle

Resources/views/Form/form_admin_fields.html.twig
* Move radio/checkbox logic to `choice_widget_expanded`
* Add missing `required` variable handling
=> Update choice related form templates to be closer to the stock ones

Admin/Admin.php, Admin/AdminInterface.php, Controller/CRUDController.php, Datagrid/DatagridInterface.php, Tests/Admin/AdminTest.php, Tests/Admin/PoolTest.php
=> Minor doc and CS fix

CHANGELOG.md, Controller/CRUDController.php, Tests/Controller/CRUDControllerTest.php
| BC breaks?    | Yes, but only if someone puts html code inside `_toString` method which is bad practice anyway. For the majority of use cases: no.
| Fixed tickets | #2637
=> Fix possible XSS vulnerability

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, composer.json
=> Added check if translator service is enabled.

Resources/views/Core/dashboard.html.twig
Sections are not shown if there are no blocks in it visible for user.
=> Changed dasboard's blocks layout with roles

Resources/views/CRUD/base_edit_form.html.twig, Resources/views/CRUD/base_edit_form_macro.html.twig
With this PR, it will be possible to use grids in the groups.
=> Changed tab styles to use the grid

Resources/doc/reference/action_list.rst, Tests/Twig/Extension/SonataAdminExtensionTest.php, Twig/Extension/SonataAdminExtension.php
Hi, 
A little pull request to add the possibility to use a closure in the options associated_property.
=> Add closure possibility on the options associated_property

Resources/translations/SonataAdminBundle.fa.xliff
=> update fa language file

.travis.yml, composer.json
Added a job to test the lower boundary of the specified version ranges. This will probably cause errors.
=> Add test against lowest dependencies

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, Tests/Twig/Extension/SonataAdminExtensionTest.php
=> [Dashboard groups][compiler pass] fixed default value of item.

Resources/doc/reference/form_types.rst
* In admin.yml file for sonata_type_admin, miss 'services' key.
* Add a note and link about where admin.yml comes from.
=> Doc Form types sonata type admin services

Admin/Admin.php, Admin/AdminInterface.php, CHANGELOG.md, Tests/Twig/Extension/SonataAdminExtensionTest.php, Twig/Extension/SonataAdminExtension.php
| BC breaks?    | yes, but just a small (adding `hasRoute` to `AdminInterface`)
| Fixed tickets | #2746, #2740
Note: so many changes are created by phpcsfixer.
=> Do not add item in menu if the route list is disabled or LIST operation is not granted

Resources/views/Core/add_block.html.twig
=> Show icons in admins dropdown headers

Resources/views/Form/form_admin_fields.html.twig
Remove duplicated logic and fix form tabs width.
**Before**
**After**
=> Fix/Refactor form row/label template

DependencyInjection/Configuration.php, Resources/public/Admin.js
I don't find the current ones very sexy ;) What about you ?
**Before**
**After**
=> Update iCheck css

Resources/public/Admin.js, Resources/views/CRUD/base_list.html.twig
Clicking on the minus icon will : 
- hide the corresponding filter line
- uncheck the filter name from the dropdown
=> Add icons to remove filters

Resources/public/Admin.js, Resources/public/App.js
=> Make advanced filters work on ajax loaded content

Resources/doc/cookbook/recipe_custom_action.rst
the getSubject() method does pretty much what is shown in the example.
@koyaan : I followed the recipe, it works well, but I'm not sure why `getSubject()` was not used here. Maybe it did not exist at the time you wrote the recipe ?
=> simplify sample code

CONTRIBUTING.md
Ironically, I'm not making this P.R on 2.3 because I believe no one reads it. Tell me if you feel otherwise.
=> describe contribution workflow

Tests/SonataAdminBundleTest.php
Fixes failing tests since https://github.com/sonata-project/SonataAdminBundle/commit/a5d3d891a3ac054e559471e084a8dc626f2babcb
=> Fix compiler pass tests

Resources/views/Form/form_admin_fields.html.twig
=> Update form_errors block

Resources/public/Admin.js
Change collection count.
bug if we don't want to update but delete/insert.
=> change collection count

Resources/views/Block/block_admin_list.html.twig
Adding translation management for subclass in add links
=> Fix missing translation in admin list block

Admin/Admin.php, Tests/Admin/AdminTest.php
backport #2594 to 2.3 (i just cherry-picked the commit, hope that is ok)
=> backport fix for bundle without vendor name to 2.3

Resources/doc/cookbook/recipe_custom_action.rst
=> Docs custom action: notice about creating template

Resources/views/CRUD/base_edit_form_macro.html.twig
Fix to remove Row calculation in admin 
We want to keep it responsive
=> Remove form row calculation

Resources/public/Admin.js
Related to https://github.com/sonata-project/SonataAdminBundle/pull/2858
The collection counter is not correctly initialized (always equal to 0).
@Soullivaneuh could you tell me if it still works with you doctrine collections with this fix ?
=> Fix collection JS (again)

Resources/doc/reference/action_show.rst, Resources/views/CRUD/base_show.html.twig
=> Added possibility to customize class and box class for groups on show page

Resources/views/CRUD/base_edit_form.html.twig, Resources/views/CRUD/base_list.html.twig
=> Added new twig blocks to easier add new action buttons and change CSS class of filter groups

Resources/doc/reference/action_create_edit.rst
Otherwise, it looks kinda strange :)
=> Add `class` keyword

Resources/public/Admin.js
=> Change the x-editable popover placement from "top" (default) to "auto"

DependencyInjection/SonataAdminExtension.php, Resources/config/security.xml, Security/Handler/RoleSecurityHandler.php, Tests/Security/Handler/RoleSecurityHandlerTest.php
Should fix #2969.
ping @rande @magedan
=> Fix bad service argument on RoleSecurityHandler

Tests/Controller/CRUDControllerTest.php
=> Fixed unit tests in CRUDControllerTest

Datagrid/ListMapper.php, Tests/Datagrid/ListMapperTest.php
Should fix https://github.com/sonata-project/SonataAdminBundle/issues/2967
=> Add missing s to actions type

Tests/Export/ExporterTest.php, composer.json
Fixes test introduced here: https://travis-ci.org/sonata-project/SonataAdminBundle/builds/63627550
=> Fix exporter double quotes assert on tests

DependencyInjection/Configuration.php, Resources/doc/reference/configuration.rst
The jquery.form.js path is broken and a 404 error is issued. This PR corrects this.
=> [Bug] Fix jquery.form.js path

Resources/public/Admin.js
setup_collection_buttons only need to be run once on document scope.
Call it in shared setup register multiple listener on add button in ajax loaded admin and add multiple item in collection on click
=> Fix collection management

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
It's my first time contributing, is everything alright ?
Also, do I have to make another PR for the 2.3 branch (since the fix is in a different file) ?
=> Escape sonata_type_model_autocomplete url in template. Issue #3011.

CHANGELOG.md, Resources/doc/reference/routing.rst, Route/RouteCollection.php, Tests/Route/RouteCollectionTest.php
Adds possibility to define host, schemes, methods and condition to a custom route.
=> Add missing Route constructor parameters to RouteCollection:add method

Resources/translations/SonataAdminBundle.sv_SE.xliff
I've noticed that Swedish translation is missing from SonataAdminBundle, so I created some basic one.
Hope you'll find it good enough.
=> Swedish (sv_SE) translations for SonataAdminBundle translations' domain

Twig/Extension/SonataAdminExtension.php
Permit inline edit of html field in list.
=> Adding html field conversion for xEditable

.travis.yml
See https://github.com/composer/composer/issues/4282#issuecomment-123662454.
=> Global config for GitHub token

Resources/doc/reference/installation.rst, composer.json
=> Make symfony/security-acl as a suggestion

Controller/HelperController.php, Resources/views/CRUD/base_list_field.html.twig, Twig/Extension/SonataAdminExtension.php
A PR to handle date field in x-editable
=> Add date management for X-Editable

Resources/views/CRUD/base_edit.html.twig
A base edit template little contribution
=> Fix minor Twig CS

Block/AdminListBlockService.php, Block/AdminSearchBlockService.php, Block/AdminStatsBlockService.php, Tests/Block/AdminListBlockServiceTest.php, Tests/Block/AdminSearchBlockServiceTest.php, Tests/Block/AdminStatsBlockServiceTest.php, Tests/Block/FakeBlockService.php, composer.json
=> Fix deprecated BlockService::setDefaultSettings usage

Resources/public/css/layout.css
=> Fix issue with sticky header on mobile

Resources/translations/SonataAdminBundle.ar.xliff, Resources/translations/SonataAdminBundle.ca.xliff, Resources/translations/SonataAdminBundle.cs.xliff, Resources/translations/SonataAdminBundle.de.xliff, Resources/translations/SonataAdminBundle.eu.xliff, Resources/translations/SonataAdminBundle.fa.xliff, Resources/translations/SonataAdminBundle.fr.xliff, Resources/translations/SonataAdminBundle.ja.xliff, Resources/translations/SonataAdminBundle.lb.xliff, Resources/translations/SonataAdminBundle.lt.xliff, Resources/translations/SonataAdminBundle.pl.xliff, Resources/translations/SonataAdminBundle.pt_BR.xliff, Resources/translations/SonataAdminBundle.ro.xliff, Resources/translations/SonataAdminBundle.ru.xliff, Resources/translations/SonataAdminBundle.sk.xliff, Resources/translations/SonataAdminBundle.sl.xliff, Resources/translations/SonataAdminBundle.uk.xliff, Resources/translations/SonataAdminBundle.zh_CN.xliff
Use fa icon fa-home instead of &#8962; character.
=> Use same dashboard fa icon as english translation

Resources/translations/SonataAdminBundle.ar.xliff, Resources/translations/SonataAdminBundle.bg.xliff, Resources/translations/SonataAdminBundle.ca.xliff, Resources/translations/SonataAdminBundle.cs.xliff, Resources/translations/SonataAdminBundle.de.xliff, Resources/translations/SonataAdminBundle.en.xliff, Resources/translations/SonataAdminBundle.es.xliff, Resources/translations/SonataAdminBundle.eu.xliff, Resources/translations/SonataAdminBundle.fa.xliff, Resources/translations/SonataAdminBundle.fr.xliff, Resources/translations/SonataAdminBundle.hr.xliff, Resources/translations/SonataAdminBundle.hu.xliff, Resources/translations/SonataAdminBundle.it.xliff, Resources/translations/SonataAdminBundle.ja.xliff, Resources/translations/SonataAdminBundle.lb.xliff, Resources/translations/SonataAdminBundle.lt.xliff, Resources/translations/SonataAdminBundle.nl.xliff, Resources/translations/SonataAdminBundle.no.xliff, Resources/translations/SonataAdminBundle.pl.xliff, Resources/translations/SonataAdminBundle.pt.xliff, Resources/translations/SonataAdminBundle.pt_BR.xliff, Resources/translations/SonataAdminBundle.ro.xliff, Resources/translations/SonataAdminBundle.ru.xliff, Resources/translations/SonataAdminBundle.sk.xliff, Resources/translations/SonataAdminBundle.sl.xliff, Resources/translations/SonataAdminBundle.sv_SE.xliff, Resources/translations/SonataAdminBundle.uk.xliff, Resources/translations/SonataAdminBundle.zh_CN.xliff
Fixed indentation and adding missing translations in the translation files.
=> Normalize translation files

Resources/public/css/layout.css
I need to increase this value because in some cases we got multiple layers in our forms, and I need to be sure thoose sticky bars are going to be always on top.
=> Fix sticky z-index

Admin/Admin.php, Admin/AdminInterface.php, Controller/CRUDController.php, Resources/doc/reference/advanced_configuration.rst, Tests/Controller/CRUDControllerTest.php
This is a first draft, improvements and/or advices are welcome ! :)
=> Add a hook to manage permissions

Resources/public/Admin.js
=> typo fix in css class name

Resources/doc/reference/action_list.rst
=> formatting

Resources/doc/reference/action_list.rst
=> use valid use statements in doc

Search/SearchHandler.php
=> Pager was not initialised

Resources/doc/reference/configuration.rst
i would like to keep this up to date
this is the result from ```app/console config:dump-reference sonata_admin```
ping @Soullivaneuh @rande
=> updated full configuration options

Resources/doc/cookbook/recipe_knp_menu.rst, Resources/doc/reference/preview_mode.rst, Resources/public/Admin.js, Resources/views/CRUD/base_edit_form.html.twig
* Replace some glyphicon with fontawesome icons in docs and js.
* initial hide error icons in edit form
=> replace last glyphicons with font-awesome

Resources/doc/index.rst, Resources/doc/reference/console.rst
demo-url was not working after docker setup
=> doc fix + demo url fix

Resources/doc/cookbook/recipe_sortable_listing.rst
=> add missing inline literal end string

Resources/translations/SonataAdminBundle.de.xliff
the key "flash_lock_error" had no german translation.
=> added german translation

.travis.yml
=> require platform-compatible phpunit version

.travis.yml
Try of https://github.com/composer/composer/issues/4474#issuecomment-145400156.
=> PHPUnit / stable requirement

Resources/doc/reference/action_create_edit.rst, Resources/doc/reference/action_list.rst, Resources/doc/reference/action_show.rst, Resources/doc/reference/advanced_configuration.rst, Resources/doc/reference/architecture.rst, Resources/doc/reference/configuration.rst, Resources/doc/reference/dashboard.rst, Resources/doc/reference/field_types.rst, Resources/doc/reference/form_types.rst, Resources/doc/reference/getting_started.rst, Resources/doc/reference/installation.rst, Resources/doc/reference/search.rst, Resources/doc/reference/troubleshooting.rst
please review this PR
Thank you!
=> documentation review and finetuning

Block/AdminSearchBlockService.php, Resources/public/css/layout.css, Resources/views/Block/block_search_result.html.twig, Resources/views/Core/search.html.twig, Tests/Block/AdminSearchBlockServiceTest.php
This will update the ui of the search result page:
* Result page is better integrated in the admin theme
* Added icon to result list
* Mobile page breaks on different screen sizes
Before:
After:
=> Better search ui

Controller/CRUDController.php
It's a fix from the refacto of `Check routes before redirecting`
=> Fix isGranted check

Tests/Controller/CRUDControllerTest.php
Add some test U to avoid regression
=> Fix isGranted check - tests U

CONTRIBUTING.md
=> Remove some special chars from CONTRIBUTING.md

Controller/HelperController.php
Otherwise persistent filters are always applied
=> [autocomplete] Disable persistent filters

Resources/public/css/styles.css
See https://github.com/sonata-project/SonataAdminBundle/pull/3353
=> Fixed x-editable datepicker

Resources/translations/SonataAdminBundle.ca.xliff
Add missing catalan translations
=> Update catalan translations

Resources/doc/cookbook/recipe_lock_protection.rst
Follow up from https://github.com/sonata-project/SonataAdminBundle/pull/3170#issuecomment-149632675
=> add more config info to Lock Protection cookbook

Tests/Twig/Extension/SonataAdminExtensionTest.php
=> Fixed falling unit tests on php 5.6

Route/RoutesCacheWarmUp.php, Tests/Route/RoutesCacheWarmUpTest.php
Fix related to the issue https://github.com/sonata-project/SonataAdminBundle/issues/3342
=> Fix isOptional() method in the RoutesCacheWarmUp service

Resources/doc/reference/form_types.rst
This PR fixes bug introduces in #3386
=> Fix wrong doc link in form_types.rst

Resources/doc/reference/dashboard.rst
Added an RST table for the dashboard layout.
=> Add layout explanatory table

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, Form/FormMapper.php, Form/Type/AclMatrixType.php, Form/Type/AdminType.php, Form/Type/ChoiceFieldMaskType.php, Form/Type/CollectionType.php, Form/Type/Filter/ChoiceType.php, Form/Type/Filter/DateRangeType.php, Form/Type/Filter/DateTimeRangeType.php, Form/Type/Filter/DateTimeType.php, Form/Type/Filter/DateType.php, Form/Type/Filter/DefaultType.php, Form/Type/Filter/NumberType.php, Form/Type/ModelHiddenType.php, Form/Type/ModelReferenceType.php, Form/Type/ModelType.php, Form/Type/ModelTypeList.php
Fixes https://github.com/sonata-project/SonataAdminBundle/issues/3248
=> Update for Symfony 2.8 deprecations

Twig/Extension/SonataAdminExtension.php, composer.json
fixes this issue https://github.com/sonata-project/SonataAdminBundle/issues/3401
=> Twig deprecation message

Resources/views/CRUD/batch_confirmation.html.twig
=> Updated UI for batch actions

Resources/translations/SonataAdminBundle.pt_BR.xliff
Changes in the Brazilian Portuguese translation. Some values were missing and others were just wrong.
=> Changes in the Brazilian Portuguese translation

Form/FormMapper.php, Resources/doc/cookbook/recipe_delete_field_group.rst, Resources/doc/index.rst, Tests/Form/FormMapperTest.php
Rebased https://github.com/sonata-project/SonataAdminBundle/pull/2996/
=> Added function to remove a form group as suggested in Issue #2294

Form/Type/ModelAutocompleteType.php, Resources/doc/reference/form_types.rst, Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig, Tests/Form/Type/ModelAutocompleteTypeTest.php
Allow to configure *quietMills* and *cache* options.
=> Autocomplete options

Resources/doc/reference/security.rst
There were few occurrences where a colon or semicolon was missing at the end of line for list items.
Also few grammar errors are corrected.
=> Corrected small grammar errors and typos

composer.json
=> Fix failing test on composer with --prefer-lowest flag

Form/ChoiceList/ModelChoiceList.php, Form/Type/ModelType.php, Tests/Form/ChoiceList/ModelChoiceListTest.php
=> [ISSUE-3453]: defaults choices must be an array sf2.8

Form/ChoiceList/ModelChoiceLoader.php, Form/DataTransformer/ModelsToArrayTransformer.php
=> Improve ModelChoiceLoader

DependencyInjection/SonataAdminExtension.php, Tests/DependencyInjection/ConfigurationTest.php
Use more common way that already used inside core bundles.
=> Minior refactoring of configuration handling

Resources/views/Form/form_admin_fields.html.twig, Tests/Form/Widget/BaseWidgetTest.php, Tests/Form/Widget/FilterChoiceWidgetTest.php, Tests/Form/Widget/FormChoiceWidgetTest.php
Closes #3528. Mostly WIP - the first commit is basically to trigger travis builds and check 5.3 and sf 2.8.
@OskarStark , please take a look.
=> [Done] Test suite for form widget rendering

Admin/AdminInterface.php
Added new and removed some unused @return's in AdminInterface.
=> PHPDoc fixes

Resources/translations/SonataAdminBundle.it.xliff
Complete the latest translations
=> Update IT Translations 

Resources/doc/cookbook/recipe_sortable_listing.rst, Resources/doc/reference/advanced_configuration.rst, Resources/doc/reference/architecture.rst, Resources/doc/reference/getting_started.rst, Resources/doc/reference/preview_mode.rst
see https://github.com/sphinx-doc/sphinx/issues/2264
Fixes the build.
=> Fix broken documentation build

.travis.yml, Resources/doc/cookbook/recipe_sortable_listing.rst, Resources/doc/reference/advanced.rst, Resources/doc/reference/getting_started.rst, Resources/doc/reference/preview_mode.rst, Tests/Controller/CRUDControllerTest.php, Tests/Controller/CoreControllerTest.php, composer.json
=> [WIP] Fix tests for 2.3

Tests/Controller/CRUDControllerTest.php, Tests/Controller/CoreControllerTest.php, Tests/Controller/HelperControllerTest.php
Removed useless return statements, unused variables, check for class existense instead of version comparasion
=> Simplify some tests

Admin/AdminExtension.php, Admin/AdminExtensionInterface.php
ping @sonata-project/contributors
=> use the same variable names like in the AdminClass

Admin/Admin.php
Removes duplicate code and adds one more rule for ```$action == 'create'```
=> Remove duplicate code from Admin

Resources/views/CRUD/base_edit_form_macro.html.twig
Quick fix for bad tag <div>
Man, I hate Mondays...
=> Fix for show tabs when embedded as sonata_type_admin

Admin/Admin.php
The goal of this PR is to give to possibility to add something when you are on tree view.
Tree view is pretty much like List so I think this makes sense.
=> Display create button on tree view

Form/ChoiceList/ModelChoiceLoader.php, Tests/Form/ChoiceList/ModelChoiceLoaderTest.php
Fix choice loading from entities with identical property values
=> Fix choice loading from entities with identical property values

Resources/translations/SonataAdminBundle.nl.xliff
Some dutch translations of the admin bundle were missing
=> add missing dutch translations

Admin/AdminHelper.php, Tests/Admin/AdminHelperTest.php
Basically same functionality as in 
https://github.com/sonata-project/SonataAdminBundle/pull/2985 but BC breaks fixed
fixed also to work with underscore model properties
https://github.com/sonata-project/SonataAdminBundle/pull/2985#issuecomment-150670027
=> working new item button for nested (> 2nd level)

Resources/views/CRUD/base_edit_form_macro.html.twig
Reverts sonata-project/SonataAdminBundle#3593
=> Revert "Fix for show tabs when embedded as sonata_type_admin"

Resources/views/CRUD/base_edit_form_macro.html.twig
Reverts sonata-project/SonataAdminBundle#3540
=> Revert "show tabs when embedded as sonata_type_admin"

Form/Extension/Field/Type/FormTypeFieldExtension.php, Resources/views/Form/form_admin_fields.html.twig, Tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php, Tests/Form/Widget/BaseWidgetTest.php, Tests/Form/Widget/FormChoiceWidgetTest.php, Tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php
This PR makes tests easier to write, and removes a condition that leaked into the code (my fault). This could benefit #3127
=> Widget test

Form/Extension/Field/Type/FormTypeFieldExtension.php, Form/Type/CollectionType.php, Tests/Form/Extension/ChoiceTypeExtensionTest.php, Tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php, Tests/Form/Widget/BaseWidgetTest.php, Tests/Form/Widget/FilterChoiceWidgetTest.php, Tests/Form/Widget/FormChoiceWidgetTest.php, Tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php
The kernel version might differ from components versions.
=> avoid Kernel::VERSION when detecting features

README.md
This branch matters as much as master, we should be aware when it is
broken.
=> display last stable branch build status

Command/ExplainAdminCommand.php, Controller/CRUDController.php, Controller/CoreController.php, Datagrid/ListMapper.php, Form/Extension/Field/Type/FormTypeFieldExtension.php, Form/Type/CollectionType.php, Resources/config/routing/sonata_admin.xml, Tests/Command/ExplainAdminCommandTest.php, Tests/Command/GenerateAdminCommandTest.php, Tests/Controller/CRUDControllerTest.php, Tests/Controller/CoreControllerTest.php, Tests/Controller/HelperControllerTest.php, Tests/Datagrid/ListMapperTest.php, Tests/Fixtures/Resources/config/routing/routing.xml, Tests/Form/DataTransformer/ModelsToArrayTransformerTest.php, Tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php, Tests/Twig/Extension/SonataAdminExtensionTest.php, Twig/Extension/SonataAdminExtension.php
Backports many deprecation fixes from master
=> Remove deprecation notices

Resources/doc/getting_started/the_form_view.rst
The property option has been deprecated in favor of choice_label.
=> recommend choice_label instead of property

.travis.yml, Admin/Admin.php, Resources/doc/reference/security.rst, Resources/views/empty_layout.html.twig, Tests/Admin/AdminTest.php, Tests/Controller/CoreControllerTest.php, Tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php, Tests/Twig/Extension/SonataAdminExtensionTest.php, Twig/Extension/SonataAdminExtension.php
~~I'm just using travis to test this branch.~~ Can and should be merged when the build is passing, in fact.
=> Backport 2.3 changes

Controller/CRUDController.php, Controller/CoreController.php
Adding this argument was a BC-break.
=> remove request argument from method signatures

Controller/CRUDController.php
This was overlooked in a previous refactoring.
=> remove unneeded request argument

Resources/doc/reference/batch_actions.rst
Stop recommending using the request service.
Using the request service has been deprecated in Symfony 2.8/3
=> clean up with request

Controller/HelperController.php
The first argument was recently added.
=> add missing argument

Controller/CRUDController.php
When edit a object in the action of CRUDController is called to handleRequest and after submit of the form. Due to this I get the error "A form can only be submitted once".
I have solved it by removing this line.
=> remove call twice to "submit"

Form/DataTransformer/ModelsToArrayTransformer.php, Form/Type/ModelType.php
Add ModelChoiceLoader class support for sf2.7+ for multi-choice select widget in Sonata Admin Form
=> Fix ChoiceLoader issue SF2.7+

Resources/public/Admin.js
Fixes https://github.com/sonata-project/SonataAdminBundle/issues/3698
=> JavaScript error in #3632

Resources/config/menu.xml
This solves https://github.com/sonata-project/SonataAdminBundle/issues/3712
=> Remove `setRequest` method call from menu builder definition

Resources/public/css/layout.css
Fix for issues #3570 and #3576
=> Correct view for mobile devices

Controller/HelperController.php, Twig/Extension/SonataAdminExtension.php
=> remove interface implementation

Resources/doc/reference/installation.rst
The console file is located in the bin folder and not in the app folder.
=> Updates installation.rst, changes the default binary path in command samples

Twig/Extension/SonataAdminExtension.php
Added the twig environment to the Twig extension 'render_view_element_compare'.
=> Fix Twig filter 'render_view_element_compare'

Twig/Extension/SonataAdminExtension.php
Fixed CS in multiline array declarations.
=> Fix CS in Twig/Extension/SonataAdminExtension.php

UPGRADE-3.0.md, composer.json
=> Good bye 2.4, welcome 3.x!

Admin/AdminInterface.php, Controller/CRUDController.php, Controller/CoreController.php, Datagrid/ListMapper.php, Resources/doc/cookbook/recipe_bootlint.rst, Resources/doc/cookbook/recipe_customizing_a_mosaic_list.rst, Resources/public/Admin.js, Util/AdminObjectAclData.php, Util/AdminObjectAclManipulator.php
Old planned version was 2.4. It's now 3.0.
See why on #3731.
=> Replace deprecation messages and comment for 3.0

Resources/doc/getting_started/installation.rst
=> Fixed typo on installation documentation

Resources/doc/getting_started/creating_an_admin.rst
In the doku we create a BlogPost class -> https://sonata-project.org/bundles/admin/2-3/doc/getting_started/creating_an_admin.html Later if you try to safe a blog post you will get a error because doctrine can't save null to a boolean. I added it to the Doku
=> Added to doku

Tests/Admin/AdminTest.php
@tim96 wants to modify this uncovered piece of code in #3749 , which would be dangerous. Let's add tests first to be sure everything still works after his changes.
=> test check access

Admin/Admin.php, Admin/AdminInterface.php, Tests/Admin/AdminTest.php
@greg0ire hello. I add PR to check access in admin class without exception to try fix problem like this:  https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/529
=> Add function to check access without exception message

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, DependencyInjection/Configuration.php, Menu/Matcher/Voter/AdminVoter.php, Menu/Provider/GroupMenuProvider.php, Resources/doc/cookbook/recipe_knp_menu.rst, Resources/views/Menu/sonata_menu.html.twig, Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, Tests/Menu/Matcher/Voter/AbstractVoterTest.php, Tests/Menu/Matcher/Voter/ActiveVoterTest.php, Tests/Menu/Matcher/Voter/AdminVoterTest.php, Tests/Menu/Provider/GroupMenuProviderTest.php
@Soullivaneuh hello.
I want to add some link to list on sidebar menu without tree view. I can't find how do it in documentation. So I write a small PR to do it, using additional parameter. What do you think, can we add this features?
=> Add new option "onTop" to show link in sidebar menu without tree view.

Resources/doc/reference/advanced_configuration.rst
Fixes #2607
Fixes #2807 
I applied your comments from #2807 @Soullivaneuh and moved the doc block to the correct section.
I kept the commit of @webdevilopers 
@greg0ire @core23 @Soullivaneuh , can someone please merge this?
=> Add how to add filters to tab menu example see issue

composer.json
This will resolve failing test like this: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/128526889#L327
=> Authorize block-bundle ^4.0@dev

Admin/AdminHelper.php, Admin/BaseFieldDescription.php, CHANGELOG.md, Controller/CRUDController.php, DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, Tests/Admin/BaseFieldDescriptionTest.php, UPGRADE-3.0.md
Replaces #3787 
Replaces #3148
NO BC break anymore
=> Replace BaseFieldDescription::camelize with Inflector::classify

Admin/Admin.php, Admin/AdminExtensionInterface.php, Admin/AdminInterface.php, CHANGELOG.md, UPGRADE-4.0.md
Refs https://github.com/sonata-project/SonataAdminBundle/pull/3559
=> Add configureActionButtons to the admin interfaces

Admin/Admin.php, Admin/AdminExtensionInterface.php, CHANGELOG.md, UPGRADE-4.0.md
~~Please schedule for 3.0~~
Please schedule for 4.0
Refs https://github.com/sonata-project/SonataAdminBundle/pull/3548
=> Added "configureBatchActions" method to AdminExtensionInterface

CHANGELOG.md, UPGRADE-2.1.md, UPGRADE-2.3.md, UPGRADE-3.0.md
=> replaced two backticks with one backtick

Resources/doc/cookbook/recipe_custom_action.rst, Resources/doc/cookbook/recipe_sortable_listing.rst, Resources/doc/reference/action_list.rst, Resources/skeleton/Admin.php.twig, Tests/Fixtures/Admin/ModelAdmin.php
This is not necessary to specify it to get it working.
Need @sonata-project/contributors opinions for this one.
=> Do not specify 'actions' type on list _action field

Security/Handler/AclSecurityHandler.php, Security/Handler/RoleSecurityHandler.php
Because this is completly useless.
=> Fix ugly exceptions management

CHANGELOG.md, Resources/config/core.xml, Tests/Twig/Extension/SonataAdminExtensionTest.php, Twig/Extension/SonataAdminExtension.php, UPGRADE-4.0.md
This PR introduces BC breaks.
Food for thoughts : 
- http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html
- https://ocramius.github.io/blog/when-to-declare-classes-final
=> Api closing first batch

Admin/AbstractAdmin.php, Admin/AdminInterface.php, CHANGELOG.md
=> Removed deprecated buildSideMenu method

Admin/AbstractAdmin.php, Tests/Admin/AdminTest.php, Tests/Fixtures/Admin/PostAdmin.php
Added new method to configure batch actions inside the admin class.
Refs https://github.com/sonata-project/SonataAdminBundle/pull/3844
```markdown
- Added `AbstractAdmin::configureBatchActions` method
```
=> Added configureBatchActions method to AbstractAdmin

Admin/AdminInterface.php, CHANGELOG.md, Resources/doc/cookbook/recipe_dynamic_form_modification.rst, UPGRADE-4.0.md
=> Uncomment AdminInterface::isCurrentRoute method for next major relase

Tests/Admin/Extension/LockExtensionTest.php
I'm trying to increase the coverage of the project. I just picked up the first class on the first folder. I will try to create a PR for every class that I cover.
Have some questions for the contributors:
- Do you like the old getMock method from PHPUnit? (will be deprecated in future versions of PHPUnit). Personally I think [prophecy](https://github.com/phpspec/prophecy) is better and cleaner, but I saw everything using getMock, so didn't want to change it at first.
- What do you think about using Phpdoc to mark a function as a test instead of having it as a name.
=> Increased Coverage of LockExtension

Resources/views/Button/acl_button.html.twig, Resources/views/Button/create_button.html.twig, Resources/views/Button/edit_button.html.twig, Resources/views/Button/list_button.html.twig
```markdown
- Added missing space at end of condition on twig template
- Fixed CS
```
It's just about coding style
=> Fixed CS on action button

Tests/Controller/CRUDControllerTest.php
This will avoid deprecation notice because of the following PR: #3865
cc @greg0ire
=> Add @group legacy on CRUDControllerTest

Admin/AbstractAdmin.php, Admin/AdminInterface.php, CHANGELOG.md, DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, DependencyInjection/Configuration.php, DependencyInjection/SonataAdminExtension.php, Resources/doc/reference/action_list.rst, Resources/doc/reference/configuration.rst, Tests/Admin/AdminTest.php, Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Closes #2551
Add new configuration parameter to show/hide mosaic button.
=> Add new configuration parameter to show/hide mosaic button.

Tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php, Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php, composer.json
Fixes #3876
```markdown
JMS translation bundle related tests were not run
```
This PR makes sure JMS Translation Bundle -related tests are run again.
=> Enable and fix jms tests

DependencyInjection/SonataAdminExtension.php
Fixes #3909
```markdown
- Eternal deprecation warning because of old class on compilation
```
@rafrsr This should fix your issue.
=> Use new AbstractAdminExtension on class compile

Controller/CRUDController.php
Rebase of #3630
```markdown
- Removed unnecessary check for `Admin::preValidate` in `CRUDController`
```
This check isn't necessary anymore, because the method was moved to the `AdminInterface`
=> Removed unnecessary check for Admin::preValidate

Admin/AbstractAdmin.php, Admin/AdminInterface.php
```markdown
- Added `AdminInterface::getSearchResultLink` method
- Added `AdminInterface::showMosaicButton` method
```
Uncomment all methods that were marked as `NEXT_MAJOR`.
=> Uncomment NEXT_MAJOR methods in AdminInterface

Resources/translations/SonataAdminBundle.pt_BR.xliff
```markdown
- Fixed PT-BR translations
```
Some translations were missing and others were incorrect
=> Changes in Brazilian Portuguese Translations

Resources/translations/SonataAdminBundle.es.xliff
I am targetting this branch, because…
I would like to change a translation.
Fixes #
The spanish batch confirmation translation when only one item is selected.
Updated spanish batch confirmation message translation.
SonataAdminBundle.es.xliff
Updated spanish batch confirmation message translation
=> Updated spanish translation

Resources/translations/SonataAdminBundle.pl.xliff
- Added the object name to message_delete_confirmation translation.
- Added the action name to title_batch_confirmation translation.
SonataAdminBundle.pl.xliff
Added missing parameters in polish translation.
=> Added missing parameters in polish translation

Tests/Admin/AdminHelperTest.php
I am targetting this branch, because this is a bug fix
Closes #4078 
To be merged asap :rotating_light:
=> Fix spelling

Admin/AbstractAdmin.php, Resources/views/Button/acl_button.html.twig, Resources/views/Button/create_button.html.twig, Resources/views/Button/edit_button.html.twig, Resources/views/Button/history_button.html.twig, Resources/views/Button/list_button.html.twig, Resources/views/Button/show_button.html.twig, Tests/Admin/AdminTest.php
This fix regressions I added in #4062.
Should I write a changelog?
This re-add conditions that were removed in #4062.
@axzx can you test this with your project/code ?
=> add actions buttons tests in templates

Command/ExplainAdminCommand.php, Command/GenerateAdminCommand.php, Command/SetupAclCommand.php, Command/Validators.php, Datagrid/ListMapper.php, Form/Extension/ChoiceTypeExtension.php, Form/Extension/Field/Type/FormTypeFieldExtension.php, Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php, Form/Type/AclMatrixType.php, Form/Type/AdminType.php, Form/Type/ChoiceFieldMaskType.php, Form/Type/CollectionType.php, Form/Type/Filter/ChoiceType.php, Form/Type/Filter/DateRangeType.php, Form/Type/Filter/DateTimeRangeType.php, Form/Type/Filter/DateTimeType.php, Form/Type/Filter/DateType.php, Form/Type/Filter/DefaultType.php, Form/Type/Filter/NumberType.php, Form/Type/ModelAutocompleteType.php, Form/Type/ModelHiddenType.php, Form/Type/ModelListType.php, Form/Type/ModelReferenceType.php, Form/Type/ModelType.php, Security/Handler/AclSecurityHandler.php, Security/Handler/RoleSecurityHandler.php, Tests/Command/GenerateAdminCommandTest.php
I am targetting this branch, because it is BC and does not change any code behaviour
avoid long lines and use `NEXT_MAJOR` instead of `@todo`
=> Small fixes

Datagrid/ListMapper.php, Twig/Extension/SonataAdminExtension.php, Util/AdminObjectAclData.php, Util/AdminObjectAclManipulator.php
I am targetting this branch, because there is no BC break
Fixes #4106
Be more clear when they will be removed!
=> Detailed deprecation messages

Resources/doc/getting_started/installation.rst, Resources/doc/reference/installation.rst
I am targetting this branch, because it is the doc
Add information about translator service that is needed.
=> Doc installation update

Tests/Admin/Extension/LockExtensionTest.php
Refactored LockExtensionTest to use Prophecy.
=> Refactor LockExtensionTest to use Prophecy

Resources/translations/SonataAdminBundle.sl.xliff
I am targetting this branch, because it updates translations based on English origin version.
```markdown
- Slovenian (sl_SI) translation updated
```
This patch updates Slovenian (sl_SI) translation.
=> Update sl_SI translation

Admin/AbstractAdmin.php, Admin/Admin.php, Admin/AdminExtension.php, Admin/AdminExtensionInterface.php, Admin/AdminHelper.php, Admin/AdminInterface.php, Admin/BaseFieldDescription.php, Controller/CoreController.php, Export/Exporter.php, Form/Type/Filter/ChoiceType.php, Form/Type/Filter/DateRangeType.php, Form/Type/Filter/DateTimeRangeType.php, Form/Type/Filter/DateTimeType.php, Form/Type/Filter/DateType.php, Form/Type/Filter/NumberType.php, Form/Type/ModelTypeList.php, Resources/public/Admin.js, Tests/Util/AdminObjectAclDataTest.php, Util/AdminObjectAclData.php, Util/AdminObjectAclManipulator.php
=> Next major

Resources/translations/SonataAdminBundle.ru.xliff, Resources/translations/SonataAdminBundle.uk.xliff
I am targetting this branch, to correct translations
Add Russian and Ukrainian translations, and correct existing
=> Correct translations

Tests/Fixtures/Util/DummyObjectAclManipulator.php, Tests/Util/ObjectAclManipulatorTest.php
I am targetting this branch, because this is b/c (testing)
Increase code coverage
=> Test object manipulator

Resources/doc/reference/batch_actions.rst
parameters should be in filter key
=> update example of code

Resources/doc/reference/batch_actions.rst
I'm targetting this branch, because I found a bug in the documentation.
parameters should be in filter key
=> add missing parameter key in code sample

Tests/Twig/Extension/SonataAdminExtensionTest.php
I am targetting this branch, because this is fully BC (only tests are touched)
Refs #4164 
This is to keep the ball rolling on #4164
=> Unit test xeditable

Tests/Controller/HelperControllerTest.php
I am targetting this branch, because only tests are changing, by definition BC.
It seems to vary depending on the version of some package (the build
with the lowest possible dependencies passes). Anyway, this is not
really what we want to test here, do we ?
=> Remove expectation on method call count

Tests/Command/ExplainAdminCommandTest.php, Tests/Fixtures/Command/explain_admin.txt, Tests/Fixtures/Command/explain_admin_empty_validator.txt
I am targetting this branch, because this is about tests
Resurrects an old test
Rebase and fix of #4110
=> Carry #4110

Controller/CRUDController.php, Controller/HelperController.php, Tests/Controller/CRUDControllerTest.php, Tests/Controller/HelperControllerTest.php, Tests/Form/Widget/BaseWidgetTest.php, composer.json
This PR fixes notices which appeared in Twig 1.26
Closes #4162
=> Fix Twig deprecations (carry #4162)

Controller/CRUDController.php
I am targetting this branch, because this is BC
These parameters aren't available
=> fixed php doc

Admin/AbstractAdmin.php, Admin/AdminHelper.php, Admin/AdminInterface.php, Admin/Pool.php, Controller/CRUDController.php, Controller/HelperController.php, Datagrid/Pager.php, Form/ChoiceList/ModelChoiceLoader.php, Form/DataTransformer/ModelToIdPropertyTransformer.php, Form/DataTransformer/ModelsToArrayTransformer.php, Mapper/BaseGroupedMapper.php, Search/SearchHandler.php, Twig/Extension/SonataAdminExtension.php
I am targetting this branch, because this is BC (and does not warrant a release.
I'm trying to run phpstan/phpstan on the admin bundle.
=> Apply phpstan fixes

Resources/public/Admin.js
I am targetting this branch, because it is BC (and pedantic).
=> Fixed typos in comments

Datagrid/Pager.php
=> removed useless comment

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
=> fix symfony url

Admin/AdminHelper.php, Controller/CoreController.php
=> added @throws annotation

Resources/views/CRUD/list_array.html.twig, Resources/views/Core/tab_menu_template.html.twig, Tests/Twig/Extension/SonataAdminExtensionTest.php, composer.json
Closes #4241
```markdown
- Compatibility with Twig 2.0
```
Labeled as patch to please @Soullivaneuh , but should be labeled minor IMO.
=> Twig 2 support

Resources/translations/SonataAdminBundle.ro.xliff
I am targetting this branch, because it is a translation and it is BC.
```markdown
- Added ro translation for `btn_advanced_filters`
```
Added ro translation for btn_advanced_filters
=> Added ro translation for btn_advanced_filters

Admin/AdminExtensionInterface.php, Admin/AdminInterface.php, Admin/FieldDescriptionInterface.php, Builder/BuilderInterface.php, Builder/DatagridBuilderInterface.php, Builder/ListBuilderInterface.php, Builder/RouteBuilderInterface.php, Builder/ShowBuilderInterface.php, Controller/CoreController.php, Datagrid/DatagridInterface.php, Datagrid/PagerInterface.php, Datagrid/ProxyQueryInterface.php, Filter/FilterFactoryInterface.php, Filter/FilterInterface.php, Guesser/TypeGuesserInterface.php, Model/AuditManagerInterface.php, Model/AuditReaderInterface.php, Route/RouteGeneratorInterface.php, Security/Handler/AclSecurityHandlerInterface.php, Security/Handler/SecurityHandlerInterface.php, Translator/LabelTranslatorStrategyInterface.php, Util/AdminAclManipulatorInterface.php, Util/ObjectAclManipulatorInterface.php
=> removed useless class comments

Resources/doc/reference/action_export.rst
I am targetting this branch, because it's just about docs upgrading.
Fixes #1550 
```markdown
- Added some solutions to customize export action
```
Just added some solutions to ExportAction docs, because for now it is almost empty.
=> add customizing solutions to export action docs

Admin/AbstractAdmin.php, Admin/AdminHelper.php, Admin/Pool.php, Command/GenerateAdminCommand.php, Controller/HelperController.php, Datagrid/DatagridMapper.php
=> avoid long lines

Resources/doc/cookbook/recipe_sortable_listing.rst
I am targetting this branch, because the documentation needs to be updated.
Closes #4326 
Updated cookbook recipe for SortableBehaviour.
```markdown
- Fixed cookbook recipe for SortableBehaviour.
```
It updates the cookbook recipe when using pixassociates/sortable-behavior-bundle 1.1 or higher.
Please also see #4326
=> Update cookbook sortable

Resources/doc/reference/saving_hooks.rst
I am targeting this branch because it's the one everybody read on the Symfony doc.
Just some doc for hooks in the `CRUDController`.
=> Add a note about hooks in the CRUDController

Controller/HelperController.php
I am targeting this branch, because it's a bugfix.
Closes #4368
```markdown
- Handling of boolean types in `HelperController`
=> Fix the incorrect handling of boolean types

Resources/translations/SonataAdminBundle.lb.xliff
```markdown
- Updated Luxembourgish translations
```
I added a few missing translations for Luxembourgish
=> Updated Luxembourgish (lb) translations

Resources/doc/reference/action_show.rst
I am targeting this branch, because this patch doesn't break the BC.
=> Improve documentation

Resources/doc/index.rst
I am targeting this branch, because it is documentation fix.
```markdown
updated documentation
```
Adds chapter names to the table of contents.
Before:
After:
=> Add captions to TOC tree in docs

Resources/doc/reference/form_types.rst
I am targeting this branch, because this is a typo fix.
=> Fix a typo in the documentation

Resources/doc/reference/form_types.rst
I am targeting this branch, because this is a doc fix.
Refs #4399
=> small doc fix

Resources/doc/reference/security.rst
I am targeting this branch, because it's a documentation change for this version and above (documentation for branch 4.0 doesn't include Symfony 3.0 changes as well)
=> ACL Permission Map config updated for Symfony >= 3

Resources/views/ajax_layout.html.twig, Resources/views/empty_layout.html.twig, Resources/views/standard_layout.html.twig
I am targeting this branch, because this is pedantic.
Just fixing indentation and of base templates (and added a missing trim)
=> Fixed indentation of base templates

Form/Type/AdminType.php, Resources/doc/reference/form_types.rst, Resources/public/Admin.js, Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
```markdown
- recently introduced checkbox-disabling feature, which was not stable enough
```
This reverts #4358 (partially)
=> Revert 4358

Resources/doc/conf.py, Resources/doc/reference/architecture.rst
I am targeting this branch, because this is about docs.
=> Add a tip about clearing parent routes

Controller/HelperController.php
I am targeting this branch, because bug fix patch.
Closes #4467
```markdown
- [ModelAutocompleteFilter] Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property
```
Hotfix for [ModelAutocompleteFilter] Action "" could not be found in
access mapping. Please make sure your action is defined into your admin
class accessMapping property #4467
=> Hotfix Bug #4467

Resources/doc/cookbook/recipe_file_uploads.rst
I am targeting this branch, because my patch just fixes indentations in documentation
```markdown
- Fix indentations in recipe_file_uploads.rst
```
Fix indentations
=> Fix indentations in code-block

Resources/doc/reference/security.rst
I am targeting this branch, because this error was introduced in 3.x.
=> Fix configuration AdminPermissionMap w/ Symfony>=3

Resources/doc/reference/installation.rst
I am targeting this branch, because this is a docs change.
This note is not necessary
=> removed unnecessary note

Resources/views/CRUD/base_array_macro.html.twig, Resources/views/CRUD/list_array.html.twig, Resources/views/CRUD/show_array.html.twig
```markdown
- multidimensional arrays support in show array
- inline option in list array
```
This PR adds multidimensional arrays support in show array, and adds inline option in list array.
=> Improve show array template

Resources/doc/reference/action_create_edit.rst, Resources/doc/reference/form_types.rst
I am targeting the 3.x branch, because these are updates to the documentation of that branch.
Updates #1557
Please let me know if I'm doing this correctly or if I should change anything. This pull request does not complete #1557 fully, but it's a step.
Improved documentation of the create/edit view.
=> Updated documentation for create/edit view

Tests/DependencyInjection/SonataAdminExtensionTest.php, composer.json
I am targeting this branch, because this PR is pedantic.
Added some tests
=> added extension test for lock_extension

Controller/CRUDController.php, Tests/Controller/CRUDControllerTest.php
```markdown
- Fix missing flash message translations
```
This PR fixes some untranslated flash messages (batch and acl).
=> Fix missing flash message translations

Resources/public/Admin.js
```markdown
- Fixed sticky navbar regression
```
As @dmarkowicz [noticed in my previous PR](https://github.com/sonata-project/SonataAdminBundle/pull/4675#issuecomment-333204372), the `debounce` function was added to improve performances. Removing it was a mistake !
My PR was merged before I fixed it, so here is another one with the `debounce` function reintroduced.  I have adjusted the code to make it correctly work with it.
=> Fix sticky navbar regression

Admin/AbstractAdmin.php, Form/Extension/ChoiceTypeExtension.php, Form/Extension/Field/Type/FormTypeFieldExtension.php, Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php, Form/Type/AclMatrixType.php, Form/Type/AdminType.php, Form/Type/ChoiceFieldMaskType.php, Form/Type/Filter/ChoiceType.php, Form/Type/Filter/DateRangeType.php, Form/Type/Filter/DateTimeRangeType.php, Form/Type/Filter/DateTimeType.php, Form/Type/Filter/DateType.php, Form/Type/Filter/DefaultType.php, Form/Type/Filter/NumberType.php, Form/Type/ModelAutocompleteType.php, Form/Type/ModelHiddenType.php, Form/Type/ModelListType.php, Form/Type/ModelReferenceType.php, Form/Type/ModelType.php
No  changelog needed
<!--
```markdown
- Support for old versions of Symfony.
```
>
=> Drop old versions of sf

Admin/AdminInterface.php, Admin/FieldDescriptionInterface.php, Datagrid/ListMapper.php, Datagrid/ProxyQueryInterface.php, Filter/FilterInterface.php, Form/ChoiceList/ModelChoiceList.php, Form/ChoiceList/ModelChoiceLoader.php, Form/DataTransformer/ModelToIdPropertyTransformer.php, Model/ModelManagerInterface.php, Security/Handler/SecurityHandlerInterface.php
I am targeting this branch, because this is pedantic.
Fixed some PHPDoc.
=> Fixed PHPDoc

CHANGELOG.md, docs/reference/form_types.rst, src/Admin/AbstractAdmin.php, src/Controller/CRUDController.php, src/Form/Type/Filter/DateRangeType.php, src/Form/Type/Filter/DateTimeRangeType.php, src/Form/Type/Filter/DateTimeType.php, src/Form/Type/Filter/DateType.php, src/Form/Type/Filter/NumberType.php, src/Form/Type/ModelListType.php, src/Resources/translations/SonataAdminBundle.de.xliff, src/Resources/translations/SonataAdminBundle.en.xliff, src/Resources/translations/SonataAdminBundle.es.xliff, src/Resources/translations/SonataAdminBundle.fr.xliff, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig, tests/Controller/CRUDControllerTest.php, tests/Controller/CoreControllerTest.php, tests/Form/Type/ModelTypeListTest.php
=> Manual merge master with 3.x

src/Resources/translations/SonataAdminBundle.ja.xliff
I am targeting this branch, because I'm just adding some translation messages.
```markdown
- Added some Japanese messages 
```
I added Japanese translations for recent messages.
=> Added latest Japanese translations

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
I am targeting this branch, because discover XSS vulnerabilty when using autocomplete form type.
```markdown
- Fixed XSS vulnerability in autocomplete form type
```
=> Fix XSS vulnerability in autocomplete

src/Resources/config/block.xml, src/Resources/config/commands.xml, src/Resources/config/core.xml, src/Resources/config/exporter.xml, src/Resources/config/form_types.xml, src/Resources/config/menu.xml, src/Resources/config/route.xml, src/Resources/config/security.xml, src/Resources/config/twig.xml, src/Resources/config/validator.xml
Closes #4704 
```markdown
- All services without a declared visibility are now public
```
This improves forward compatibility.
=> Make services explicitely public

CHANGELOG.md, UPGRADE-3.x.md, src/Controller/CRUDController.php, src/Resources/translations/SonataAdminBundle.ja.xliff, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
=> Manual merge

src/Resources/translations/SonataAdminBundle.ru.xliff
```markdown
- Added Russian translations
```
There were added Russian translations for missing keys.
=> Added Russian translations

tests/Controller/CRUDControllerTest.php, tests/Controller/CoreControllerTest.php
This should fix the sf4 test job
=> Add missing mocked results

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
```markdown
- Added `CRUDController::redirectToList` method for all list redirections
```
This is a DRY fix.
=> Created function to list redirection

src/Admin/Extension/LockExtension.php, src/Command/ExplainAdminCommand.php, src/Datagrid/Datagrid.php, src/DependencyInjection/SonataAdminExtension.php, src/Form/DataTransformer/LegacyModelsToArrayTransformer.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Form/Type/AclMatrixType.php, tests/Command/ExplainAdminCommandTest.php, tests/Controller/HelperControllerTest.php, tests/Datagrid/DatagridMapperTest.php, tests/Datagrid/DatagridTest.php, tests/Datagrid/ListMapperTest.php, tests/Form/ChoiceList/ModelChoiceListTest.php, tests/Form/DataTransformer/LegacyModelsToArrayTransformerTest.php, tests/Form/FormMapperTest.php, tests/Form/Type/AdminTypeTest.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Show/ShowMapperTest.php, tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php
This PR removes more unnecessary code.
=> Drop old Symfony and PHP code

src/Resources/translations/SonataAdminBundle.it.xliff
Add some missing italian translations
```markdown
- added missing italian translations
```
=> Add missing italian translations

.editorconfig, .flintci.yml, .yamllint
@sonata-project/core FlintCI is a tool I am working on to provide a "StyleCI like" services but with "configuration free" linters/fixers.
I setup this tool on admin-bundle for testing at the moment. The others would be configured later with dev-kit.
More info: https://flintci.io (Yeah, not too much info, WIP! :trollface:)
=> FlintCI integration

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
I am targeting this branch, because I noticed that admin service is created several times per request.
Closes #4863
```markdown
- Admin and filter services are shared
```
=> Make services shared

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
Reverts sonata-project/SonataAdminBundle#4864
=> Revert "Make services shared"

docs/getting_started/installation.rst
fixing inconsistency in current 3.x docs 
_https://sonata-project.org/bundles/admin/3-x/doc/getting_started/installation.html_
=> fix doc routing section inconsistency

docs/reference/search.rst
=> fixed yaml indention in docs

src/Util/AdminObjectAclManipulator.php, tests/Util/AdminObjectAclManipulatorTest.php
Closes #4928 
```markdown
- Use FQCN form types for ACL form creation
```
=> Use FQCN for form types on ACL

src/Resources/translations/SonataAdminBundle.de.xliff, src/Resources/translations/SonataAdminBundle.en.xliff, src/Resources/views/standard_layout.html.twig
```markdown
- Added missing translation for `Toggle navigation`
```
=> Added missing translation

CHANGELOG.md
=> Manuel merge

docs/getting_started/installation.rst
I am targeting this branch, because I am updating docs.
https://github.com/sonata-project/SonataAdminBundle/pull/4971 this was merged into master, should be stable, so instead of reverting it, here is the same PR on this branch.
=> Update installation docs

docs/cookbook/recipe_custom_action.rst
This makes more sense as a tip than a sub section.
=> Fix docs for custom action

docs/cookbook/recipe_custom_action.rst
=> Improve create action docs

src/DependencyInjection/SonataAdminExtension.php, src/Resources/config/core.xml
Refs #4817 
see: https://github.com/sonata-project/SonataAdminBundle/pull/4817/files/437e907aaa37feb1c83787e3dd2c5346273c6bf8#diff-156ed93418fe946ee724987b790b24ba
=> removed old code

docs/reference/action_list.rst
I am targeting this branch, because it fixes the documentation.
Closes #5056
I changed the parameters.
=> Corrected collapse parameters

docs/reference/configuration.rst
It is so hard to maintain that it was not completely aligned, so I think
we should just give up on it and stop trying to align things.
=> Remove alignment

CHANGELOG.md, UPGRADE-3.x.md, docs/reference/child_admin.rst, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/Pool.php, src/Controller/CRUDController.php, src/Resources/public/Admin.js, src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig, src/Resources/views/Menu/sonata_menu.html.twig, src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/TemplateRegistryExtension.php, tests/Admin/AdminTest.php, tests/Controller/CRUDControllerTest.php, tests/Controller/HelperControllerTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php, tests/Twig/Extension/TemplateRegistryExtensionTest.php
Do not merge, just approve please.
=> Merge stable

docs/getting_started/creating_an_admin.rst
I am targeting this branch, because docs.
Closes #5081
=> Update getting started docs

tests/DependencyInjection/SonataAdminExtensionTest.php
I am targeting this branch, because this guards BC.
Use default assets configuration at `SonataAdminExtensionTest` in order to avoid hardcoded values.
=> [tests] Simplify assets tests at `SonataAdminExtensionTest`

src/Resources/translations/SonataAdminBundle.ru.xliff
I am targeting this branch, because missing translation appears after project update.
```markdown
- Added missing russian translation for `Toggle Navigation`
```
=> Add missing russian translation

src/Resources/translations/SonataAdminBundle.pl.xliff
I am targeting this branch, because missing translation appears after project update.
```markdown
- Added missing polish translation for `Toggle Navigation`
```
=> Add missing polish translation

src/Admin/Pool.php
Add an explicit error message to help the user
```markdown
- An exception message was improved to include hints about the correct configuration value
```
=> Add hint to exception message

src/Resources/views/CRUD/base_edit_form.html.twig
I am targeting this branch, because it adds the delete button in form action buttons when the request is ajax.
```markdown
- Added delete button in form action buttons when the request is ajax
```
=> Add delete button in form action buttons when the request is ajax

docs/cookbook/recipe_delete_field_group.rst
=> Simple Typo fix

src/Admin/AbstractAdmin.php
```markdown
- allow using overwritten constant for the mosaic html classes inside of admin class
```
There was a request for this feature on slack since const is used it seems reasonable.
=> Update Mosaic Class

src/Resources/translations/SonataAdminBundle.fr.xliff
```markdown
- Added missing french translation
```
=> Add missing translation

docs/cookbook/recipe_creating_an_admin_with_annotations.rst, docs/cookbook/recipe_custom_action.rst, docs/cookbook/recipe_delete_field_group.rst, docs/cookbook/recipe_image_previews.rst, docs/cookbook/recipe_knp_menu.rst, docs/cookbook/recipe_select2.rst, docs/cookbook/recipe_sonata_admin_without_user_bundle.rst, docs/cookbook/recipe_sortable_listing.rst, docs/cookbook/recipe_sortable_sonata_type_model.rst
I am targeting this branch, because docs.
=> Fix code highlight

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/BreadcrumbsBuilder.php, src/Admin/FieldDescriptionInterface.php, src/Admin/Pool.php, src/Admin/UrlGeneratorInterface.php, src/Annotation/Admin.php, src/Bridge/Exporter/AdminExporter.php, src/Command/GenerateAdminCommand.php, src/Command/GenerateObjectAclCommand.php, src/Command/SetupAclCommand.php, src/Command/Validators.php, src/Controller/CRUDController.php, src/Controller/CoreController.php, src/Datagrid/DatagridInterface.php, src/Datagrid/ProxyQueryInterface.php, src/Form/ChoiceList/ModelChoiceList.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/FormMapper.php, src/Form/Type/ModelReferenceType.php, src/Model/ModelManagerInterface.php, src/Search/SearchHandler.php, src/Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php, src/Twig/Extension/TemplateRegistryExtension.php, src/Twig/GlobalVariables.php, src/Util/FormBuilderIterator.php
```markdown
- An error message about subclasses has been fixed
```
=> Fix issues found with phpstan 0.10.1

src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_show.html.twig
I am targeting this branch, because it's a patch.
```markdown
Use Admin::getUniqid() to generate HTML tab id
```
There was a change in the way HTML id attribute for tabs was generated in https://github.com/sonata-project/SonataAdminBundle/pull/5103 because at that time `Admin::getUniqid()` generated random strings for each request. Because of that there were problems with the `id` when the Admin service was defined with the FQCN and to fix it, [I added some repeated code](https://github.com/sonata-project/SonataAdminBundle/pull/5186). Since https://github.com/sonata-project/SonataAdminBundle/pull/5176, `Admin::getUniqid()` return consistent values, so we can go back to use that method for generating the HTML id attribute and remove some code.
=> Use uniqid method to generate tab id

src/Resources/translations/SonataAdminBundle.lb.xliff
I am targeting this branch, because a couple translations were updated or added, but none were removed, so this is backwards compatible.
Updated Luxembourgish translations
I updated the Luxembourgish translations to add missing strings.
=> Updated Luxembourgish translations

docs/cookbook/recipe_knp_menu.rst, docs/reference/annotations.rst, docs/reference/form_types.rst, docs/reference/routing.rst, src/Annotation/Admin.php, src/Command/GenerateAdminCommand.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Route/RouteCollection.php, tests/Command/ExplainAdminCommandTest.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php, tests/Fixtures/Command/explain_admin.txt, tests/Fixtures/Command/explain_admin_empty_validator.txt
I am targeting this branch, because it should be a non-BC fix.
Closes #5227
```markdown
- Fixed controller reference deprecations
```
Fixed controller reference deprecations
=> Fixed controller reference deprecations

src/Resources/public/Admin.js, src/Resources/public/jquery/jquery.confirmExit.js, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/standard_layout.html.twig
```markdown
- Removed inline scripts for `SONATA_CONFIG` and `SONATA_TRANSLATIONS`
```
Inline scripts are bad, because they allow XSS and other evil stuff.
=> Removed inline scripts

src/Resources/public/Admin.js
Closes #5249 
```markdown
- Minor bug in JavaScripts (Admin.js)
```
=> Bugfix TypeError: data.config is not a function in Admin.js

docs/reference/action_list.rst
I am targeting this branch, because its a docs change.
Rework of #5110
Closes #5110
=> fixes wrong url

src/Resources/public/css/layout.css
I am targeting this branch, because this is BC change (only style fix).
Closes #5246 
```markdown
- Change icon on list column sorting
```
Change icon on list column sorting
Icon in list column sotring was inverted by vertical. This fix change layout.css file only (swap several css rules for icon).
=> Change icon on list column sorting

tests/bootstrap.php
Refs https://github.com/sonata-project/dev-kit/issues/436
=> updated bootstrap.php file

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
I am targeting this branch, because it's the main brach affected bu the bug.
Closes #5328 
```markdown
Fix crash on listing pages that have a datagrid filter
```
=> Check field_description existence in ModelAutocompleteType form field

docs/reference/conditional_validation.rst
I am targeting this branch, because it's doc.
```markdown
- Added note to inline validation troubleshooting documentation.
=> Document inline validation

src/Resources/public/css/styles.css
I am targeting this branch, because it's backwards compatible.
```markdown
- Better css layout for single column dropdowns
```
=> Improve css for single column dropdowns

docs/getting_started/creating_an_admin.rst
Post -> BlogPost
Tag -> Category
=> named entites are wrong

docs/cookbook/recipe_customizing_a_mosaic_list.rst
I am targeting this branch, because it's doc.
=> [Docs] Update about customizing mosaic list

docs/cookbook/recipe_improve_performance_large_datasets.rst, docs/cookbook/recipe_persisting_filters.rst, docs/cookbook/recipe_sortable_listing.rst, docs/reference/advanced_configuration.rst, docs/reference/architecture.rst, docs/reference/dashboard.rst, docs/reference/form_types.rst, docs/reference/routing.rst, docs/reference/templates.rst
Use the following order for yaml service registrations:
- class
- arguments
- calls
- tags
- public
=> [Docs] fixed order

docs/cookbook/recipe_custom_action.rst, docs/cookbook/recipe_custom_view.rst, docs/cookbook/recipe_improve_performance_large_datasets.rst, docs/cookbook/recipe_knp_menu.rst, docs/cookbook/recipe_sortable_listing.rst, docs/cookbook/recipe_workflow_integration.rst, docs/getting_started/creating_an_admin.rst, docs/getting_started/the_form_view.rst, docs/reference/advanced_configuration.rst, docs/reference/architecture.rst, docs/reference/dashboard.rst, docs/reference/form_types.rst, docs/reference/routing.rst, docs/reference/templates.rst
cause they don't need to be public...
=> [Docs] removed public: true for admin classes

docs/cookbook/recipe_customizing_a_mosaic_list.rst, docs/reference/advanced_configuration.rst, docs/reference/dashboard.rst
please review commit by commit
=> [Docs] small changes

tests/Action/Bar.php, tests/Action/Baz.php, tests/Action/Foo.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/BaseAdminModelManagerTest.php, tests/Admin/BaseAdminModelManager_Admin.php, tests/Controller/AdminControllerHelper_Bar.php, tests/Controller/AdminControllerHelper_Foo.php, tests/Controller/HelperControllerTest.php, tests/Maker/AdminMakerTest.php
New php-cs-fixer version, new fixes.
Refs #5394
=> Cs fixer compliance

.travis.yml, composer.json, src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, src/Admin/AdminInterface.php, src/Admin/Pool.php, src/Builder/ListBuilderInterface.php, src/Controller/CRUDController.php, src/Datagrid/SimplePager.php, src/DependencyInjection/Configuration.php, src/Maker/AdminMaker.php, src/Route/RouteCollection.php, src/Security/Handler/AclSecurityHandlerInterface.php, src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/TemplateRegistryExtension.php, tests/Action/Bar.php, tests/Action/Baz.php, tests/Action/Foo.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/BaseAdminModelManagerTest.php, tests/Admin/BaseAdminModelManager_Admin.php, tests/Controller/AdminControllerHelper_Bar.php, tests/Controller/AdminControllerHelper_Foo.php, tests/Controller/HelperControllerTest.php, tests/Datagrid/SimplePagerTest.php, tests/Maker/AdminMakerTest.php
=> Merge master

tests/Action/DashboardActionTest.php, tests/Admin/BaseFieldDescriptionTest.php, tests/Admin/BreadcrumbsBuilderTest.php, tests/Admin/Extension/LockExtensionTest.php, tests/Controller/CoreControllerTest.php, tests/Datagrid/ListMapperTest.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/DependencyInjection/Compiler/AdminMakerCompilerPassTest.php, tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php, tests/Form/FormMapperTest.php, tests/Maker/AdminMakerTest.php, tests/Menu/Matcher/Voter/AdminVoterTest.php, tests/Util/AdminObjectAclDataTest.php, tests/Util/FormBuilderIteratorTest.php
This takes care of risky tests
=> No assertions

src/Resources/skeleton/Admin.php.twig, src/Resources/skeleton/AdminController.php.twig, src/Resources/skeleton/AdminController.tpl.php, tests/Fixtures/Admin/ModelAdmin.php, tests/Fixtures/Controller/ModelAdminController.php
We are trying to encourage composition over inheritance. Maybe this will
help arousing curiosity in our users about this topic, and make them
more aware about the coding style we recommend. It will also prepare
them for our future moves away from inheritance.
```markdown
- generated classes are now final
```
=> Make the generated classes final

src/Admin/BaseFieldDescription.php, src/Controller/CRUDController.php, src/Controller/PolyfillControllerTrait.php, src/Route/RouteCollection.php, src/Twig/Extension/SonataAdminExtension.php, tests/Event/AdminEventExtensionTest.php
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |
=> Remove usages of `call_user_func_array()`

src/Maker/AdminMaker.php
Closes #5465
```markdown
Replaced tabs with spaces
```
=> Bug Fix: Admin maker produces tabs #5465

CHANGELOG.md, src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, src/Admin/FieldDescriptionCollection.php, src/Controller/CRUDController.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Configuration.php, src/Filter/Filter.php, src/Form/ChoiceList/ModelChoiceLoader.php, src/Form/Extension/ChoiceTypeExtension.php, src/Form/Type/AdminType.php, src/Form/Type/ModelAutocompleteType.php, src/Manipulator/ServicesManipulator.php, src/Mapper/BaseGroupedMapper.php, src/Object/Metadata.php, src/Route/DefaultRouteGenerator.php, src/Route/RouteCollection.php, src/Twig/Extension/SonataAdminExtension.php, src/Util/AdminObjectAclManipulator.php
=> 3.45.2 +cs fixes

composer.json, src/DependencyInjection/Configuration.php
Adding a few styles from corebundle
=> added styles from corebundle

docs/reference/child_admin.rst
=> Use correct class in example

src/Admin/AbstractAdmin.php
Add hasRequest to prevent error : `The Request object has not been set` in dashboard
Closes https://github.com/sonata-project/SonataAdminBundle/issues/5500
```markdown
- Check if request exists before using it and getting an exception
```
=> Add hasRequest to prevent error in dashboard

src/Controller/CRUDController.php, src/Resources/public/Admin.js, src/Resources/views/CRUD/base_edit_form.html.twig, tests/Controller/CRUDControllerTest.php
I am targeting this branch, because it's a small feature.
Closes #1911
```markdown
- Added ability to back to the tab which was edited on saving an object
```
=> redirect to tab

tests/Controller/HelperControllerTest.php
Tests are failing and I think it's because [these type hints](https://github.com/twigphp/Twig/commit/6c91803a9067b5aeab4ab029ce92c34ed72f0467), I'm not sure if this is the way to fix them... 😬
=> Fix failing tests

docs/reference/action_show.rst
documentation change only: updated path according to where I found the file in my local dev environment
I am targeting this branch, because I know this works for version 3.
=> Documentation: Updated path of original template for show action

src/Admin/AdminInterface.php
This PR continues #5527 
I am targeting this branch, because Exporter namespace is not fixed everywhere.
=> Fix exporter namespace

src/Command/CreateClassCacheCommand.php, src/Resources/config/commands.xml
Closes #5293
```markdown
- CreateClassCacheCommand deprecation message on container compiling
```
=> Fix CreateClassCacheCommand deprecation message

src/Command/GenerateAdminCommand.php, tests/Command/GenerateAdminCommandTest.php
Use new controller syntax at "sonata:admin:generate" command.
Related to #5251, #5227, #5346.
```markdown
- Deprecated controller syntax generated by "sonata:admin:generate" command.
```
=> Use new controller syntax at "sonata:admin:generate" command

src/Controller/HelperController.php, tests/Controller/CRUDControllerTest.php, tests/Form/Widget/BaseWidgetTest.php, tests/Menu/Integration/BaseMenuTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Replace `Twig_Environment` by its namespaced variant.
I am targeting this branch, because these changes doesn't affect BC.
=> Replace `Twig_Environment` by its namespaced variant

src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, src/Admin/BaseFieldDescription.php, src/Controller/CRUDController.php, src/Datagrid/Datagrid.php, src/Datagrid/Pager.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/DataTransformer/ModelToIdTransformer.php, src/Menu/Matcher/Voter/ActiveVoter.php, src/Menu/Matcher/Voter/ChildrenVoter.php, src/Security/Acl/Permission/AdminPermissionMap.php, src/Security/Handler/AclSecurityHandler.php, src/Templating/TemplateRegistry.php, src/Templating/TemplateRegistryInterface.php, tests/Admin/AdminTest.php, tests/Datagrid/DatagridTest.php, tests/Templating/TemplateRegistryTest.php
Fix some wrong void returns
```markdown
- Method `TemplateRegistry::hasTemplate()` in order to know if a template with a given name is registered.
- Passing invalid filter names to `Datagrid::getFilter()`;
- Passing invalid template names to `TemplateRegistry::getTemplate()`;
- Calling `AbstractAdmin::getActiveSubClass()` and `AbstractAdmin::getActiveSubclassCode()` when there is no active subclass.
- Returning `void` instead of `null` in functions which are capable to return values.
```
=> Prepare API narrowing

src/Twig/Extension/SonataAdminExtension.php, tests/Twig/Extension/SonataAdminExtensionTest.php
=> Use Twig namespaced classes

src/Admin/AccessRegistryInterface.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminInterface.php, src/Admin/FieldDescriptionInterface.php, src/Command/CreateClassCacheCommand.php, src/Command/ExplainAdminCommand.php, src/Command/GenerateAdminCommand.php, src/Command/GenerateObjectAclCommand.php, src/Command/ListAdminCommand.php, src/Command/SetupAclCommand.php, src/Controller/CRUDController.php, src/Filter/Persister/SessionFilterPersister.php, src/Model/ModelManagerInterface.php, src/Security/Handler/SecurityHandlerInterface.php, src/Twig/Extension/SonataAdminExtension.php
Update some docblocks
* Removed `{@inheritdoc}` docblocks;
* Update `@param mixed $object` docblocks with `@param object $object`;
* Add type declarations for interface methods that are intended to be added in 4.x.
=> Update some docblocks

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/BreadcrumbsBuilderInterface.php, src/Admin/UrlGeneratorInterface.php, src/Datagrid/Pager.php, src/Event/ConfigureEvent.php, src/Event/PersistenceEvent.php, src/Twig/GlobalVariables.php, src/Util/AdminObjectAclData.php
Update some docblocks with "mixed" types
=> Update some docblocks with "mixed" types

src/Admin/AdminInterface.php, src/Admin/FieldDescriptionInterface.php, src/Builder/DatagridBuilderInterface.php, src/Builder/FormContractorInterface.php, src/Builder/ShowBuilderInterface.php, src/Datagrid/ProxyQueryInterface.php, src/Filter/FilterFactoryInterface.php, src/Guesser/TypeGuesserInterface.php, src/Model/AuditReaderInterface.php, src/Model/ModelManagerInterface.php, src/Security/Handler/AclSecurityHandlerInterface.php, src/Security/Handler/SecurityHandlerInterface.php, src/Util/ObjectAclManipulatorInterface.php
=>  Added more specific PHPDoc to interfaces 

src/Admin/AdminInterface.php
I am targeting this branch, because this is a fixup of #5671
=> Fixed wrong phpdoc

composer.json, src/Block/AdminListBlockService.php, src/Block/AdminSearchBlockService.php, src/Block/AdminStatsBlockService.php, src/Resources/config/block.xml
Use "twig" service instead of "sonata.templating"
I am targeting this branch, because these changes try to respect BC.
```markdown
- Minimum version required for "sonata-project/block-bundle" (3.11 => 3.17).
```
=> Use "twig" service instead of "sonata.templating"

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php
=> Added more specific PHPDoc

src/Resources/views/Block/block_rss_dashboard.html.twig, src/Resources/views/CRUD/Association/edit_many_script.html.twig, src/Resources/views/CRUD/Association/edit_many_to_many.html.twig, src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/CRUD/Association/show_one_to_many.html.twig, src/Resources/views/CRUD/base_array_macro.html.twig, src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_edit_form_macro.html.twig, src/Resources/views/CRUD/base_inline_edit_field.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/CRUD/base_show_macro.html.twig, src/Resources/views/CRUD/base_standard_edit_field.html.twig, src/Resources/views/CRUD/edit_boolean.html.twig, src/Resources/views/CRUD/list_trans.html.twig, src/Resources/views/CRUD/show_array.html.twig, src/Resources/views/CRUD/show_choice.html.twig, src/Resources/views/CRUD/show_html.html.twig, src/Resources/views/CRUD/show_trans.html.twig, src/Resources/views/CRUD/tree.html.twig, src/Resources/views/Core/add_block.html.twig, src/Resources/views/Core/dashboard.html.twig, src/Resources/views/Core/tab_menu_template.html.twig, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig, src/Resources/views/Form/form_admin_fields.html.twig, src/Resources/views/Pager/base_links.html.twig
Fix some CS issues at Twig templates.
=> Fix some CS issues at Twig templates

src/Admin/AdminInterface.php
This is a followup of #5671 
```markdown
- Add more `@method` annotation to propagate new methods of `AdminInterface`
```
=>  Use more @method annotation to propagate new methods 

docs/reference/form_types.rst
Escape backslashes in markdown in order to allow them to be shown.
**PREVIEW**:
=> Escape backslashes in markdown

docs/getting_started/creating_an_admin.rst
Add a link to the chapter 24 for those who didn't read the full menu in the introduction. That might be useful for people wanting to speedup the configuration with a quick win solution.
=> Autoconfigure bundle hint

tests/Maker/AdminMakerTest.php
As @greg0ire [pointed out](https://github.com/sonata-project/SonataAdminBundle/pull/5733#discussion_r352345161),  the AdminMakerTest was creating files inside the working directory, [it was never executed before](https://github.com/sonata-project/SonataAdminBundle/pull/5733/files#diff-0463affa95ff37db3879825feab3d2bfL68). 
I've tried to use [MakerTestCase](https://github.com/symfony/maker-bundle/blob/master/src/Test/MakerTestCase.php) which I guess it the way to test it, but it wasn't that easy... I'll may try it some other time.
=> Fix creating files in the working directory with AdminMakerTest

src/Action/AppendFormFieldElementAction.php, src/Action/RetrieveFormFieldElementAction.php, src/Action/SetObjectFieldValueAction.php, src/Admin/BaseFieldDescription.php, src/Annotation/Admin.php, src/Controller/CRUDController.php, src/DependencyInjection/SonataAdminExtension.php, src/Filter/Persister/SessionFilterPersister.php, src/Form/DataTransformer/ModelsToArrayTransformer.php, src/Twig/Extension/TemplateRegistryExtension.php, src/Twig/GlobalVariables.php
Adds as many type declarations without causing BC-breaks or requiring php 7.2
Refs #5791
=> Php71 compatible bc type declarations

src/Admin/AbstractAdmin.php, src/Admin/AccessRegistryInterface.php, src/Admin/AdminInterface.php, src/Admin/LifecycleHookProviderInterface.php, src/Templating/TemplateRegistryInterface.php, tests/Admin/BreadcrumbsBuilderTest.php
I am targeting this branch, because this is a BC break.
```markdown
- Implemented `@method`s
```
=> Implement @methods

composer.json, src/Resources/config/block.xml, tests/Command/ValidatorsTest.php, tests/Functional/AppKernel.php, tests/Functional/Controller/DashboardActionTest.php
This is the minimal functional test I can think of. Not sure if it is the way it should be...
=> Add minimal functional test

docs/reference/child_admin.rst
=> actualize docs

docs/reference/action_list.rst
Right version of #5809
Based on
https://github.com/sonata-project/SonataAdminBundle/blob/9dc6d53b9563299cee5cf2fbf3c2e358498d97dd/src/Resources/views/CRUD/display_date.html.twig#L18
https://github.com/sonata-project/SonataAdminBundle/blob/9dc6d53b9563299cee5cf2fbf3c2e358498d97dd/src/Resources/views/CRUD/display_datetime.html.twig#L18
=> [docs] list date/datetime timezone option

.github/stale.yml, .travis.yml, composer.json, src/Datagrid/Pager.php
```markdown
- php 7.4 compatibility
```
=> DevKit updates for 3.x branch

src/Command/CreateClassCacheCommand.php, src/Command/ExplainAdminCommand.php, src/Command/GenerateObjectAclCommand.php, src/Command/ListAdminCommand.php, src/Command/SetupAclCommand.php, tests/Admin/Extension/LockExtensionTest.php, tests/Block/AdminListBlockServiceTest.php, tests/Block/AdminSearchBlockServiceTest.php, tests/Block/AdminStatsBlockServiceTest.php
I'm marking this as pedantic since the only code in `src` I fixed are commands, and I don't think you can get deprecations from commands.
=> Address some direct deprecations

docs/reference/routing.rst, src/Route/RouteCollection.php, tests/Route/RouteCollectionTest.php
See https://github.com/sonata-project/SonataAdminBundle/pull/5807#issuecomment-573427323 for more information.
I am targeting this branch, because BC-break free.
```markdown
- Restore function in route collection
```
=> Add restore function

src/Resources/views/Form/form_admin_fields.html.twig
```markdown
- Add support for symfony form help
```
=> Add support for symfony form help

tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
=> Applied fixes from FlintCI

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
I am targeting this branch, because Symfony 3 support is dropped.
No need for changelog (?)
=> Remove BC code for Symfony 3

src/Mapper/BaseGroupedMapper.php, tests/Mapper/BaseGroupedMapperTest.php
Closes #5806
Following https://github.com/sonata-project/SonataAdminBundle/pull/5779
I am targeting this branch, because it's not a breaking change if it's merged before the next release.
```markdown
- ifEnd throw LogicException if there is nothing to end.
```
=> Add ifEnd exception

tests/App/AppKernel.php, tests/Menu/MenuBuilderTest.php
Remove deprecations.
Closes #{put_issue_number_here}
```markdown
- Some deprecations in tests.
=> Remove deprecations

docs/reference/field_types.rst
I spent a bit of time figuring out how to create my own field type. I thought it would be helpful to document this for other users.
I am targeting this branch, because it's just documentation.
=> Document creating a custom field type

src/Datagrid/ProxyQueryInterface.php
```markdown
ProxyQueryInterface::getSortOrder phpDoc
```
=> Fix phpDoc

tests/Action/DashboardActionTest.php, tests/Admin/AdminHelperTest.php, tests/Admin/PoolTest.php, tests/Command/ExplainAdminCommandTest.php, tests/Command/GenerateObjectAclCommandTest.php, tests/Command/ListAdminCommandTest.php, tests/Command/SetupAclCommandTest.php, tests/Controller/CoreControllerTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php
Following https://github.com/sonata-project/SonataAdminBundle/pull/5866 and https://github.com/sonata-project/SonataMediaBundle/pull/1719
=> Remove ContainerInterface mocks

tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
I was trying to remove deprecations in `master` and I had to change this test, so I'd better change it in the `stable` branch.
=> Rewrite ModelManagerCompilerPassTest without mocks

tests/Twig/Extension/UnicodeStringTest.php
Tests were failing in `master`
=> Fix UnicodeString tests

docs/cookbook/recipe_customizing_a_mosaic_list.rst, src/Resources/views/CRUD/base_edit.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig, src/Resources/views/standard_layout.html.twig, tests/App/config/services.yml
I am targeting this branch, because these changes belong to the next major.
Related to #5983.
=> Use "sonata_truncate" Twig filter

src/Admin/AdminInterface.php, src/Admin/UrlGeneratorInterface.php, src/Filter/FilterInterface.php, src/Route/RouteGeneratorInterface.php
=> Add more specific phpdoc

src/Model/ModelManagerInterface.php
Master because BC-break
```markdown
- Remove `getModelIndentifier` from `ModelManagerInterface`
```
=> Merge 3.X into master and remove deprecate function

docs/reference/action_list.rst, docs/reference/field_types.rst, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Datagrid/ListMapper.php, src/Form/Type/AdminType.php, src/Resources/views/CRUD/base_array_macro.html.twig, src/Resources/views/CRUD/list_array.html.twig, src/Resources/views/CRUD/show_array.html.twig, tests/Datagrid/ListMapperTest.php, tests/Form/Type/AdminTypeTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php
=> Merge 3.x into master

tests/Functional/Controller/DashboardActionTest.php
=> Remove deprecation in test

src/Admin/AbstractAdmin.php
=> Fix deprecation message

docs/reference/action_list.rst
While using the CallbackFilter class I noticed some minor defects in the documentation/
I am targeting this branch, because docs.
=> Improve documentation of CallbackFilter

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Builder/BuilderInterface.php, src/Builder/DatagridBuilderInterface.php, src/Builder/FormContractorInterface.php, src/Builder/ListBuilderInterface.php, src/Builder/RouteBuilderInterface.php, src/Builder/ShowBuilderInterface.php, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, src/Mapper/BaseMapper.php, src/Route/QueryStringBuilder.php, src/Show/ShowMapper.php, tests/Admin/AdminTest.php, tests/App/Builder/FormContractor.php, tests/Fixtures/Mapper/AbstractDummyGroupedMapper.php, tests/Form/FormMapperTest.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Show/ShowMapperTest.php
=> Add some typehint

docs/cookbook/recipe_sortable_listing.rst, docs/reference/action_list.rst
Documentation update.
Close https://github.com/sonata-project/SonataAdminBundle/issues/6129
=> Improve doc

tests/App/Admin/FooAdmin.php, tests/App/Builder/DatagridBuilder.php, tests/App/Builder/FormContractor.php, tests/App/Datagrid/Datagrid.php, tests/App/Datagrid/Pager.php, tests/App/Model/Foo.php, tests/App/Model/FooRepository.php, tests/App/Model/ModelManager.php, tests/Fixtures/Admin/FieldDescription.php, tests/Fixtures/Admin/PostAdmin.php, tests/Fixtures/Bundle/DemoAdminBundle.php, tests/Fixtures/Controller/AbstractFooAdminController.php, tests/Fixtures/Controller/BarAdminController.php, tests/Fixtures/Controller/FooAdminController.php, tests/Fixtures/Entity/Form/FooEntity.php, tests/Fixtures/TestExtension.php
This is pedantic.
I added some phpdoc, removed some non-used methods and fixed some interface implementations.
=> Improve tests fixtures

CHANGELOG.md, UPGRADE-3.x.md, src/Admin/AdminHelper.php, src/Form/Type/AdminType.php, src/Resources/config/core.xml, src/Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php, tests/Admin/AdminHelperTest.php
=> Prepare 3.72

src/Admin/AbstractAdmin.php
Pedantic.
See https://github.com/sonata-project/SonataAdminBundle/pull/6210#discussion_r456786792
Following the NEXT_MAJOR comment would be incorrect.
I updated the explanations.
=> Improve Next_major comment

docs/reference/action_list.rst, src/Model/ModelManagerInterface.php, src/Twig/Extension/SonataAdminExtension.php
Fix tests failure
Long term fix is https://github.com/sonata-project/dev-kit/pull/795
=> Replace 3.x to avoid test failure

tests/App/Admin/TranslatedAdmin.php, tests/App/AppKernel.php, tests/App/Model/ModelManager.php, tests/App/Model/Translated.php, tests/App/config/services.yml, tests/Functional/Translator/Extractor/AdminExtractorTest.php
Add functional test for AdminExtractor.
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6224
=> Add functional test to AdminExtractor

src/Model/ModelManagerInterface.php, tests/App/Admin/EmptyAdmin.php, tests/App/Admin/FieldDescription.php, tests/App/Admin/FooAdmin.php, tests/App/Admin/TranslatedAdmin.php, tests/App/AppKernel.php, tests/App/Datagrid/Datagrid.php, tests/App/Datagrid/Pager.php, tests/App/Datagrid/ProxyQuery.php, tests/App/Model/ModelManager.php, tests/Form/Type/Operator/StringOperatorTypeTest.php, tests/Resources/XliffValidatorTestCase.php, tests/Security/Handler/AclSecurityHandlerTest.php
Done with the following command:
`php-cs-fixer fix tests --rules='void_return' --allow-risky=yes`
=> Add void return type declaration to test classes

src/Admin/AbstractAdmin.php, src/Admin/BaseFieldDescription.php, src/Controller/CRUDController.php, src/Twig/Extension/DeprecatedTextExtension.php
Done with the following command:
psalm --threads=4 --alter --issues=InvalidNullableReturnType,InvalidReturnType,MissingParamType
I rejected some changes that were not BC or did not have to do with
declarations themselves.
=> Infer parameter type declarations

.phpstan/phpstan-baseline.neon, UPGRADE-3.x.md, composer.json, src/Block/AdminListBlockService.php, src/Block/AdminSearchBlockService.php, src/Block/AdminStatsBlockService.php
I am targeting this branch, because I am trying to see if this is possible on 3.x.
```markdown
- Add support for SonataBlockBundle 4.0
```
=> Add Support for BlockBundle 4

.phpstan/phpstan-baseline.neon, .phpstan/phpstan.neon.dist, composer.json, src/Admin/AbstractAdmin.php, src/Guesser/TypeGuesserChain.php, src/Menu/MenuBuilder.php, src/Util/AdminObjectAclManipulator.php, src/Util/FormViewIterator.php, tests/Admin/AdminTest.php
Just bumping to the next level of phpstan
=> bump PHPStan to level 3

src/Resources/config/routing/sonata_admin.xml
I am targeting this branch, because this is pedantic.
=> Simplify routes config by following Symfony standards

.phpstan/phpstan-baseline.neon, .phpstan/phpstan.neon.dist, src/Action/GetShortObjectDescriptionAction.php, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/FieldDescriptionRegistryInterface.php, src/Controller/CRUDController.php, src/Datagrid/Pager.php, src/Form/ChoiceList/ModelChoiceLoader.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Maker/AdminMaker.php, src/Menu/Provider/GroupMenuProvider.php, src/Twig/Extension/SonataAdminExtension.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Admin/AdminTest.php, tests/Controller/HelperControllerTest.php
yet another bump of PHPStan level
=> bump PHPStan to level 4

src/Filter/Filter.php, src/Filter/FilterFactory.php, src/Filter/FilterFactoryInterface.php, src/Filter/FilterInterface.php, src/Filter/Persister/FilterPersisterInterface.php, src/Filter/Persister/SessionFilterPersister.php, tests/Filter/FilterFactoryTest.php, tests/Filter/FilterTest.php, tests/Fixtures/Filter/FooFilter.php
I am targeting this branch, because this is a BC break.
```markdown
- Narrow the API for classes declared under the `Sonata\AdminBundle\Filter\` namespace.
```
I have applied PHPStan level 8 when doing it and all of the errors related to the typehints are done.
=> Narrow Filter API

phpstan-baseline.neon, src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, src/Datagrid/ProxyQueryInterface.php, src/Datagrid/SimplePager.php, tests/App/Datagrid/Datagrid.php, tests/App/Datagrid/Pager.php, tests/App/Datagrid/ProxyQuery.php, tests/Datagrid/DatagridTest.php, tests/Search/SearchHandlerTest.php
I am targeting this branch, because this is a BC break.
```markdown
- Narrow the API for classes declared under the `Sonata\AdminBundle\Datagrid\` namespace.
```
I have applied PHPStan level 8 when doing it and all of the errors related to the typehints are done.
=> Narrow Datagrid API

composer.json
#Subject
Adding `ext-json` as required since json_encode/json_decode are used
=> explicitly require json extension 

.phpstan/phpstan-baseline.neon, src/Datagrid/PagerInterface.php
So IDEs can also autocomplete and phpstan does not complain.
=> Add @method to PagerInterface

.phpstan/phpstan-baseline.neon, .phpstan/phpstan.neon.dist, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/BaseFieldDescription.php, src/Admin/BreadcrumbsBuilder.php, src/Security/Handler/AclSecurityHandler.php, src/Security/Handler/AclSecurityHandlerInterface.php, src/Twig/Extension/StringExtension.php, src/Util/AdminObjectAclData.php, src/Util/AdminObjectAclManipulator.php, tests/Admin/BreadcrumbsBuilderTest.php, tests/Form/Widget/FormChoiceWidgetTest.php
`pedantic` PR
----
this will be probably the last level for 3.x branch. Level 6 gives 983 errors in 136 files.
=> bump PHPStan to level 5

src/Admin/AdminInterface.php
It's used here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L179
Then I'll add it to master.
Is it needed ?
=> Add getPagerType to AdminInterface

src/Model/ModelManagerInterface.php
Add some more generics to our project.
```markdown
- Add generics to `ModelManagerInterface`
```
=> Add generics to ModelManagerInterface

src/Guesser/TypeGuesserChain.php, src/Guesser/TypeGuesserInterface.php
This is pedantic.
I'm fixing phpstan build since the assert is now always true.
=> Fix phpstan

src/Admin/AbstractAdmin.php, src/Admin/AdminExtensionInterface.php
I am targeting this branch, because this is a pedantic change.
=> Add more type hints to AbstractAdmin

src/Action/GetShortObjectDescriptionAction.php, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/UrlGeneratorInterface.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Admin/AdminTest.php
The question object vs ?object seems already resolved when looking at storage bundles.
=> Remove some NEXT_MAJOR comment

composer.json
Related to https://github.com/sonata-project/dev-kit/issues/1026
Kinda opened to discussion.
=> Update composer.json keyword

CHANGELOG.md, UPGRADE-3.x.md, src/Action/GetShortObjectDescriptionAction.php, src/Action/SetObjectFieldValueAction.php, src/Admin/AbstractAdmin.php, src/Admin/BaseFieldDescription.php, src/Block/AdminListBlockService.php, src/Block/AdminSearchBlockService.php, src/Block/AdminStatsBlockService.php, src/Controller/HelperController.php, src/Datagrid/ProxyQueryInterface.php, src/Form/ChoiceList/ModelChoiceLoader.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Admin/AdminTest.php, tests/Block/DeprecatedAdminListBlockServiceTest.php, tests/Block/DeprecatedAdminSearchBlockServiceTest.php, tests/Block/DeprecatedAdminStatsBlockServiceTest.php, tests/Form/ChoiceList/ModelChoiceLoaderTest.php
I think it's time to make a release.
=> Prepare 3.76 release

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php
When using static analysis with `AdminInterface`, I get error when I want to `try/catch` these methods, since, according to the phpdoc, they are not throwing any errors.
=> Add some phpdoc about exceptions

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AccessRegistryInterface.php, src/Admin/AdminExtensionInterface.php
```markdown
- Add phpdoc for access mappings
```
=> Add more phpdoc

tests/Action/AppendFormFieldElementActionTest.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Action/RetrieveFormFieldElementActionTest.php, tests/Admin/AdminTest.php, tests/Admin/BreadcrumbsBuilderTest.php, tests/Controller/HelperControllerTest.php, tests/Filter/Persister/SessionFilterPersisterTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php, tests/Util/ObjectAclManipulatorTest.php
=> Improve mock usage

src/Admin/AdminInterface.php
Not sure we should merge this or just close the issue. @sonata-project/contributors 
Closes #6403 
Can you confirm it's what you want @jaikdean ?
=> Allow null as value to `AdminInterface::toString()` until next major

tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/BreadcrumbsBuilderTest.php, tests/Controller/HelperControllerTest.php, tests/Filter/FilterFactoryTest.php, tests/Form/Extension/ChoiceTypeExtensionTest.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Model/AuditManagerTest.php, tests/Route/AdminPoolLoaderTest.php, tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php, tests/Twig/Extension/TemplateRegistryExtensionTest.php, tests/Twig/GlobalVariablesTest.php
Also addresses https://github.com/sonata-project/SonataAdminBundle/pull/6422#discussion_r495573223
=> Replace mocks of ContainerInterface by Container

docs/reference/action_list.rst
Otherwise this piece of code is not working
=> Fix: Wrong documentation

phpstan-baseline.neon, phpstan.neon.dist
I would keep the stubs in `.phpstan/stubs`, WDYT?
=> Enhancement: Move PHPStan config files to the root folder

src/DependencyInjection/Compiler/ExtensionCompilerPass.php
Minor refactoring to prepare #6027.
=> Refactoring ExtensionCompilerPass

src/Maker/AdminMaker.php
Added type hint to constructor
=> Typehint Maker

src/Route/AdminPoolLoader.php, src/Route/DefaultRouteGenerator.php, src/Route/RouteCollection.php, src/Route/RouteCollectionInterface.php, src/Route/RouteGeneratorInterface.php, src/Route/RoutesCache.php, src/Route/RoutesCacheWarmUp.php
Added type hints to all files in the Route directory
=> Typehinted Route dir

phpstan-baseline.neon, psalm-baseline.xml, src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminHelper.php, src/Admin/AdminInterface.php, src/Admin/FieldDescriptionCollection.php, src/Admin/FieldDescriptionInterface.php, src/Admin/Pool.php, src/Builder/FormContractorInterface.php, src/Command/Validators.php, src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php, src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, src/Filter/Filter.php, src/Filter/FilterInterface.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Model/ModelManagerInterface.php, src/Route/RouteGeneratorInterface.php
```markdown
- Add phpdoc to array returns
```
=> Add phpdoc to array returns

src/Templating/MutableTemplateRegistryInterface.php, src/Templating/TemplateRegistry.php, src/Templating/TemplateRegistryInterface.php
I am targeting this branch, because {reason}.
```markdown
- Added parameter and return type hints to all files in the Translator dir
=> [Templating] Add param & return type hints to all files in the Templating dir

src/Action/GetShortObjectDescriptionAction.php, src/Admin/AbstractAdmin.php, src/Admin/Pool.php, src/Templating/TemplateRegistryAwareInterface.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Admin/PoolTest.php
There was a new use of `Pool::getContainer`, I've removed it before removing the method.
=> Remove next major comments

UPGRADE-4.0.md, src/Block/AdminSearchBlockService.php, src/Search/SearchHandler.php, tests/Action/SearchActionTest.php, tests/Block/AdminSearchBlockServiceTest.php, tests/Search/SearchHandlerTest.php
```markdown
- Added parameter type hints to `SearchHandler`
=> [Search] Add param type hints 

src/DependencyInjection/AbstractSonataAdminExtension.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/ExtensionCompilerPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php
```markdown
- Added parameter and return type hints to all files in the DependencyInjection dir
=> [DependencyInjection] Add param & return type hints to all files in the DI dir

src/Command/GenerateObjectAclCommand.php, src/Command/QuestionableCommand.php, src/Command/Validators.php, src/Resources/config/commands.php
=> Add typehint to command

src/Event/AdminEventExtension.php, src/Event/ConfigureEvent.php, src/Event/ConfigureMenuEvent.php, src/Event/ConfigureQueryEvent.php, src/Event/PersistenceEvent.php
```markdown
- Added parameter and return type hints to all files in the Event dir
=> [Event] Add param & return type hints to all files in the Event dir

phpstan-baseline.neon
Ignore errors:
```
Method Sonata\AdminBundle\Datagrid\Pager::next() with return type void returns mixed but should not return anything.
Method Sonata\AdminBundle\Datagrid\Pager::rewind() with return type void returns mixed but should not return anything.
```
This will be fixed in the next major release.
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Datagrid/Pager.php#L495
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Datagrid/Pager.php#L507
=> Ignore PHPStan errors in Pager::next() and Pager::rewind()

composer.json
Pedantic
Related to this conversation: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1170#issuecomment-716130507
The conflict introduce a cyclic dependency issue.
=> Remove conflict with persistence bundle

composer.json
Allow to run
```
vendor/bin/phpstan --memory-limit=1G analyse
vendor/bin/psalm
```
=> Add phpstan plugin

UPGRADE-3.x.md, src/Model/ModelManagerInterface.php, tests/App/Model/ModelManager.php
This method was added in https://github.com/sonata-project/SonataAdminBundle/commit/a92abd893a7d4ce727825d69b8152b24abfea659#diff-97440ecd150adde5ecadae8c76660025dd3bf30c93cf42bd3531da0fc69d86acR165
but[ it was never used](https://github.com/search?q=org%3Asonata-project+modelTransform&type=code).
I guess the idea was to call it to [`ArrayToModelTransformer::transform`](https://github.com/sonata-project/SonataAdminBundle/blob/6bc37adbf9840860ec9e446e6c320cff9323f03c/src/Form/DataTransformer/ArrayToModelTransformer.php#L88), but it was never done.
The other solution is to add the call, but given it has never been changed in 10 years... I guess is better to just deprecate it.
```markdown
- Deprecated `ModelManagerInterface::modelTransform()` …
```
=> Deprecate ModelManagerInterface::modelTransform method

src/Controller/CRUDController.php, src/Model/AuditReaderInterface.php, tests/Controller/CRUDControllerTest.php, tests/Fixtures/Controller/PreCRUDController.php
```markdown
- Added type hints to `CRUDController`.
=> [Controller] Add type hints

composer.json, phpstan-baseline.neon
This automatically use phpstan-symfony (and others extensions if installed).
=> Use phpstan extension installer

src/Builder/DatagridBuilderInterface.php, src/Model/ModelManagerInterface.php, src/Util/AdminObjectAclData.php
Things I'm finding trying to raise psalm levels.
=> Add some type declarations

composer.json
=> Remove useless dependency

src/Exporter/DataSourceInterface.php
=> Improve createIterator parameter name

src/Resources/views/Block/block_search_result.html.twig
I think this PR was closed to quickly
=> Correct search service reference

src/Admin/FieldDescriptionInterface.php
=> Add class-string typehint for getTargetEntity and getTargetModel

src/Admin/LifecycleHookProviderInterface.php, src/Controller/CRUDController.php
I am targeting this branch, because BC
```markdown
- Added generics to `CRUDController`
```
=> Add generic for CRUDController

src/Controller/CRUDController.php
Cherry-picked from https://github.com/sonata-project/SonataAdminBundle/pull/6655
=> Add psalm generics to the object returned by the form

src/Admin/BaseFieldDescription.php
I've just realised that I didn't add any
=> Add phpdoc to abstract methods

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, src/Admin/Pool.php, src/Twig/GlobalVariables.php, tests/Admin/AdminTest.php, tests/Admin/BaseFieldDescriptionTest.php, tests/Admin/PoolTest.php
=> Bump to 3.83

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
This call should not trigger a deprecation since it is just a check.
Closes #6664.
```markdown
- Fixed triggering a deprecation in a check.
```
=> Mute deprecation

src/Action/GetShortObjectDescriptionAction.php, src/Command/CreateClassCacheCommand.php, src/Controller/CRUDController.php, src/DependencyInjection/SonataAdminExtension.php, src/Util/FormBuilderIterator.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Reverts sonata-project/SonataAdminBundle#6682
=> Revert "Applied fixes from FlintCI"

tests/DependencyInjection/SonataAdminExtensionTest.php
I was trying to remove some NEXT_MAJOR comments and bumped into this.
=> Test sonata configuration options

tests/DependencyInjection/SonataAdminExtensionTest.php
This is the continuation of https://github.com/sonata-project/SonataAdminBundle/pull/6674, there was a missing test.
=> test default sking with sonata configuration

tests/Event/AdminEventExtensionTest.php, tests/Util/AdminObjectAclManipulatorTest.php
Similar to https://github.com/sonata-project/SonataAdminBundle/pull/6704
=> Use instances instead of mocks for tests

UPGRADE-4.0.md
Add missing upgrade note from #6537.
I am targeting this branch, because the documented change was introduced at `master` branch.
Related to #6537.
See https://github.com/sonata-project/SonataAdminBundle/pull/6537#pullrequestreview-550922734.
=> Add missing upgrade note from #6537

src/Datagrid/ProxyQueryInterface.php, src/Route/RouteCollectionInterface.php, src/Util/AdminObjectAclData.php
I am targeting this branch, because it's related to the self typehint added in major.
=> Add static phpdoc

src/Datagrid/Pager.php
Fix https://github.com/sonata-project/SonataAdminBundle/commit/94b4faee9d520ddb78a4e8878fdb91699fa48e97#r45680298
=> Allow persistence bundle to avoid deprecation

tests/Controller/CRUDControllerTest.php
This will make tests pass in https://github.com/sonata-project/SonataAdminBundle/pull/6753
=> Add tests for CRUDController::configureAdmin

tests/App/Admin/FooAdmin.php, tests/App/Admin/FooAdminWithCustomController.php, tests/App/Controller/CustomCRUDController.php, tests/App/config/services.yml, tests/Functional/Controller/CRUDControllerTest.php
Pedantic.
These tests will fail on master, it will illustrate the issue https://github.com/sonata-project/SonataAdminBundle/issues/6773
=> Add functional tests about custom controller

src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, tests/App/AppKernel.php
=> Repair unfixable trigger_error

src/Admin/AdminInterface.php
=> Improve phpdoc

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/AdminMakerCompilerPass.php, src/DependencyInjection/Compiler/AdminSearchCompilerPass.php, src/DependencyInjection/Compiler/CheckAclUserManagerCompilerPass.php, src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
=> Fix psalm issues

src/Admin/AbstractAdmin.php
Pedantic 
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1282#issuecomment-767161673
=> Do not throw exception in next major in attachAdminClass if there is no class to attach

src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Form/FormMapper.php, src/Search/SearchHandler.php, src/Show/ShowMapper.php, src/Util/AdminObjectAclData.php, src/Util/AdminObjectAclManipulator.php
I am targeting this branch, because this breaks BC.
```markdown
- Add final modifier to classes marked as `@final`.
```
=> Add final modifier to classes marked as @final

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/AdminMakerCompilerPass.php, src/DependencyInjection/Compiler/AdminSearchCompilerPass.php, src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php, src/Resources/views/CRUD/base_list.html.twig
Close https://github.com/sonata-project/SonataAdminBundle/issues/6822
=> 3.X into Master

src/Resources/config/exporter.php
Exporting doesn't work on master without setting the AdminExporter FQN as an alias. The following error occurs:
> Service "sonata.admin.admin_exporter" not found: even though it exists in the app's container, the container inside "..." is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "logger", "message_bus", "messenger.default_bus", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "sonata.admin.audit.manager", "sonata.admin.breadcrumbs_builder", "sonata.admin.object.manipulator.acl.admin", "sonata.admin.pool", "sonata.exporter.exporter", "translator" and "twig" services. Try using dependency injection instead.
I am targeting this …
=> Set alias for sonata.admin.admin_exporter

src/Admin/Pool.php, src/Maker/AdminMaker.php, src/Twig/GlobalVariables.php
=> Fix psalm and deprecations

src/Admin/AbstractAdmin.php
Similar to https://github.com/sonata-project/SonataAdminBundle/pull/6850
```markdown
- Added `AbstractAdmin::alterObject()`
- Overriding `AbstractAdmin::getObject()`
```
=> Add alterObject method

src/Admin/AbstractAdmin.php
Remove some tautologies at `AbstractAdmin`.
I am targeting this branch, because these changes are pedantic.
=> Remove some tautologies at `AbstractAdmin`

src/Admin/AbstractAdminExtension.php
```markdown
- Add missing `AbstractAdminExtension::configurePersistentParameters()`
```
=> Add missing method in AbstractAdminExtension

docs/getting_started/the_form_view.rst
=> [Doc] Minor code syntax issue

src/Controller/CRUDController.php
Use `while` statement instead of `do / while` at `CRUDController::assertObjectExists()`.
See https://github.com/sonata-project/SonataAdminBundle/pull/6917#issuecomment-792095431.
```markdown
- Issue "Right side of && is always true" detected by PHPStan.
```
=> Use `while` statement instead of `do / while` at `CRUDController::assertObjectExists()`

docs/cookbook/recipe_custom_action.rst, docs/cookbook/recipe_improve_performance_large_datasets.rst, docs/cookbook/recipe_overwrite_admin_configuration.rst, docs/cookbook/recipe_sonata_admin_without_user_bundle.rst, docs/cookbook/recipe_sortable_listing.rst, docs/getting_started/installation.rst, docs/reference/action_export.rst, docs/reference/action_list.rst, docs/reference/advanced_configuration.rst, docs/reference/field_types.rst, docs/reference/form_types.rst, docs/reference/search.rst, docs/reference/security.rst, docs/reference/templates.rst
Just some minor fixes found while reviewing the docs. Cheers!
=> [Doc] Fixed some minor syntax issues

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php
No changelog needed since there is no release.
The signature should be consistent with others methods.
=> Make consistent signature

src/Twig/Extension/GroupExtension.php, src/Twig/Extension/RenderElementExtension.php, src/Twig/Extension/SecurityExtension.php, src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/TemplateRegistryExtension.php, src/Twig/Extension/XEditableExtension.php
=> Improve typehint for phpstan

UPGRADE-3.x.md, src/Form/DataTransformer/ArrayToModelTransformer.php, src/Model/ModelManagerInterface.php, tests/App/Model/ModelManager.php
Closes #6929.
```markdown
- `ModelManager::reverseTransform()`
- `ModelManager::modelReverseTransform()`
```
=> Add reverseTransform method

src/Builder/BuilderInterface.php, src/Builder/DatagridBuilderInterface.php, src/Builder/FormContractorInterface.php, src/Builder/ListBuilderInterface.php, src/Builder/ShowBuilderInterface.php, src/Exporter/DataSourceInterface.php
=> Improve typehint

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
=> Remove unused values

src/Admin/AdminInterface.php, src/Exporter/DataSourceInterface.php
Need https://github.com/sonata-project/exporter/pull/463
```markdown
- Return typehint of DataSourceInterface::createIterator
```
=> Add typehint

tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
There was a commented out test, not sure why, this replaces it with an up-to-date test.
=> Add test to FormTypeFieldExtension::buildForm

src/Resources/config/core.php, tests/DependencyInjection/SonataAdminExtensionTest.php
Fix https://github.com/sonata-project/SonataAdminBundle/pull/7009#issuecomment-812599394
=> Remove alias

docs/reference/action_list.rst
As discussed with @VincentLanglet via Slack I noticed that the docs are not up-to-date here.
=> Fix documentation for customizing list actions

src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
Follow-up of https://github.com/sonata-project/SonataAdminBundle/pull/7055
=> Use AdminInterface::generateObjectUrl instead of generateUrl

src/Resources/config/twig.php
Should've been removed in https://github.com/sonata-project/SonataAdminBundle/pull/6996
=> Remove unused arguments

src/Resources/translations/SonataAdminBundle.ar.xliff, src/Resources/translations/SonataAdminBundle.eu.xliff, src/Resources/translations/SonataAdminBundle.hr.xliff, src/Resources/translations/SonataAdminBundle.lt.xliff, src/Resources/translations/SonataAdminBundle.no.xliff, src/Resources/translations/SonataAdminBundle.pt.xliff, src/Resources/translations/SonataAdminBundle.ro.xliff, src/Resources/translations/SonataAdminBundle.sv_SE.xliff, src/Resources/translations/SonataAdminBundle.zh_CN.xliff, tests/Block/AdminPreviewBlockServiceTest.php
Mock the interface instead of the implementation and replace deprecated class.
=> Fix tests for 4.x

src/Action/SearchAction.php, src/Twig/Extension/BreadcrumbsExtension.php, tests/Action/DashboardActionTest.php, tests/Action/SearchActionTest.php, tests/Fixtures/StubTranslator.php, tests/Twig/Extension/BreadcrumbsExtensionTest.php
I put it in the wrong property
=> Fix next major comment

src/Controller/CRUDController.php, src/DependencyInjection/Compiler/AliasDeprecatedPublicServicesCompilerPass.php, src/Resources/config/commands.php, src/Resources/config/core.php, src/Resources/config/exporter.php, src/Resources/config/form_types.php, src/Resources/config/menu.php, src/Resources/config/route.php, src/Resources/config/security.php, src/Resources/config/twig.php, src/Resources/config/validator.php, src/SonataAdminBundle.php, tests/Controller/CRUDControllerTest.php, tests/DependencyInjection/Compiler/AliasDeprecatedPublicServicesCompilerPassTest.php, tests/SonataAdminBundleTest.php
I am targeting this branch, because it need to be showed in the current version
Closes #6962
```markdown
- Deprecated public services
```
=> Deprecate public services

composer.json, src/Admin/AbstractAdmin.php, src/Admin/Pool.php, src/FieldDescription/BaseFieldDescription.php, src/FieldDescription/FieldDescriptionFactoryInterface.php, src/FieldDescription/FieldDescriptionInterface.php, src/Model/ModelManagerInterface.php, src/SonataConfiguration.php
Pedantic
Need https://github.com/vimeo/psalm/issues/5647
=> Use phpstan-type instead of psalm

src/DependencyInjection/Admin/AbstractTaggedAdmin.php, src/DependencyInjection/Admin/TaggedAdminInterface.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, tests/Admin/AdminTest.php
Closes: #7041
Closes: #7035
```markdown
- `TaggedAdmin::setListModes()`
- `TaggedAdmin::showMosaicButton()`
```
=> Use setListModes instead of showMosaicButton

src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
Bugfix
Closes #7124.
```markdown
- Unclosed "{" on src/Resources/views/CRUD/Association/edit_one_to_one.html.twig
```
=> Fix OneToOne template

src/Resources/translations/SonataAdminBundle.bs.xliff, src/Resources/translations/SonataAdminBundle.fr.xliff, src/Resources/translations/SonataAdminBundle.hr.xliff, src/Resources/translations/SonataAdminBundle.hu.xliff, src/Resources/translations/SonataAdminBundle.it.xliff, src/Resources/translations/SonataAdminBundle.ja.xliff, src/Resources/translations/SonataAdminBundle.lb.xliff, src/Resources/translations/SonataAdminBundle.lt.xliff, src/Resources/translations/SonataAdminBundle.lv.xliff, src/Resources/translations/SonataAdminBundle.nl.xliff, src/Resources/translations/SonataAdminBundle.no.xliff, src/Resources/translations/SonataAdminBundle.pl.xliff, src/Resources/translations/SonataAdminBundle.pt.xliff, src/Resources/translations/SonataAdminBundle.pt_BR.xliff, src/Resources/translations/SonataAdminBundle.ro.xliff, src/Resources/translations/SonataAdminBundle.ru.xliff, src/Resources/translations/SonataAdminBundle.sk.xliff, src/Resources/translations/SonataAdminBundle.sl.xliff, src/Resources/translations/SonataAdminBundle.sr_Cyrl.xliff, src/Resources/translations/SonataAdminBundle.sr_Latn.xliff, src/Resources/translations/SonataAdminBundle.sv_SE.xliff, src/Resources/translations/SonataAdminBundle.tr.xliff, src/Resources/translations/SonataAdminBundle.uk.xliff, src/Resources/translations/SonataAdminBundle.zh_CN.xliff, src/Resources/translations/SonataAdminBundle.zh_HK.xliff, src/Resources/views/CRUD/base_list.html.twig
Closes #7122.
```markdown
- Fix displays of the link to go to page 1 when accessing on a non-existent List page
```
=> Fix displays of the link to go to page 1

src/Resources/public/css/styles.css
Closes #7160 
```markdown
- Fix font route to be relative and not absolute.
```
=> Fix fonts route

src/Resources/views/CRUD/Association/edit_many_script.html.twig
```markdown
- Missing comma & bracket
```
=> Missing comma & bracket

src/Resources/views/CRUD/Association/edit_many_script.html.twig
```markdown
- `edit_many_script.html.twig` rendering
```
=> Fix missing comma and bracket

composer.json
Pedantic
see https://github.com/sonata-project/SonataAdminBundle/security/dependabot
=> Avoid github security alert

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
One developer of my team didn't understand the exception message.
I'm trying to improve it.
=> Improve exception message

UPGRADE-4.0.md, src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Follow https://github.com/sonata-project/SonataAdminBundle/pull/7238#issuecomment-856777962
=> Revert passing $request to renderWithExtraParam

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php, tests/EventListener/ConfigureCRUDControllerListenerTest.php
The code is the same, so we can remove it from `CRUDController`
=> Use AdminFetcher in CRUDController

phpstan-baseline.neon, src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Event/ConfigureEvent.php, src/Event/PersistenceEvent.php, src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, src/Mapper/MapperInterface.php, src/Show/ShowMapper.php
Backport of https://github.com/sonata-project/SonataAdminBundle/pull/7278
```markdown
- Add generic to MapperInterface and all extending classes.
- Added generic to ConfigureEvent and PersistenceEvent.
```
=> Add generic to Mapper and Event

UPGRADE-3.x.md, src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php, src/Filter/Filter.php, src/Search/ChainableFilterInterface.php, src/Search/SearchHandler.php, tests/Search/SearchHandlerTest.php
This is a way to finish the https://github.com/sonata-project/SonataAdminBundle/pull/7272 PR of @phansys.
Closes #7272.
Closes #7096 .
```markdown
- `ChainableFilterInterface`.
```
=> Add chainable filter interface

src/Admin/AbstractAdmin.php
=> Improve configureBatchActions phpdoc

docs/cookbook/recipe_select2.rst
Pr https://github.com/sonata-project/SonataAdminBundle/pull/7294 backport to 3.x
=> Add doc about select2 minimum results

src/Datagrid/Datagrid.php, src/Resources/views/CRUD/base_list.html.twig
Pedantic, just improving some performances.
=> Reduce some methods call number

src/Resources/views/Core/add_block.html.twig, src/Resources/views/Core/user_block.html.twig
I discover the block in the `add_block` was called `user_block` like the one in the `user_block`.
I first wanted to fix this, but then I start wondering why a block for the full template would be use for, except overriding the whole template, which can already be done.
=> Remove block from `add_block` and `user_block`

tests/App/AppKernel.php
I am targeting this branch, because Symfony 5 support is here.
Pedantic since the deprecations are only on tests, but still nice to have them solved.
=> Avoid Symfony 5.3 deprecations

src/Admin/AbstractAdmin.php, src/Command/GenerateObjectAclCommand.php, src/Controller/CRUDController.php, src/Datagrid/SimplePager.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Form/DataTransformerResolver.php, src/Form/Extension/ChoiceTypeExtension.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Form/Type/AdminType.php, src/Form/Type/ModelAutocompleteType.php, src/Form/Type/ModelType.php, src/Mapper/BaseGroupedMapper.php, src/Menu/Matcher/Voter/ActiveVoter.php, tests/Datagrid/DatagridTest.php, tests/Form/AbstractLayoutTestCase.php, tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Menu/Provider/GroupMenuProviderTest.php, tests/Search/SearchHandlerTest.php
I am targeting this branch, because this is where we are trying to add the strict plugin.
Pedantic, it should only add more strict checks. Feel free to close if you prefer to merge your PR, it will probably be more complete than this one.
Still 150 errors to go.
=> Fix some phpstan strict rules errors

composer.json, phpstan-baseline.neon
```markdown
- Added support for `psr/log` ^2.0.
```
Requires release of `sonata-project/cache`
=> Add psr/log version 2

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
I am targeting this branch, because Bugfix.
Closes #7361.
```markdown
- Requesting a non existent service "sonata.admin.exporter.do-not-use".
```
=> Fix sonata.admin.exporter usage

composer.json, src/Form/FormMapper.php
=> Implement FormMapper from BlockBundle

src/Controller/CRUDController.php
I tried to bump to level 2 of psalm on my project and got some errors.
I discovered that suppressing on the property in the CRUDController solve the issues.
=> Avoid error when extendings CRUDController

src/ArgumentResolver/AdminValueResolver.php, src/Request/AdminFetcherInterface.php, tests/ArgumentResolver/AdminValueResolverTest.php
```markdown
- Do not throw error when trying to inject an admin as a service in an action.
```
=> 3.x into 4.x

src/Admin/AbstractAdmin.php, src/DependencyInjection/Configuration.php
=> Use Permission Map constants

src/Resources/views/Block/block_admin_preview.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_list_flat_inner_row.html.twig, src/Resources/views/CRUD/base_list_inner_row.html.twig, src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig, tests/App/Admin/FooAdmin.php, tests/App/Builder/ListBuilder.php, tests/App/Builder/ShowBuilder.php, tests/App/FieldDescription/FieldDescription.php, tests/App/FieldDescription/FieldDescriptionFactory.php, tests/App/Model/Foo.php
Closes #7447.
```markdown
- Display of list when a field is called `elements`.
```
=> Fix list when a field is called elements
