sonata-project/SonataAdminBundle

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

| Fixed tickets | #1929
The label of batch action is already translated so we can just display it.

Fixed problem with batch action confirmation label

---

Resources/views/CRUD/base_list.html.twig

Updated list_filters_actions block to return nothing if there are no filters defined.
This is important because in standard_layout.html.twig there is a check for emptiness:
{# in standard_layout.html.twig #}
{% block sonata_page_content_nav %}
{% if _tab_menu is not empty or _actions is not empty or _list_filters_actions is not empty %}
{# ... #}
{% endblock %}
Prior to this update list_filters_actions was returning the outer list with "Filter ^" but no options in the sub-menu.

Fix empty filter list

---

Mapper/BaseGroupedMapper.php
Tests/Fixtures/Admin/CleanAdmin.php
Tests/Form/FormMapperTest.php
Tests/Show/ShowMapperTest.php

| BC breaks?    | no (these methods were not released in tagged version, so it's OK to change them)

Fixed methods if_true, if_false, if_end in BaseGroupedMapper to camelCase, added tests

---

Resources/doc/reference/console.rst

Within the online documentation, the command to generate a Sonata Admin class is specified as:
php app/console sonata:admin:generate YourNS\FooBundle\Entity\Bar
However, this appears to throw up an error message stating that a fully qualified class model does not exist.
Using forward slashes instead of back slashes works without throwing back this message and ensures that the admin class is successfully generated, e.g.
php app/console sonata:admin:generate YourNS/FooBundle/Entity/Bar

sonata:admin:generate - replace backslashes with forward slashes

---

Mapper/BaseGroupedMapper.php
Tests/Mapper/BaseGroupedMapperTest.php

If an Admin didn't use tabs, the `default` tab will never be closed. This causes issues when an admin extension adds a tab to the formmapper (it'll result in the "there is a current open tab" exception).

Add a way to see if a tab group is open

---

Datagrid/DatagridMapper.php
Tests/Datagrid/DatagridMapperTest.php

Fixed bug with toString conversion if fieldDescription object is added to DatagridMapper, improved error messages

---

DependencyInjection/Compiler/ExtensionCompilerPass.php

This is a bug fix that exists in all SonataAdminBundle versions. I don't know which version is the oldest still maintained version, so I've targeted 2.3.
`hasDefinition` only searches for real service definitions, `findDefinition` searches through both real service definitions and aliases.
This is usefull as we're going to rename some service IDs for admin extensions and the CMF, but we want to be compatible with older versions (we do that by using aliases). Unfortunately, this wasn't support yet by this bundle.

Update ExtensionCompilerPass to support aliases

---

Resources/views/standard_layout.html.twig

Add locale js of moment.js according to the current symfony locale in order to translate the datetimepicker
I used the same way than the one for select2.

Include appropriate moment.js locale file

---

.travis.yml

Instead of testing each Symfony version on each PHP version, this updated travis file tests only the latest stable Symfony version (2.6.*) against all PHP versions and then only tests other Symfony versions against the latest PHP version (5.6).
This will reduce the amount of jobs, which is a good thing, since Travis does only allow 6 parrallel running jobs per organization.
Btw, I've also removed Symfony 2.4, as it has reached end of life.

Reduce Travis jobs

---

Resources/public/css/styles.css

tidies up the use of sonata_type_date_picker inside the filter box
before image: http://postimg.org/image/62hpl3vw4/
after image: http://postimg.org/image/4w4h7otbn/

fix date picker styles inside filter box

---

Resources/doc/reference/form_types.rst

Wrong variable naming in example of sonata_type_model_autocomplete in form_types page.
$enitity should be $entity.

Fix wrong variable naming enitity in form_types

---

Resources/views/Form/form_admin_fields.html.twig

On autocompletion, the url contains the host of the current request.
My issue is when symfony is used behind a reverse proxy the rewrite the domain name, the AJAX request for auto completion is done on the wrong host.

Use relative urls for model_autocomplete_widget

---

Form/Type/AclMatrixType.php
Resources/views/CRUD/base_acl.html.twig
Resources/views/CRUD/base_acl_macro.html.twig
Tests/Form/Type/AclMatrixTypeTest.php
Util/AdminObjectAclManipulator.php

This PR fixes the `InvalidArgumentException` on the ACL editor when a role or an user contains illegal characters.
Example with the username `baptiste.meyer`:
```
Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException:
"The name "baptiste.meyer_VIEW" contains illegal characters.
Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":")."
at /Users/meyerb/Documents/workspace/france-autopartage/vendor/symfony/symfony/src/Symfony/Component/Form/FormConfigBuilder.php line 894 
```
This bug was introduced in #2600, see https://github.com/sonata-project/SonataAdminBundle/commit/d562b1e614e29f757d68ee3c416780c0c78ded05#commitcomment-9546496.
cc @sroze @dunglas

Fix form exception for ACL editor

---

Resources/doc/reference/getting_started.rst

I was setting up admin panel following the doc and it took me a few minutes to figure out correct value of manager_type for ODM storage. Example in the docs is valid only for ORM, so I added the info so that no one else gets stuck when using other storages.

Doc: info about different manager_type values to be set depending on storage

---

Form/Extension/ChoiceTypeExtension.php
Resources/config/form_types.xml
Resources/doc/reference/form_types.rst
Resources/public/Admin.js
Resources/views/Form/form_admin_fields.html.twig
Tests/Form/Extension/ChoiceTypeExtensionTest.php

This pr add a "sortable" option for multiple choice.
Exemple:
```
$builder->add('availability', 'choice', array(
'choices'   => array(
'morning'   => 'Morning',
'afternoon' => 'Afternoon',
'evening'   => 'Evening',
),
'multiple'  => true,
'sortable'  => true
));
```
this initialise the widget with select2 sortable

feat(form): add sortable option for multiple choice widget

---

Resources/doc/reference/preview_mode.rst

In https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/preview.html.twig
there is ``sonata-preview-form-container`` and not ``sonata-preview-form`` class.

Fixed wrong class in preview documentation

---

Mapper/BaseGroupedMapper.php
Mapper/BaseMapper.php

Fixes PhpStorm auto-completion for this kind of code, in a class extending `BaseMapper` : 
```
protected function configureShowFields(ShowMapper $showMapper)
{
$showMapper
->with('something')
->add('foo', 'text') // <-- add is not recognized without this PR
->end();
}
```

Adapt PHPDoc Block @return value for proper auto-completion.

---

.travis.yml

From some tests on the CMF, it looks like Sonata has some problems with PHP 7. Let's find out if we can fix them :)

Test against PHP7

---

Datagrid/Datagrid.php
Filter/Filter.php
Resources/doc/reference/action_list.rst
Resources/views/CRUD/base_list.html.twig
Tests/Datagrid/DatagridMapperTest.php
Tests/Datagrid/DatagridTest.php
Tests/Filter/FilterTest.php

| Fixed tickets | #2668
This PR deprecates #2490.
The current master version of SonataAdmin hides all filters by default which is great UI improvement. But there are some use cases, when we need some filters to be always visible.
Instead of adding another option (which may be confusing) this PR uses alreay available option `show_filter`. The default value of this option is changed from `true` to `null`. `null` in this context means: use the default behaviour of filters (hidden, but usable after check the checkbox).
If it will be set to `true`, the filter will be always visible.

Improved `show_filter` filter option to always display filter.

---

DependencyInjection/Compiler/ExtensionCompilerPass.php

I commited some broken code to Sonata recently, this PR fixes it.
`findDefinition` throws an exception when the definition does not exists, which is not what you want.
`hasDefinition` only searches in the definitions, which is not what you want as it doesn't support aliases
`has` searches in both definitions and aliases, which is what you want.

Fixed service existence check

---

Resources/views/CRUD/base_list.html.twig
Resources/views/Pager/base_links.html.twig

This PR give a fix for not needed overflow on table-responsive with twitter bootsrap `3.3.*`.
It's related to #2582.
Batch action form, export, pager and page links are now on `list_footer` block instead of `table_block` because this is now outside the table.
Please feel free to review and comment this PR to fix and/or improve it! :+1: 
Thanks.

Fix not needed dropdown table-responsive overflow

---

Twig/Extension/SonataAdminExtension.php

This PR simplify use the group ``label_catalogue`` option to translation the items labels.

Use label_catalogue to translate menu items labels

---

Resources/views/Form/form_admin_fields.html.twig

File inputs should not have a ``form-control`` class (see http://getbootstrap.com/css/#forms)

Do not add form-control class to file inputs

---

Resources/views/CRUD/base_edit_form_macro.html.twig

I think it's a more apprioriate class name. It's better to override "box-primary" instead of "box-success" to customize this color.
**Before**
**After**

Replace box-success with box-primary

---

Resources/views/CRUD/base_list.html.twig
Resources/views/Pager/base_results.html.twig

Do not add ``form-control`` class to lists bottom selects (batch actions and element per page choices) if select2 is used.

Do not add form-control class if select2 is used

---

DependencyInjection/Configuration.php
Resources/public/css/styles.css
Resources/views/Form/filter_admin_fields.html.twig

Needs https://github.com/sonata-project/SonataCoreBundle/pull/146
This PR updates select2 css for bootstrap : 
**Filters**
**Forms**
**Lists (bottom)**

Add select2-bootstrap css

---

Resources/public/css/styles.css
Resources/views/CRUD/base_list.html.twig

Filters inputs are not more large and responsive.
***Large***
**Before**
**After**
***Small***
**Before**
**After**

Update datagrid filters template

---

Resources/public/App.js
Resources/translations/SonataAdminBundle.ar.xliff
Resources/translations/SonataAdminBundle.bg.xliff
Resources/translations/SonataAdminBundle.ca.xliff
Resources/translations/SonataAdminBundle.cs.xliff
Resources/translations/SonataAdminBundle.de.xliff
Resources/translations/SonataAdminBundle.en.xliff
Resources/translations/SonataAdminBundle.es.xliff
Resources/translations/SonataAdminBundle.eu.xliff
Resources/translations/SonataAdminBundle.fa.xliff
Resources/translations/SonataAdminBundle.fr.xliff
Resources/translations/SonataAdminBundle.hr.xliff
Resources/translations/SonataAdminBundle.hu.xliff
Resources/translations/SonataAdminBundle.it.xliff
Resources/translations/SonataAdminBundle.ja.xliff
Resources/translations/SonataAdminBundle.lb.xliff
Resources/translations/SonataAdminBundle.lt.xliff
Resources/translations/SonataAdminBundle.nl.xliff
Resources/translations/SonataAdminBundle.pl.xliff
Resources/translations/SonataAdminBundle.pt.xliff
Resources/translations/SonataAdminBundle.pt_BR.xliff
Resources/translations/SonataAdminBundle.ro.xliff
Resources/translations/SonataAdminBundle.ru.xliff
Resources/translations/SonataAdminBundle.sk.xliff
Resources/translations/SonataAdminBundle.sl.xliff
Resources/translations/SonataAdminBundle.uk.xliff
Resources/translations/SonataAdminBundle.zh_CN.xliff
Resources/views/CRUD/base_list.html.twig

The advanced filters are hidden with JS on page load, if all the visible ones are empty.

Add advanced filters toggle link

---

Resources/public/Admin.js
Resources/views/CRUD/base_list.html.twig
Resources/views/Form/filter_admin_fields.html.twig
Resources/views/Form/form_admin_fields.html.twig
Resources/views/Pager/base_results.html.twig

Remove the ``form-control`` class dynamically instead of doing it in every template.

Remove form-control class on select2 init

---

Admin/Admin.php

This PR adds ``'show_filter' => false`` to the filter automatically added to a child admin.
**Before**
**After**

Hide automatic parent admin filter

---

Command/ExplainAdminCommand.php
Controller/CRUDController.php
Controller/CoreController.php
Form/Extension/ChoiceTypeExtension.php
Resources/config/routing/sonata_admin.xml
Tests/Command/ExplainAdminCommandTest.php
Tests/Controller/CRUDControllerTest.php
Tests/Controller/CoreControllerTest.php
Tests/Datagrid/ListMapperTest.php
Tests/Fixtures/Resources/config/routing/routing.xml
Tests/Util/AdminObjectAclDataTest.php
Tests/tests/bootstrap.php
composer.json

The CMF tests contain much deprecation errors coming from SonataAdmin.
That's why this PR tries to remove as much deprecation errors as possible. As you can see in the tests, there are still some deprecation errors, but I don't have a solution for it which supports both 2.3 and 2.7.
I tried to make everything as BC as possible.
Meanwhile, I also integrated the very usefull PhpUnit Bridge which does a great job in helping with deprecation errors.

Remove as much deprecation errors as possible

---

Route/DefaultRouteGenerator.php
Tests/Route/DefaultRouteGeneratorTest.php

An admin will include all the routes for child admins when generating
routes. So no need to let a child admin populate any caches.
This should fix #2142.

Skip child admin when loading route cache

---

Resources/public/Admin.js

When the filter form is submitted, all the hidden fields are cleared. This way, not extra fields will be submitted after : 
- removing a whole filter line (by unchecking it from the dropdown)
- hidding the advancers filters

Clear hidden filters on submit

---

Resources/views/Form/form_admin_fields.html.twig

This will fix https://github.com/sonata-project/SonataAdminBundle/issues/2783
However, I wonder if we should not make the ``admin_pool`` as a global variable in twig template ? I don't understand in which cases it is not defined.

Check if admin_pool is defined in admin form template

---

Resources/translations/SonataAdminBundle.de.xliff

* Fixed pluralization of list results count
* Resulting in a 500 error when having 0 search results

Got 500 errors when using German als locale

---

Route/AdminPoolLoader.php

I've made the check more readable and extracted the route type name into an `AdminPoolLoader` class constant. I think this improves readability and understandability a bit.

Extracted route type into constant, simplified type comparison

---

Resources/public/css/layout.css
Resources/public/css/styles.css
Resources/views/Form/form_admin_fields.html.twig

**Before**
**After**
***Date***
***Time***
***Datetime (without seconds)***
I had to removed this css because it causes each datetime input to be 80% large only. Is it still usefull ?
```
.sonata-ba-form .select2-container {
width: 80% !important;
}
```

Update date, time and datetime form template

---

Resources/views/CRUD/base_list_field.html.twig

The url for inline editables in admin listings was missing support for persistent parameters

Support for persistent parameters in list editables

---

DependencyInjection/SonataAdminExtension.php
Form/Extension/Field/Type/FormTypeFieldExtension.php
Resources/config/form_types.xml
Resources/views/Form/form_admin_fields.html.twig
Tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php

See : https://github.com/sonata-project/SonataAdminBundle/commit/e710524a7b7ea58a84924ebef3b1a042259fa531#commitcomment-10090830
To check ``form_type`` in form templates, we can't use : 
- ``admin_pool`` because it's not necessarily available
- ``sonata_admin.admin.getAdminPool()`` because ``sonata_admin.admin`` is not necessarily defined (some forms type do not have a linked admin).
So this PR pass the ``options`` to the templates., this way we don't have to rely on the admin pool anymore.

Pass options in form templates

---

Controller/CRUDController.php

When doctrine removes an object, its identifier is set to ``null``. If this identifier is used in the ``__toString`` method, then getting it after the ``delete($object)`` will lead to an incomplete string.
**Before**
``Element "Object number #" was successfully deleted``
**After**
``Element "Object number #123" was successfully deleted``

Get the object name before doctrine drops its identifier

---

composer.json

Since `ErrorElement` namespace change, sonata-admin must use sonata-block ~2.3.

sonata-project/block-bundle ~2.3

---

Resources/doc/reference/action_list.rst

Though the `SonataDoctrineORMAdminBundle` has its own docs the `queryBuilder` was mentioned in a previous chapter.
That's why I added the `full_text` filter example.
I tried to add different approaches and use cases. I hope this covers a lot of stuff.
Can somebody check for typos and markup?
Feedback @caponica ?

Improve docs for (default) filter usage see issue #2529 and #1519

---

Resources/views/Form/form_admin_fields.html.twig

On chrome (at least), ``sonata_type_collection`` type with ``edit => inline`` and ``inline => table`` options are not displayed correctly. Adding the ``form-inline`` class fixes the problem.
**Before**
**After**

Add form-inline class to inline editable fields

---

Form/FormMapper.php
Tests/Form/FormMapperTest.php

Since commit https://github.com/sonata-project/SonataAdminBundle/commit/187b3d2c9577b83332af6d31d946f7fb31893002, the FormMapper didn't accept FormBuilder instances anymore.
Some references to FormBuilder were not updated to FormBuilderInterface. I've provided a test to reproduce.

Fix FormBuilder references in FormMapper

---

Resources/views/CRUD/show_array.html.twig

Until now, show ``array`` type was displayed inline, which can be hard to read when there is a lot of data :
This PR displays it vertically by default :
However, you there is now an ``inline`` option that you can set to ``true`` to get the old behavior.
If you prefer to display it inline by default instead, I can update my PR.

Add inline option to show array type

---

composer.json

Since this commit https://github.com/sonata-project/SonataAdminBundle/commit/d25ef67bf925221b2f5f2a1fe03f21ad252a7ad2, tests are broken.
``doctrine/inflector`` is required by ``doctrine/common`` only from version ``2.4``
Moreover, the ``symfony/property-access`` component is missing too (used here https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L934)

Add missing dependencies to fix tests

---

Resources/public/css/layout.css

@rande Like you asked in https://github.com/sonata-project/SonataAdminBundle/pull/2834#issuecomment-82388376
**Normal**
**Hovered**
I didn't use the ``btn-outline`` class for 2 reasons : 
- it already exists in AdminLte with a different behavior
- it avoid to add a specific class on these buttons across different bundles

Only show border on actions buttons

---

Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php

In these screenshots, the ``Affiliation``, ``Media`` and ``Reporting`` items are empty because the user is not allowed access to any of their children. However, they are visible.
This PR fixes it.
Before | After
------------ | -------------

Do not display menu item if no child is displayed

---

Resources/public/Admin.js

This fix issue #2857 that was introduced on PR #2831.
Fixed issue: The counter was not properly initialized (counting nothing) and always started by 0 on page load.
Improvement: Instead of a global `counter` variable, I make a `counters` to count element number collection by collection. I think it's very more proper.
@rande @EmmanuelVella can you please review and merge it? Even if is dev branch, this issue is quite critical.
Thanks.

Fix bad form collection JS counter

---

DependencyInjection/Configuration.php
Resources/config/twig.xml
Resources/doc/cookbook/recipe_knp_menu.rst
Resources/views/Menu/sonata_menu.html.twig
Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php

This PR allows usage of a custom Knp menu as a menu group:
sonata_admin:
dashboard:
groups:
my_group:
provider: 'MyBundle:MyMenuProvider:getMyMenu'

Custom Knp menu

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

The `sonata_type_model_autocomplete`  form type broke the symfony DomCrawler.
HTML tags are not allowed inside `<script>` tags: http://stackoverflow.com/a/1450633/450789
Where can I add a test that use the DomCrawler ?

Fix invalid HTML in JS causing test errors

---

Resources/views/Form/form_admin_fields.html.twig

Bootstrap button must have a style class after `.btn`.
I propose 3 solutions.
Note: This solution is nearly the same as the actual design.
If you choose solution 1, just merge this PR right now to take modifications effect! :+1: 
If you want another, tell me so I will update my PR.
Thanks.

Specify btn classes on sonata-collection buttons

---

Admin/BaseFieldDescription.php
Tests/Admin/BaseFieldDescriptionTest.php
Tests/Fixtures/Entity/FooCall.php

Related to https://github.com/sonata-project/SonataAdminBundle/pull/2262
With this PR, the ``FieldDescription::getFieldValue`` method can now handle magic ``__call`` methods by passing the ``fieldName`` **and** the ``parameters`` option.

Handle __call method in FieldDescription::getFieldValue

---

Resources/views/CRUD/base_list.html.twig

I suppose the class was accidentally removed here : https://github.com/sonata-project/SonataAdminBundle/commit/4505646a37d975a0fff27865253e9f92d237cd4f

Add sonata-ba-list class (fixes regression)

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Hello,
First of all, thank you for this amazing bundle!
I found an issue with the sonata_type_model_autocomplete with this error:
```text
InvalidArgumentException: Malformed field path "s5527e68f85fe3[contact]_autocomplete_input"
/space/home/vchabot/paprika/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/FormFieldRegistry.php:211
/space/home/vchabot/paprika/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/FormFieldRegistry.php:34
/space/home/vchabot/paprika/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Form.php:293
/space/home/vchabot/paprika/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Form.php:483
/space/home/vchabot/paprika/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Form.php:458 …
```

Remove mal-formatted name for autocomplete type

---

Resources/views/CRUD/base_edit_form.html.twig

Fix method to generate tab id to avoid conflict when using sonata_type_model field which open an admin with tabs too.
Pb : When you click on tab of loaded admin, it trigger original admin tab

Fix tab id in forms

---

Resources/doc/reference/security.rst

For a while, it wasn't obvious to me where these role names were coming from, until renaming services broke my security rules.

Added info about how role names are built.

---

Resources/views/CRUD/base_edit_form.html.twig

Added block `sonata_form_action_url` to easier overload form action url

---

Form/Extension/ChoiceTypeExtension.php
Form/Extension/Field/Type/FormTypeFieldExtension.php
Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
Form/Type/AclMatrixType.php
Form/Type/AdminType.php
Form/Type/ChoiceFieldMaskType.php
Form/Type/Filter/ChoiceType.php
Form/Type/Filter/DateRangeType.php
Form/Type/Filter/DateTimeRangeType.php
Form/Type/Filter/DateTimeType.php
Form/Type/Filter/DateType.php
Form/Type/Filter/DefaultType.php
Form/Type/Filter/NumberType.php
Form/Type/ModelAutocompleteType.php
Form/Type/ModelHiddenType.php
Form/Type/ModelReferenceType.php
Form/Type/ModelType.php
Form/Type/ModelTypeList.php

This PR fixes deprecated notices since SF 2.7.

Fix deprecated forms setDefaultOptions method

---

Block/AdminListBlockService.php
Form/Type/AclMatrixType.php

Fix deprecated `setAllowedTypes` method parameters from SF 2.6.

Fix deprecated setAllowedTypes method

---

Admin/Admin.php
Tests/Admin/AdminTest.php

This PR is submitted after bug dicovered when following online doc to create a "clone" action on an entity with UUID as Identifier.

Admin::getSubject() is not valid for UUID as identifier

---

Admin/Admin.php
Admin/BaseFieldDescription.php
Datagrid/ListMapper.php
Resources/doc/cookbook/recipe_virtual_field.rst
Resources/doc/index.rst
Tests/Admin/BaseFieldDescriptionTest.php
Tests/Datagrid/ListMapperTest.php

Follow up on #2830
This PR is working and includes tests.
However, this feels more like a path than an actual solution to me. I would need a bit more info/doc before being able to provide a more complete solution.
I currently simply check if the type of the field is a problematic one (action/batch) and added virtual as a generic solution.
--
I think we should refactor `BaseFieldDescription` in order to split it in two:
- One (`AbstractFieldDescription`?) with only the most basic needs (name, type (?), options, etc.) required for every FieldDescription, but striping away all the mapping information.
- One (`BaseFieldDescription` or `BaseMappedFieldDescription` ?) extending the first one and including all the properties and methods related to the mapping.
With this, we could create a …

[FieldDescription] Ensure the object is not used when getting the value of a virtual field (action, batch, etc.)

---

DependencyInjection/Configuration.php
Resources/doc/cookbook/recipe_bootlint.rst
Resources/doc/index.rst
Resources/doc/reference/configuration.rst
Resources/views/standard_layout.html.twig

Related to #2878.
As our Sonata Admin default theme is based on Twitter Bootstrap, it could be useful to have bootlint for dev env in order to fix and optimize bootstrap integration.
> Bootlint is a tool that checks for several common HTML mistakes in webpages that are using Bootstrap in a fairly "vanilla" way. Vanilla Bootstrap's components/widgets require their parts of the DOM to conform to certain structures. Bootlint checks that instances of Bootstrap components have correctly-structured HTML. Optimal usage of Bootstrap also requires that your pages include certain <meta> tags, an HTML5 doctype declaration, etc.; Bootlint checks that these are present.
Related repository: https://github.com/twbs/bootlint
Note: Bootlint only works included on bottom of the body. So I move all the …

Bootlint integration

---

Controller/CRUDController.php
Resources/doc/reference/architecture.rst
Tests/Controller/CRUDControllerTest.php
Tests/Fixtures/Controller/PreCRUDController.php

This PR adds some methdos to help develoipers overload the CRUDController´and reduce the code they have to duplicate in overloaded methods.

Added preCreate, preEdit, preDelete, preShow, preList methods in the CRUDController

---

DependencyInjection/SonataAdminExtension.php
Resources/config/security.xml
Security/Handler/AclSecurityHandler.php
Security/Handler/RoleSecurityHandler.php
Tests/Security/Handler/AclSecurityHandlerTest.php
UPGRADE-2.4.md

Replaces deprecated `SecurityContextInterface` by `TokenStorageInterface` and `AuthorizationCheckerInterface` for Symfony 2.6+.
This introduce a little BC break on `AclSecurityHandler` constructor that got a new argument for spitted classes.
I had a note on the `UPGRADE.md` file.

Fix deprecated SecurityContextInterface usage

---

Admin/Admin.php
Command/ExplainAdminCommand.php

Fixes the following deprecation notice:
```
The Symfony\Component\Validator\Validator\RecursiveValidator::getMetadataFactory method is deprecated in version 2.5 and will be removed in version 3.0. Use the Symfony\Component\Validator\Validator\ValidatorInterface::getMetadataFor or Symfony\Component\Validator\Validator\ValidatorInterface::hasMetadataFor method instead.
```

Fix deprecated getMetadataFactory method usage

---

Admin/Admin.php
Admin/AdminInterface.php

This fixes following deprecation notice:
```php
* @deprecated since version 2.5, to be removed in 3.0.
*             Use {@link \Symfony\Component\Validator\ValidatorInterface} instead.
```
I manage `AdminInterface` and `Admin` class to accept both old and new `ValidatorInterface` on `setValidator` to keep Symfony 2.3+ BC.

Fix deprecated ValidatorInterface usage

---

Controller/CRUDController.php

Fix deprecated notice:
> The Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfTokenManagerAdapter::generateCsrfToken method is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead.

Fix deprecated CsrfTokenManagerAdapter::generateCsrfToken method usage

---

Admin/AdminHelper.php
Controller/CRUDController.php
Controller/HelperController.php
Tests/Controller/CRUDControllerTest.php

Fixes following deprecation notices:
> Passing a Symfony\Component\HttpFoundation\Request object to the Symfony\Component\Form\Form::bind and Symfony\Component\Form\Form::submit methods is deprecated since 2.3 and will be removed in 3.0. Use the Symfony\Component\Form\Form::handleRequest method instead. If you want to test whether the form was submitted separately, you can use the Symfony\Component\Form\Form::isSubmitted method.
> The Symfony\Component\Form\Extension\HttpFoundation\EventListener\BindRequestListener class is deprecated since version 2.3 and will be removed in 3.0. Pass the Request instance to the \Symfony\Component\Form\Form::handleRequest() method instead.

Fix deprecated Form::submit usage

---

Resources/views/standard_layout.html.twig

Since #2880, I got sometime error on `document.body.appendChild` of the bootlint bookmarklet.
It's because of including it on head, the body is not already existing.
This part **must be** on end of body document.
As @rande says, we can't move all the JS block on the body. So I juste move bootlint on a new block.

Fix bootlint placement

---

Datagrid/ListMapper.php

If we have the EDIT role but not the edit route, the identifier doesn't contains a link to the show action.
I have an admin which doesn't contains an edit action, but only an editable field form the list.
I've disable the route, but the user still have the right to edit the object (required for the editable column)

Show link should be used if we doesn't have the edit route

---

Command/GenerateAdminCommand.php
Resources/doc/reference/console.rst
composer.json

Move sensio/generator-bundle to suggest section section in composer.json and disable command if the bundle is not present.
This allow having the generator bundle installed only in dev environment.

Make the SensioGeneratorBundle an optional dependency

---

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

Symfony has his own `addFlash` method since `2.6` that do globally the same thing with same signature: https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php#L107
In this PR, `CRUDController::addFlash` method will use his parent if exists.
I also added a todo note to remove completely this method when bumping requirements to Symfony `>=2.6`.

Use Symfony addFlash method

---

Route/DefaultRouteGenerator.php
Tests/Export/ExporterTest.php
Tests/Route/DefaultRouteGeneratorTest.php

Backport #2147 to 2.3
An admin will include all the routes for child admins when generating
routes. So no need to let a child admin populate any caches.

Backport #2147 to 2.3. Skip child admin when loading route cache

---

Resources/views/CRUD/base_list.html.twig

Use case: I am implementing inline editing in list and return empty batch actions. But form renders and I have form in form.

Do not render form for batch actions if they are not available

---

Resources/views/Form/form_admin_fields.html.twig

This PR allow the sonata admin form theme to work with form types that use this feature.

Add support for label_format in form_admin_fields.html.twig

---

Resources/views/standard_layout.html.twig

Fix the following deprecation notice:
> The "app.security" variable is deprecated since version 2.6 and will be removed in 3.0.
Btw, checking `app.security.token` before `is_granted` is not necessary, isn't it?

Fix deprecated app.security usage

---

Route/AdminPoolLoader.php
UPGRADE-2.4.md

| Fixed tickets |
| Doc PR        |
Added missing ```array``` type hint for 2nd argument in ```AdminPoolLoader::__construct()```.

[AdminPoolLoader] Added missing "array" type hint in constructor

---

.travis.yml
Makefile
composer.json

Use composer to install dev binaries on global home.
This will permit to remove dependencies on project composer that could make conflicts and always get the latest versions.

Global phpunit and fabpot/php-cs-fixer install

---

Resources/views/standard_layout.html.twig

Actually, when there is one action, the navbar render a dropdown like that:
I think that it is unnecessary and not user friendly, so this pull request will render it like that:
When there is more than one action, a dropdown is still rendered like before.

Don't create dropdown if there is only one action

---

.travis.yml

This cause issue on PR for update: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/72089785#L127
Must be applied on other sonata projects.

Remove global vendor folder from cache

---

Form/Type/AdminType.php

This bug occurs in Symfony `2.3` with old version of `PropertyAccessor`.
| Fixed tickets | #2951, #2942

Fixed bug in sonata_type_collection that calls entity's remove method with null argument

---

composer.json

This is needed since this package is not part of SF 2.8 anymore
Issue #3150 (do not closed, another re flexion in progress).

Add symfony/security-acl requirement

---

DependencyInjection/Configuration.php

Admin LTE enables the [bootstrap tooltip by default](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L59). But if the jquery ui is loaded after the bootstrap js, the bootstrap tooltip plugin is replaced by jquery's tooltip plugin. Because of different parameters (jQuery doesn't have the `selector` parameter) of the plugins it's wrongly enabled [on all items in `body`](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L183-L185) - see screenshot of button in LIst view below. This commit fixes the tooltip conflict, the bootstrap tooltip plugin is prefered.
| BC breaks?    | yes, if user uses the jquery tooltip plugin. He has to modify the order of the files to prefer …

Load jquery ui before the boostrap js to fix tooltip conflict

---

Form/Type/AdminType.php

Whithout checking the subject value, PropertyAccessor throws error: `PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "boolean" while trying to traverse path "examples[0]" at property "examples".` (PropertyAccessor 2.7) or `Expected argument of type "object or array", "boolean" given ` (old PropertyAccessor 2.3) when creating new item with collection.

Check if subject is available to avoid error in PropertyAccessor

---

Resources/public/css/styles.css
Resources/views/Form/form_admin_fields.html.twig

PR https://github.com/sonata-project/SonataAdminBundle/pull/2811 tried to fix a width issue on collection with a table display. But it introduced another display issue on non-inline forms, for example when using sonata_type_admin : 
**With form-inline class**
**Without form-inline class**
The original width issue only occurs when there is an ``.input-group-addon`` element. So I removed the ``form-inline`` class and added a small css fix for this class only.
**Without fix**
**With fix**
Now, all theses cases display correctly.

Fix collection table cell width on chrome

---

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
DependencyInjection/Configuration.php
DependencyInjection/SonataAdminExtension.php
Resources/doc/reference/configuration.rst
Resources/doc/reference/dashboard.rst
Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php

Sorts all admins and groups regardless of their order in configuration. (https://github.com/sonata-project/SonataAdminBundle/issues/3018)
to activate you have to set the config option admins_sort to true
* ```<tag name="sonata.admin" group="Z-Group" label="A-Admin"/>```
* ```<tag name="sonata.admin" group="Y-Group" label="C-Admin"/>```
* ```<tag name="sonata.admin" group="Y-Group" label="B-Admin"/>```
would result in the following order:
- Y-Group:
- B-Admin
- C-Admin
- Z-Group:
- A-Admin

Sort default Groups and Admins

---

Resources/public/css/tree.css

This should fix a styling issue in the tree list. 
Before:
After:
You can see this at the media tree view in the MediaBundle.

Tree style issue

---

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

When passing additional form data in a batch action, the request should not be replaced. Instead it should be merged with the form.

Request should not be replaced in batch action

---

Resources/views/standard_layout.html.twig

There is an issue with this count, because sometimes we got empty li or an li with a class and this doesn't match.
The goal of this dropdown is to provide links to with this we count only links tags

Fix count on actions

---

Resources/views/standard_layout.html.twig

so you don't need to overwrite the markup

add new block to overwrite just the content

---

Block/AdminListBlockService.php

Compare kernel version is not reliable because kernel version **could** differ from options resolver component version.
Method detection rules is better.

Remove kernel version compare for BC

---

Resources/public/Admin.js
Resources/views/CRUD/base_edit_form.html.twig

Sticky form introduced on #3194 by @qsomazzi use a too generic class selector for footer.
This introduced issues with another unrelated `.form-actions` on the view being stuck for no reason.

Fix too generic class selector for sticky footer

---

Resources/translations/SonataAdminBundle.hu.xliff

I fixed some translations based on how they are generally translated on websites. I also translated some unstranslated strings.

Fix action translations, translate remaining strings

---

Controller/HelperController.php
Tests/Controller/HelperControllerTest.php

My Admin is only granted to display the list of my entities, i should be able to filter the list with the autocomplete filter the same way i can use the doctrine_orm_model filter

We can use the autocomplete with only the LIST role

---

Form/Extension/Field/Type/FormTypeFieldExtension.php
Tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php

Changed deprecated 'field' type to 'form' in FormTypeFieldExtension

---

Resources/views/CRUD/list__action_delete.html.twig
Resources/views/CRUD/list__action_edit.html.twig
Resources/views/CRUD/list__action_show.html.twig

use font-awesome icons instead of glyphicons

---

Resources/views/Block/block_admin_list.html.twig
Resources/views/CRUD/base_edit_form.html.twig
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/batch_confirmation.html.twig
Resources/views/CRUD/delete.html.twig
Resources/views/CRUD/list__select.html.twig
Resources/views/CRUD/preview.html.twig
Resources/views/Form/form_admin_fields.html.twig

Some icons are missing in #3291 
Preview (before/after)
Delete (before/after)
Batch (before/after)
Edit error tabs (before/after)
List export (before/after)
Modal select (before/after)

replace glyphicons with font-awesome

---

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

When creating new objects, the existence and permissions for the route are checked before redirecting to the item.

Check routes before redirecting in CRUDController

---

Resources/translations/SonataAdminBundle.fr.xliff

French typography requires a space before a colon.

Update colon spacing in french translation

---

Resources/public/Admin.js

| Fixed tickets | #3347
Fixed by moving the code before select2 initializing code.

Move initialization of filters before select2 to properly detect if advanced filters should be visible

---

Resources/public/Admin.js

The goal of this PR is to fix the select2 sortable when the field isn't required.
Let's take a field `groups` inside an UserAdmin : 
````php
->add('groups', 'sonata_type_model', [
'label' => 'Groups',
'required' => false,
'multiple' => true,
'by_reference' => false,
'sortable' => true,
])
````
**Before this fix**
When submitting the form, we got `groups` with value : `[""]`
**After this fix**
When submitting the form, we got `groups` with value : `[]`

Fix select2 sortable

---

Form/DataTransformer/ModelToIdPropertyTransformer.php
Tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php

When using `OneToMany` collections in a form field with `'multiple' => true` the `ModelToIdPropertyTransformer` expects an `ArrayCollection` and throws an exception if the supplied value is an `array`.
Example: A `User` entity which implements the `UserInterface` has to return an `array` for `getRoles` even though the property `roles` (might be /) is an `ArrayCollection`; hence the getter will return `$this->roles->toArray()`.
- Check if $entityOrCollection is array
- Add test case for transforming an array

Array support for property transformer when using $multiple = true

---

Controller/HelperController.php
Tests/Controller/HelperControllerTest.php

| Fixed tickets | #3164, #3406

Removed type check of sonata_type_model_autocomplete to allow extending the form type.

---

Admin/Admin.php
Resources/doc/reference/batch_actions.rst
Resources/views/CRUD/base_list.html.twig

With this PR you don't have to translate the batchAction label manually. Now the domain comes from the admin translation domain or can be set a via ``translation_domain`` in the action.

Added translation domain to batchActions

---

Resources/public/Admin.js

When a collection is populated with more than 10 elements, the regexp ``_([0-9])+$`` only matches the last digit. The last element is always "9" and the new one "10".

Fix collection counter when we have more than 10 elements

---

Tests/Command/ExplainAdminCommandTest.php
Tests/Controller/CRUDControllerTest.php
Tests/Controller/CoreControllerTest.php

This pull request contains some miscellaneous test fixes for the Symfony 2.8 and 3.0 branches, specifically:
- In `FrameworkBundle:Controller:render()` a check is added for the presence of either the `templating` or `twig` services as of Symfony 2.8
- Configuring the RequestStack in CRUDControllerTest for Symfony 3.0
- BC checks for interfaces that are removed in Symfony 3.0

Symfony 2.8 & 3.0 test fixes

---

Controller/HelperController.php
Tests/Controller/HelperControllerTest.php

Hello,
The Symfony Validator API [changed between 2.4 and 2.5](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.5.md#validator) but the SonataAdminBundle is compatible with API 2.4 only. 
After upgrading the project configuration in `framework: validation: api: 2.5`, the `Sonata\AdminBundle\Controller\HelperController` can't be used (for autocomplete):
```
Catchable Fatal Error: Argument 4 passed to
Sonata\AdminBundle\Controller\HelperController::__construct() 
must be an instance of Symfony\Component\Validator\ValidatorInterface,
instance of Symfony\Component\Validator\Validator\RecursiveValidator given
```
The compatibility was partially fixed fixed by the PR #2961.
The PR #2176 tried to make the `HelperController` compatible with validation 2.5, but this PR was abandoned.

Allows Symfony Validation API 2.5 in ControllerHelper

---

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

The label isn't translated on the confirmation page.

Fix: Translate 'action_label' in batchAction

---

Route/AdminPoolLoader.php

Ref. https://github.com/sonata-project/SonataAdminBundle/issues/3091#issuecomment-147698804

[AdminPoolLoader] Extend Loader instead of FileLoader to avoid deprecation message

---

Resources/views/CRUD/action.html.twig
Resources/views/CRUD/base_acl.html.twig
Resources/views/CRUD/base_edit.html.twig
Resources/views/CRUD/base_edit_form.html.twig
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/batch_confirmation.html.twig
Resources/views/CRUD/delete.html.twig
Resources/views/Core/add_block.html.twig
Resources/views/Core/dashboard.html.twig
Resources/views/standard_layout.html.twig

This PR replaces all instances of the "admin_pool" variable in the templates with the global variable "sonata_admin.adminPool". This reduces complexity because some "if" blocks can be removed, but it also makes it easier for third party or custom components to integrate with Sonata Admin, because they can simply "extend" the standard_layout.html.twig from their own templates and reuse the same layout without worrying about the admin pool.

Replaced all instances of "admin_pool" with the global "sonata_admin.adminPool"

---

DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
DependencyInjection/SonataAdminExtension.php
Form/Extension/Field/Type/FormTypeFieldExtension.php

Since commit 5443959ecea1b77fb6b0e053f49a1f657d76c70c, the filter list form is broken.
Filters of the **same** type are displayed multiple times.
This is because the same instance of the filter is given for every filters of the same type (`stringFilter` for instance).
Before : 
After :
In this example, `remoteId` and `name` are both filters of the type `string`
Linked issue : https://github.com/sonata-project/SonataAdminBundle/issues/3475

Instanciate a new class for each Filter, fix #3475

---

Resources/doc/reference/form_types.rst
Resources/public/Admin.js

Add new trigger event, when ".sonata-collection-row" successfully removed. Issue #3442

Add new trigger after ".sonata-collection-row" successfully removed.

---

Admin/Admin.php
Resources/doc/reference/routing.rst
Tests/Admin/AdminTest.php
Tests/Fixtures/Admin/CommentWithCustomRouteAdmin.php
Tests/Fixtures/Admin/PostWithCustomRouteAdmin.php

Hello,
This is a rebase of PR #3095 from 2.3 to master.
https://github.com/sonata-project/SonataAdminBundle/pull/3095
Copy of previous PR documentation :
------------------------------------------
I have tried to set the `$baseRoutePattern` in a child admin class and the behavior is that the parent base route pattern prefix is overridden by the child base route pattern.
Example:
```php
// ParentAdmin.php
protected $baseRoutePattern = 'my-parent';
// ChildAdmin.php
protected $baseRoutePattern = 'my-child';
```
So currently the generated route is : `/admin/my-child/list` (which is generated twice: once for the generic admin and once for the child (parent specific) admin)
This prevents filtering the children of my `Parent` instance.
With this pull request the generated route will be : …

Add support for child base route pattern and name in admin class

---

composer.json

It's strange to say "you have to require `symfony/security-acl` in order to use this bundle in Symfony >2.8", as making sure packages are usuable is exactly the task of Composer.
The bug (ref https://github.com/sonata-project/SonataAdminBundle/issues/3152) that was causing problems when this was added as a requirement a half year ago has been fixed on Symfony's side (ref https://github.com/symfony/symfony/pull/16144) and is included in all latest releases of the maintained versions (2.3.25, 2.7.7, 2.8.0 and 3.0.0). So it should not cause any troubles again.

Move Security ACL dependency to required again

---

Resources/public/Admin.js

Once the collection items has been removed we can't trigger event on it.
We need to use document instead of this to make it work.
fix issue introduced in #3473

Event on "this" can't triggered on deleted element

---

Resources/views/CRUD/base_edit_form.html.twig

Use case: we need to set `autocomplete="off"` to the whole `form`, but not as a global option, just to a few edit pages.

Added new Twig block sonata_form_attributes into base_edit_form.html.twig

---

Admin/Admin.php
Admin/AdminInterface.php
Controller/CRUDController.php
Resources/doc/reference/saving_hooks.rst

Use cases for this: slug/sku generation. Slug and sku cannot be empty and should be unique. We cann't generate they in `preUpdate` methods because validation not pass and `preUpdate` not calls. So I've added method which triggered after bind sumbitted data from user and before it will validated.

Add preValidate method.

---

Resources/doc/reference/security.rst

Quick typo fix in the voter docs.
I removed $ in front of function call is_subclass_of

Fix typo in voter doc

---

Admin/Admin.php

Would be great if you can add one simple subclass to an admin instead of replacing the whole subclasses by using ``setSubClasses``.

Add one subclass to admin

---

Admin/Admin.php
Admin/AdminExtension.php
Admin/AdminExtensionInterface.php

When adding some routes with `configureRoutes`, there should be a way to add the corresponding access mappings.

Handle permissions in admin extension

---

Resources/public/Admin.js

Missing coma triggers "Admin.js:73 Uncaught SyntaxError: Unexpected identifier" at least on admin dashboard

Missing coma

---

Resources/views/empty_layout.html.twig

We have overriden layout template using bundle configuration, but our layout not applied

Allow using overriden layout template in empty_layout

---

Resources/doc/reference/installation.rst
composer.json

This reverts commit a0a3157a34e49e4f32069b9343bb61ead5ab42ff.
Do not pretend ACLs are optional when they are really not. The admin
class implements an interface from the ACL package. This means that
anyone that uses an admin (so any user of the package, really), needs
to have that interface (and the ACL package).
Fixes #3511

Revert "Make symfony/security-acl as a suggestion"

---

Form/Type/CollectionType.php
Resources/views/Form/form_admin_fields.html.twig
Tests/Form/Widget/BaseWidgetTest.php
Tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php

It makes no sense to prevent people from deleting things that are not
yet persisted.

always include delete button in option prototype

---

Admin/Admin.php
Tests/Admin/AdminTest.php

| Fixed tickets | #2068
| Doc PR        | -
Using the Admin class with Entities not in Bundle namespacing currently requires overriding both the `getBaseRoutePattern()` and `getBaseRouteName()` methods for each Admin/Entity pair. There is a slightly less ugly workaround mentioned in #2068 but it breaks child admin functionality and so cannot be used with child entities

Add support for entities outside of bundles

---

Resources/views/CRUD/base_show.html.twig

Now the show group names are translated with the ``translation_domain`` option (with fallback on admin ``translation_domain``)

Translate show group using translation_domain

---

Resources/translations/SonataAdminBundle.ar.xliff
Resources/translations/SonataAdminBundle.bg.xliff
Resources/translations/SonataAdminBundle.ca.xliff
Resources/translations/SonataAdminBundle.cs.xliff
Resources/translations/SonataAdminBundle.de.xliff
Resources/translations/SonataAdminBundle.en.xliff
Resources/translations/SonataAdminBundle.es.xliff
Resources/translations/SonataAdminBundle.eu.xliff
Resources/translations/SonataAdminBundle.fa.xliff
Resources/translations/SonataAdminBundle.fr.xliff
Resources/translations/SonataAdminBundle.hr.xliff
Resources/translations/SonataAdminBundle.hu.xliff
Resources/translations/SonataAdminBundle.it.xliff
Resources/translations/SonataAdminBundle.ja.xliff
Resources/translations/SonataAdminBundle.lb.xliff
Resources/translations/SonataAdminBundle.lt.xliff
Resources/translations/SonataAdminBundle.nl.xliff
Resources/translations/SonataAdminBundle.no.xliff
Resources/translations/SonataAdminBundle.pl.xliff
Resources/translations/SonataAdminBundle.pt.xliff
Resources/translations/SonataAdminBundle.pt_BR.xliff
Resources/translations/SonataAdminBundle.ro.xliff
Resources/translations/SonataAdminBundle.ru.xliff
Resources/translations/SonataAdminBundle.sk.xliff
Resources/translations/SonataAdminBundle.sl.xliff
Resources/translations/SonataAdminBundle.sv_SE.xliff
Resources/translations/SonataAdminBundle.uk.xliff
Resources/translations/SonataAdminBundle.zh_CN.xliff
Resources/views/CRUD/base_history.html.twig

before:
after:
The simplethings guys do the same here:
https://github.com/simplethings/EntityAudit/blob/master/src/SimpleThings/EntityAudit/Resources/views/Audit/view_entity.html.twig#L29

show a default value if revision has no username set

---

Resources/doc/reference/security.rst

For 
return array($kevin, $anne);
you receive ContextErrorException:
Catchable Fatal Error: Argument 3 passed to Sonata\AdminBundle\Util\AdminObjectAclData::__construct() must implement interface Traversable, array given, called in C:\_\xampp\htdocs\_projects\laas\git\vendor\sonata-project\admin-bundle\Controller\CRUDController.php on line 1027 and defined
500 Internal Server Error - ContextErrorException
Also maybe $container can be replaced by $this->container on line 689?
Thanks!

Catchable Fatal Error on Update security.rst

---

Resources/views/CRUD/base_edit_form_macro.html.twig

**Based on the PR of @sujjayjaju here: #2564**
----------------------------------------------------------------
Cascade form groups / groups formatting for sonata_type_admin
Before:
After:

show tabs when embedded as sonata_type_admin

---

Show/ShowMapper.php
Tests/Show/ShowMapperTest.php

Q | A
------------ | -------------
Bug fix? |	no
New feature? |	yes
BC breaks? |	no
Deprecations? |	no
Tests pass? |	yes
Fixed tickets |	no
License |	MIT
Doc PR |	no
Suggest change exception message from "invalid state" to "Duplicate field name in show mapper." in show mapper when add duplicate field name. Add test case.
What do you think @rande ?

Change exception message if duplicate field name in show mapper.

---

Resources/views/CRUD/base_edit_form_macro.html.twig

Fix for show tabs when embedded as sonata_type_admin
Currently if no tabs exists results in messed Html tree, because of this ```<div>``` without checking  "has_tab".

Fix show tabs when embedded as sonata_type_admin

---

Form/Type/Filter/ChoiceType.php
Form/Type/Filter/DateRangeType.php
Form/Type/Filter/DateTimeRangeType.php
Form/Type/Filter/DateTimeType.php
Form/Type/Filter/DateType.php
Form/Type/Filter/NumberType.php
Tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php

Related to #3565 
Symfony 3.* remove choices_as_value = false 
> symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php
```php
if (true !== $choicesAsValues) {
throw new \RuntimeException(sprintf('The "choices_as_values" option of the %s should not be used. Remove it and flip the contents of the "choices" option instead.', get_class($this)));
}
```
[source code](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L269)

choice options in advanced filters are flipped [sf3]

---

Resources/public/Admin.js

The Admin.js file first sets up event listeners. When loaded asynchronously, document ready may have already fired, causing instant execution and a JS error as the Admin object has not been defined.
Moving the event after the Admin object definition fixes this problem.

Execute Admin methods after the object is defined

---

composer.json

It is the version required by default when installing a brand new sf 2.8
project. See symfony/symfony-standard
Fixes #3596

allow version 3.0 of the generator bundle

---

Tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php

Related to a [comment](https://github.com/sonata-project/SonataAdminBundle/pull/3585#issuecomment-184741402) on #3585 
> This PR is not valid, version_compare should not be used even if on tests.
@Soullivaneuh  it's ok?

Remove method version_compare used on Form component integration tests

---

Resources/views/Form/form_admin_fields.html.twig
Tests/Form/Widget/BaseWidgetTest.php
Tests/Form/Widget/FormChoiceWidgetTest.php

This PR fix #2630
Before (with option `use_icheck` to true)
After (with option `use_icheck` to true)
Before (with option `use_icheck` to false)
After (with option `use_icheck` to false)

Fix #2630 : Checkbox labels NOT showing with Bootstrap SF2.6 form theme

---

Admin/Admin.php
Admin/AdminHelper.php
Admin/Pool.php
Controller/HelperController.php
DependencyInjection/SonataAdminExtension.php
Form/ChoiceList/ModelChoiceList.php
Form/ChoiceList/ModelChoiceLoader.php
Form/Type/ModelType.php
Resources/config/core.xml
Resources/config/form_types.xml
Resources/doc/reference/action_list.rst
Tests/Admin/AdminTest.php
Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Tests/Form/Type/ModelTypeTest.php
Twig/Extension/SonataAdminExtension.php

Reuse existing property access instance for performance improvement.
Reasons:
1. starting from Symfony v2.3.35 there is internal cache for this component (cache inside request) https://github.com/symfony/symfony/commit/284dc75796b693562e2c091fd770c4a04c179a2b . Cache working using class property and we should use same instance to get it works properly.
2. there is unmerged yet PR that adds cache outside request https://github.com/symfony/symfony/pull/16838 . For getting it working we should use configured instance with passed cache layer inside it instead of creating new one.
3. in two classes you instanciate property accessor inside foreach.

Property access reuse

---

Tests/Command/GenerateAdminCommandTest.php

Apparently, it is called and needs to return something.

mock Kernel::getContainer()

---

Tests/Controller/HelperControllerTest.php

These methods do not actually exist on the mock object, which means we will get
an error anyway if they are called. Recent versions of phpunit forbid
configuring inexistant methods in mocks, which makes tests fail.
See https://github.com/sebastianbergmann/phpunit-mock-objects/issues/299

Remove method expectations

---

Resources/public/css/styles.css
Resources/views/Form/form_admin_fields.html.twig
Tests/Form/Widget/FormChoiceWidgetTest.php

As asked here : https://github.com/sonata-project/SonataAdminBundle/issues/2630#issuecomment-196755129
* Add space between checkbox and label when using icheck
* Hide checkbox label on embedded collection tables
When using `sonata_type_collection` with `['edit' => 'inline', 'inline => 'table']`. The label of boolean fields are not visible (as they're already in the table heading). For expanded choices the label is still visible.

Fix #2630 : "Delete" label rendering on embedded collection + add space between checkbox and label when using icheck

---

Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/base_show_macro.html.twig

This PR fixed old issue with tabs in the show action: See https://github.com/sonata-project/SonataAdminBundle/issues/2933
Should be
instead of

Render tabs correctly in the ShowAction

---

Resources/public/css/styles.css

Fix the height of images when the max-width is reached.

[FIX] Height on images in the table of media

---

Resources/views/CRUD/base_show.html.twig

Commit 95d9d6c contained a typo in a template path, causing the following Twig exception:
```
Unable to find template "@Admin/CRUD/base_show_macro.html.twig" in SonataAdminBundle:CRUD:base_show.html.twig at line 14.
```

Fixes typo introduced in 95d9d6c. Closes #3684

---

Controller/CRUDController.php

It was like that from the beginning, removing the request parameter was
a BC-break in this case.

restore the signature for exportAction

---

Resources/public/Admin.js

This commit removes the javascript function that hides form errors only to show them in a popover.
This feature had a number of serious issues.
1. Instead of drawing attention to the errors, it hides them. Consider **this**:
**Versus**:
And this is a very simple example. It tends to get exponentially more confusing as the number of fields increase.
2. Showing tooltips oh hover doesn't work for touch devices.
3. Relying only on color is an obvious accessibility issue.
So I propose to remove it entirely because this feature actually does more harm than good.
I'll work on solutions to improve the situation regarding the client-side error feedback.
Notably trying to fix [#522](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/522) which is a major issue.
But this is for …

Remove the add_pretty_errors feature. Fixes #1076.

---

Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php

I wanted to work on the api closing, but ended up making this big backwards-compatible refactoring, which is BC.

Twig extension refactoring

---

Menu/MenuBuilder.php
Menu/Provider/GroupMenuProvider.php
Resources/config/menu.xml
Tests/Menu/MenuBuilderTest.php
Tests/Menu/Provider/GroupMenuProviderTest.php

This PR introduces a few changes that make the MenuBuilder class more flexible, easier to test and more complaint to SRP:
1. The request is added to the root menu options through an extension: `RequestExtension`
2. The logic of the creation process for the default menu items is moved to the menu provider `GroupMenuProvider`

Remove default menu creation logic from MenuBuilder

---

Tests/Util/FormBuilderIteratorTest.php
Util/FormBuilderIterator.php
phpunit.xml.dist

Add FormBuilderIteratorTest and provide php-ini setting for precision

---

.travis.yml

We have to test with the default composer behavior.

No Symfony version constraint test

---

Resources/doc/reference/architecture.rst

Previous XML results in error:
```[Symfony\Component\Debug\Exception\ContextErrorException]
Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Admin\Admin::setLabelTranslatorStrategy() must implement interface Sonata\AdminBundle\Translator\LabelTranslatorStrategyInterface, string given```

Update admin service definition XML

---

Resources/config/twig.xml
Resources/views/CRUD/list_choice.html.twig
Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php

Add x-editable support for (non multiple) choice in lists, this feature was once mentioned in #1867 by @EmmanuelVella  and also requested in #2269.
Multiple choice may require more work though.
First thing was to move the `x-editable` types mapping to the **parameters**, *imho* its was pretty annoying to have it hard-coded in the twig extension. Especially if you need to add more editable types in your project.
The behaviour is quite similar to the way `booleans` were handled. 
```php
protected function configureListFields(ListMapper $list)
{
$list
->add('status', 'choice',
[
'editable' => true,
'choices' => ['Status1' => 'Alias1', 'Status2' => 'Alias2'],
'catalogue' =>'admin'
]
);
}
```
The tricky part is to transform the provided **choices** options into something that can be fed to the …

List editable choice

---

Resources/views/CRUD/base_show_macro.html.twig

Commit fd1a1596f86bfb4afdafe9767efaa4c787bba6a5 introduced a visual bug by forgetting to add a default css class.
This commits fixes the issue.
See github issue #3729 for more details.

Fix visual regression in base_show_macro.html.twig. Closes #3729.

---

Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/base_show_macro.html.twig

Commit fd1a159 removed two wrapper divs that shouldn't have been removed, one of these being a BC break (see first commit).
The other is closely related to issue #3729 and PR #3730 (I should have done it there, but it is merged already, see second commit)

add back missing wrapper divs

---

Admin/Admin.php
Resources/doc/reference/dashboard.rst
Resources/views/Block/block_admin_list.html.twig
Resources/views/CRUD/dashboard__action.html.twig
Resources/views/CRUD/dashboard__action_create.html.twig
Tests/Admin/AdminTest.php

The actions displayed on the dashboard for each admin type are hard-coded: only "create" and "list" are available. I wanted to customize them to add direct links to special views. Unfortunately, that was not possible yet, so I came up with a solution. The templates for the two existing actions are moved into individual templates: "dashboard__action_list.html.twig" and "dashboard__action_create.html.twig". What remains is a "for" loop that retrieves the necessary configuration from the getDashboardActions methon in the admin class. This method can then be overwritten for individual types.
This is not a finished patch yet, as I first wanted to gather feedback: Would this patch be accepted if I finish it? Is this something other people would find useful as well?

Ability to add custom dashboard actions

---

.php_cs
.styleci.yml
.travis.yml
Admin/AdminExtensionInterface.php
Admin/AdminInterface.php
Builder/DatagridBuilderInterface.php
Builder/ListBuilderInterface.php
Builder/ShowBuilderInterface.php
Command/GenerateAdminCommand.php
Datagrid/DatagridInterface.php
DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
DependencyInjection/SonataAdminExtension.php
Makefile
Manipulator/ServicesManipulator.php
Mapper/BaseGroupedMapper.php
Tests/Validator/Constraints/InlineConstraintTest.php
Twig/Extension/SonataAdminExtension.php
composer.json

@rande I assigned you for this.
StyleCI is a php-cs-fixer interface that make CS lint quicker and proper than Travis.
I propose to integrate it: https://styleci.io/
You need to link this project. The only config that must be done on interface is for header comment.
If possible, could you give me access to StyleCI management? With that, I could set up this tools quiclky on each sonata project.
Regards.

StyleCI integration

---

Datagrid/Datagrid.php
Filter/Filter.php
Tests/Datagrid/DatagridMapperTest.php
Tests/Filter/FilterTest.php

Revert #3709
Now I have to figure out why things don't work nice with the CMF on Symfony 3...

Using form type names instead of FQCN to significantly reduce the change of getting an error while visiting the admin panel

---

Admin/Admin.php
Admin/AdminInterface.php
Resources/doc/cookbook/recipe_dynamic_form_modification.rst
Tests/Admin/AdminTest.php

Check the current request's name, if matched with given admin's route, will return true. This is useful when share configureFormFields method's result between create/edit/custom action, you can build different rule form for different pages.

add AdminInterface::isCurrentRoute method

---

Resources/doc/index.rst
composer.json

The goal is to permit to apply the generic readme on this bundle/
Ref: https://github.com/sonata-project/dev-kit/blob/4ff0f529c6f5e80203478bf769096ad964f0b322/project/README.md

Add some precisions on documentation and composer

---

Admin/AdminHelper.php
CHANGELOG.md
Tests/Admin/AdminHelperTest.php

Fixes #3763
Reopened with the correct base branch.
With this fix, getElementAccessPath now detects better when a property is accesible and shows better exception message when it's not. Added PHPDocs on the AdminHelperTest and fixed the compatibility with symfony 2.3.
I added more test to be sure it's working.

Fixed detection of properties with underscores on nested forms

---

CHANGELOG.md
Resources/views/Form/form_admin_fields.html.twig

Fixes #3812.
When you choose `single_text` for date and time fields from a datetime one, you have to do a special case on twig rendering.
Before:
After:

Handle separated date and time single_text widget from datetime

---

Tests/Twig/Extension/SonataAdminExtensionTest.php

We are only interested in deprecation notices from external libraries
(which can happen when tests are not really unit tests).

Silence internal deprecation notices

---

CHANGELOG.md

With the last two PR we introduced duplicated Fixed section on the CHANGELOG.md

Removed duplicated Fixed section on CHANGELOG

---

CHANGELOG.md
Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php
UPGRADE-3.x.md

There does not seem to be a valid use for that. Deprecating it will help
us make sure no one actually relies on it before removing it.

Deprecate template fallback mechanism

---

CHANGELOG.md
Resources/doc/reference/routing.rst
Route/RouteCollection.php
Tests/Route/RouteCollectionTest.php

On some very simple admin classes allowing just listing, you can now do something like this:
```php
$collection->clearExcept('list');
```
Instead of this:
```php
$collection->clearExcept(['list']);
```

Allow RouteCollection::clearExcept to have only one string argument

---

Admin/AbstractAdminExtension.php
Admin/AdminExtension.php
Admin/Extension/LockExtension.php
CHANGELOG.md
Event/AdminEventExtension.php
Resources/doc/reference/extensions.rst
Resources/doc/reference/form_help_message.rst
Tests/Admin/AdminTest.php
UPGRADE-3.x.md

This follows Symfony coding standard rules.
Ref: http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

Rename AdminExtension to AbstractAdminExtension

---

Admin/AbstractAdmin.php
Admin/AdminExtensionInterface.php
CHANGELOG.md
UPGRADE-4.0.md

Added missing method to interface (See https://github.com/sonata-project/SonataAdminBundle/pull/3297)
This should be scheduled for the next major.

Added "getAccessMapping" method to AdminExtensionInterface

---

CHANGELOG.md
Resources/views/CRUD/base_edit_form_macro.html.twig

If you remove fields that are in a tab, you got a template error. This isn't the best solution, but it will fix: https://github.com/sonata-project/SonataUserBundle/issues/503
Refs https://github.com/sonata-project/SonataAdminBundle/pull/3447 https://github.com/sonata-project/SonataAdminBundle/pull/3661

Empty groups

---

CHANGELOG.md
Datagrid/DatagridMapper.php
Datagrid/ListMapper.php
Form/FormMapper.php
Mapper/BaseMapper.php
Show/ShowMapper.php
Tests/Datagrid/DatagridMapperTest.php
Tests/Datagrid/ListMapperTest.php
Tests/Form/FormMapperTest.php
Tests/Show/ShowMapperTest.php

Add `keys` method to `DatagridMapper`, `ShowMapper`, `FormMapper` and `ListMapper`.
This will permit to get all the configured keys.
For example, this could be used to do an advanced key ordering on `BaseMapper::reorder` method.
For me, this PR is RTM. But I would like a review from @sonata-project/contributors before merge it.

Add keys method to mappers

---

CHANGELOG.md
Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php
UPGRADE-4.0.md

Why would anyone want to rely on that? Maybe there is a valid reason,
but it does not appear in the comments or in the commit history. The
best way to find out is to remove the "feature". If anyone reverts this
commit, please make sure to add a comment to explain this.

remove default template loading on exception

---

Form/FormMapper.php

```markdown
- Fixed wrong phpdoc in FormMapper
```
The `@return` doc exists twice in `FormMapper::removeGroup`.

Fixed wrong phpdoc in FormMapper

---

Admin/AbstractAdmin.php

```markdown
- Wrong phpdoc for `AbstractAdmin::configure**`
```
The protected methods doesn't have parents with any phpdoc.

Fixed wrong phpdoc

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
CHANGELOG.md
UPGRADE-4.0.md

```markdown
- Add the `getExportFields` method to the AdminInterface
- Add the `setTemplates` method to the AdminInterface
- Add the `setTemplate` method to the AdminInterface
- Add the `getTemplates` method to the AdminInterface
- Add the `getClassnameLabel` method to the AdminInterface
- Add the `getPersistentParameter` method to the AdminInterface
- Add the `preValidate` method to the AdminInterface
- Add the `getSubClasses` method to the AdminInterface
- Add the `addSubClass` method to the AdminInterface
- Add the `getDashboardActions` method to the AdminInterface
- Add the `getActionButtons` method to the AdminInterface
```
Added some public methods of `Admin` to the `AdminInterface`.

Moved public methods to AdminInterface

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
CHANGELOG.md
Resources/doc/reference/advanced_configuration.rst
UPGRADE-4.0.md

```markdown
- `AbstractAdmin::configureActionButtons` method is now protected
- `AbstractAdmin::getActionButtons` is now final
```
There is no reason for a public access to `AbstractAdmin::configureActionButtons`.

Closing API for AbstractAdmin::configureActionButtons and AbstractAdmin::getActionButtons

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
CHANGELOG.md
UPGRADE-4.0.md

```markdown
- `AbstractAdmin::configure` method is now protected
- `AbstractAdmin::buildDatagrid` method is now private
- `AbstractAdmin::urlize` method is now protected and final
- `AbstractAdmin::defineFormBuilder` method is now private
- `AdminInterface::configure` was removed
```
Closing the API for `AbstractAdmin` by decreasing the method visiblity. This methods shouldn't be called outsite the admin class.

Closing API methods in AbstractAdmin

---

Admin/AbstractAdmin.php
CHANGELOG.md
Resources/doc/reference/advanced_configuration.rst
UPGRADE-4.0.md

Should be merged with #3855
```markdown
- `AbstractAdmin::configureActionButtons` method signature has changed
- Moved default buttons from `AbstractAdmin::configureActionButtons` to `AbstractAdmin::getActionButtons`
```
Moved all default action buttons to `getActionButtons` so all `configure*` methods are empty by default. This will help to close our API.

Moved body of configureActionButtons to getActionButtons

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
Admin/BreadcrumbsBuilder.php
Admin/BreadcrumbsBuilderInterface.php
CHANGELOG.md
Tests/Admin/AdminTest.php
Tests/Admin/BreadcrumbsBuilderTest.php
Tests/Fixtures/Bundle/Entity/DummySubject.php

The Admin class is huge (~ 3000 lines), and it handles many unrelated
things. Let's move out what we can, starting with the breadcrumb
generation code.

move the breadcrumb build in a separate component

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
CHANGELOG.md
Resources/doc/reference/search.rst
Resources/views/Block/block_search_result.html.twig

This commit allows you to configure the search result link for each admin separately
Fixes (partial) #2581, #3092
It's kind of hard where to configure the default action for the link. Should the **Admin class define the final action or should a global config value override it.

Configure search result link in admin

---

Controller/CRUDController.php
UPGRADE-3.x.md

```markdown
- Overriding `AbstractAdmin::configureBatchActions` is now deprecated
```
This PR have to be merged before #3844.
It introduce a BC deprecated message warning user to not override `AbstractAdmin::configureBatchActions` anymore.

Deprecate AbstractAdmin::getBatchActions method override

---

Admin/AbstractAdmin.php
CHANGELOG.md
Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php
UPGRADE-4.0.md

```markdown
- Made `AbstractAdmin::getBatchActions` final
```
This change closes the api for `AbstractAdmin::getBatchActions` in favor of `AbstractAdmin::configureBatchActions`

Closing api for AbstractAdmin::getBatchActions

---

Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php
UPGRADE-4.0.md

```markdown
- The class `Sonata\AdminBundle\Translator\Extractor\JMSTranslatorBundle\AdminExtractor` is now `final`.
```
This closes the admin extractor, I don't think it is meant to be extended.
Not sure if the corresponding service should be made private.

Close admin extractor

---

Admin/AbstractAdmin.php
Form/ChoiceList/ModelChoiceLoader.php
Form/DataTransformer/ModelsToArrayTransformer.php
Tests/Admin/AdminTest.php
UPGRADE-3.x.md

Closes #3870
```markdown
- Fix support for composite primary key in `AbstractAdmin::getSubject`
```
Remove primary key validation because it may extend beyond the constraint `#^[0-9A-Fa-f\-]+$#` and it can contain a character `~` if it is a composite key.
**SonataAdminBundle** does not work with composite primary key. This PR might remedy the situation.
@Soullivaneuh you can comment this, why do need constraint for primary key?

Add support composite primary key

---

Resources/views/CRUD/list__select.html.twig

Rebase of #2859
Closes #
```markdown
- Fixed wrong route in `list__select.html.twig`
```
The button should show a `list` route instead of the `edit` route.

Fixed wrong route in "list__select.html.twig"

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
Admin/BreadcrumbsBuilder.php
Admin/BreadcrumbsBuilderInterface.php
Controller/CRUDController.php
Controller/CoreController.php
Resources/config/core.xml
Resources/doc/index.rst
Resources/doc/reference/breadcrumbs.rst
Resources/views/standard_layout.html.twig
Tests/Admin/AdminTest.php
Tests/Admin/BreadcrumbsBuilderTest.php
Tests/Controller/CoreControllerTest.php
Tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php
UPGRADE-3.x.md

See #3833 
```markdown
- `AbstractAdmin::getBreadcrumbs`, in favor of `BreadcrumbsBuilder::getBreadcrumbs`
- `AbstractAdmin::buildBreadcrumbs`, will be removed
- `AbstractAdmin::$breadcrumbs`, will be removed
```
The ultimate goal of this PR is to remove everything breadcrumbs-related from the `AbstractAdmin` class

Use breadcrumbs builder directly

---

Route/AdminPoolLoader.php
Route/RoutesCache.php

`Symfony\Component\Config\Resource\FileResource` fail if the given path is invalid since Symfony 3.1.
It was the case from the begining because of mocking an interface.
A condition is added to the `RoutesCache` class.
Ref: https://github.com/phpDocumentor/ReflectionDocBlock/pull/72#issuecomment-222651257

Fix DefaultRouteGenerator cache tests with Symfony 3.1

---

Resources/views/CRUD/list__select.html.twig

```markdown
- Fixed wrong method call in `list__select.html.twig`. 
```
Fixed bug introduced with #3887. The wrong method was used.

Fixed wrong method call in "list__select.html.twig" 

---

Admin/Pool.php
Tests/Admin/PoolTest.php

```markdown
- Fixed `Pool::getAdminsByGroup()` for the new admin groups values
```
In df42796fde5d850f04440fb344cac25caad25268, the admin groups variable was
changed from containing only service IDs to containing an array of options
per item.
To get the service ID, the 'admin' entry should be used.
This is a bug in 3.0.0, but I can't see a way to target 3.0 specifically. Is there any way
to get this into a 3.0.1 versions or how do you handle that?

Use admin entry as service ID

---

Resources/doc/getting_started/installation.rst

The docs were referencing the wrong (outdated) version.

Updated required version in docs

---

Resources/public/css/layout.css
Resources/views/CRUD/list__select.html.twig

Rebase of https://github.com/sonata-project/SonataAdminBundle/pull/3252
```markdown
- The `Select` button is always visible and has a primary check style in `sonata_type_model_list` popups
```
The `Select` button is always visible and never hidden. This is a improvement for mobile devices.
Before
After

Always show the "Select" button in "sonata_type_model_list"

---

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
DependencyInjection/Compiler/ExtensionCompilerPass.php
DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
DependencyInjection/Configuration.php
DependencyInjection/SonataAdminExtension.php
UPGRADE-4.0.md

```markdown
- Class `Sonata\AdminBundle\DependencyInjection\Compiler\AddDependencyCallsCompilerPass` is now final
- Class `Sonata\AdminBundle\DependencyInjection\Compiler\AddFilterTypeCompilerPass` is now final
- Class `Sonata\AdminBundle\DependencyInjection\Compiler\ExtensionCompilerPass` is now final
- Class `Sonata\AdminBundle\DependencyInjection\Compiler\GlobalVariablesCompilerPass` is now final
- Class `Sonata\AdminBundle\DependencyInjection\Configuration` is now final
- Class `Sonata\AdminBundle\DependencyInjection\SonataAdminExtension` is now final
```
Because those classes should never be overridden.

Final dependency injection classes

---

DependencyInjection/SonataAdminExtension.php

The bundle is required on the composer.json file.
Check it manually makes no sense.

Remove core-bundle presence check

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
Tests/Admin/AdminTest.php
UPGRADE-3.x.md

Closes #3795
```markdown
- The `$context` argument of `AdminInterface::createQuery` was deprecated.
```
Having a variable named $context is a code smell indicating a possible
violation of the Open-Close Principle. Removing this argument should
lead to better architecture.

Deprecate $context argument of createQuery

---

Admin/AbstractAdmin.php

Closes #3939 
```markdown
- `AbstractAdmin::defineFormBuilder` method is public again
```
This method is called by `AdminType::buildForm`.

Revert: Making AbstractAdmin::defineFormBuilder private

---

Admin/AbstractAdmin.php

```markdown
- Fix wrong view role check on `AbstractAdmin::getSearchResultLink`
```
If the search link is a show action, it will check against the `SHOW` role.
This role does not exists. The right one is `VIEW`.

Fix wrong view role check on AbstractAdmin::getSearchResultLink

---

Resources/config/core.xml

Closes #3948 
```markdown
- Fixes broken extractor
```
I broke the extractor, and did not notice it. Adding a smoke test for the service would be helpful

Use valid syntax for method call argument

---

Controller/CRUDController.php

I am targetting this branch, because it's broken in the current branch. Will have to be forward merged into master.
The `CRUDController::editAction` accepted an `$id` parameter which was always overwritten, serving 99% of use cases just fine, but not the exceptional case it was added for.
```markdown
- Made CRUDController::editAction respect optional parameter
```

Fix CRUDController::editAction ignoring its optional parameter

---

Resources/views/Form/form_admin_fields.html.twig

I am targetting this branch, because this is a bugfix.
Fixes #3951 
```markdown
- Not aligned checkbox and radio on horizontal form
```
With Twitter Bootstrap, checkbox and radio inputs need a col-sm-offset-* class to get aligned with the other inputs.
Before:
After:
@EmmanuelVella can you please review and confirm this one?

Fix not aligned checkbox and radio on horizontal form

---

Controller/CRUDController.php

Reverts sonata-project/SonataAdminBundle#3961
```markdown
- Reverted #3961 to fix a regression concerning child admins on edit route
```
#3961 brought a regression with child admins.
More info here: https://github.com/sonata-project/SonataAdminBundle/commit/be82d59407de9a2613fcd700e78d86794fdc464e#commitcomment-17941270

Revert "Fix CRUDController::editAction ignoring its optional parameter"

---

Tests/Form/ChoiceList/ModelChoiceListTest.php
Tests/Form/ChoiceList/ModelChoiceLoaderTest.php

I am targetting this branch, because…
The import path was wrong. This wouldn't work when we remove the tests from the autoloader (Refs https://github.com/sonata-project/SonataCoreBundle/pull/316).

Fixed wrong import in tests

---

DependencyInjection/SonataAdminExtension.php
Form/Type/ModelListType.php
Form/Type/ModelTypeList.php
Tests/Form/Type/ModelTypeListTest.php
UPGRADE-3.x.md

I am targetting this branch, because this is a deprecation.
```markdown
- The `Sonata\AdminBundle\Form\Type\ModelTypeList` is deprecated for `ModelListType`
```
All form type should finish by `Type`. This one is a mistake.

Fix bad class name for ModelListType

---

Admin/AbstractAdmin.php
Tests/Admin/AdminTest.php

I am targetting this branch, because…
Closes #2883, #2946
```markdown
- Ignoring `translation_domain` in tab menu
```
The `translation_domain` of the admin was ignored when rendering a tab menu defined under `configureTabMenu`. The default domain `messages` was used instead.
Before
After

Fixed missing tab translation

---

Form/Type/ModelAutocompleteType.php

I am targetting this branch, because it's a code patch.
```markdown
- Removed useless `ModelAutocompleteType::getParent` override
```
This override is useless because it's the default behavior of `Symfony\Component\Form\AbstractType`.
Ref: https://github.com/symfony/symfony/blob/v2.3.42/src/Symfony/Component/Form/AbstractType.php#L52-L55

Remove ModelAutocompleteType::getParent override

---

Form/Type/ModelAutocompleteType.php
Tests/Form/Type/ModelAutocompleteTypeTest.php

I am targetting this branch, because it's a deprecation bugfix.
```markdown
- Removed useless `read_only` option definition from `ModelAutocompleteType`
```
This option is already provided by Symfony since v2.3.
Ref: http://symfony.com/doc/2.3/reference/forms/types/form.html#read-only
It's deprecated since v2.8 and removed since v3.0.
It has to be removed on next major.
cc @pulzarraider @axzx

Remove read_only option definition from ModelAutocompleteType

---

Resources/public/Admin.js

```markdown
- Support for select2 v4 (`select2.full.js` file is needed)
```
Because changing Select2 vendor version is BC break for our case, I propose an alternative waiting #2795 to be updated and merged for next major.
The BC trick between Select2 v3 and v4 is quite simple, so let add this to make admin-bundle compatible with both.
With that, user can upgrade Select2 vendor manually without waiting the next major release of admin-bundle.

Make it compatible with both Select2 v3 and v4

---

Builder/BuilderInterface.php
Builder/FormContractorInterface.php

This should give a better idea of what this method is supposed to be
doing.

Document interface method

---

Tests/Menu/Integration/BaseMenuTest.php

I am targetting this branch, because this is a bugfix.
Fixes #3766
```markdown
- Fixed unit test suite runned from a project
```
Applied the same strategy that in this existing test to restore the ability to run AdminBundle test suite from a project context:
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Tests/Form/Widget/BaseWidgetTest.php

Allow unit test suite to run from project context

---

Tests/Block/AdminListBlockServiceTest.php
Tests/Block/AdminSearchBlockServiceTest.php
Tests/Block/AdminStatsBlockServiceTest.php
Tests/Fixtures/Block/FakeBlockService.php
composer.json

I am targetting this branch, because this is a fix for the unit tests in the stable branch.
```markdown
- unit tests use the correct namespace in imports.
```
This fixes the imports in the test cases. The sub namespace `Tests` isn't public anymore.

Fixed wrong imports in tests

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targetting this branch, because this is a bugfix.
Fixes #3996
```markdown
- Not working `read_only` option on Twig with Symfony 3
```
This option does not exist anymore on Symfony 3.0+
@qbbr Could you please test this PR and confirm this solve your issue?

Test if read_only is defined on the form view

---

Datagrid/Datagrid.php

I am targetting this branch, because it's a BC bugfix.
```markdown
- Handle Symfony BC for Datagrid hidden types
```
Use `HiddenType` class instead of `hidden` string for Symfony 2.8+.

Handle Symfony BC for Datagrid hidden types

---

Resources/doc/getting_started/creating_an_admin.rst
Resources/doc/getting_started/installation.rst

I am targeting this branch, because I am fixing bugs so it is backward compatible.
```markdown
Typos in the get started doc
```
I did the get started doc and found a few typos. Here are fixes for them.

Doc: Get started fixes

---

Resources/public/css/styles.css

I am targetting this branch, because this change must effect 3.x branch.
Fixes #4038
```markdown
- Changed css `margin-left: -20px` of checkbox. 
```
Checkbox on filter field was shown 20px on the left to where it supposed to be. This was because all the checkboxes were being effected from a change which has been done for checkboxes on edit page.

corrected css margin-left for checkbox

---

Resources/views/standard_layout.html.twig

I am targetting this branch, because there's no BC break.
Fixes #3579
```markdown
- Fixed visibility of block `sonata_top_nav_menu` contents
```
Added security checks in order to show contents of block sonata_top_nav_menu only to logged in users. So far `add` and `user` dropdowns were visible to everyone.

Fixed sonata_top_nav_menu visibility

---

Admin/FieldDescriptionCollection.php
Command/ExplainAdminCommand.php
Filter/FilterFactory.php
Tests/Admin/FieldDescriptionCollectionTest.php
Tests/Filter/FilterTest.php
Tests/Security/Handler/AclSecurityHandlerTest.php
Twig/Extension/SonataAdminExtension.php

I am targetting this branch, because it is a bugfix as `RunTimeException` never exist.
```markdown
- use `RuntimeException` instead of non existing `RunTimeException`
```
`RunTimeException` does not exist, use `RuntimeException` instead.

use RuntimeException instead of non existing RunTimeException

---

Resources/config/core.xml
Tests/Twig/GlobalVariablesTest.php
Twig/GlobalVariables.php
UPGRADE-3.x.md

I am targetting this branch, because I would like to improve code and test coverage
```markdown
- Changed injection of `$container` to `$adminPool` in `Twig/GlobalVariables`
- The `$container` property in `Twig/GlobalVariables`
```
Improving code and test coverage

changed injection of container to injection of pool

---

Form/Type/Filter/ChoiceType.php
Form/Type/Filter/DateRangeType.php
Form/Type/Filter/DateTimeRangeType.php
Form/Type/Filter/DateTimeType.php
Form/Type/Filter/DateType.php
Form/Type/Filter/NumberType.php
Tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php

I am targetting this branch, because this is a patch.
Closes #3283
```markdown
- Fixed duplicate translation for list filters
```
The filters in the list were translated two times, once in the php classes and a second time in the twig template. 
Before
After

Fixed duplicate translation in filters

---

Admin/BreadcrumbsBuilder.php
Resources/views/standard_layout.html.twig
Tests/Admin/BreadcrumbsBuilderTest.php

I am targetting this branch, because it is a bug fix
```markdown
- XSS Vulnerability in breadcrumbs
```
Fix {{ menu.label }} instead of {{menu.label | raw}}
This fixes breadcrumbs xss vulnerability in Sonata Admin Bundle

Bug: XSS vulnerability

---

Resources/views/standard_layout.html.twig

I am targetting this branch, because this is a minor change.
Rebase of https://github.com/sonata-project/SonataAdminBundle/pull/3465
```markdown
- Removed unnecessary securiy checks in `standard_layout.html.twig`
```
This checks weren't needed anymore, because only this template is only used for authed users.

Removed unnecessary security checks

---

Resources/views/CRUD/base_list.html.twig

I am targetting the 3.x branch, because this is a bugfix.
```markdown
- The "batch" checkbox at the top of the list would not work when iCheck is disabled.
```
When you disable iCheck (by putting "sonata_admin.options.use_icheck: false" in your configuration), the checkbox at the top of the list would not work anymore. This is due to the fact that currently only the "ifChanged" event from iCheck is handled, instead of the standard "change" event for checkboxes. This patch fixes this. Unfortunately, putting only the standard "change" event doesn't work either, because of this issue: https://github.com/fronteed/iCheck/issues/244, so we need to intercept both.
I also added documentation to the JavaScript code related to the patch.

Bugfix for batch checkbox not working if "icheck" is disabled

---

Admin/AbstractAdmin.php
Tests/Admin/AdminTest.php
Tests/Admin/BreadcrumbsBuilderTest.php
Tests/Fixtures/Bundle/Entity/BlogPost.php
Tests/Fixtures/Bundle/Entity/Comment.php

I am targeting branch 3.x, because it's a patch.
Fixes #2585 
```markdown
- `AbstractAdmin::setSubject` in order to check that given `$subject` matches registered admin class entity.
```
Checks the type of `$subject` against `$this->class`

Checks the type of $subject against $this->class

---

Resources/doc/reference/batch_actions.rst

I am targetting this branch, because the documentation is currently incorrect for this example.
- Added missing comma
```markdown
- Added missing comma in documentation example
```
A missing comma made the array in the example invalid.

Add missing comma

---

Admin/BreadcrumbsBuilder.php
Admin/BreadcrumbsBuilderInterface.php
Tests/Admin/BreadcrumbsBuilderTest.php
UPGRADE-4.0.md

```markdown
- The `BreadcrumbsBuilder::buildBreadcrumbs()` public visibility
- The `BreadcrumbsBuilderInterface::buildBreadcrumbs()` method
```
This was needed before, because the breadcrumbs building process was
half in the admin class, half in this class.

Remove buildBreadcrumbs from the public interface

---

Tests/Menu/Matcher/Voter/ChildrenVoterTest.php

I am targetting this branch, because I would like to improve code and test coverage
```markdown
- Added test for `AdminBundle\Menu\Matcher\Voter\ChildrenVoter`
```
Adding more tests.

added test for ChildrenVoter

---

Admin/AbstractAdmin.php
Resources/doc/reference/action_export.rst
Tests/Admin/AdminTest.php

Refs https://github.com/sonata-project/SonataAdminBundle/pull/3527
```markdown
- export fields names are now translated
```
The export function now checks, if a label exists with the name created by the translator strategy.

Make export fields translateable

---

DependencyInjection/Compiler/AddFilterTypeCompilerPass.php
Resources/doc/reference/action_list.rst
Tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php

I am targetting this branch, because this feature is BC.
Closes #4035
```markdown
- Added class name support for `AbstractAdmin::configureDatagridFilters`
```
When using `AbstractAdmin::configureDatagridFilters`, you can now use the alias (e.g. `doctrine_orm_choice`) or the class name (`ChoiceFilter::class`), which is the symfony2.8+ style.

Added support for filter class names

---

Controller/CRUDController.php
Resources/views/CRUD/batch_confirmation.html.twig
Tests/Controller/CRUDControllerTest.php

I am targetting this branch, because this is BC this is BC.
```markdown
- Moved translation of batch action_label to twig template
```
We use twig for translating several labels and text. This should also been done for batch action. The new `batch_translation_domain` parameter could be used for other translations too.

Moved translation of batch action_label to template

---

Admin/BreadcrumbsBuilder.php
Resources/views/standard_layout.html.twig
Tests/Admin/BreadcrumbsBuilderTest.php

```markdown
- Moved translation of breadcrumbs to twig template
```
We use twig for translating several labels and text. This should also been done for the breadcrumb, so we could use the `KnpMenuBundle` for the whole breadcrumb generation and translation logic.

Moved translation of breadcrumbs to template

---

Admin/AbstractAdmin.php
Resources/views/Button/acl_button.html.twig
Resources/views/Button/create_button.html.twig
Resources/views/Button/edit_button.html.twig
Resources/views/Button/history_button.html.twig
Resources/views/Button/list_button.html.twig
Resources/views/Button/show_button.html.twig
Resources/views/CRUD/action.html.twig
Resources/views/CRUD/base_acl.html.twig
Resources/views/CRUD/base_edit.html.twig
Resources/views/CRUD/base_history.html.twig
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/batch_confirmation.html.twig
Resources/views/CRUD/delete.html.twig
Tests/Admin/AdminTest.php

Pull requested against 3.x as it looks like a bug!
```markdown
- Move actions buttons display logic from templates to `AbstractAdmin::configureActionButtons`
- Hide filters action button if admin doesn't have any displayable filters
- ability to hide the navbar if there are no displayable filters and no actions buttons
- Hide the actions navbar if empty
```
Without these changes, it was not possible to hide the navbar even if there is no mosaic button, no displayable filters and no actions. This may have been a feature in the past because https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L241 contains emptyness checks against tabs menu, filters and actions.
For the BC beak, I don't know if I did things right by removing the checks in …

Fix empty list navbar

---

Command/ExplainAdminCommand.php

I am targetting this branch, because it is the stable one
```markdown
- Fix how metadata information are retrieved when admin information are dumped
```
Fix how metadata information are retrieved when admin information are dumped

fix getMetadataFor detection

---

Form/Type/AclMatrixType.php

I am targetting this branch, because…
Closes #
Fixes #
```markdown
- symfony 3 type support in AclMatrixType
```
Support symfony3 form type naming

fix(bc): form type support of >2.8

---

Util/AdminObjectAclManipulator.php

Rebase of #3786
```markdown
- symfony 3 support in AclMatrixType
```
Updated `AclMatrixType` to work with symfony 3.
Refs #3746

Fix BC issue on AclMatrixType

---

Resources/views/standard_layout.html.twig

I am targetting this branch, because this is a patch for #4070.
```markdown
- Fixed translation in browser titles breadcrumb
```
#4070 moved the translation of breadcrumbs to the template. The translation of the browser titles breadcrumb was missing.

Fixed translation in title breadcrumb

---

Admin/BreadcrumbsBuilder.php
Tests/Admin/BreadcrumbsBuilderTest.php

I am targetting this branch, because this is a patch for #4070.
```markdown
- Fixed translation of entities in breadcrumb
```
Removed unneeded translation of entitiy names in breadcrumb.

Fixed incorrect translation of entity names

---

Resources/views/CRUD/base_list.html.twig

Changes in #4062 by commit 7056ebbcfeba959539326be3f4dfa8be05db112a are breaking compatibility. I will update the #4062 changelog as things are no longer complete.

Revert "don't display action menu if there are no filters"

---

Resources/doc/reference/configuration.rst

Targeting 3.x because no BC Break
Update the configuration in the documentation
No css is applied without this line, for example when you create a new page on sonata page, and the url unique exception occured.

[DOC] Fix the render of global errors on the form

---

Tests/Form/Widget/BaseWidgetTest.php
Tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
composer.json

```markdown
- Widget tests should extend `AbstractWidgetTestCase`
```
Use the exsting TestCase to reduce code.

Extending existing widget TestCase

---

Resources/doc/reference/action_show.rst
Show/ShowMapper.php
Tests/Show/ShowMapperTest.php

I am targetting this branch, because it is a new feature
```markdown
- Added `ShowMapper::removeGroup` method
```
Add ShowMapper::removeGroup method, similar to Add FormlMapper::removeGroup method

Add ShowMapper::removeGroup method

---

Resources/public/css/colors.css
Resources/views/CRUD/base_acl_macro.html.twig
Resources/views/CRUD/base_edit_form.html.twig
Resources/views/Helper/render_form_dismissable_errors.html.twig

I am targetting 3.x because no BC Break
Close a part of #4099
Fixes a part of #4099 
The render of global form error is now a Bootstrap 3 alert dismissible

Standardize the global form error

---

Form/FormMapper.php
Resources/doc/reference/form_types.rst
Tests/Form/FormMapperTest.php

I am targeting this branch, because it looks like a bug and it's BC.
Fixes #4100
```markdown
- auto-detect type when adding `FormBuilderInterface` to `FormMapper`
```
When adding a `FormBuilderInterface` to `FormMapper` the type is now auto-detected. This avoid repeating informations hold in the `FormBuilderInterface` when adding the field and is never overriding the type if provided.

Autodetect type when adding a FormBuilderInterface

---

Admin/AbstractAdmin.php
Admin/AbstractAdminExtension.php
Admin/AdminExtensionInterface.php
Admin/AdminInterface.php
Resources/doc/reference/action_list.rst
Resources/views/CRUD/base_list.html.twig
Tests/Admin/AdminTest.php
Tests/Fixtures/Admin/FilteredAdmin.php

I am targetting this branch, because this is a new BC feature.
Rebase of #4017
```markdown
- Added new methods to set default values for the list view
```
If you set a filter to the `AbstractAdmin::$datagridValues`, the filter is always shown. This PR adds a feature to have a better solution for default values, so filters that matches the default value are now hidden.

Hide filters with a default value

---

Form/Type/Filter/ChoiceType.php

I am targetting this branch, because it's about avoiding deprecation warnings when using Sf >= 2.8, while keeping the old behavior.
```markdown
- Type for `Filter Operator` to be compatible with Symfony 2.8+
```
Remove deprecation warnings when using Sf >= 2.8

Fixed Symfony deprecation warning on filter operator type

---

Form/Type/ChoiceFieldMaskType.php
Form/Type/Filter/DateRangeType.php
Form/Type/Filter/DateTimeRangeType.php
Form/Type/Filter/DateTimeType.php
Form/Type/Filter/DateType.php
Form/Type/Filter/DefaultType.php
Form/Type/Filter/NumberType.php
Form/Type/ModelHiddenType.php
Form/Type/ModelListType.php
Form/Type/ModelReferenceType.php
Form/Type/ModelType.php
Tests/Form/Type/ChoiceFieldMaskTypeTest.php
Tests/Form/Type/ModelHiddenTypeTest.php

I am targetting this branch, because it's about avoiding deprecation warnings when using Sf >= 2.8, while keeping the old behavior.
```markdown
- Use class name when referencing `Form Type` to be compatible with Symfony 2.8+
```
Remove deprecation warnings when using Sf >= 2.8

Used classname in form type name

---

DependencyInjection/SonataAdminExtension.php

I am targetting this branch, because it's about removing sonata deprecation warning that gets populated on each page.
```markdown
- Remove `Sonata\CoreBundle\Exporter\Exporter` from classes to compile to cache to avoid deprecation warning
```
Remove deprecation warnings for sonata version >= 3.1
Here's the current deprecation message: 
```
The Sonata\CoreBundle\Exporter\Exporter class is deprecated since version 3.1 and will be removed in 4.0. Use Exporter\Exporter instead
```

Removed exporter class from classes to compile

---

Form/Type/Filter/ChoiceType.php
Form/Type/Filter/DateRangeType.php
Form/Type/Filter/DateTimeRangeType.php
Form/Type/Filter/DateTimeType.php
Form/Type/Filter/DateType.php
Form/Type/Filter/NumberType.php

I am targetting this branch, because it's about avoiding deprecation warnings when using Sf >= 2.8, while keeping the old behavior.
```markdown
- Set `choices_as_values` to `true` on choice type based to be compatible with Symfony 3
```
Remove deprecation warnings when using Sf >= 2.8
Here's the current deprecation message: 
```
The value "false" for the "choices_as_values" option of the "choice" form type (Symfony\Component\Form\Extension\Core\Type\ChoiceType) is deprecated since version 2.8 and will not be supported anymore in 3.0. Set this option to "true" and flip the contents of the "choices" option instead.
```

Fixed choices_as_values deprecation warning

---

Tests/Controller/CRUDControllerTest.php
Tests/Export/ExporterTest.php
Tests/Form/Widget/BaseWidgetTest.php

I am targetting this branch, because this is BC
No changelog, this is only about the test suite (so the users do not care).
This fixes several (but not all) deprecation notices. The only deprecation notice left comes from the SonataCoreBundle, it's about the `initRuntime` call in `AbstractWidgetTestCase` (I think, might actually be wrong b/c the `FormExtension` is marked with an interface that should make that ok).

Avoid deprecation notices

---

Admin/AbstractAdmin.php
Tests/Admin/AdminTest.php
Tests/Controller/CRUDControllerTest.php

I am targetting this branch, because I think this is BC
```markdown
- The admin no longer checks for the `translator` service before translating.
```
To use SonataAdminBundle, the translator service has to be enabled. It
is always injected in the admin by a compiler pass, which means there is
no point (anymore?) in checking it exists.
Closes #4089

Remove checks for existing translator

---

Resources/doc/getting_started/the_list_view.rst

I am targeting this branch, because the documentation is out of date for Symfony3
```markdown
- `property` to `choice_label` in the docs
```
Docs update for Symfony3: changed 'property' to 'choice_label'

Update for Symfony2

---

Resources/views/Pager/base_results.html.twig

```markdown
- whitespace in HTML output for `entries per page` dropdown
```
It is much easier for tests, Behat for example

avoid whitespace in rendered html output

---

Resources/doc/reference/security.rst
Security/Handler/RoleSecurityHandler.php
Tests/Security/Handler/RoleSecurityHandlerTest.php

I targeted this branch because it was the lastest branch when the PR was created. There is no BC break so really could be applied to all active branches IMO.
This allows user to give coarse grained access to an admin area by
granting LIST,VIEW,CREATE,EDIT,DELETE and EXPORT to a user with the
corresponding _ALL role. So if an app has an admin area with service id
acme.user.admin and they provide a user with ROLE_ACME_USER_ADMIN_ALL
they automatically have LIST,VIEW,CREATE,EDIT,DELETE.
This is the implementation for #3806 
Fixes #3806 
```markdown
- Added additional `_ALL` role check to `RolesecurityHandler`
```

Provide _ALL type Role for role base security

---

Resources/views/Block/block_rss_dashboard.html.twig
Resources/views/Block/block_search_result.html.twig
Resources/views/Block/block_stats.html.twig
Resources/views/Button/acl_button.html.twig
Resources/views/Button/create_button.html.twig
Resources/views/Button/edit_button.html.twig
Resources/views/Button/history_button.html.twig
Resources/views/Button/list_button.html.twig
Resources/views/Button/show_button.html.twig
Resources/views/CRUD/base_edit_form.html.twig
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/batch_confirmation.html.twig
Resources/views/CRUD/dashboard__action.html.twig
Resources/views/CRUD/dashboard__action_create.html.twig
Resources/views/CRUD/delete.html.twig
Resources/views/CRUD/list__action_delete.html.twig
Resources/views/CRUD/list__action_edit.html.twig
Resources/views/CRUD/list__action_show.html.twig
Resources/views/CRUD/list__select.html.twig
Resources/views/CRUD/preview.html.twig
Resources/views/CRUD/select_subclass.html.twig
Resources/views/CRUD/tree.html.twig
Resources/views/Form/form_admin_fields.html.twig
Resources/views/Menu/sonata_menu.html.twig
Resources/views/standard_layout.html.twig

I am targetting this branch, because it's backward compatibibile changes
```markdown
- Improve accessibility by adding `aria-hidden="true"`
```
You could read more about it on: http://fontawesome.io/accessibility/
Main part is: 
> The assistive technology may read the unicode equivalent, which could not match up to what the icon means in context, or worse is just plain confusing

Add aria-hidden to icon

---

Security/Handler/RoleSecurityHandler.php
Tests/Security/Handler/RoleSecurityHandlerTest.php

I am targetting this branch, because it is a bug fix.
```markdown
- The `ALL` role needs to be checked separately, otherwise the `AuthorizationChecker` return false all the time.
```

Check all role

---

Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because this is just explicitly defining a variable (which would generate an error if strict mode was used). It doesn't break or change any behaviour.
```markdown
- Added `var` keyword to explicitly define the "showMaskChoiceEl" variable
```
The JS variable "showMaskChoiceEl" was not defined in the twig template. It's always better to do this. In strict mode it's even required or an error will be generated.

Explicitly defined "showMaskChoiceEl" JS variable

---

Admin/AbstractAdmin.php
DependencyInjection/Configuration.php
Resources/doc/reference/templates.rst
Tests/Admin/AdminTest.php
Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php

I am targetting this branch, because this PR is full compatible with previous versions.
```markdown
- Moved the raw references of buttons templates from `Admin\AbstractAdmin` to configuration options
```
The templates used to render the buttons (create, update, ...) are not configurable. This make impossible or at least hard to override from a third part bundle. For exemple, i'm working on a [bundle that provide a Gentellela theme](https://github.com/kinulab/sonata-gentellela-theme-bundle), but does files are not overwrittable without putting them in `app/Resources`.
So this PR move the hard linked references to configurable options in the templates part.

Add configuration options to define the template of buttons

---

Resources/views/standard_layout.html.twig

I am targetting this branch, because the change is backward compatible
```markdown
- Added three new sub-blocks to standard_layouts javascript block
```
Added three new sub-blocks to standard_layouts javascript block. This allows for more granular extension without breaking BC
- I wondered what's the reason that the loading of the localised versions of moment.js and select2 are not registered and loaded via the admin pool? Doing so would make the template simpler and we would not need the block javascripts_sonata_l10n at all. We could then also move the logic of generating the proper localised names to PHP instead of Twig (f.e. for respecting the fact that the portuguese version of select2 is called 'pt_PT' and not 'pt'). I didn't include this in the PR because I wanted to hear your …

Added additional extension points for standard_layout

---

Admin/AbstractAdmin.php
Admin/AdminInterface.php
Controller/CRUDController.php
Resources/config/twig.xml
Resources/doc/reference/translation.rst
Resources/views/Block/block_admin_list.html.twig
Resources/views/Block/block_search_result.html.twig
Resources/views/CRUD/base_edit_form.html.twig
Resources/views/CRUD/base_edit_form_macro.html.twig
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/base_show_compare.html.twig
Resources/views/CRUD/base_show_field.html.twig
Resources/views/CRUD/base_show_macro.html.twig
Resources/views/CRUD/preview.html.twig
Resources/views/CRUD/tree.html.twig
Resources/views/Form/form_admin_fields.html.twig
Tests/Admin/AdminTest.php
Tests/Controller/CRUDControllerTest.php
Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php
UPGRADE-3.x.md

Closes #4072
Rebase of #4089
```markdown
- Added `CRUDController::trans` method
- translation in twig templates uses the twig translation filter
- deprecated `AdminInterface::trans` method
- deprecated `AbstractAdmin::$translator` property
- deprecated `AbstractAdmin::trans` method
- deprecated `AbstractAdmin::transChoice` method
- deprecated `AbstractAdmin::getTranslator` method
- deprecated `AbstractAdmin::setTranslator` method
```
This change deprecates the translator in the `AbstractAdmin` and moves all translation logic to the templates and the CRUDController.

Deprecate translation in Admin class

---

Resources/views/Block/block_admin_list.html.twig
Resources/views/Block/block_search_result.html.twig

I am targetting this branch, because this is a patch.
Fixes #4124
Fixed wrong template replacements for `admin.trans`.

Fixed #4124

---

Resources/views/CRUD/base_edit_form.html.twig
Resources/views/CRUD/base_edit_form_macro.html.twig
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/base_show_field.html.twig
Resources/views/CRUD/base_show_macro.html.twig
Resources/views/Form/form_admin_fields.html.twig

I am targetting this branch, because this is a bugfix.
Closes #4124 
```markdown
- Fixed missing default `translationDomain`
```
Added the admin translation domain if it hasn't been set.

Fixed default translation domain in #4124

---

Block/AdminListBlockService.php
Block/AdminSearchBlockService.php
Block/AdminStatsBlockService.php
composer.json

Fixes #4155
```markdown
- extend `AbstractBlockService` instead of deprecated `BaseBlockService`
- block-bundle dependency is now 3.2
```
extend AbstractBlockService instead of deprecated BaseBlockService and increase block-bundle dependency to ^3.2
Deprecation was introduced here https://github.com/sonata-project/SonataBlockBundle/pull/328 and released in Block-Bundle 3.2.0

extend AbstractBlockService instead of deprecated BaseBlockService and increase block-bundle dependency to ^3.2

---

Admin/AbstractAdmin.php

I am targetting this branch, because it is a patch
```markdown
- fixed `trigger_error` calls - `E_USER_DEPRECATED` was concatenated to the sentence, not passed as argument.
```
Changing dot `.` to comma `,` in `trigger_error` calls, added in #4124

AbstractAdmin trigger_error punctuation fix

---

Resources/translations/SonataAdminBundle.it.xliff

I am targetting this branch, because it only add a missing translation field
added a missing translation for the Italian version

added a missing field in the italian translation

---

Tests/Form/Type/AdminTypeTest.php
Tests/Form/Type/ModelListTypeTest.php
Tests/Form/Type/ModelReferenceTypeTest.php
Tests/Security/Acl/Permission/AdminPermissionMapTest.php

I am targetting this branch, because this is pedantic
This PR increases code coverage.

Increase coverage

---

Filter/FilterFactory.php
Tests/Filter/FilterFactoryTest.php

I am targetting this branch, because this is a BC feature.
``` markdown
- Improved class support for filter factory
```
Added support for filters that doesn't exists as a service.

Improved class support for filter factory

---

Resources/doc/cookbook/recipe_custom_action.rst

I am targetting this branch, because this is just a little documentation change.
```markdown
- Added a note to the 'Create a custom admin action' cookbook.
```
Modified recipe_custom_action.rst file to document a note for when a user want to render a custom action directly into a template.

Add note for actions rendered directly into a template.

---

Resources/doc/getting_started/installation.rst
Resources/doc/reference/console.rst
Resources/doc/reference/getting_started.rst
Resources/doc/reference/routing.rst
Resources/doc/reference/security.rst

symfony 3 changed console paths to /bin
Simple fix for the documented path to the bin/console

updated bin paths

---

Resources/views/CRUD/base_show.html.twig
Resources/views/CRUD/base_show_compare.html.twig
Resources/views/CRUD/base_show_macro.html.twig

I am targetting this branch, because there is no BC break
Closes #4014
Fixes #4014
```markdown
- Use block instead of macro to render show groups
- Fixed bug in revisions compare view
- Deprecated base_show_macro.html.twig
```
Fix for revisions compare view

Fixed revisions compare view

---

Controller/CRUDController.php
Controller/HelperController.php
Tests/Controller/CRUDControllerTest.php
Tests/Controller/HelperControllerTest.php
Tests/Twig/Extension/SonataAdminExtensionTest.php

I am targetting this branch, because this is bugfix.
Closes #4152, #4154
```markdown
- Added helper method `CRUDController::setFormTheme`.
- Fix compatibility with Symfony 3.2 form renderer.
```
Proposed sollution in #4154 breaks compatibility with older Symfony versions because `twig.form.renderer` service is private https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml#L156 . Also I've updated code in other places.

Fix compatibility with Symfony 3.2 form renderer

---

DependencyInjection/SonataAdminExtension.php

I am targetting this branch, because this is BC since the roles deleted shouldn't be there in the first place AFAIK.
```markdown
- Fixed permissions when setting role for the security handler
```
Fixed permissions when setting role for the security handler. Operator and Master should be only for ACL based permission. Also, the role ALL is missing.
Reference: https://sonata-project.org/bundles/admin/3-x/doc/reference/security.html#role-handler

Adjust role permission

---

Resources/views/CRUD/base_show.html.twig

Partially closes #4229
```markdown
- translation in twig templates uses the twig translation filter
```
Removes deprecated translations calls from the `AdminInterface::trans` method.

Remove deprecated translation logic

---

Controller/CRUDController.php

I am targetting this branch, because of a bug introduced with commit https://github.com/sonata-project/SonataAdminBundle/commit/d8fc2edae14bc22d32e7d99990bcea54b626d01a .
Closes #4231 
* Fixes #4231 broken form theme
```markdown
* Filter form theme was used for create and edit forms too.
```
The wrong form theme was used in create and edit forms, because of the changes made in https://github.com/sonata-project/SonataAdminBundle/commit/d8fc2edae14bc22d32e7d99990bcea54b626d01a (in tag 3.10.1). 
Please tag a new version of this bundle after this changes have been merged.

Set correct form theme for edit/create actions, fixes #4231

---

Resources/views/CRUD/base_show.html.twig

Closes #4230
```markdown
- display correct name of group uses default translation domain
```
Set default translation domain.

fix uses the twig translation filter

---

Admin/AbstractAdmin.php
DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Resources/views/standard_layout.html.twig

I am targetting this branch, because no BC break, bug fix.
Closes #4229
```markdown
- a Twig deprecation added in Twig 1.28.0
- a Sonata deprecation called by Sonata itself by adding a way to disable it when called internally
```

Fix deprecations

---

Resources/views/Menu/sonata_menu.html.twig

I am targetting this branch, because its a bug fix.
Closes #4218
```markdown
- a bug with the side menu arrow position was fixed
```
https://github.com/sonata-project/SonataAdminBundle/issues/4218

Dropdown arrows position corrected

---

Tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php

I am targetting this branch, because it's a BC feature.
```markdown
- Extract admin group and label translations.
```
When using JMSTranslationBundle to extract translations, neither the admin group nor the admin label are extracted. Those are now extracted allowing full extraction of the admin strings using the JMSTranslationBundle extractor.

extract admin group and label translations

---

Resources/doc/cookbook/recipe_image_previews.rst

I am targetting this branch, because {reason}.
update image preview recipe
The current version of the recipe uses `request` service which is deprecated since symfony 3.0 and should not be used since 2.4.

update recipe to use request_stack

---

Resources/doc/getting_started/installation.rst

I am targetting this branch, because it's one I'm reading.
I noticed that on the documentation https://sonata-project.org/bundles/admin/master/doc/getting_started/installation.html the note on translator is present twice

note on translator is present twice

---

Resources/views/CRUD/base_list_field.html.twig
Tests/Twig/Extension/SonataAdminExtensionTest.php

I am targetting this branch, because it is BC.
Closes sonata-project/SonataClassificationBundle#241
```markdown
- Fixed behaviour of persistent parameters in list editables
```
Prevents overwriting parameters set in template. For example classification-bundle introduce `context` parameter which conflicts with `context == 'list'` expected by setObjectFieldValueAction() (see sonata-project/SonataClassificationBundle#241). Overwriting `context` cause "Invalid context" error while editing fields.
Merging with persistent parameters was implemented in #2725. I do not see any discussion about how it should work or the unit test for this case. So I assume that the author's intention was to include parameters from expansions, and no overriding existing ones.

Inverse merge order of persistent parameters in list editables

---

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
Tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php

I am targetting 3.x, because it's about adding admin service inheritance. It doesn't break backward compatilibity.
```markdown
- Updated compiler pass to support parent definition when using abstract service for admin.
```
This PR is about supporting abstract service definition for admin service.
It allows to declare another admin service using the same admin class, with different parameters, but let us avoid redeclaring common arguments for the admin class.
This allow to use this kind of code:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<container xmlns="http://symfony.com/schema/dic/services"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
<services>
<service …
```

Support abstract admin service inheritance

---

Datagrid/Pager.php
Tests/Datagrid/PagerTest.php
UPGRADE-3.x.md

**This is a rebase of #4185**
Fixes #3494
```markdown
- `Pager::getFirstIndex()` and `Pager::getLastIndex()`
- `Pager::getFirstIndice()` and `Pager::getLastIndice()`
```
@see #3494

renamed Pager::getLastIndice() and Pager::getFirstIndice()

---

Form/DataTransformer/LegacyModelsToArrayTransformer.php

I am targetting this branch, because this is BC (a new deprecation was introduced).
```markdown
- `LegacyModelsToArrayTransformer` was deprecated although the name should make it pretty obvious already.
```
This should have been setup when creating this class.

Deprecate legacy class

---

Resources/doc/reference/form_types.rst
Resources/public/Admin.js

Admin.setup_list_modal now triggers a 'sonata-admin-setup-list-modal' jQuery event
Closes #4270 
- JQuery event trigger to Admin.setup_list_modal()

Added 'sonata-admin-setup-list-modal' event trigger

---

Admin/AbstractAdmin.php
Tests/Admin/AdminTest.php

I am targetting this branch, because this is very very BC.
The test for securityInformation had inaccurate data, and there was no
documentation for the accessMapping. This change helps getting what the
difference between both properties is.

Show the difference between security properties

---

Resources/views/Form/filter_admin_fields.html.twig
composer.json

I am targetting this branch, because it fixes a deprecation with twig 1.29.
```markdown
- "Silent display of undefined block" Twig deprecation
```
Fixes the deprecation:
```
Silent display of undefined block "form_message" is deprecated since version 1.29 and will throw an exception in 2.0. Use the "block('form_message') is defined" expression to test for block existence
```

Fix twig deprecation

---

Command/GenerateAdminCommand.php
Tests/Command/GenerateAdminCommandTest.php

I am targetting this branch, because of a bug-fix.
Closes #4267 
Set `services` option default-value to null in command `Sonata\AdminBundle\Command\GenerateAdminCommand`
Fix for #4267 
If I answer the question `Do you want to update the services YAML configuration file [yes]?` with no, then `interact` sets no value for `services` which is ok. 
Then the command checks in https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Command/GenerateAdminCommand.php#L135 if a service-file is set, which is always true because of the default value `->addOption('services', 'y', InputOption::VALUE_OPTIONAL, 'The services YAML file', 'services.yml')`.

Fix for #4267

---

Controller/CoreController.php
UPGRADE-3.x.md

```markdown
- `Sonata\AdminBundle\Controller\CoreController::getRequest()`
```

better deprecation handling for Sonata\AdminBundle\Controller\CoreController::getRequest()

---

Resources/views/CRUD/base_edit.html.twig
Resources/views/CRUD/base_edit_form.html.twig

I am targetting this branch, because this is minor fix and it can help to getting twig 2.0 dependency.
```
- Twig deprecation notice when using template inheritance to get a macro
```
This issue avoids similar message in logs:
```
php.INFO: User Deprecated: Calling "render_groups" on template "SonataAdminBundle:CRUD:base_edit_form_macro.html.twig" from template "SonataAdminBundle:CRUD:base_edit_form.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): User Deprecated: Calling \"render_groups\" on template \"SonataAdminBundle:CRUD:base_edit_form_macro.html.twig\" from template \"SonataAdminBundle:CRUD:base_edit_form.html.twig\" is deprecated since version 1.28 and …
```

Move macros import to child template for editing form

---

Form/DataTransformer/ModelsToArrayTransformer.php
Form/Type/ModelType.php
Tests/Form/DataTransformer/ModelsToArrayTransformerTest.php
UPGRADE-3.x.md

I am targetting this branch, because there is not BC break.
Closes #4283
```markdown
- `ModelToArrayTransformer::$choiceList` property 
- `ModelToArrayTransformer::$choiceList::__construct()` three-argument-signature is deprecated
```

Deprecated ModelsToArrayTransformer::$choiceList

---

Resources/doc/cookbook/recipe_knp_menu.rst

I am targetting this branch, because it's a 3.x doc fix.
The icon is now defined onto the extras options and the label can be set directly from child creation options.

Fix menu builder listener code sample

---

composer.json

I am targetting this branch, because this is a pedantic change.
There is no reason for this entry, because the `Tests` namespace is already covered by the normal `autoload` entry.

Removed unnecessary autoload-dev entry

---

Controller/CRUDController.php

I am targetting this branch, because this is a patch.
Partial revers #3692
```markdown
- the `request` parameter is passed to custom batch actions.
```
The https://github.com/sonata-project/SonataAdminBundle/pull/3692 removes this parameter by mistake.

Partial revert #3692

---

DependencyInjection/Compiler/ExtensionCompilerPass.php
Resources/doc/reference/extensions.rst
Tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php

(Screwed up last PR so here is a new one)
I am targetting this branch, because i currently have no reason to believe there are extensions that rely on a specific order.
Closes #4036
```markdown
- Added support for priority attribute in the Extension compiler pass.
```
This pull request should add support for priority when tagging admin extensions.
There should not be any BC breaks, in case there is please leave a comment.

#4036 Add priority support for admin extensions

---

Resources/views/ajax_layout.html.twig

No idea why this did not fail before. Maybe Twig 2.0 is stricter?
Fixes #4305
```markdown
- compatibility of ajax actions with Twig 2.0
```

Check Twig blocks exist before rendering them

---

Controller/CoreController.php
Tests/Admin/AdminTest.php

```markdown
- deprecation notices that could not be avoided in the `CoreController` class
```
There are still deprecation notices, but they come from Symfony. This PR fixes all outstanding internal deprecation notices.

Fix internal deprecation notices

---

Controller/CRUDController.php

Removed unneeded `use` statement for `Symfony\Component\Form\Form` in CRUDContreoller

Removed unnecessary 'use' statement

---

.github/PULL_REQUEST_TEMPLATE.md

I am targetting this branch, because this is pedantic.

Removed extra 't' in targetting

---

Admin/AbstractAdmin.php
Resources/doc/reference/batch_actions.rst
Tests/Admin/AdminTest.php
Tests/Fixtures/Admin/PostAdmin.php

```markdown
- Added `label` fallback for batch actions
- Added `translation_domain` fallback for batch actions
```
Use the existing label generator and translation domain to translate labels in batch actions.

Added fallback for batch labels

---

Menu/Matcher/Voter/ActiveVoter.php
Menu/Matcher/Voter/ChildrenVoter.php
Menu/MenuBuilder.php
Tests/Menu/Matcher/Voter/ActiveVoterTest.php
Tests/Menu/Matcher/Voter/ChildrenVoterTest.php

Closes #4254 
```markdown
- Changed `ActiveVoter` and `ChildrenVoter` to only work with menu items having the `SonataAdminBundle` extra set.
```
This avoids incorrectly matching items outside the admin dashboard. See #4254 for a more detailed description of what happends when this PR is not applied.

Only vote on menu items created by SonataAdminBundle

---

Resources/doc/cookbook/recipe_sortable_listing.rst

I am targetting this branch (3.x), because it's tiny documentation patch.
```markdown
- Fix code indentation in cookbook/recipe_sortable_listing.rst 
```
We need additional white spaces before `sortable: true`
```
stof_doctrine_extensions:
orm:
default:
sortable: true
```

Fix code indentation in recipe_sortable_listing.rst 

---

Resources/views/Button/create_button.html.twig

There was a wrong markup when using subclasses, li without an ul
Also wrong styles, fixed markup and removed default li styles.
```markdown
- Fixed markup on list on Admin with subclasses
```
Markup on admin with subclasses was broken. There was an li without an ul. I fixed that and also removed default styles on li.
Before:
After:

Removed wrong styles on an Admin with Subclasses

---

Admin/AbstractAdmin.php

```markdown
- Removed non FQCNs on form types on AbstractAdmin
```
There was a non FQCN on a form type only visible when using child admins

Remove non FQCNs on form types on AbstractAdmin

---

Tests/Twig/Extension/SonataAdminExtensionTest.php
Twig/Extension/SonataAdminExtension.php

I am targetting this branch, because it's a BC bugfix.
```markdown
- Xeditable choices are now correctly translated
```
Simply add a missing variable affectation when translating xeditable choices.

Fix xeditable choices translations

---

Resources/views/CRUD/base_list.html.twig

I am targetting this branch, because it is a bug fix.
``` markdown
- Missing title for nested admin
```
Before:
After:

fix missing title for nested admin

---

Admin/BreadcrumbsBuilder.php
Tests/Admin/BreadcrumbsBuilderTest.php

```markdown
- Default translation of Base Breadcrumb `Dashboard`
```
The thing is, since now, when you are defining an Admin, if you don't set Translator Strategy to `sonata.admin.label.strategy.underscore` you end up having the base breadcrumb without the correct translation. Default behavior should be having a house icon as the base breadcrumb.
I would like to stay on default translator strategy but still have that icon displayed.
Before:
After:

Changed translations of base breadcrumb

---

Admin/BreadcrumbsBuilder.php

```markdown
- Remove duplicated breadcrumb on admin list
```
When you are on any admin list, there is a duplicated breadcrumb (one with link and the other without). This does not apply to list of childs.
Before:
After:

Remove duplicated breadcrumb on admin list

---

Resources/views/standard_layout.html.twig

```markdown
- Breadcrumb without link are now displayed correctly
```
Breadcrumb without link was displayed without an span, which is incorrect visually speaking.
Before:
After:

Fix breadcrumb without link

---

Resources/doc/reference/advanced_configuration.rst

documentation about adding custom items to the actions menu
signature of method in doc is not the same as in AdminExtensionInterface and AbstractAdminExtension. So example before my change in the doc will not work.

use signature from AdminExtensionInterface

---

Resources/views/Button/acl_button.html.twig
Resources/views/Button/create_button.html.twig
Resources/views/Button/edit_button.html.twig
Resources/views/Button/history_button.html.twig
Resources/views/Button/list_button.html.twig
Resources/views/Button/show_button.html.twig
Resources/views/CRUD/action_buttons.html.twig
Resources/views/CRUD/base_list.html.twig

I am targetting this branch, because this is BC and a continuation of #4337.
```markdown
- Unified styles between admins with subclasses and admins without subclasses
```
On my previous PR (#4337) I fixed the visualization of the no results page of an admin list (with subclasses), that broke the side menu:
BEFORE THIS PR:
AFTER THIS PR:

Fixing styles on admin with subclasses

---

Resources/doc/cookbook/recipe_customizing_a_mosaic_list.rst
Resources/views/CRUD/list_outer_rows_mosaic.html.twig

I am targetting this branch, because BC.
Closes #4359 
```markdown
- name of permission, use `VIEW` instead of `SHOW`
```
SHOW is a name of action, VIEW is a name of permission. In a function isGranted should be name of permission.

fix permission name - not SHOW, but VIEW;

---

Resources/doc/index.rst

there is no need for the username an the password, because a separate container is launched

removed the username and password

---

Resources/doc/reference/form_types.rst

Found some typos in https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html# an fixed them.

Fixed 2 misspellings of "sonata_choice_field_mask"

---

Resources/doc/reference/batch_actions.rst

I am targeting this branch, because this patch doesn't break the BC.
Fixed example code which otherwise threw 
> Type error: Argument 2 passed to AppBundle\Controller\CRUDController::batchActionMerge() must be an instance of AppBundle\Controller\Request or null, instance of Symfony\Component\HttpFoundation\Request given

Fix example code in docs

---

Resources/translations/SonataAdminBundle.ru.xliff

I am targeting this branch, because this is a BC patch.
The `read_less` snippet is a bit tricky. It should be translated literally as `Read less` but the English version reads as `Close`. I translated consistently to the English version.

Add missing Russian translations

---

Admin/AbstractAdmin.php

I am targetting this branch, because this is a pedantic change for PHPDoc.
The PHPDoc for `AbstractAdmin::$parentAssociationMapping` is wrong.

Fixed PHPDoc

---

Admin/Pool.php

I am targeting this branch, because this is only a little improved legibility of error adding a space after ','
Closes none
```markdown
When several admins are available throws and error like 
`Unable to find a valid admin for the class: CoreBundle\Entity\User, there are too many registered: admin.user.admin,admin.user.teacher,admin.user.student,admin.user.client`
now a errror like this will be rendered
`Unable to find a valid admin for the class: CoreBundle\Entity\User, there are too many registered: admin.user.admin, admin.user.teacher, admin.user.student, admin.user.client`
```
little improved legibility of error adding a space after ','

Improved legibility of error

---

Resources/translations/SonataAdminBundle.ar.xliff
Resources/translations/SonataAdminBundle.bg.xliff
Resources/translations/SonataAdminBundle.ca.xliff
Resources/translations/SonataAdminBundle.cs.xliff
Resources/translations/SonataAdminBundle.de.xliff
Resources/translations/SonataAdminBundle.en.xliff
Resources/translations/SonataAdminBundle.es.xliff
Resources/translations/SonataAdminBundle.eu.xliff
Resources/translations/SonataAdminBundle.fa.xliff
Resources/translations/SonataAdminBundle.fr.xliff
Resources/translations/SonataAdminBundle.hr.xliff
Resources/translations/SonataAdminBundle.hu.xliff
Resources/translations/SonataAdminBundle.it.xliff
Resources/translations/SonataAdminBundle.ja.xliff
Resources/translations/SonataAdminBundle.lb.xliff
Resources/translations/SonataAdminBundle.lt.xliff
Resources/translations/SonataAdminBundle.nl.xliff
Resources/translations/SonataAdminBundle.no.xliff
Resources/translations/SonataAdminBundle.pl.xliff
Resources/translations/SonataAdminBundle.pt.xliff
Resources/translations/SonataAdminBundle.pt_BR.xliff
Resources/translations/SonataAdminBundle.ro.xliff
Resources/translations/SonataAdminBundle.ru.xliff
Resources/translations/SonataAdminBundle.sk.xliff
Resources/translations/SonataAdminBundle.sl.xliff
Resources/translations/SonataAdminBundle.sv_SE.xliff
Resources/translations/SonataAdminBundle.uk.xliff
Resources/translations/SonataAdminBundle.zh_CN.xliff
Resources/views/CRUD/base_show.html.twig

I am targeting this branch, because this is a BC fix.
```markdown
- Added missing titles to the CRUD show page.
```

Add missing titles to the CRUD show page

---

Controller/HelperController.php
Tests/Controller/HelperControllerTest.php

I am targetting this branch, because it is a patch.
```markdown
- Setting data form on update form field element by using ``sonata_type_model``
```
`AdminInterface::getFormBuilder` signature doesn't accept any argument currently (it do nothing with `$subject`) so, before that, the form does not have a binded data (`$subject`).
Currently this leads to null `$form->getParent()->getData()` inside any child form type when a new element is added/updating through `sonata_type_model`. This PR try to solve it. (copied from https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Admin/AdminHelper.php#L112-L115)

Setting subject data form on retrieve form field element

---

Admin/BreadcrumbsBuilder.php
Resources/translations/SonataAdminBundle.ar.xliff
Resources/translations/SonataAdminBundle.bg.xliff
Resources/translations/SonataAdminBundle.ca.xliff
Resources/translations/SonataAdminBundle.cs.xliff
Resources/translations/SonataAdminBundle.de.xliff
Resources/translations/SonataAdminBundle.en.xliff
Resources/translations/SonataAdminBundle.es.xliff
Resources/translations/SonataAdminBundle.eu.xliff
Resources/translations/SonataAdminBundle.fa.xliff
Resources/translations/SonataAdminBundle.fr.xliff
Resources/translations/SonataAdminBundle.hr.xliff
Resources/translations/SonataAdminBundle.hu.xliff
Resources/translations/SonataAdminBundle.it.xliff
Resources/translations/SonataAdminBundle.ja.xliff
Resources/translations/SonataAdminBundle.lb.xliff
Resources/translations/SonataAdminBundle.lt.xliff
Resources/translations/SonataAdminBundle.nl.xliff
Resources/translations/SonataAdminBundle.no.xliff
Resources/translations/SonataAdminBundle.pl.xliff
Resources/translations/SonataAdminBundle.pt.xliff
Resources/translations/SonataAdminBundle.pt_BR.xliff
Resources/translations/SonataAdminBundle.ro.xliff
Resources/translations/SonataAdminBundle.ru.xliff
Resources/translations/SonataAdminBundle.sk.xliff
Resources/translations/SonataAdminBundle.sl.xliff
Resources/translations/SonataAdminBundle.sv_SE.xliff
Resources/translations/SonataAdminBundle.uk.xliff
Resources/translations/SonataAdminBundle.zh_CN.xliff
Tests/Admin/BreadcrumbsBuilderTest.php

I am targeting this branch, because this seems like a somewhat backward compatible patch. Well in fact some one may have had a custom translation for the `breadcrumb.link_dashboard` but it's broken anyway in the current release.
```markdown
Changed inconsistent translation unit name.
```
Ranamed source translation of the `link_breadcrumb_dashboard` form `breadcrumb.link_dashboard` to `link_breadcrumb_dashboard` to be consistent with other translation units.

Refactor translation units

---

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

```markdown
- use `hasAccess` instead of `isGranted`
```
Method change to verify access to the object
referer PR #4370 
I think it will be nice to clean up the buttons in the view `base_edit_form.html.twig` in block `sonata_form_actions`.

Method change to verify access to the object

---

Resources/translations/SonataAdminBundle.ca.xliff
Resources/translations/SonataAdminBundle.es.xliff

I am targeting this branch, because this only changes translations.
```markdown
- Improve Catalan and Spanish translations
```
Updated Spanish and Catalan translations. Some of them were wrong, specially in catalan, they looked like were generated using google translate.

Spanish and Catalan Translations

---

Resources/doc/reference/field_types.rst
Resources/views/CRUD/list_url.html.twig
Resources/views/CRUD/show_url.html.twig
Tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch, because this is new feature with BC.
```markdown
- Added 'attributes' parameter for 'url' field type
```
We have case, when we want open url in new tab, for this we need set target="_blank" for <a> tag. This PR add generic solution for this and similar use cases.

Added 'attributes' parameter for 'url' field type

---

Admin/AbstractAdmin.php
Bridge/Exporter/AdminExporter.php
Controller/CRUDController.php
DependencyInjection/SonataAdminExtension.php
Export/Exporter.php
Resources/config/core.xml
Resources/config/exporter.xml
Resources/doc/reference/action_export.rst
Resources/views/CRUD/base_list.html.twig
Resources/views/CRUD/list_outer_rows_mosaic.html.twig
Tests/Bridge/Exporter/AdminExporterTest.php
Tests/Controller/CRUDControllerTest.php
Tests/DependencyInjection/SonataAdminExtensionTest.php
Tests/Export/ExporterTest.php
UPGRADE-3.x.md
composer.json

I am targetting this branch, because this is BC
Closes #3124 , #1550 (I think)
``` markdown
- The export and list actions now integrate the sonata exporter bundle
- Exporter class and service : use equivalents from `sonata-project/exporter` instead.
```
This deprecates the export class and service

Deprecate exporter class and service

---

Resources/translations/SonataAdminBundle.en.xliff

I am targeting this branch, because this is a BC patch.
```markdown
- Fixed inconsistent translation placeholder quoting.
```
Fixed inconsistent translation placeholder quoting.

Improve English translation

---

Resources/translations/SonataAdminBundle.ru.xliff

I am targeting this branch, because this is a BC patch.
```markdown
- Added a missing variable placeholder to a translation unit.
```
Added a missing variable placeholder to a translation unit.

Improve Russian translation

---

Controller/CRUDController.php

I am targeting this branch, because this is BC and fixes a bug.
Closes #3850 #3332
```markdown
- Batch action breaks when coming from list view with filter using `doctrine_orm_model_autocomplete`
```
Overtake PR #3850

set filter form theme

---

Resources/views/CRUD/base_list_field.html.twig

I am targeting this branch, because it's a hotfix
```markdown
- Fixed non-existent variable `action` in `base_list_field.html.twig`
```

Fix non-existent variable "action" in base_list_field.html.twig

---

Form/Type/AdminType.php
Resources/doc/reference/form_types.rst
Resources/public/Admin.js
Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Closes #4348 
```markdown
When checking the delete checkbox of an inline child form of `CollectionType` the related fields are now disabled to avoid preventing submission of the form when one of those inputs is required.
```
See #4348

Fixed AdminType delete checkboxes

---

Resources/doc/reference/form_types.rst

I am targetting this branch, to enhance documentation.
Closes #4397 
```markdown
replace empty_value by placeholder in form definition documentation
```
The current documentation lead to an exception since `empty_value` doesn't exist anymore and has been replaced by `placeholder`, this PR fix the example in documentation

update form types documentation - fix #4397

---

Resources/doc/reference/action_show.rst
Show/ShowMapper.php
Tests/Show/ShowMapperTest.php

```markdown
- Added the ability to leave the label of a show field empty by passing `label => false` to `ShowMapper::add()`
```

Added the ability to remove the label of a show field

---

composer.json

This dependency is required in both require and require-dev section,
which can lead to unexpected behavior.
```markdown
- The sonata/exporter constraint has been bumped to `^1.7`
```

Remove duplicate dependency

---

Form/FormMapper.php
Form/Type/ChoiceFieldMaskType.php
Tests/Form/FormMapperTest.php

I am targeting this branch, because it's patch.
Closes #4401
```markdown
- sanitize masked fields in `ChoiceFieldMaskType`
```
This add a new method to sanitize field's name in FormMapper, this method is used in `add`, `get` and `has`.
The same process is used to sanitize fields in the ChoiceFieldMaskType options

sanitize choice mask fields like in formMapper

---

Resources/translations/SonataAdminBundle.pl.xliff

```markdown
add polish translation of `title_show`
```
I added the missing phrase

title_show - add polish translation

---

Resources/views/standard_layout.html.twig

The scripts will now have it's name all in lowercase. This will make the server stops return 404 when requesting the script for locales like pt_BR
I am targeting this branch, because this is the one I'm currently working on, but this PR should be done in the `master` branch also .
```markdown
- Change how moment locale scripts are loaded. Before they were loaded with the raw locale from `app.request`, now the they are being loaded with the locale all in lowercase.
```

Changes how locale scripts of Moment.js lib are loaded - Branch 3.x

---

Resources/views/standard_layout.html.twig

```markdown
- Whitespaces are not taken into account when rendering blocks on `standard_layout`
```
There was a lot of empty html because the comparisons between `blocks` and `is not empty` is not working if the block has whitespaces.
Can I remove the equal sign alignment?
Example.
BEFORE:
AFTER:

Avoid whitespaces on blocks

---

Tests/Form/Widget/BaseWidgetTest.php

This LSP violation caused the build to fail. This change makes the test
forward-compatible with the next major version of the twig bridge.
I am targeting this branch, because this is BC (the tests are not autoloadable).
It's pedantic because it fixes nothing for users, but is critical because contributors can't do anything without this change.

Fix broken build 🚨

---

Resources/views/CRUD/base_list_field.html.twig
Tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch, because this is bc.
Closes  #1968
```markdown
- fixed boolean handling for `xEditableType`
```
```html
<span class="x-editable editable editable-click editable-open" data-type="select" data-value="" data-title="Aktiviert" data-pk="2" data-url="/app_dev.php/admin/core/set-object-field-value?context=list&amp;field=enabled&amp;objectId=2&amp;code=topic.admin.archive_topic" data-source="[{value: 0, text: 'nein'},{value: 1, text: 'ja'}]" data-original-title="" title="" aria-describedby="popover210070">
<span class="label label-danger">nein</span>
</span>
```
The ` data-value ` is always ` null `, and results in `data-value=""`, which could not be handled by the javascript part.
```html
<span class="x-editable editable editable-click editable-open" data-type="select" …
```

fixed xeditable boolean handling

---

Tests/tests/autoload.php.dist
Tests/tests/bootstrap.php

I am targeting this branch, because it's a pedantic change for tests.
We excluded the tests directory from the public autoloader, so there's no reason to run this tests out of the project scope.

Removed old autoloader from tests

---

Admin/AdminHelper.php
Admin/BaseFieldDescription.php
Tests/Admin/BaseFieldDescriptionTest.php

I am targeting this branch, because this removes already deprecated code.
Refs #3788
```markdown
- Removed deprecated `BaseFieldDescription::camelize()` and `AdminHelper::camelize()`
```

Removed camelize

---

Resources/translations/SonataAdminBundle.pt_BR.xliff

I am targeting this branch, because this is the one I'm currently working on.
```markdown
- Added Brazilian Portuguese translation of `title_show`
```
Added the Brazilian Portuguese translation of the `title_show` label.

title_show - Add Brazilian Portuguese Translation

---

Resources/views/CRUD/list__action_show.html.twig

I am targeting this branch, because this affect the current release.
```markdown
- change show picto on list view to use the same than in edit view
```

Use same show picto in list view

---

Form/Type/AdminType.php
Tests/Form/Type/AdminTypeTest.php

I am targeting this branch, because it's a bugfix for #4425.
Fixes #4425 
Closes #4428 
```markdown
- do not double `FieldDescription::Name` and `property_path` in ``AdminType``
```
This removes the doubled FieldDescription::Name and property_path as described in #4425

AdminType doubles $fieldDescription and property_path

---

Annotation/Admin.php
Resources/doc/reference/annotations.rst
Tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php

I am targeting this branch, because the change is BC.
```markdown
- Added `onTop` parameter on `@Admin` annotation
```
add on_top tag functionality to annotations as seen here: https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_knp_menu.html

add missing onTop annotation to @admin

---

Resources/views/CRUD/base_list_field.html.twig

I am targeting this branch, because it is a bugfix.
Closes #4433
[`base_list_field.html.twig`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/CRUD/base_list_field.html.twig#L51) `field_description` comparison
#4415 introduced a bug for editable list field for `date` type.

Editable date - base_list_field.html.twig

---

Admin/AdminInterface.php
Controller/CoreController.php
Tests/Helpers/PHPUnit_Framework_TestCase.php

I am targeting this branch, because this is pedantic.
The implementation of the method in the interface is protected, so there is no reason to make it
public, is there?

Remove protected method

---

Form/Extension/ChoiceTypeExtension.php
Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
Tests/Form/Extension/ChoiceTypeExtensionTest.php

I am targeting this branch, because i want to fix the issue #3474 in the 3.x branch (which is the one that the issue happens).
Closes #3474
```markdown
Fixed issue on getExtendedType of MopaCompatibilityTypeFieldExtension and ChoiceTypeExtension because the method requires to return the fully-qualified class name (FQCN) since symfony version 2.8
```
Fixed issue on getExtendedType of MopaCompatibilityTypeFieldExtension and ChoiceTypeExtension because the method requires to return the fully-qualified class name (FQCN) since symfony version 2.8
The commit that adds the code that cause the issue is: https://github.com/symfony/form/commit/4416ae7c67f511e92f19f962f8a73723f5df35bc

Fixed getExtendedType compatibility for symfony >= 2.8

---

Resources/views/CRUD/base_edit_form_macro.html.twig

```markdown
- Add a condition to check if there is a field in the form
```
In some situations I get an error:
`
Key "isSuperior" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist.
`
I think that this condition is missing.
Actually, there could be only one condition `form[field_name] is defined`.

Add a condition to check if there is a field

---

Form/Type/ModelType.php

Closes #4443
```markdown
- ModelType have choices as values by default now on SF 2.7+.
```
Not sure if only with this change, this will work again with SF 2.8.18. Have to test ir properly.
Can you take a look @eschultz-magix @Soullivaneuh ?

Add choices_as_values to ModelType

---

Resources/doc/reference/translation.rst
Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because this is BC (people cannot use `false` as a translation domain).
```markdown
- Translation can now be disabled on specific form fields
```
This is what Symfony does in its Twig integration bundle, we should do
the same.

Allow disabling translation on form fields

---

Menu/Provider/GroupMenuProvider.php

I am targeting this branch, because it's currently developed for Symfony 3.
```markdown
- Changed GroupMenuProvider::get to setDisplay(false) on menuItem if on_top used and no items could be displayed
```
Hiding menu group if it has only one item with on_top and user has no permissions to access 'list' action or no 'list' action exists.

Fixed menu group being displayed for user without permissions when on_top is specified

---

Command/GenerateAdminCommand.php
Command/GenerateObjectAclCommand.php
Command/QuestionableCommand.php

I am targetting this branch, because I found bug The helper "dialog" is not defined (Undefined DialogHelper Class)
Closes #4327
```markdown
- Fixed the bug that caused an error "The helper "dialog" is not defined." on Symfony3 with new `\Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper` when you run command "sonata:admin:generate-object-acl". 
```
Delete or re-right Command/QuestionableCommand.php
https://github.com/sonata-project/SonataAdminBundle/issues/4327

Fix bug The helper "dialog" is not defined (Undefined DialogHelper Class)

---

Controller/HelperController.php
Form/Type/ModelAutocompleteType.php
Resources/doc/reference/form_types.rst
Tests/Controller/HelperControllerTest.php
Tests/Form/Type/ModelAutocompleteTypeTest.php

I am targeting this branch, because this is a bugfix for #4132 and #3131.
Closes #4132, #3131
```markdown
- Users without the `LIST` role can access the autocomplete items by configuring the `target_admin_access_action` option
```
This PR adds option `target_admin_access_action` to `ModelAutocompleteType` to configure which access action (converted to role) should be checked on target admin. For BC the `list` is used by default.
I have also improved performance a little bit storing the `$formAutocomplete->getConfig();` in the `$formAutocompleteConfig` variable.

Add option `target_admin_access_action` to ModelAutocompleteType

---

Resources/config/form_types.xml
SonataAdminBundle.php

I am targeting this branch, because I got deprecation notification when using autowire for my services.
```markdown
- deprecations when using `sonata.admin.form.type.model_list`
```
Deprecated classes should not be used in not deprecated services.
So we need to use not deprecated classes in services or mark service as deprecated.

Use ModelListType instead of deprecated ModelTypeList

---

Resources/translations/SonataAdminBundle.it.xliff

Closes #4465.
```markdown
- added missing italian translations
```

replace title_show placeholder with transleted value (only for IT)

---

Resources/doc/reference/getting_started.rst

I am targeting this branch, because this was missing in this branch
Missing namespaces into example in documentation
Documentation Missing namespaces in yaml loader example

Documentation update getting_started.rst missing namespaces

---

Resources/skeleton/Admin.php.twig
Resources/skeleton/AdminController.php.twig
Tests/Fixtures/Admin/ModelAdmin.php
Tests/Fixtures/Controller/ModelAdminController.php

Otherwise this would be fixed by PHP-CS-Fixer all the time afterwards

skeletons are now valid for @Symfony ruleset by PHP-CS-Fixer

---

Resources/public/Admin.js
Resources/views/Menu/sonata_menu.html.twig

Fix select2 width calculation when using select2 4.
I am targetting this branch, because I am fix bug, and kept BC.
```markdown
- Fixed select2 width calculation when using select2 v4
```
Fix select2 width calculation when using select2 4.

Fix wrong context on Select2 v4 field width calculation

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because this a bug fix.
```markdown
- Compatibility with Select2 v4 on model autocomplete type
```
Select2 v4 compatibility was brought on #3988 but it appears to be still buggy on model autocomplete type.
This is because of the JS logic, placed outside the `Admin.js` type.
Compatibility layer is added on this PR.

Select2 v4 compatibility for model autocomplete

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because this is a fix.
```markdown
- Selected values issue with Select2 v4 on model autocomplete type
```
This is a missing part of #4480 for already selected values.

Fix missing selected value on Select2 v4 autocomplete

---

Menu/Provider/GroupMenuProvider.php

I am targeting this branch, because this is BC
Refs #4023
```markdown
- use generated route instead of plain route in nav items
```
As mentioned here https://github.com/sonata-project/SonataAdminBundle/issues/4023#issuecomment-302629065, I can confirm this fixes the problem

use generated route instead of plain route in nav items

---

Resources/views/Menu/sonata_menu.html.twig

I am targeting this branch, because this is BC
Refs #4023
```markdown
- Show icon for nav items when using `on_top`-option 
```
As mentioned here https://github.com/sonata-project/SonataAdminBundle/issues/4023#issuecomment-302629065, I can confirm this fixes the problem

fix icon for nav items with on_top: true

---

Controller/CRUDController.php
Tests/Controller/CRUDControllerTest.php

I am targeting this branch, because 3.x branch is used on a project I'm working on. On the other hand it should be applicable to master according to CRUDController code.
Closes #4494
```markdown
- compatibility with immutable entities was improved
```
On the project I'm working on immutable entities are used. DataMapper solves the problem with creating new Entity instance based on Form data. But $object is never got from the form in CRUDController::createAction() and CRUDController::editAction(). If new object is not created then nothing will change as the same instance will be returned. But this patch can be easily adopted and provides others working with DDD entities with a solution.

Get data from the form in create/update actions.

---

composer.json

People that upgrade the admin bundle in order to get Symfony 3.3
compatibility might not be aware that the core bundle is compatible with
it only since 3.4.0, and not think of updating it too. This change is
not pure in the sense that this incompatibility should be expressed in
the core bundle itself, but it should spare us some support issues.
```markdown
- it is no longer possible to get core bundle versions incompatible with sf3
```

Bump SonataCoreBundle version constraint

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Hiding is not enough. If you are using AJAX, and your field is required,
you may end up with an empty select tag, with a required attribute that
is never filled with options, because there are currently 2 tags, one
for each version of Select2, and only one of them is filled.
This commit removes the other one instead of just hiding it,
that way it can't interfere with the other.
Fixes #4486, #4261
```markdown
- forms with a required autocomplete ajax field can be submitted again
```

Remove unused field

---

DependencyInjection/SonataAdminExtension.php

I am targeting this branch, because this fix a deprecation warning and is BC.
```markdown
- deprecation notices related to `addClassesToCompile`
```
Only call addClassesToCompile on PHP < 7.0 since it is deprecated and doesn't improve performances with PHP >= 7.0

Only add classes to compile on PHP < 7.0

---

Resources/views/CRUD/base_show.html.twig

I am targeting this branch, because this bug was introduced there.
Closes #4525
```markdown
- Fixed undefined `view_group` variable in show template
```
#4028 introduced bug in base_show.html.twig. This Pull Request will fix that bug.
In the CRUD/base_show.html.twig view on line 47, the variable ``name`` was replaced with ``view_group``. However, this should have been ``show_tab`` (see start of loop on line 43).

Fixed undefined variable in base_show.html.twig

---

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php

I am targeting this branch, because of a bug fix.
```markdown
- Fixed compatibility with Symfony's IdentityTranslator when translator is disabled
```
When translator is disabled in the FrameworkBundle config (for tests purposes in our case), a IdentityTranslator (that does nothing) is still registered by the FrameworkBundle as a `translator` `service` (and not an `alias`). I think Sonata should not break in this case.

Fix compatibility with Symfony's IdentityTranslator when translator is disabled

---

Manipulator/ServicesManipulator.php
Resources/doc/cookbook/recipe_custom_action.rst
Resources/doc/cookbook/recipe_improve_performance_large_datasets.rst
Resources/doc/cookbook/recipe_knp_menu.rst
Resources/doc/cookbook/recipe_sortable_listing.rst
Resources/doc/getting_started/creating_an_admin.rst
Resources/doc/getting_started/the_form_view.rst
Resources/doc/reference/advanced_configuration.rst
Resources/doc/reference/architecture.rst
Resources/doc/reference/dashboard.rst
Resources/doc/reference/form_types.rst
Resources/doc/reference/getting_started.rst
Resources/doc/reference/routing.rst
Resources/doc/reference/templates.rst
Tests/Manipulator/ServicesManipulatorTest.php

I am targeting this branch, because symfony 3.3 out-of-box compatibility is broken.
Closes #4538 
```markdown
- `ServiceManipulator` now adds `public: true` to service declaration by default
```
Fixes missing `public: true` needed for symfony 3.3+ (#4538)

Fixes missing 'public: true' needed for symfony 3.3+ (#4538)

---

Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because this fix is backwards compatible.
```markdown
- Fixed choice field mask type javascript in the twig templates to works with immutable array form types
```
The javascript code showing/hiding fields on the ChoiceFieldMaskType widget did not work when the ChoiceFieldMaskType was used inside an ImmutableArrayType. This is due to the use of a different glue character, the dash, in ImmutableArrayType to append keys in the widget name. This fix consists in adding a fallback on this dash-naming if the default naming with underscore does not match any javascript element.
```php
protected function configureFormFields(FormMapper $formMapper)
{
parent::configureFormFields($formMapper);
$formMapper
// Was working before
->with('Test Without Immutable') …
```

fixed choice field mask form type using immutable array form type

---

Form/ChoiceList/ModelChoiceList.php
Resources/doc/reference/form_types.rst
UPGRADE-3.x.md

I am targeting this branch, because this is a deprecation PR.
Closes #4484
```markdown
- `ModelChoiceList` in favor of `ModelChoiceLoader`
```

Deprecate ModelChoiceList

---

Admin/Extension/LockExtension.php
Tests/Admin/Extension/LockExtensionTest.php

I am targeting this branch, because this is just a fix for a deprecation warning. Change is BC.
```markdown
- Fixed deprecation for Sf 3. support
```
Fixed a Symfony 3 form type as string deprecation warning.

Fixed 'hidden' form type deprecation warning

---

Menu/Matcher/Voter/AdminVoter.php
Tests/Menu/Matcher/Voter/AdminVoterTest.php

```markdown
- Sidebar menu elements are active when the current route is a child admin.
```
Every element of the sidebar menu is displayed as active when
the current route is a child admin of the menu element's admin.

Display sidebar menu as active on child admin routes.

---

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
DependencyInjection/Configuration.php
Tests/DependencyInjection/ConfigurationTest.php

I am targeting this branch, because I just change urls building in sidebar. For now it creates relative urls by default instead of absolute.
```markdown
- Fixes potentially wrong scheme in the sidebar urls by using relative urls
```
It can be useful for example when you are using https provided by cloudflare. So the urls will always navigate to current schema. Almost all another generated urls in sonata admin are relative by default.

Make urls in sidebar relative by default.

---

Annotation/Admin.php
Resources/doc/reference/annotations.rst
Tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php

I am targeting this branch, because it is a small fix. 
```markdown
- Take admin annotation id into account
```
service id was not used from annotation and therefor was autogenerated every time. this pull requests corrects this behavior and corrects the namespace of the annotation in the documentation
original in https://github.com/sonata-project/SonataAdminBundle/pull/4555

fix admin annotation id setting

---

Tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php

Tests written for #4557 were wrong
and were not testing anything.
This can be quickly verified with the coverage report of #4557: https://coveralls.io/builds/12466808/source?filename=Annotation%2FAdmin.php#L128

Fix tests of #4557

---

Datagrid/ListMapper.php
Resources/doc/reference/action_list.rst
Resources/public/css/layout.css
Resources/views/CRUD/base_list.html.twig

I am targeting 3.x, because this is BC, it will not break any current working applications.
```markdown
- Allow label icon on CRUD list table headers.
- Allow to disable label on CRUD list table heades.
```
I want to use Font Awesome icons on table headers:
```php
->add('upvotes', null, [
'label' => '<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>',
])
->add('downvotes', null, [
'label' => '<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>',
])
```
But currently it displays the escaped html:
After adding the raw filter it will look like this:

Allow html labels on list

---

Resources/doc/reference/action_list.rst
Resources/doc/reference/form_types.rst
Resources/public/Admin.js

```markdown
- Added checkbox range selection with shift + click
```
This PR adds checkbox range selection by clicking a first then a second checkbox with shift + click. All the checkboxes between them will be checked / unchecked. It's working from top to bottom and vice versa.
I tried to use an existing JS library (checkboxes.js), but it's not working with iCheck. So I ended up adding some custom JS (inspired by https://www.hieule.info/web/html-checkbox-enhancement-icheck-shift-click). It's working when iCheck is enabled or disabled.

Add checkbox range selection

---

Resources/doc/cookbook/recipe_data_mapper.rst
Resources/doc/index.rst

I am targeting this branch, because this PR supplements #4495 by providing documentation on how to use DataMapper with Admin classes.
```markdown
- Added 'Resources/doc/cookbook/recipe_data_mapper.rst'
```
Provides documentation on using DataMapper with entities that do not have conventional per field setters.

Added cookbook entry on using DataMapper with admin classes.

---

Resources/translations/SonataAdminBundle.lv.xliff

I am targeting this branch, because currently there is no Latvian translation of the bundle.
```markdown
- Added Latvian translation of the bundle
```
I am asking for pull request because I want to bring bundle's Latvian translation to open source

Added Latvian translation of bundle

---

Resources/views/CRUD/Association/edit_many_script.html.twig
Resources/views/CRUD/Association/edit_many_to_many.html.twig
Resources/views/CRUD/Association/edit_many_to_one.html.twig
Resources/views/CRUD/Association/edit_modal.html.twig
Resources/views/CRUD/Association/edit_one_script.html.twig
Resources/views/CRUD/Association/edit_one_to_many.html.twig
Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Resources/views/CRUD/Association/edit_one_to_many_sortable_script_table.html.twig
Resources/views/CRUD/Association/edit_one_to_many_sortable_script_tabs.html.twig
Resources/views/CRUD/Association/edit_one_to_one.html.twig
Resources/views/CRUD/Association/list_many_to_many.html.twig
Resources/views/CRUD/Association/list_many_to_one.html.twig
Resources/views/CRUD/Association/list_one_to_many.html.twig
Resources/views/CRUD/Association/list_one_to_one.html.twig
Resources/views/CRUD/Association/show_many_to_many.html.twig
Resources/views/CRUD/Association/show_many_to_one.html.twig
Resources/views/CRUD/Association/show_one_to_many.html.twig
Resources/views/CRUD/Association/show_one_to_one.html.twig

I am targeting this branch, because 
"This is the current stable version"
Closes #{put_issue_number_here}
```markdown
- Added the persistence independent association templates
```
As mentioned in https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/485#issuecomment-320895309 (There should be some open issues to) we whant to squeeze all common templates together. So we whant to have them central in AdminBundle and simply use them through field widget configuration in persistence depending bundles.

Move relation templates

---

Resources/translations/SonataAdminBundle.de.xliff

- Fix typo in german translation of "noscript_warning"
Fix a typo in german translation "noscript_warning": _Brwoser_ => _Browser_

Fix typo in german translation of "noscript_warning"

---

Form/Type/ModelAutocompleteType.php

I am targeting this branch, because this fixes a deprecation warning.
```markdown
- Fixed deprecation when using hidden form type in model autocomplete
```
Fixed deprecation warning.

Use fully qualified hidden type

---

Resources/doc/reference/form_types.rst

I am targeting this branch, because it is the documentation of the current version.
I found and fixed a typo in the documentation of form types (sonata_type_model_autocomplete, options, multiple)

Fixed documentation typo

---

Resources/views/Menu/sonata_menu.html.twig

I am targeting this branch, because this PR is backwards compatible.
Closes #4598
Closes #4568 
```markdown
- Make [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Menu/sonata_menu.html.twig#L29) execute, even on_top is true. Before, this line would not be called and the labels would be translated against the messages catalogue.
- Fixed the extra option being retrieved. The translation catalogue to be used is inside the label_catalogue option, not translation_domain.
```
Consider a admin with on_top set to true, the catalogue used to translate the labels would always be the messages catalogue, because the line that sets the `translation_domain` variable would never be executed. This PR fix this problem calling the line that sets `translation_domain` …

KnpMenu - Set translation_domain even if on_top is true

---

Datagrid/ListMapper.php
Tests/Datagrid/ListMapperTest.php

I am targeting this branch, because this PR is backwards compatible.
```markdown
- setting the column title 
```
In documentation you can read 
`label (o): the name used for the column’s title` 
but it does not work

fix set up header label in list mapper

---

Resources/views/standard_layout.html.twig

I am targeting this branch, because this PR is backwards compatible.
```markdown
- Html tags do not appear in the meta title
```
If in the title block you insert the html tags, they are displayed in the meta title. This change removes the html tags and only then uses the raw filter.

Delete html tags in custom head title

---

Admin/AbstractAdmin.php
Tests/Admin/AdminTest.php

```markdown
- Fixed AbstractAdmin::getSubject on admins with parentFieldDescription
```
When an admin has a `parentFieldDescription`, the `AbstractAdmin::getSubject` method should not use the url id parameter to load the object (because the id correspond to the root object only).
Example: I have an issue when submitting a form with a collection which contains an `AdminType` field. In `AdminType`, this line loads a (random) collection element by using the url id (which is the root object id) : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Type/AdminType.php#L57
Should fix https://github.com/sonata-project/SonataAdminBundle/issues/2879

Fix getSubject method when admin has parentFieldDescription

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because this change is backward compatible.
```markdown
- Run the Select2 code for autocomplete form type at onload event
```
The autocomplete model form type uses Select2 to render the dropdown. However the code runs before the onload JS event, which is not compatible with loading the JS files at the end of the page.
This changes allows one to change the standard_layout template and move the JavaScript files (except jQuery) to the end of the HTML page.

Fix JS loading in autocomplete form type

---

Controller/CRUDController.php
Resources/views/CRUD/base_edit.html.twig
Resources/views/CRUD/base_edit_form.html.twig

Closes #4545
```markdown
- Passing object id in edit form from CRUD controller instead of getting it in twig
```
Passing object id from controller prevent situation when in twig we can't get object id because model manager reopened. It geting id before starts operations with database and will always open edit form even we have some database exception.

Fix bug with creating new object while editing

---

Resources/views/CRUD/base_list.html.twig

I am targeting this branch, because this is a fix.
```markdown
- Escaping of list headers.
```
This was overlooked in https://github.com/sonata-project/SonataAdminBundle/pull/4551.
The original purpose of the PR was to let user add raw html to list headers.
We wanted to avoid the use of a `raw` filter, so we agreed to introduce a `label_icon` option
for this particular purpose.
But we ended up with a `raw` filter and the `label_icon`...
This PR removes the `raw` filter.

Remove unwanted raw filter on list headers.

---

Resources/views/Menu/sonata_menu.html.twig

I am targeting this branch, because this PR will not cause a BC.
```Markdown
- Fixed the setting of the `translation_domain` twig variable. The value must change depending if the item has on_top set to true or false.
```
The line with the `set translation_domain` must be called in the IF clause and in the ELSE clause. The IF will happen when the item being translated is inside a treeview, which means that the label must be translated against the translation_domain option. The ELSE will happen when on_top is true, which means that the label shoule be translated against the label_catalogue option.

Add the `set translation_domain` inside the else clause

---

Resources/doc/getting_started/installation.rst
Resources/doc/reference/getting_started.rst

I am targeting this branch, because this is a doc change.
- Remove unnecessary bundle information from docs
- Moved route config to installation docs

Remove unnecessary bundle from docs

---

Resources/translations/SonataAdminBundle.ca.xliff

Fix dynamic error value on delete message confirmation.
I am targeting this branch, because is a translations issue.
Fix a bad translation dynamic value translation on delete subject view.

Update catalan translation

---

Form/Type/AdminType.php

I am targeting this branch, because this fixes a deprecation warning.
```markdown
- Fixed deprecation when using checkbox in admin form type
```
Fixed deprecation warning.

Use fully qualified checkbox type

---

DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
DependencyInjection/SonataAdminExtension.php

```markdown
- Reference %sonata.admin.configuration.templates% when possible
```
This PR allows generating lighter containers by leveraging https://github.com/symfony/symfony/pull/23143
This prevents generating the same array again for all service blocks - and replacing them by a simple reference to the parameter's value.

Reference %sonata.admin.configuration.templates% when possible

---

Controller/CRUDController.php
Resources/doc/cookbook/recipe_custom_action.rst
Tests/Controller/CRUDControllerTest.php

I am targeting this branch, because this PR is backwards compatible.
```markdown
- Removed white space before colon in message of exception
```
In polish language before the colon has no spaces. How about in other languages?

Removed white space before colon

---

Resources/doc/reference/architecture.rst

I am targeting this branch, because this is a doc change for the latest stable.
Rebase of #3807 
Improved getting architecture docs.

Document how to display a child admin

---

Menu/Provider/GroupMenuProvider.php
Resources/views/Menu/sonata_menu.html.twig
Tests/Menu/Provider/GroupMenuProviderTest.php

Related to #4601 and #4614
```markdown
- Fix knp menu extra configuration for domain translations in Group Menu
```
The menu extras uses **label_catalogue**, not **translation_domain**.

Fix group menu sub items translation domain

---

Resources/public/Admin.js

I am targeting this branch, because this is a removal of useless code part.
This is a patch because it also fixes a not declared variable issue.
```markdown
- Not declared variable trowing errors on some browsers
- Useless IE8 compatibility code
```
No need because admin-lte does not support IE8.
https://adminlte.io/themes/AdminLTE/documentation/index.html#browsers

Remove IE8 event compatibility

---

Admin/AccessRegistryInterface.php
Admin/AdminInterface.php
Admin/FieldDescriptionRegistryInterface.php
Admin/LifecycleHookProviderInterface.php
Admin/MenuBuilderInterface.php
Admin/ParentAdminInterface.php
Admin/UrlGeneratorInterface.php
Model/ModelManagerInterface.php
Twig/Extension/SonataAdminExtension.php

The admin interface should be split into smaller interfaces, as per the ISP. This should ease the splitting in of the `AbstractAdmin` class itself.
```markdown
- `Sonata\AdminBundle\Admin\AdminInterface` was split into smaller interfaces, namely
- `Sonata\AdminBundle\AdminFieldDescriptionRegistryInterface`
- `Sonata\AdminBundle\LifecycleHookProviderInterface`
- `Sonata\AdminBundle\MenuBuilderInterface`
- `Sonata\AdminBundle\ParentAdminInterface`
```

Fix isp violations

---

Resources/views/Block/block_search_result.html.twig

I am targeting this branch, because it's just a typo in the current release.
```markdown
- Fixed a typo in CSS classes in `block_search_result.html.twig`
```
`box-primary` wasn't separated from `{{ visibility_class }}`, causing weird uncoloured styling on several search results blocks.

Fix a typo in block_search_result.html.twig

---

Resources/views/Block/block_search_result.html.twig

I am targeting this branch, because it's just a little fix on template for the current release.
```markdown
- Always apply "global_search.empty_boxes" setting to never searched admins
```
Currently the `sonata-search-result-[fade,hide]` CSS class is only applied when there is a pager returned by the SearchHandler and this pager has no results.
But if the Admin has no `global_search` filter set or no filter at all, the SearchHandler returns _false_ instead of a pager. Therefore, such Admins, with no `global_search` filters, which won't ever be queried by the SearchHandler, are always shown empty on the results page as is.
That's why I propose to set the CSS class first, and then change/remove it if there is results.
Feel free to set an empty string to the visibility class when there is …

Always apply "global_search.empty_boxes" setting to never searched admins

---

Resources/doc/reference/architecture.rst

I am targeting this branch, because this is a docs fix.

use same example for docs

---

Admin/BaseFieldDescription.php
Tests/Admin/BaseFieldDescriptionTest.php
Tests/Fixtures/Entity/FooBoolean.php

I am targeting this branch, because the fix I'm proposing seems like a bug fix to me and does not break BC.
```markdown
- Fixed the BaseFieldDescription class to also support 'has' prefixed getter methods for boolean properties on entities (besides the 'is' prefixed getters)
```
Twig supports both 'is' and 'has' getters for boolean properties (`$user->hasSuperPowers()` and `$user->isSuperHero()` translate to `user.superPowers` and `user.superHero` in Twig). The PHP Mess Detector will also suggest using either an 'is' or 'has' prefix for boolean getters, instead of 'get'.
However, SonataAdminBundle only seems to support 'get' and 'is' as prefixes. Wouldn't it be a good idea to add the 'has' prefix as well or has it been omitted on purpose? I now need to refactor my code to use the 'is' …

Added support for the ‘has’ getter prefix

---

Model/ModelManagerInterface.php

I am targeting this branch, because this is only PHPdoc.
According to the implementations (https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Model/ModelManager.php, https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/1.x/Model/ModelManager.php), the following PHPdoc was wrong.

Added missing throws annotations

---

Form/Extension/Field/Type/FormTypeFieldExtension.php
Resources/views/Form/form_admin_fields.html.twig
Tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php

Closes #4656
```markdown
- Print of `sonata_help` for form subfields
- Error class for `sonata_type_immutable_array` form group
```
Sonata help for subfields isn't shown, but it should be as explained [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field). When aan error occurs in a subfield, error message is not in red color as other form fields with errors.

Fix sonata_help not showing for subfields and add the has-error class

---

composer.json

It is necessary in order to be able to build the block bundle, which has
a dev dependency on this bundle, because of some optional features it
has that need to be tested. Those should probably be moved in an
integration bundle.

Restore unstable version constraint

---

Admin/AbstractAdmin.php

I am targeting this branch, because I am found a critical bug in sonata admin, and I want to fix it as soon as possible.
No issue is related
Fix usage of classes with same name : UrlGeneratorInterface
```markdown
- naming conflict with `UrlGeneratorInterface`
```
They’re was a problem with the name of the interface name UrlGeneratorInterface : it is conflicted in AbstractAdmin
```
PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface as UrlGeneratorInterface because the name is already in use in […]/app/cache/dev/classes.php on line 12223
```
with  PHP -v : 5.6.30-12

Fix conflict between UrlGeneratorInterface(s)

---

Admin/AbstractAdmin.php
Route/DefaultRouteGenerator.php
Tests/Admin/AdminTest.php
Tests/Route/DefaultRouteGeneratorTest.php

I cherry picked the commit https://github.com/sonata-project/SonataAdminBundle/commit/26d69b89b3184d12653dffc2fdea65ea37125c6f and then cleaned NEXT_MAJOR comments.
I don't know if this should be closed or merged, but a discussion started here about it: https://github.com/sonata-project/SonataAdminBundle/pull/4542#discussion_r125561202
ping @greg0ire @OskarStark

Clean NEXT_MAJOR comments of #4542

---

Resources/public/Admin.js
Resources/public/css/styles.css

```markdown
- Fixed sticky navbar when top navbar height changes
```
This PR fixes the navbar position when the top navbar height changes (when breadcrumbs are too long, for example).
To achieve this, on `document load` and `window resize`, I : 
- set the `content-wrapper` `padding-top` to the height of the `top navbar` (fixes content hidden behind it).
- update a dynamically inserted css class, by updating the `stuck navbar` top position (didn't find a better way).
I also removed the `debounce` function which seems not usefull anymore (we don't have to wait for any animation anymore, tell me if i'm wrong).
**Before**
**After**

Fix sticky navbar when top navbar height changes

---

Tests/Controller/CRUDControllerTest.php

Closes https://github.com/sonata-project/SonataAdminBundle/issues/4685
The build is broken with SF >= 3.3.10.
Caused by https://github.com/symfony/symfony/pull/24431/files?diff=unified#diff-064e58dbe11951327d614e6922caaae5R234

Fix tests for SF >= 3.3.10

---

Datagrid/Datagrid.php
Tests/Datagrid/DatagridTest.php

I am targeting this branch, because Datagrid generates several the same queries to get results.
```markdown
- Fix duplicate DB queries on empty results.
```

Don't get result twice if it is empty

---

Controller/CRUDController.php
DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
DependencyInjection/Configuration.php
Resources/config/core.xml
Resources/doc/cookbook/recipe_hashid.rst
Resources/doc/cookbook/recipe_overwrite_admin_configuration.rst
Resources/doc/index.rst
Resources/doc/reference/configuration.rst
Route/Handler/RouteIdHandler.php
Route/Handler/RouteIdHandlerInterface.php
Tests/Controller/CRUDControllerTest.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/Route/RouteIdHandlerTest.php

Added a `RouteIdHandlerInterface` component that will allow developers to change how the ID is taken from the route in the request. By default, it will take the ID from the ID parameter. But the intention is to be able to easily add a component that will decode any encoded IDs. For example using something like [HashIds](https://github.com/roukmoute/HashidsBundle) to secure routes from users.
```markdown
- RouteIdHandler that decides how to process the ID in the route on CRUDController
```

Adding a function that grabs the ID from the request

---

Resources/config/core.xml

```markdown
- Fixed wrong class name
```
Errors after update:
```
PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "RouteIdHandler" from namespace "Sonata\AdminBundle\Route"
```

Fix class name for sonata.admin.route_id_handler

---

Resources/views/Form/form_admin_fields.html.twig

```markdown
- Fixed missing space when form class is defined in label_attr
```
Small PR to fix missing space in form label class attribute.

Add missing space when merging label classes

---

Resources/doc/cookbook/recipe_custom_action.rst

I am targeting this branch, to fix documentation.
```markdown
-  List filter parameters example in documentation
```

fix list filter parameters example in documentation

---

Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because this is bug fix.
Closes -
```markdown
- Fixed autocomplete for cases when admin code uses service id and service id is equal to FQCN ('AppBundle\Admin\CompanyAdmin')
```

Fix admin code escaping in autocomplete

---

Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because it fixed the translation domain for expanded choices in admin.
imo that was a bug which is fixed by this backwards compatible thing
```markdown
- fixed choice_translation_domain for expanded choices in admin
- make false translation_domain working for the label if no translation is needed
```
because i broke #4667

Fixed choice_translation_domain for expanded choices

---

Controller/CRUDController.php

I am targeting this branch because the `addFlash` method exists in FrameworkBundle since Sf 2.6 and the SonataAdminBundle branch 3.x require Sf 2.8^ || 3.0^.
Closes #4702 
```markdown
- Removed overridden method `CRUDController::addFlash` because it exists since Symfony 2.6 and it's final in 3.4.
```

Remove obsolete addFlash method

---

Block/AdminStatsBlockService.php
Resources/views/Block/block_stats.html.twig
Tests/Block/AdminStatsBlockServiceTest.php

```markdown
- Added `translation_domain` key to `AdminStatsBlockService` to change or disable translation
```
All block texts were translation by default, which isn't unseful if you don't use translation keys.

Allow disabling block translation

---

Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because I got missing translate for empty string on form render.
```markdown
- Don't translate empty placeholder on form render
```

Don't translate empty placeholder

---

Admin/AbstractAdmin.php
Tests/Admin/AdminTest.php
Tests/Admin/BreadcrumbsBuilderTest.php

Closes #4569
```markdown
- `AbstractAdmin::hasSubject` is now populating `AbstractAdmin::$subject` property
```
AbstractAdmin::hasSubject is now populating AbstractAdmin::$subject property.

AbstractAdmin::hasSubject is now populating AbstractAdmin::$subject property

---

DependencyInjection/SonataAdminExtension.php
Resources/config/commands.xml

I am targeting this branch, because deprecation notices are thrown after update to Symfony 3.4.
Closes #4703
```markdown
- Register commands as services to prevent deprecation notices on Symfony 3.4
```
After updating Symfony version to 3.4 the following deprecation notices are thrown:
> Auto-registration of the command "Sonata\AdminBundle\Command\CreateClassCacheCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead.

Commands as services

---

Form/Type/ModelAutocompleteType.php
Resources/doc/reference/form_types.rst
Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Tests/Form/Type/ModelAutocompleteTypeTest.php

I am targeting this branch, because it's the latest stable branch.
Closes #2366 
Adding the `add` functionnality to the **ModelAutocompleteType** through a `add` button which open a modal window just like **ModelType** field
This works the same way, by opening a modal window when you click on the `Add` button.
```markdown
- Add support for `add` button in `sonata_type_model_autocomplete`
```
This pull request add the possibility to add a new record from an ModelAutocompleteType like the ModelEntityType does.
PHPUnit tests passed
Can't run PHP CS Fixer because of the [error below](https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/issues/75)
```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpCsFixer\Config::finder() in …
```

Add support for `add` button in `sonata_type_model_autocomplete`

---

Controller/CRUDController.php
Controller/HelperController.php
Tests/Controller/CRUDControllerTest.php
Tests/Controller/HelperControllerTest.php

```markdown
- getRuntime now receives a non deprecated runtime
```
Using Symfony 3.4 I found that this code does not work:
`$twig->getRuntime('Symfony\Bridge\Twig\Form\TwigRenderer')`
I have been looking at Symfony docs and found the following:
`Symfony\Bridge\Twig\Form\TwigRenderer` is deprecated since 3.4
http://api.symfony.com/3.4/Symfony/Bridge/Twig/Form/TwigRenderer.html
And we should use `Symfony/Component/Form/FormRenderer` that is present since 2.8:
http://api.symfony.com/3.4/Symfony/Component/Form/FormRenderer.html
We probably never face an issue on this bundle because it is on a try/catch block but there are other bundles that use if/else: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Controller/GalleryAdminController …

getRuntime now receives a non deprecated runtime

---

src/Form/Type/AdminType.php
tests/Form/Type/AdminTypeTest.php

I am targeting this branch, because the issue was introduced in https://github.com/sonata-project/SonataAdminBundle/pull/4429
also noted in commit: https://github.com/sonata-project/SonataAdminBundle/commit/0761127cfbaf83f2eec3b02e329f2d751a0b6b0f
Closes #4517
Closes #4475
```markdown
- subject assignment in embedded admins
```
right now embedded admins within a sonata type collect do not populate subject (this was working till version 3.15)
Since the commit that introduced the error was about fixing a path duplication I also added a check for that (this was in issue: #4425)

fix subject assignment in embedded admins

---

src/Controller/CRUDController.php
src/Controller/HelperController.php
tests/Controller/CRUDControllerTest.php
tests/Controller/HelperControllerTest.php

Closes #4758
```markdown
- Fix for getRuntime on Symfony older than 3.4
```
TwigRenderer is used as runtime until SF 3.4.
This code makes sure we retrieve the correct runtime for SF < 3.4
This should fix the issue, can you check it @0l1v3r5?
I don't know if this is the best way to do it @xabbuh or there is other work-around for this issue

Add BC layer for SF < 3.4 and > 2.8

---

src/Resources/views/standard_layout.html.twig

This is a patch that displays a title if there are no actions set
```markdown
- a condition to check if the navbar is to be displayed
- displaying a title when there are no specific actions
```
The navbar does not show up when no action is set.

Display title when it is set

---

src/Controller/CRUDController.php
tests/Controller/CRUDControllerTest.php
tests/Controller/CoreControllerTest.php

`render()` is annotated with `@final` since 3.4, and its signature changes in 4.0. Since we do not need to override it, let's not do that. Fixes #4701
I am targeting this branch, because this is BC (removing a method that also exists in the parent is BC).
```markdown
- deprecation about `Controller::render` being final
```

Refactor render to renderWithExtraParams

---

src/Form/Type/Filter/DateTimeType.php
src/Form/Type/Filter/DateType.php

Closes #4769 
Refs #4670 
```markdown
- Wrong configuration for DateTimeType and DateType filters
```
We missed a use statement on those classes, and because of that there are options that cannot be passed to those types

Add necessary Use

---

src/Resources/views/CRUD/base_list.html.twig

```markdown
- check if the field is used to sort the list
```
In configure field list we can set path to sort
```php
->add('size', null, [
'sortable' => 'recentVersion.size',              
])
```
But this field is not mark as current sorting field. 
before:
after:

Fix check current field sorting

---

docs/reference/form_types.rst

I am targeting this branch, because I am updating documentation about form types.
```markdown
- Changed documentation for Form Types.
```
After finishing my last PR and updating these docs about form types I saw that all other types need an update, so here it goes, the only thing I am not sure about is the CollectionTypes as that part is a bit confusing because of the same class name but a different bundle.

Update docs about form types

---

src/Form/Type/Filter/DateRangeType.php
src/Form/Type/Filter/DateTimeRangeType.php
src/Form/Type/Filter/DateTimeType.php
src/Form/Type/Filter/DateType.php
src/Form/Type/Filter/NumberType.php

Closes #4774 
```markdown
- Add alias on ChoiceType uses to avoid collisions on Form filter classes
```
There is already a ChoiceType class on that namespace so, in order
to use ChoiceType from Symfony we need to alias it
I am not sure why travis didn't show that on the builds, but it should be fixed (I guess on PHP 7 there is no such issue because I am using it without this patch with 0 problems)

Alias ChoiceType to avoid collisions on Form filters

---

src/Controller/CRUDController.php
tests/Controller/CRUDControllerTest.php
tests/Controller/CoreControllerTest.php

I am targeting this branch, because this reverts a BC-break.
Closes sonata-project/SonataPageBundle#910
Reopens #4701
```markdown
- BC-break in CRUDController::render()
```
This reverts commit 20372c52d255c215c07de9d3220421362ae624da.
It was a BC-break, because children classes might still call render()
and should get the extra parameters.

Revert "Refactor render to renderWithExtraParams"

---

src/Admin/AbstractAdmin.php

I am targeting this branch, because this PR fixes a bug in this branch.
```markdown
- Fixed `AbstractAdmin::getSubject()` behavior when `id` parameter is not specified
```
Calling this function with the request that does not have an id could cause a bug.

Changed AbstractAdmin::getSubject() so that the "subject" is not requested unless its "id" is specified

---

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because it's the one with the bug.
This PR fixes the #4771 issue.
```markdown
- Add a check for existing var associationadmin which is null for filter

Fix autocomplete form type in filter (issue #4771)

---

docs/reference/form_types.rst
src/Form/Type/ModelListType.php
src/Resources/translations/SonataAdminBundle.de.xliff
src/Resources/translations/SonataAdminBundle.en.xliff
src/Resources/translations/SonataAdminBundle.es.xliff
src/Resources/translations/SonataAdminBundle.fr.xliff
tests/Form/Type/ModelTypeListTest.php

I am targeting this branch, because I am adding `btn_edit` option to ModelListType that is needed for https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/708
```markdown
- Added edit button that opens in dialog instead of add if there is object already in sonata type model list
```
Currently we have only add button on ModelListType that replaces the object/value, this will add edit button that would open current object in a dialog and allow edit instead of replacing.

add btn_edit option to ModelListType

---

src/Controller/HelperController.php

Closes #4787 
```markdown
- Problem with FormRenderer not having environment causing that inline collection was unusable on SF 3.4
```
FormRenderer does not have `setEnvironment` method.
Does this fix your issue @virtualize ? I would like to test it also, don't want to make more mistakes with this one

FormRenderer does not have a method to set its environment

---

UPGRADE-3.x.md
src/Controller/CRUDController.php
src/Controller/PolyfillControllerTrait.php
tests/Controller/CRUDControllerTest.php

I am targeting this branch, because this fixes a deprecation warning in Symfony 3.4 and a possible incompatibility with Symfony 4.0+.
Closes #4701 
```markdown
- Added `CRUDController::renderWithExtraParams` as a replacement for the `render` method
- Deprecated `CRUDController::render`
- Deprecation warning for overriding `Controller::render` which is supposed to be final
```
The basic solution has already been merged previously, in #4765.
It has then been reverted again in #4780 because it introduced a BC issue due to the now different behaviour of `CRUDController::render` (which was the inherited method from `Controller` that does not add required parameters.)
This PR re-implements the solution while avoiding the BC issues:
**Symfony 3.4 / 4.0+:** Instead of inheriting from …

Do not override final Controller method render()

---

docs/reference/security.rst

I am targeting this branch, because this is a docs fix.
If you use FQCN's for service ids, the generated roles are different.
Please review commit by commit

Reflect new generated roles in docs

---

src/Controller/CRUDController.php
src/Resources/translations/SonataAdminBundle.en.xliff
src/Resources/translations/SonataAdminBundle.fr.xliff
tests/Controller/CRUDControllerTest.php

Refs #4736
```markdown
- Handle empty id list in `CRUDController::batchAction`
```
Allow nullable query in batchActionDelete where using preBatchAction to remove elements from list of ids to be delete by the batchActionDelete.

Handle empty id list in CRUDController::batchAction

---

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Actually this PR is continuation for #4784.
I don't know why I did not notice it in previous PR.
```markdown
- Fixed XSS vulnerability in autocomplete form type
```

Fix XSS vulnerability in autocomplete

---

src/Resources/views/standard_layout.html.twig

I am targeting this branch, because this fix doesn't introduce any backward incompatible change.
```markdown
- Updated `src/Resources/views/standard_layout.html.twig` template in order to remove whitespace rendering before HTML DOCTYPE declaration.
```
~~- [ ] Add test~~
Without this fix, there are 2 line breaks before the `<!DOCTYPE html>` declaration:
Causing client to throw an `Uncaught SyntaxError`:

Add whitespace control in `standard_layout.html.twig` in order to avoid client side rendering issues

---

src/DependencyInjection/SonataAdminExtension.php
src/Resources/config/templates.xml

It has been around for 6 years, seemingly for no reason.
Should have been removed in 645e56a904c0a4762e4f4dee0b3bff2a79bbab5a

Remove useless file

---

UPGRADE-3.x.md
src/Menu/Matcher/Voter/ChildrenVoter.php
src/Resources/config/menu.xml
src/Resources/views/Menu/sonata_menu.html.twig
tests/Menu/Matcher/Voter/ChildrenVoterTest.php

Closes #4639 
Fixes #4805
```markdown
- interference with other bundles
- using the `ChildrenVoter` class
- using the `sonata.admin.menu.matcher.voter.children` service
```
This is a carry of #4639

Use class for ancestors and remove set parent as current

---

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php

I am targeting this branch, because this is backward-compatible bug fix.
```markdown
- Services tagged with `sonata.admin` and `sonata.admin.filter.type` are now public
```
Prevents the following messages:
> User Deprecated: The "sonata.admin.orm.filter.type.number"  service is private, getting it from the container is deprecated since  Symfony 3.2 and will fail in 4.0. You should either make the service  public, or stop using the container directly and use dependency  injection instead.
Also should fix SF4 compatibility

Temporary fix for SF4 DI changes until we can support service locators

---

tests/Controller/HelperControllerTest.php
tests/Datagrid/PagerTest.php

Fix build for php 7.2

---

src/Admin/UrlGeneratorInterface.php
src/Twig/GlobalVariables.php
tests/Twig/GlobalVariablesTest.php

```markdown
- Fixed calling route generator with boolean value
```
This will reduce some deprecation warnings.

Replace deprecated boolean flag in route generator

---

src/Resources/views/CRUD/Association/edit_many_script.html.twig

I am targeting this branch, because I am moving the javascript for edit button to the main bundle.
```markdown
- Added edit button functionality
```
We weren't aware that association templates were moved to SonataAdminBundle (https://github.com/sonata-project/SonataAdminBundle/pull/4589), while doing the https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/708 so I am moving the edit button functionality here as next step is to switch `SonataDoctrineORMAdminBundle` to use `SonataAdminBundle` templates.

Move edit button javascript to SonataAdminBundle

---

src/Resources/views/CRUD/base_edit_form.html.twig
src/Resources/views/CRUD/base_edit_form_macro.html.twig

I am targeting this branch, because some texts are not translatable in admin.
```markdown
- Add trans filter to form_group and form_tab description
```
Fix missing trans filter in form_group and form_tab description

Fix missing trans filter in form_group and form_tab description

---

src/Admin/AbstractAdmin.php
tests/Admin/AdminTest.php

I am targeting this branch, because the issue (loops in our phpcr admin) occurs on this branch.
```Markdown
- Improvements on `AbstractAdmin::getClass()` method
```
I faced some loops in our phpcr admin imlementation casuse we used `getClass() method in our `AbstractAdmin::getSubject()` implementation, cause getClass() calls getSubject() again. We had to solve our issue in our code, but here are some fixes to make the code consistent to the doc block information.

improvments on getClass() method

---

src/Resources/views/CRUD/Association/edit_one_script.html.twig
src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig

I am targeting this branch, because I am moving merged changes from `SonataDoctrineORMAdminBundle` to templates in this bundle.
```markdown
- Added changes that were merged after moving of templates
```
As we forgot that association templates were moved to `SonataAdminBundle` people still continued to submit PRs to `SonataDoctrineORMAdminBundle` to change templates, https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/675 and https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/720 are PRs that were merged after moving the temapltes and now as we are deprecating templates in `SonataDoctrineORMAdminBundle` we have to update templates here.

Add merged changes from old templates

---

composer.json

Closes #4841 
```markdown
-  exporter-related error during cache:clear command.
```

Modify sonata-project/exporter requirement to ^1.7.1

---

docs/reference/configuration.rst
src/DependencyInjection/Configuration.php
src/DependencyInjection/SonataAdminExtension.php
tests/DependencyInjection/ConfigurationTest.php
tests/DependencyInjection/SonataAdminExtensionTest.php

I am targeting this branch, because my change is backwards compatible. It only adds additional configuration features.
Closes #2425
```markdown
- Added possibility to add and remove javascripts/stylesheets without adding all defaults again
```
This PR will allow developers to add additional stylesheets and javascripts to the page without having to edit the defaults. It also adds configuration to remove stylesheets and javascripts that are added in the default array. Fixes #2425.

Extra and remove assets added to configuration

---

src/DependencyInjection/SonataAdminExtension.php
tests/DependencyInjection/SonataAdminExtensionTest.php

```markdown
- Fixed container compile error, if JMSDiExtraBundle is enabled.
```
After this changes https://github.com/sonata-project/SonataAdminBundle/commit/d6ffaef34cf6e0b08a12478478d5105eec592b50#diff-156ed93418fe946ee724987b790b24baR349
```
Unrecognized options "security, title, title_logo, options, persist_filters, show_mosaic_button, templates, dashboard, extensions, assets" under "jms_di_extra"
```
Because class `Sonata\AdminBundle\DependencyInjection\Configuration` overrided `JMS\DiExtraBundle\DependencyInjection\Configuration`

Fixed invalid class name DependencyInjection\Configuration

---

UPGRADE-3.x.md
src/Admin/AbstractAdmin.php
tests/Admin/AdminTest.php

Refs #4543 @vyshkant , I did not have the courage to read it again, but maybe using `setSubClasses` would solve the issues you had.
```markdown
- `AbstractAdmin::addSubClass()`
```
As spotted by @ElectricMaxxx , this method is incoherent with the underlying property, which is supposed to be a hash and not a simple array.

Deprecated AbstractAdmin::addSubClass()

---

docs/reference/configuration.rst
src/DependencyInjection/Configuration.php
src/Resources/public/sidebar.js
src/Resources/views/standard_layout.html.twig
tests/DependencyInjection/SonataAdminExtensionTest.php

I am targeting this branch, because I am adding a feature.
Closes #4837
```markdown
- Menu on the left side stays hidden while changing pages.
```
Something I wished I had when working with multiple pages on one screen. When I saw the issue I asked on slack and @Xymanek mentioned that cookies would be a good solution so here it is. I was not sure where should I put the javascript (or should I even use jquery?) so I will move it if you tell me where.

Keep menu on left side hidden when browsing

---

composer.json

```markdown
- Fixed twig dependency for sonata.admin.controller.admin service
```
`sonata-project/admin-bundle` actualy depends on `symfony/twig-bundle`, not from `symfony/twig-bridge`+`twig/twig`.
`sonata.admin.controller.admin` service, defined in `src/Resources/config/core.xml` depends on `twig` service, which defined in `symfony/twig-bundle`. See https://github.com/symfony/twig-bundle/blob/master/Resources/config/twig.xml

Fix twig dependency

---

src/Resources/public/Admin.js

I am targeting this branch, because this has no BC breaks in it.
The patch which was introduced by [this PR](https://github.com/sonata-project/SonataAdminBundle/pull/4678) is needed, if the `body` element uses the `fixed` class offered by AdminLTE for making the header fixed. However the above mentioned patch creates a big gap in the layout, if the header is not fixed. 
```markdown
- Checking for fixed class on body before adjusting the position of the content div
```
Fix content position only if needed.

Fix content position only if needed

---

composer.json

```markdown
- Make explicit dependency with `symfony/asset`
```
Trying to make SonataDoctrinePHPCRAdminBundle build pass I saw we make use of `asset` function on twig, but we are not depending on the package that enables this function.

Add asset component to enable use of asset twig function

---

src/Resources/public/Admin.js
src/Resources/views/CRUD/base_list.html.twig

I am targeting this branch, because this is a BC feature.
```markdown
- Added filter counter to admin lists
```

Added filter counter

---

src/Resources/public/sidebar.js

I am targeting this branch, because I am fixing a bug with cookies when hiding sidebar.
```markdown
- Added path to cookies when hiding sidebar to avoid creating multiple cookies
```
As @jordisala1991 pointed out [here](https://github.com/sonata-project/SonataAdminBundle/pull/4854#issuecomment-354736451), as I did not add the path every page had it own cookie, which leads to some pages having sidebar even when it should be hidden and vice versa, this should fix it.

Add path to cookie to avoid multiple cookies

---

src/Menu/Matcher/Voter/AdminVoter.php
src/Resources/config/menu.xml
tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
tests/Menu/Matcher/Voter/AdminVoterTest.php

@TorbenLundsgaard seems to be away, so I fixed the last issues and merged the conflicts
Closes https://github.com/sonata-project/SonataAdminBundle/pull/4808
```markdown
- `request` attribute deprecation on `knp_menu.voter`
```
Using the "request" attribute of the "knp_menu.voter" tag is deprecated since KnpMenuBundle version 2.2. The RequestStack should be injected in the voter instead.

Fix "request" attribute deprecation on "knp_menu.voter"

---

src/Resources/views/CRUD/base_array_macro.html.twig

Closes #4684 #4436 #4683
```markdown
- Nested arrays will show properly on show/list fields
```
There was an error with newer versions of twig where you need to explicit load macros even when you are recursively calling a macro.

Nested arrays now displays correctly on show/list views

---

docs/reference/dashboard.rst
src/Resources/config/routing/sonata_admin.xml

```markdown
- path to dashboard
```
In the previous PR the routing path was unnecessarily overwritten.

Quickfix path in routing (revert)

---

src/Form/Type/ModelHiddenType.php
src/Twig/Extension/SonataAdminExtension.php

I am targeting this branch, because there is no BC-break.
Closes #4886
```markdown
- ModelHiddenType - default hidden attribute is now set to true
```
ModelHiddenType - default hidden attribute is now set to true

ModelHiddenType: changed default hidden attr value to true

---

docs/getting_started/installation.rst

```markdown
- Update documentation about configuration of block default contexts
```
This PR updates documentation about optional parameter `sonata_block.default_contexts`. See https://github.com/sonata-project/SonataBlockBundle/pull/464#issuecomment-356209084 for details

Update documentation about configuration of BlockBundle

---

src/Admin/BaseFieldDescription.php
tests/Admin/BaseFieldDescriptionTest.php

I am targeting this branch, because this is backward compatible bug fix.
```markdown
- Fix bug when we pass null as fieldName to BaseFieldDescriptor::getFieldValue
```
After releasing `doctrine/inflector` v1.3.0 unit tests of `sonata-project/doctrine-mongodb-admin-bundle` became failing. That tests tested behavior of `FieldDescriptor` when only `code` option was given before calling `getFieldValue`.
This PR fix bug when we pass null as fieldName to BaseFieldDescriptor::getFieldValue, so only method name given in the `code` option will be used to get a value

Fix bug when we pass null as fieldName to BaseFieldDescriptor::getFieldValue

---

docs/reference/form_types.rst
src/Form/Type/ModelAutocompleteType.php
src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because "Fix XSS vulnerability in autocomplete" #4796 prevent passing HTML through label string, due to security reason. I have added an new option called 'safe_label' which follows KNP menu render wording. By default the safe label is false.
Closes #4815
```markdown
- Added new 'safe_label' option to allow HTML pass-through on autocomplete form type
```

Allow HTML pass-through for autocomplete form type

---

docs/index.rst

We should remove this from the website too:
https://sonata-project.org/bundles/propel-admin/master/doc/index.html

removed PropelBundle from docs

---

src/Datagrid/Datagrid.php

I am targeting this branch, because it's a bug in 3.x per issue #4906
Closes #4161
Closes #4906 
```markdown
- Only do `$filter->apply` if the filter is "active" on the datagrid list
```
Just added an if ($filter->isActive()) block around the $filter->apply as described in the issue.

Only call filter->apply if active (issue #4906)

---

composer.json
docs/cookbook/recipe_custom_action.rst
docs/cookbook/recipe_customizing_a_mosaic_list.rst
docs/cookbook/recipe_knp_menu.rst
docs/cookbook/recipe_row_templates.rst
docs/cookbook/recipe_sortable_listing.rst
docs/reference/action_show.rst
docs/reference/advanced_configuration.rst
docs/reference/form_types.rst
docs/reference/preview_mode.rst
docs/reference/search.rst
docs/reference/templates.rst
src/DependencyInjection/SonataAdminExtension.php
src/Form/Type/ModelAutocompleteType.php
src/Resources/config/block.xml
tests/Admin/AdminTest.php
tests/Command/ExplainAdminCommandTest.php
tests/Controller/CRUDControllerTest.php
tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
tests/DependencyInjection/ConfigurationTest.php
tests/Fixtures/Command/explain_admin.txt
tests/Fixtures/Command/explain_admin_empty_validator.txt
tests/Form/Type/ModelAutocompleteTypeTest.php

```markdown
- Switch all templates references to Twig namespaced syntax
- Switch from templating service to sonata.templating
```
This PR is a part of a big plan of decoupling sonata-project bundles from Templating Component. See sonata-project/dev-kit#380 for details

Decouple from Templating Component, Stage 1

---

docs/getting_started/installation.rst

I am targeting this branch, because I am updating documentation for Symfony Flex.
```markdown
- Installation Documentation
```
Updating installation docs so people using flex know where to add bundles or routes.

Update installation documentation for Symfony Flex

---

src/Resources/views/standard_layout.html.twig
src/Twig/Extension/SonataAdminExtension.php
tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch, because there are some locales from bower dependencies which are not found under the current implementation.
```Markdown
- Not found issues for some locales which are not present in frontend dependencies like `moment` or `select2`
```
Closes #3642.

Translate some locales in order to match locales available from bower dependencies

---

docs/reference/child_admin.rst

I am targeting this branch, because it is BC.
Closes #4916 
According to documentation:
```
protected function configureRoutes(RouteCollection $collection)
{
if ($this->isChild()) {
// This is the route configuration as a child
$collection->clearExcept(['show', 'edit']);
return;
}
// This is the route configuration as a parent
$collection->clear();
}
```
Clearing **list action** in child admin can cause an error - route doesn't exist, if I want to list child items.
```
if ($this->isGranted('LIST')) {
$menu->addChild('Manage Videos', [
'uri' => $admin->generateUrl('sonata.admin.video.list', ['id' => $id])
]);
}
```

[Docs] Child admin

---

src/Datagrid/Datagrid.php

I am targeting this branch, because it's a regression in 3.x per issue #4906 and PR #4907 
Closes #4906 
Closes #4161 
```markdown
- Only do `$filter->apply` if the filter has a value that is not empty string
```
Check that $this->values has a value that is not the empty string before applying the filter.

Fix #4906 Only apply filters if it has a value other than empty

---

src/Util/AdminObjectAclData.php
tests/Util/AdminObjectAclManipulatorTest.php

Closes #2349
Closes #3209
```markdown
- Missing `getOwnerPermissions` to `AdminObjectAclData`
```
I was travelling through time, and found that 2 issues that was unresolved. Looked to the code and found that a method was missing since 5 years ago when it was added.
This code fixes the issue and adds tests to cover a little this code.
I do not use anything about ACL so I tried my best on the tests.
Code added here: https://github.com/sonata-project/SonataAdminBundle/pull/1475

Add missing getOwnerPermissions to AdminObjectAclData

---

src/Resources/views/CRUD/base_list.html.twig

I am targeting this branch, because this is a BC.
Closes #2203
```markdown
- Error if the field in filter list is named `children`
```
The issue is with Symfony Forms, in our code, we have `form.children[filter.formName]` and then Symfony gives us the children FormView instead of the property in children array.
```
FormView {#1510 ▼
+vars: array:30 [▶]
+parent: null
+children: array:7 [▼
"name" => FormView {#1584 ▶}
"value" => FormView {#1226 ▶}
"children" => FormView {#1578 ▶}
"_sort_by" => FormView {#1513 ▶}
"_sort_order" => FormView {#1526 ▶}
"_page" => FormView {#1588 ▶}
"_per_page" => FormView {#1585 ▶}
]
-rendered: false
-methodRendered: false
}
```
Remove `.children` from `form.children[filter.formName]` fixes the issue.

Get form field without calling the children first

---

docs/getting_started/installation.rst
docs/reference/saving_hooks.rst

I am targeting this branch, because this is for docs.
Closes #4909
Cleaning up a bit the installation page.
- Remove references to Propel
- Remove a confusing part about bower that should not be on the main installation page (really I dont know who wants to manually install bower assets, because you can't change versions unless you are not using composer, because on the next update it will get rolled back)
- Add the configuration block whenever its needed, so it shows what format have the documentation: https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/security.html Example at the end of this page
- Add missing reference to doctrineORMAdminBundle

Installation docs improvements

---

src/Controller/CRUDController.php

I am targeting this branch, because this is minior fix.
Closes -
Fix deprecation phpdoc

Fix deprecation phpdoc

---

src/Block/AdminSearchBlockService.php
tests/Block/AdminSearchBlockServiceTest.php

I am targeting this branch, because it is BC.
Closes #4574
```markdown
- Admins without global search filters will no longer be shown in the global search.
```
It was not possible to remove an Admin from the global search blocks.
The global search would list all the Admins. An Admin was shown with "no results found" if that Admin had no filters specified, no filters of that Admin had `'global_search' => true`, or no results were found within that Admin.
After this change, the Admin block will not be shown in the global search results if there are no filters specified or all specified filters have `'global_search' => false`.
The Admin block is still shown, however, if there are filters for global search, but no results were found.

Don't show admin blocks in global search results when no filters are set for global_search

---

src/Controller/HelperController.php
tests/Controller/HelperControllerTest.php

I am targeting this branch, because this is BC and is a bugfix.
Closes #4856 
```markdown
- Compatibility with edit relation on list with PHPCR and MongoDB Sonata bundles
```
Self explanatory subject. This method is not on the interface: `getEntityManager `, so only the orm has it. In order to make this work we have to work around it and load the entity manager from the container directly to be able to get the classMetadata in order to check for the associations.
Also the other wrong part was getting the orm directly from the container

Make edit relation on list compatible with phpcr and mongodb

---

tests/Controller/HelperControllerTest.php

Tests are failing https://github.com/sonata-project/SonataAdminBundle/pull/4943 becuase TwigExtension is final on master branch, this fixes it.

Fix failing tests

---

src/Resources/views/CRUD/Association/edit_one_to_many.html.twig

Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/813
```markdown
- including wrong javascript code for associations modals
```

Fix including wrong template

---

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

I am targeting this branch, because there is no BC-break.
```markdown
- `ModelAutocompleteType` can now be used without a linked admin class
```
The variable `sonata_admin.field_description.associationadmin` can be defined but is null
so `{% if sonata_admin.field_description.associationadmin is defined %} ` is TRUE
but the method hasRoute does not exist in object sonata_admin.field_description.associationadmin = null 
please see this article https://straightupcraft.com/articles/testing-if-something-exists-is-defined-length-is-not-null-is-not-empty
Example: I want to use the type sonata_type_model_autocomplete for a field not linked to an admin
```php
<?php
// NavAdmin.php
protected function configureFormFields(FormMapper $formMapper)
{
$formMapper
->add('share', …
```

Use ModelAutocompleteType without a linked admin class

---

composer.json

It was added here: https://github.com/sonata-project/SonataAdminBundle/pull/1607
To test a command added here: https://github.com/sonata-project/SonataAdminBundle/commit/c91a0ffdde47b3b41eb73bfa1ab4d4aef4a2cf22
I've never seen that command or use it, but the `class-loader` is only used there, and it is a deprecated component, so it does not have a 4.0 version. https://github.com/symfony/class-loader
On a first step, removing the ^4.0 version is a must, but I don't know if we should try move this to the require-dev and deprecate that code, or remove it directly. I don't even know what the command does, but seems something like is not needed now with the newer versions of PHP.

Class loader does not have 4.0 version

---

src/Form/Type/ChoiceFieldMaskType.php
src/Resources/views/Form/form_admin_fields.html.twig
tests/Form/Type/ChoiceFieldMaskTypeTest.php

I am targeting this branch, because this is a minor, BC fix.
Closes #4717
Closes #4127
```markdown
- Fixed PHP warnings when `ChoiceFieldMaskType` option `map` is invalid or empty
- Fixed javascript handling of `ChoiceFieldMaskType` when option `expanded` is `true`
```
The `ChoiceFieldMaskType` option `map` was not handled safely enough:
- It gave a `Warning: array_merge() expects at least 1 parameter, 0 given` if the option was not set or was set to an empty array.
- It gave a `Warning: Invalid argument supplied for foreach()` if the option was anything but an array.
Also, the javascript function to show/hide fields did not work if the `ChoiceFieldMaskType` field was expanded (radio buttons instead of a select).
I changed the following:
- Set the allowed types for the `map` option to …

Better handling of ChoiceFieldMaskType option 'map'

---

docs/reference/batch_actions.rst
docs/reference/templates.rst
src/Resources/config/twig.xml
src/Resources/views/CRUD/Association/list_many_to_many.html.twig
src/Resources/views/CRUD/Association/list_many_to_one.html.twig
src/Resources/views/CRUD/Association/list_one_to_many.html.twig
src/Resources/views/CRUD/Association/list_one_to_one.html.twig
src/Resources/views/CRUD/base_history.html.twig
src/Resources/views/CRUD/base_list.html.twig
src/Resources/views/CRUD/list__action.html.twig
src/Resources/views/CRUD/list__batch.html.twig
src/Resources/views/CRUD/list__select.html.twig
src/Resources/views/CRUD/list_array.html.twig
src/Resources/views/CRUD/list_boolean.html.twig
src/Resources/views/CRUD/list_choice.html.twig
src/Resources/views/CRUD/list_currency.html.twig
src/Resources/views/CRUD/list_date.html.twig
src/Resources/views/CRUD/list_datetime.html.twig
src/Resources/views/CRUD/list_email.html.twig
src/Resources/views/CRUD/list_html.html.twig
src/Resources/views/CRUD/list_outer_rows_list.html.twig
src/Resources/views/CRUD/list_percent.html.twig
src/Resources/views/CRUD/list_string.html.twig
src/Resources/views/CRUD/list_time.html.twig
src/Resources/views/CRUD/list_trans.html.twig
src/Resources/views/CRUD/list_url.html.twig
src/Twig/Extension/TemplateRegistryExtension.php
tests/Twig/Extension/SonataAdminExtensionTest.php
tests/Twig/Extension/TemplateRegistryExtensionTest.php

I am targeting this branch, because this is a BC fix for an earlier PR to 3.x.
```markdown
- Templates that rely on the `admin` variable in Twig can now use the `get_admin_template` function correctly.
```
In a [previous PR](https://github.com/sonata-project/SonataAdminBundle/pull/4948), the Twig function `get_admin_template` was added. This function pulled the current admin code from the `Request` object through `RequestStack::getCurrentRequest()`.
@andrewmy pointed out that this is not (always) the correct way to do this. Thank you.
In order to fix this, I added a `$adminCode` parameter to the `get_admin_template` Twig function, so that the correct admin is used again.
I changed the `SonataAdminExtensionTest` test case, because a different admin code was used in the test, then the one …

Add admin code to Twig get_admin_template function

---

src/Resources/views/CRUD/Association/edit_many_script.html.twig

I am targeting this branch, because this should be BC.
```markdown
- Allow capturing of any link click inside of modal
```
Currently, if Entity is implementing `Sonata\TranslationBundle\Model\Gedmo\TranslatableInterface` we get flags in the form that allow us to change the language. If we use `ModelListType` on associated Entity we get the same flags in the popup.
The problem is if we click 1 time on any flag the form in modal is reloaded and we will save it in that language. If we click again on some other flag we get redirected to that page with that language selected instead of reloading the modal again, so we lose info from the page where we opened the modal. With this fix, we capture any click inside of modal and reload the form without redirecting.
Not sure if this can break …

Catch all clicks on a link

---

src/Resources/public/css/styles.css
src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig

Closes #4969
```markdown
- batch checkbox is hidden when using the mosaic view in modal
- whole mosaic item is now wrapped in a tag instead of just title
```
Before:
After:
This will hide checkbox for batch action when in modal because we do not have batch actions there. Instead of making just the title clickable now the whole item can be clicked.

improve mosaic template

---

src/Admin/AbstractAdmin.php
src/Controller/CRUDController.php
tests/Admin/AdminTest.php

I am targeting this branch, because is BC.
Closes #4859 
```markdown
- fix behaviour of `AbstractAdmin::preValidate` by relying on form event listener
```
The `AbstractAdmin::preValidate` method was not called before the effective symfony validation. This PR fix that by relying on form event listener.
The real Symfony validation is done by the [ValidatorListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php) on `FormEvents::POST_SUBMIT` event with the priority 0. 
With this patch, the `preValidation` is called on `FormEvents::POST_SUBMIT` event with the priority 100 (the highest the priority, the earlier a listener is executed).

Use form event listener to fix preValidation

---

docs/getting_started/creating_an_admin.rst
docs/getting_started/installation.rst
docs/getting_started/the_form_view.rst
docs/getting_started/the_list_view.rst

Closes #4952 
Closes #4951 
This includes improvements for the getting started documentation
Based on those two PR I created a new one:
- Adapt instructions for Symfony 4, with a note at the top to inform that if you are not using Symfony 4 there are some thing that might need to change
- Minor improvements on images and newlines
- Added configuration-block to yaml code 
- Change string form types to FQCNs that is compatible with Symfony 2.8, 3 and 4

Improve docs: Getting started

---

docs/cookbook/recipe_file_uploads.rst
docs/cookbook/recipe_select2.rst
docs/reference/extensions.rst
docs/reference/form_help_message.rst
docs/reference/form_types.rst

I am targeting this branch, because I found some of the documentation was wrong while working.
I recently updated a project to SF 3.4 and SonataAdminBundle 3.31.1 and ran into some issues with existing code, looking at the docs most of the Form Types used FQCN but not all, so this is just updating some of those I ran into.

Replace string types with FQCN types in docs

---

src/Resources/views/Block/block_search_result.html.twig

```markdown
- Make search result page less heavy
```
Currently, when you admin configuration manage a lot of entities, the search result is really heavy:
First of all, the `primary` class is used for primary things. I don't think that dozen of search result panels are primary.
Here is the result of this PR without primary color:
With fade option for empty boxes:
With show option for empty boxes:
My eyes are not bleeding anymore.

Make search result page less heavy

---

docs/getting_started/creating_an_admin.rst

Fix creating admin docs

---

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php

```markdown
- Fatal error in strict mode
```
Fix a bug with strlen on null value:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: strlen() expects parameter 1 to be string, null given in /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php:402
Stack trace:
#0 /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php(402): strlen(NULL)
#1 /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php(67): Sonata\AdminBundle\DependencyInjection\Compiler\AddDependencyCallsCompilerPass->replaceDefaultArguments(Array, Object(Symfony\Component\DependencyInjection\Definition), NULL)
#2 …
```

Fix fatal error in strict mode: strlen() expects parameter 1 to be string, null given

---

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Closes #4997
```markdown
- FieldDescription null check missing in ModelAutocompleteFilter
```
fix "Impossible to access an attribute ("hasAssociationAdmin") on a null variable",
when using `ModelAutocompleteFilter` on configureDatagridFilters;

check `sonata_admin.field_description`, somewhere is null;

---

src/Admin/BaseFieldDescription.php
tests/Admin/BaseFieldDescriptionTest.php
tests/Fixtures/Entity/Foo.php

I am targeting this branch, because there is a bug when trying to access non public methods at `BaseFieldDescription`
```Markdown
- Avoid calling protected/private methods when retrieving values from entities
```

Avoid trying to use non public getters on `BaseFieldDescription`

---

src/Admin/BaseFieldDescription.php
src/Admin/FieldDescriptionInterface.php
tests/Admin/BaseFieldDescriptionTest.php

I am targeting this branch, because this is BC fix.
```markdown
- `getFieldValue` from `BaseFieldDescription` can now handle getting a value from null objects.
```
As context, I must mention the scenario in which the received subject is `null`.
I have a simple set of geo entities (**City**, **State**, **Country**) which have _many-to-one_ association respectively (a country may have _n_ states, a state may have _n_ cities). I use these entities within others, like **User**. The association between **User** and **City** is _many-to-one_ and is **NULLABLE**. So, in my `UserAdmin::configureShowFields()` I have the following call:
```php
ShowMapper::add('city.state', EntityType::class, ['class' => State::class])
```
then, when there is no city for a user, value passed to …

Allow `null` values as argument 1 for `FieldDescriptionInterface::getFieldValue()`

---

docs/getting_started/installation.rst

Because the first step is mixed with installing admin-bundle + a storage bundle people just go past it. This way we have a separate section for storage bundle and we will hopefully avoid questions when people don't install it. Also removed not needed `step %` before every title.

Improve installation docs

---

src/Resources/views/CRUD/base_list.html.twig

I am targeting this branch, because it's a patch.
```markdown
- `base_list` template includes the configurable `button_create` template rather than the default `create_button.html.twig`.
```
Fixed the `base_list` no results view to include the configurable `button_create` template rather than the default.

Configurable button_create template in base_list view

---

UPGRADE-3.x.md
src/Twig/Extension/SonataAdminExtension.php
tests/Controller/HelperControllerTest.php
tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch, because it is BC.
```markdown
- Replaced calls to Twig internal `Environment::loadTemplate()` method with `Environment::load()` in `SonataAdminExtension`.
- Deprecated `SonataAdminExtension::output()`. Now using the private `render()` method. Please use the `render*()` methods instead.
```
I noticed that the `Sonata\AdminBundle\Twig\Extension\SonataAdminExtension` class calls an internal Twig method. I replaced these calls with the suggested replacement.

Replaced calls to internal Twig Environment loadTemplate method with load

---

src/Resources/translations/SonataAdminBundle.fr.xliff

```markdown
- Added missing french translation for `Toggle Navigation`

Add missing french translation for toggle_navigation

---

docs/cookbook/recipe_custom_action.rst
docs/reference/architecture.rst
docs/reference/routing.rst

I am targeting this branch, because docs.
Missed a few controllers in docs.

Fix missed controllers in documentation

---

src/Command/ExplainAdminCommand.php
tests/Command/ExplainAdminCommandTest.php

I am targeting this branch, because this is BC fix.
Closes #5016 
```markdown
- Explain command compatible with sf4
```
This was changed in https://github.com/sonata-project/SonataAdminBundle/pull/4817 and wrong part was saved as `validator.validator_factory` is not the same service in 2.8 and in 3+

Add sf4 support to explain command

---

docs/reference/field_types.rst
src/Twig/Extension/SonataAdminExtension.php
tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch, because it's a small BC improvement.
```markdown
- Added `required` option to editable list `choice`
```
This PR adds a `required` option to editable list `choice`. If set to `false`, it will add an empty placeholder to the select input.
```
$listMapper->add('status', 'choice', [
'choices' => [
'prep' => 'Prepared',
'prog' => 'In progress',
'done' => 'Done'
],
'editable' => true,
'required' => false,
]);
```

Add required option to editable list choice

---

docs/reference/form_types.rst

I am targeting this branch, because it's a docs fix.
Fixed a form type to FQCN in `CollectionType` docs.

Fixed a form type to FQCN in CollectionType docs

---

src/Controller/HelperController.php
tests/Controller/HelperControllerTest.php

Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/818
```markdown
- Fix edit choice with a relation field on admin list
```
getManagerType does not return what was expected, also if this method works it is better since it does not rely on container, but on properties that are already loaded.
This is a bugfix from my previous PR: #4930
Please, can you check if this works @mikemix ?

Fix editable relation on list

---

docs/cookbook/recipe_custom_action.rst

I am targeting this branch, because docs
Just found out that you can create a template instead of forwarding an array, that looks like a cleaner solution to me so here is an update.

Document another way to add dashboard action

---

src/Resources/config/core.xml

I am targeting this branch, because it fixes a deprecation notice when we want to inject the Pool service and we use autowiring.
```markdown
- Fixed deprecation notice when Pool is injected in service through autowiring
```
it fixes a deprecation notice when we want to inject the Pool service and we use autowiring.

Add pool alias

---

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig

Closes #4911 
```markdown
- `ChoiceFieldMaskType` now works on inline table collections
```
Trying to fix the issue #4911 I ended up comparing those 2 templates:
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
The first one don't work as expected (the choiceFieldMaskType) and it is used when creating a collectionType with edit inline table.
The second one actually works (the choiceFieldMaskType), and it is used when creating a collectionType with edit inline standard
The solution and the issue is that the table …

Simplify template based on inline standard

---

src/Resources/views/CRUD/Association/list_many_to_one.html.twig

I am targeting this branch, because this is a BC fix.
Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/330
```markdown
- if object is empty, don't try to create an edit route
```
Currently, there is no check if the object has an id and tries to generate the route for edit on many-to-one in the list.

Fix error if no object in relationship

---

src/Resources/public/Admin.js

Closes #3346
```markdown
- Disable form submit buttons when the form gets submitted
```
All forms will get submit buttons disable after the form gets submitted, this way we enforce the form cannot get submitted multiples times.

Disable form submit buttons when the form gets submitted

---

src/Admin/AbstractAdmin.php
tests/Admin/AdminTest.php

Closes #4391 
```markdown
- Increase consistency on default page sizes (replaced 192 by 256)
```
192 didn't make sense, 256 is more consistent.

Increase consistency on default page sizes

---

src/Form/Type/Filter/ChoiceType.php
src/Form/Type/Filter/DateRangeType.php
src/Form/Type/Filter/DateTimeRangeType.php
src/Form/Type/Filter/DateTimeType.php
src/Form/Type/Filter/DateType.php
src/Form/Type/Filter/NumberType.php
tests/Form/Type/Filter/DateTimeRangeTypeTest.php

Closes #5015 
```markdown
- form types FQCN are now used in filter. Improves compatibility with SF3/4
```
There were a lot of missing Form types FQCN on filter types. Not sure how everything works without this change. But #5015 could be related. Can you check how it works with this PR? @michalwroblewski

Fix form types FQCN on Sonata Filters

---

src/Resources/public/css/layout.css

Closes #4850 
```markdown
- Navbar positioning on mobile is no longer altered like in desktop
```
I don't like to use importants, but on this case, the good solution would be BC break probably, because the perfect scenario would be to not have the fixed class on the body if the header is not fixed.

Force top: 0 on navbar positioning on mobile

---

src/Resources/views/standard_layout.html.twig

As discussed on slack, maybe we can remove this line to avoid overriding it.
```markdown
- `side_bar_after_nav_content` block is now empty by default
```

Delete sonata website on sidebar footer

---

src/Resources/public/Admin.js

```markdown
- Fix regression on #5051: It is possible again to know which button triggered the submit of the form.
```
If you disable buttons before submitting the form, it will not
include the submit button name on the variables being submitted.
Using a timeout function we ensure that the forms is sent with
that variable. This allows us to know which button was clicked.
This comes from: https://github.com/sonata-project/SonataAdminBundle/commit/082faff76276fba21c99b1d4949b951b8a4d25d7#commitcomment-28388840

Allow to know which button triggered the submit button

---

UPGRADE-3.x.md
src/Controller/CRUDController.php
tests/Controller/CRUDControllerTest.php

Closes #4556
```markdown
- Editing child admin that does not belong to a given parent
```
First of all, I am not sure if this is a BC break?
Second, is this a good way? What if they don't have a getter or named it differently? Would it even work with forms? Any suggestions?

Throw Deprecation if the child does not belong to a parent

---

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig

This reverts commit fdc7ea1756aeec0d6a9cf232e288e1a2d6779b8e.
I am targeting this branch, because it's a regression fix.
Fixes #5067 
```markdown
- Regression for child form type rendering
```

Revert "Simplify template based on inline standard"

---

src/Admin/AbstractAdmin.php
src/Admin/AdminInterface.php
src/Controller/CRUDController.php
src/Twig/Extension/SonataAdminExtension.php
src/Twig/Extension/TemplateRegistryExtension.php
tests/Controller/CRUDControllerTest.php
tests/Controller/HelperControllerTest.php
tests/Twig/Extension/SonataAdminExtensionTest.php
tests/Twig/Extension/TemplateRegistryExtensionTest.php

I am targeting this branch, because this is a fix to a BC breaking change.
Closes #5065
```markdown
- Fixed a BC break where an overwritten `getTemplate()` method in an `Admin`
was no longer called by Sonata.
```
Changes in PR #4980 introduced a BC break: the `AbstractAdmin` method `getTemplate()` was no longer called (all calls to that method were replaced with calls to the `TemplateRegistry::getTemplate()` method).
As @FabienPapet pointed out, people may override the `AbstractAdmin::getTemplate()` method to use different templates than the defaults.
Because that method is no longer called, the system reverts back to using the default templates. This is a BC break.
I replaced all admin-specific calls to `TemplateRegistry::getTemplate()` with calls to `AbstractAdmin::getTemplate()`. The …

Calls to AbstractAdmin::getTemplate put back

---

src/Admin/AbstractAdmin.php
tests/Admin/AdminTest.php

I am targeting this branch, because it's a regression fix.
Closes #5069 
```markdown
- Not working persist_filter option for legacy admin property.
```
Even if the property is deprecated, it's still used to check if the filters have to be persisted or not.
As the `setFilterPersister` method is called only if the `persist_filter` configuration key is set to `true`, I set the `persistFilters` deprecated attribute here to avoid resolvable deprecation error with the setter.

Set persistFilters option to true while setting the filter persister

---

UPGRADE-3.x.md
docs/reference/child_admin.rst
src/Admin/AbstractAdmin.php
tests/Admin/AdminTest.php

I am targeting this branch, because this is a feature without BC Break.
Closes #3339
Continuing #4954
```markdown
- Admin can now have multiple parents
- `AbstractAdmin::addChild` now accepts 2nd parameter with parent name
```
Let's finish this once and for all :smile:

Admin can have multiple parents now

---

src/Menu/Provider/GroupMenuProvider.php
tests/Menu/Provider/GroupMenuProviderTest.php

Closes #4576
Closes #4518
Closes #4413
```markdown
- Fixed route generation with parameter for on_top menu items
- Fixed custom group permission for menu items
```
This is a little refactor of the GroupMenuProvider, to generate the menu items in a unique way.

Unify menu item generation

---

docs/reference/security.rst

I am targeting this branch, because it's a docs fix.
Fix a table cell align for the correct display of the table, because currently it looks like this:
Source - https://symfony.com/doc/current/bundles/SonataAdminBundle/reference/security.html#id1

Fix a table cell align

---

src/Admin/BaseFieldDescription.php

I am targeting the 3.x branch, because my changes are made without any BC-break.
```markdown
- Added a condition in the `getFieldGetterKey` in order remove the new warning produced by PHP7.2.
```
As mentioned in this Stack Overflow post (https://stackoverflow.com/a/49752124/2087724) this small PR fixes the new warning produced by the latest release of PHP7.2.
The warning looks like the following: `get_class() expects parameter 1 to be object, null given`
Official php documentation link: http://php.net/manual/en/function.get-class.php
Extract from the documentation:
```
Note: Explicitly passing NULL as the object is no longer allowed as of PHP 7.2.0. The parameter is still optional and calling get_class() without a parameter from inside a class will work, but passing NULL now emits an …
```

Removed new warning produced by PHP7.2 in BaseFieldDescription.php

---

src/Resources/views/CRUD/base_list.html.twig

I am targeting this branch, because it's an improvement.
```markdown
- Added table-hover class to the table
```
On the list, if you want to click the action button, you can not see on which row you want to execute it.
This patch changes the color of the line when you hover over it.

Added table-hover class to the table

---

src/Resources/public/Admin.js
src/Resources/views/CRUD/base_edit_form.html.twig
src/Resources/views/CRUD/base_show.html.twig

If you're on a page that has tabs and you go to a different tab, the address in the URL bar will change, add the _tab tag.
After refreshing the page you will remain in the same tab you opened before reloading the page.
I am targeting this branch, because it is an improvement and will help with easier handling.
```markdown
- Changed ID's and added class name to tabs elements in edit view and show view, so we can control the address.
- Added new JS function in Admin.js, which handle the control of a tabs and change address in URL query string when you change tab.
```
Updating query parameter in URL and remeber opened tab after refresh.

Updating query parameter in URL and remeber opened tab after refresh.

---

docs/index.rst

I am targeting this branch, because it's just a little deal to add a link on the documentation index in an exisiting text.
Just a little PR to add the SonataAdminBundle link on the documentation index page :

[Documentation] Added SonataAdminBundle link

---

docs/reference/child_admin.rst

Refs #5109
- I added yaml configuration
- I renamed everything to `app.admin.....` instead of `sonata.admin......`

updated docs for child admins

---

src/Action/DashboardAction.php
src/Action/SearchAction.php
src/Controller/CoreController.php
src/DependencyInjection/SonataAdminExtension.php
src/Resources/config/actions.xml
src/Resources/config/routing/sonata_admin.xml
tests/Action/DashboardActionTest.php
tests/Action/SearchActionTest.php

```markdown
- `Controller\CoreController` is now deprecated in favor of `Action\{Search,Dasbhoard}Action`
```
Using invokable CaaSes vs one big controller achieves several things:
1. it discourages piling on more actions in controllers with vague names (SRP)
2. it leads to easier to unit test actions and visible deps (DIP)
3. it will allow us to make more services private

Make CoreController actions CaaSes

---

src/Resources/views/standard_layout.html.twig

I am targeting this branch, because it's an improvement.
```markdown
- Added `title` to sidebar toggle
```
On hover the text is shown.

Add title attribute to sidebar toggle

---

src/Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because this is a BC fix.
```markdown
- Fixed choice field mask initial display when field value is empty
```
When a `ChoiceFieldMaskType` is used with required set to true, there is no "empty option" added in the select options. The first option of the select is automatically selected by the browser but the field value is empty. In this case, the show/hide js function is triggered for the current field value, an empty value, and does nothing. Finally, we have the first option selected by the browser but the linked fields are not displayed.
The bug seems to have been introduced by this [commit](https://github.com/sonata-project/SonataAdminBundle/commit/9ba0ddcd15652eb0b5e908402a447a05b269501c) and this PR is adding a condition to use previous behavior when …

Fix display for empty initial value in choice field mask

---

docs/reference/configuration.rst
src/DependencyInjection/Configuration.php

I am targeting this branch, because this guards BC.
```markdown
- Default load order of `assets.javascripts` at `Configuration::getConfigTreeBuilder()`
- ECMAScript error `jquery.js:250 Uncaught Error: cannot call methods on button prior to initialization;` while trying to use `$.fn.button()` (ref: https://github.com/twbs/bootstrap/issues/6094)
```

[bugfix] Prioritize jQuery UI scripts in "assets.javascripts" config in order to avoid initialization issues

---

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Targeting 3.x as it's a bug fix.
```markdown
- Escaped admin code in autocomplete
```
When using classes names as service identifiers, the autocompletion fails because the antislash is escaped in javascript:
```
Admin service "AppControllerAdminEventAdmin" not found in admin pool.
```
```
'admin_code': 'App\Controller\Admin\EventAdmin'
=> admin_code=AppControllerAdminEventAdmin in the URL
```
This fixes it.

Escape admin code in autocomplete

---

src/Admin/AdminHelper.php

I am targeting this branch, because bug.
Closes #5140
```markdown
Worning "Parameter must be an array or an object that implements Countable" for count(null) in php 7.2
```

#5140 fix count(null) for php 7.2+

---

src/Controller/HelperController.php
tests/Controller/HelperControllerTest.php

I am targeting this branch, because I am fixing a bug with wrong method usage for getting object from admin class and it is BC
```markdown
- Fixed issue with `appendFormFieldElementAction` and `retrieveFormFieldElementAction` using ModelManager instead `getObject` admin class method
```
I faced this bug, when i create new item with sonata_type_collection. It's totally ignored my admin getObject with custom object source

Fix HelperController bug: appendFormFieldElementAction and retrieveFormFieldElementAction used wrong object source

---

src/Controller/CRUDController.php

I am targeting this branch, because this should be a backward compatible change. It should be just a performance optimization.
```markdown
- Do not load the pager when performing a batch action without confirmation
```
When performing a batch action and having `$idx` defined, currently sonata still does a query to calculate the pagination information (to be able to set the min/max results per page). 
Later that result gets discarded as the batch query runs on the elements specified by `$idx` or `$allElements` variables.
The query to calculate the total results might be very expensive, slowing down batch actions even if they update a single element via `$idx`. 
In my setup, ~90% of time is spent on calculating the total count of rows in the table and ~5% to do the batch action.

Do not build the pager when not necessary

---

docs/reference/events.rst

This is needed to avoid displaying the lists as blockquotes, as shown in https://symfony.com/doc/3.x/bundles/SonataAdminBundle/reference/events.html

Fixed a minor RST syntax issue

---

src/Controller/CRUDController.php

Reverts sonata-project/SonataAdminBundle#5145
Reverting this as it introduces a major bug. The pager was also responsible for applying the current filters... so in case you filter the results and use "select all" in a batch action, will ignore the filter and apply the batch on the whole dataset... and this is realllly bad! :cry: 
Will work on it trying to create a better implementation

Revert "Do not build the pager when not necessary"

---

src/Menu/Provider/GroupMenuProvider.php
tests/Menu/Provider/GroupMenuProviderTest.php

I am targeting this branch, because it's a fix.
Closes #5128
```markdown
- Menu item security was expected to be checked affirmatively rather than unanimously
```
Menu item security was expected to be checked affirmatively rather than unanimously, fixed it.

Made the menu checker behave affirmatively even if it's globally unanimous

---

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
src/Resources/views/CRUD/Association/edit_many_to_one.html.twig
src/Resources/views/CRUD/Association/edit_one_to_many.html.twig
src/Resources/views/CRUD/Association/edit_one_to_one.html.twig

I am targeting this branch, because these changes continue the earlier ones.
```markdown
- Changing the way of checking the permission
```
Everywhere permissions are check by `hasAccess`, but in this files it was still by `isGranted`.

Changing the way of checking the permission

---

src/Controller/HelperController.php
tests/Controller/HelperControllerTest.php

I am targeting this branch, because this PR fix existing bug.
```markdown
- fixed bug with complex properties in `ModelAutocompleteType`
```
Right now code like 
```php
->add('childEntity', ModelAutocompleteType::class, [
'class'     => Entity::class,
'property'  => 'parent.title',
])
```
doesnt work, because wrong filter names are generated in `$datagrid->values`:
`parent.title instead of `parent__title`. This PR fix this bug.

fixed bug with complex properties in ModelAutocompleteType

---

src/Resources/views/CRUD/list_datetime.html.twig
src/Resources/views/CRUD/list_time.html.twig
src/Resources/views/CRUD/show_datetime.html.twig
src/Resources/views/CRUD/show_time.html.twig
tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch (3.x), because Templating for `show_datetime`, `show_time` and `list_time` doesn't use TimeZone option to display date.
Closes #5156 
```markdown
- Enable TimeZone for datetime and time templating
```
As mentionned in issue #5156, the timezone is only set on `list_datetime` template. However the same behavior is expected for `list_time`, `show_datetime` and `show_time`. That's the goal of this PR

Fix timezone usage for datetime/time list and show template

---

src/Admin/Pool.php
tests/Admin/PoolTest.php

I am targeting this branch, because is improve.
ref 56b0201c63c50e61e6bb002c78fdd1991924d347 
```markdown
- Added `levenshtein` to improve an error message. 
```
Now the most-matched phrase is displayed. In addition, a list of all admin services is also displayed.

Improve hint to exception message

---

src/Admin/AbstractAdmin.php
tests/Admin/AdminTest.php

I am targeting this branch, because it's a BC improvement.
```markdown
- Admin uniqids are now more consistent
```
Currently, a new admin uniqid will be generated on each page load. With this PR, it will stay the same as it's now generated from the "base code route", which includes the parents codes separated by pipes (ex: `parent.admin.code|child.admin.code`). The crc32 function is used to generate a **short** hash.
I need this because I'm trying to add the [Garlicjs](http://garlicjs.org/) lib to the admin (allow form data persistence on page change), but as fields name contain the admin uniqid, they always change, so it can't work.

Use consistent admin uniqids

---

src/Resources/translations/SonataAdminBundle.nl.xliff

I noticed that the translation of edit buttons where incorrect, because the translation for the `link_edit` was missing in the Dutch language file. This PR adds the correct translation.

Added Dutch translation for link_edit

---

UPGRADE-3.x.md
src/Action/AppendFormFieldElementAction.php
src/Action/GetShortObjectDescriptionAction.php
src/Action/RetrieveAutocompleteItemsAction.php
src/Action/RetrieveFormFieldElementAction.php
src/Action/SetObjectFieldValueAction.php
src/Controller/HelperController.php
src/Resources/config/actions.xml
src/Resources/config/core.xml
src/Resources/config/routing/sonata_admin.xml
tests/Action/AppendFormFieldElementActionTest.php
tests/Action/GetShortObjectDescriptionActionTest.php
tests/Action/RetrieveAutocompleteItemsActionTest.php
tests/Action/RetrieveFormFieldElementActionTest.php
tests/Action/SetObjectFieldValueActionTest.php
tests/Controller/HelperControllerTest.php

```markdown
- `SonataAdminBundle\Controller\HelperController` is now deprecated in favor of actions
```

Split the helper controller into invokable CaSes

---

src/Resources/views/CRUD/base_edit_form.html.twig
src/Resources/views/CRUD/base_show.html.twig

Fixes #5188 
```markdown
- Fixed tab id when the Admin Id contains backslashes
```
If you define your Admin classes with the FQCN, in the edit/show page tab id is something like `tab_App\YourBundle\Admin\PostAdmin_1` and apparently [backslashes do not work properly with jQuery](https://stackoverflow.com/questions/5825948/jquery-selectors-and-backslashes) (you have to escape them). So tabs don't work and it also fails when [it tries to change the hash of the URL](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/public/Admin.js#L709).

Fix tab id when it contains backslash

---

src/Controller/CRUDController.php
tests/Controller/CRUDControllerTest.php

From the `CRUDController:editAction()` add an error message before rendering the html page if no field is defined on the  `configureFormFields()` function
```markdown
- Added exception message if no field is defined on the  `configureFormFields()` function
```

[CRUD:Edit] Add exception message

---

src/Controller/CRUDController.php
tests/Controller/CRUDControllerTest.php

I am targeting this branch, because this is a fix.
```markdown
- Checking the wrong method for form fields
```

Fix check of form fields because it didn't check correctly

---

src/Resources/config/twig.xml
src/Resources/views/Core/dashboard.html.twig
src/Twig/Extension/SonataAdminExtension.php
tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
tests/Twig/Extension/SonataAdminExtensionTest.php

I am targeting this branch, because it's a fix.
Closes #5129
```markdown
- An affirmative grant checker for Twig
- Dashboard block security was expected to be checked affirmatively rather than unanimously
```
Dashboard block security was expected to be checked affirmatively rather than unanimously, fixed it by adding a new checker function to Twig.

Added an affirmative twig grant checker

---

src/Datagrid/SimplePager.php
tests/Datagrid/SimplePagerTest.php

I am targeting this branch, because it's a patch.
```markdown
- Fixed issue with `getNbResults` return negative result, if there where no results
```
Using `SimplePager`, if there are no items `getNbResults` is returning negative number because `init` was setting `setLastPage` to `0` (which is not right, because there can't be 0-page, it's always first page) and when `getNbResults` was called following code is executed `$n = ceil(($this->getLastPage() - 1) * $this->getMaxPerPage());` and we are getting -32 (if 32 is per page)

fixing negative result getNbResults, if there are not results

---

src/Resources/translations/SonataAdminBundle.zh_HK.xliff

This is a second attempt to add zh_HK (Traditional Chinese) translation file to the codebase. (First attempt: https://github.com/sonata-project/SonataAdminBundle/pull/5210). Sorry for the noise.
I am targeting this branch, because it's backwards compatible.
```markdown
- Translation file for zh_HK (Traditional Chinese).
```
This adds a Traditional Chinese translation file to the repo.

Add translation for zh_HK (Traditional Chinese)

---

UPGRADE-4.0.md
src/Datagrid/SimplePager.php
tests/Datagrid/SimplePagerTest.php

Closes #5137
Related to #5138
```markdown
- Fixed inconsistent return-type of `SimplePager::getResults`, now it is always returning `array`
```

#5137 handle ArrayCollection from PHPCR in SimplePager
