src/Admin/AbstractAdmin.php
I am targeting this branch, because it's a bug fix.
```markdown
- Fixed negative admin unique id on 32 bits platforms
```
Replaced crc32 with the 10 first characters of a md5 checksum of the `getBaseCodeRoute` method result (no need for more complex hash in this case).
Should fix https://github.com/sonata-project/SonataAdminBundle/issues/5215
=> Fix negative admin unique id on 32 bits platforms

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
(Following #5195 )
From the `CRUDController` throw runtime exception before rendering the html page if no field is defined on the configureFormFields()  or `configureShowFields()` function
```markdown
- Added `RuntimeException` message for `Create` and `Show` actions from `CRUDController`
```
=> Add runtime exception

docs/cookbook/recipe_select2.rst, docs/reference/action_create_edit.rst, docs/reference/action_list.rst, docs/reference/action_show.rst, docs/reference/batch_actions.rst, docs/reference/extensions.rst, docs/reference/field_types.rst, docs/reference/form_help_message.rst, docs/reference/routing.rst, docs/reference/translation.rst
I am targeting this branch, because these changes are affecting 3.x docs.
Fixed methods visibility (`public` => `protected`, mainly overriding `AbstractAdmin::configure*()`) and `TYPE_EQUAL` filter constant at docs.
=> [Docs] Fixed method visibility and `TYPE_EQUAL` filter constant at docs

src/Admin/Pool.php, tests/Admin/PoolTest.php, tests/Controller/CRUDControllerTest.php
```markdown
- `Pool::getInstance` will always return a valid admin instance
```
According to the PHPDoc, the method will always return an `AdminInterface` (or null). The method never returned null, but a ContainerException if the service did not exist. Now the method checks if this is really an `AdminInterface`.
=> Pool::getInstance checks for valid admin

src/Twig/Extension/SonataAdminExtension.php, tests/Twig/Extension/SonataAdminExtensionTest.php
I am targeting this branch, because this change is backwards compatible.
```markdown
- Added support for moment.js French language
```
When loading moment.js localization file in https://github.com/sonata-project/SonataAdminBundle/blob/8fe5cad711ef707668fb4f787bc151e296efbfd3/src/Resources/views/standard_layout.html.twig#L69 when using french language, It attempts to load `fr-fr.js` file which does not exists in moment.js 2.8 and above. 
This PR fixes it by using the same method than `nl` and `es` languages ie. stripping `-fr` from the locale.
=> Moment fr locale

docs/getting_started/creating_an_admin.rst
Changing "how it looks like" to "what it looks like" in documentation.
I am targeting this branch, because it's the version live on the website.
Closes no issues.
Minor corrections on use of English in docs. Found on:
https://symfony.com/doc/master/bundles/SonataAdminBundle/getting_started/creating_an_admin.html
=> Minor language mistakes in creating_an_admin.rst

src/Resources/public/Admin.js
I am targeting this branch, because this change is backward compatible.
```markdown
- Added `Admin` object reference to javascript `window` object
```
This PR is exposing the `Admin` object to other scripts by adding its reference into the `window` object. In classical use, the `Admin` object can be easily accessed because it is considered as a global. However, this is not the case when this script is used with modules, which are introducing scopes. This change allows the Admin object to be accessed from javascript modules with `window.Admin`.
=> Expose Admin javascript object into window

src/Maker/AdminMaker.php, src/SonataAdminBundle.php, tests/SonataAdminBundleTest.php
Rework of #5252 (thank you @volodymyr-nakvasiuk)
```markdown
- `make:sonata:admin` not working
```
I changed `RuntimeException` to `InvalidArgumentException` which could be considered as a BC break, but imo its better to use it here.
I get this error when using `if (!\count($this->availableManagers))`:
//cc @indiancomet
=> fix make:sonata:admin command

docs/reference/action_list.rst
I am targeting this branch, because the target linked to the master branch.
```markdown
- Fixed bad link target in doc.
```
=> Fix bad link target in doc

src/Resources/config/routing/sonata_admin.xml
I am targeting this branch, because it's a minor fix.
References #5251.
```markdown
- FrameworkBundle redirect action notation to the current syntax
```
Fixes deprecation notice about FrameworkBundle redirect.
=> Fix deprecation notice about FrameworkBundle redirect

src/Resources/views/CRUD/base_list.html.twig
The `/` is missing in `</li>`
```markdown
- invalid html in the export links list
```
=> Close <li>

src/Resources/translations/SonataAdminBundle.pl.xliff
I am targeting this branch, because it's backwards compatible.
```markdown
- Added missing polish translation for `link_edit`
```
=> Add missing polish translation

src/Route/RouteCollection.php, tests/Route/RouteCollectionTest.php
I am targeting this branch, because it fixes a BC break when using Bundle notation with Subfolder.
```markdown
- Fixed BC break when baseControllerName uses bundle notation with subfolder
```
Related to #5228
=> Fix BC break when baseControllerName uses bundle notation with subfolder

src/Resources/views/CRUD/base_list.html.twig
I am targeting this branch, because it fixes the listMode view when a sorting is applied.
Closes #5150 
```markdown
- the list mode view is now preserved when a sorting is applied
```
=> Fix the listMode view when sorting applied

docs/reference/console.rst
replace wrong command example for "make:sonata:admin" from "$ bin/console sonata:admin:generate App/Entity/Foo" to "$ bin/console make:sonata:admin App/Entity/Foo"
=> Edit wrong example for  command make:sonata:admin

src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
I am targeting this branch, because it's a bugfix.
Closes #5306
```markdown
- Fixed `AdminType` tabs ids when used in collections 
```
Embedded tabs now get correct unique ids.
Examples (see #5306) : 
**Before** : `#s652ee50cb4_1_1`
**After** : `#s20ab319f7d_streets_0_buildings_1_1`
=> Fix admin type collection tabs ids

src/Resources/translations/SonataAdminBundle.es.xliff
I am targeting this branch, because it offer backward compatibility, add a translation will not break the compatibility.
Closes #5315
```markdown
- New missing translation
```
I've add the translation of the key 'toggle_navigation' for the spanish language
=> Added missing translation (#5315)

UPGRADE-3.x.md, src/Datagrid/ListMapper.php
I am targeting this branch, because it's related to the current version and add the trigger for the deprecated option.
Closes #4205
```markdown
- `header_style` option
```
=> deprecate header_style

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
I am targeting this branch, because this is a backwards-compatible bug fix
```markdown
- Error on some fields in collection table when `strict_variables` mode is enabled
```
When `strict_variables` mode is enabled, trying to access non-existing array key from a template results in exception.
```
{% if nested_field.vars['required'] %}
class="required"
{% endif %}
```
`nested_field.vars['required']` and `nested_field.vars.errors` can be missing if collection form contains some a not mapped field with field type defined.
FooAdmin
```
protected function configureFormFields(FormMapper $formMapper): void
{
$formMapper
->add(
'bars',
CollectionType::class,
['by_reference' => false],
['edit' => 'inline', 'inline' => 'table']
)
->end();
}
```
BarAdmin
```
protected function …
```
=> Fixed trying to access non-existing properties in strict_variables mode

src/Form/Extension/ChoiceTypeExtension.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php, tests/Form/Extension/ChoiceTypeExtensionTest.php, tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
It seems that this method is now required.
See BC-break report: https://github.com/symfony/symfony/issues/29426
Refs #5322 
The bug is in a class that is probably only used in tests, so I believe this is pedantic.
=> Implement getExtendedTypes

src/Admin/AdminInterface.php
The reflection will wrongly assume this is the phpdoc for the following
method, and symfony/debug will trigger deprecations about parameter
mismatches.
```markdown
- incorrect deprecation message about `AdminInterface::setSecurityHandler`
```
=> Move commented method at the bottom of the class

src/Form/Type/ModelAutocompleteType.php, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
I am targeting this branch, because this is the main branch.
Closes #4802 
```markdown
Newly created media is not autoselected
```
Automatically add new media to the autocomplete field after create
Thanks to @lushc
My code is [its code](https://gist.github.com/npotier/a7b2b34f0daae7205f86#gistcomment-1754374) with some adaptations, especially on the part concerning the label of the form field which was hard coded.
I need the property option to get this data. I can't find it in the FormView object. 
Maybe someone has a trick to get this data from the FormView object.
=> Automatically add new media to the autocomplete field after create

docs/reference/batch_actions.rst, src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Add ability to specify batch action confirmation template per action thus making it easier to support multiple batch actions with `ask_confirmation` and custom templates per admin.
I am targeting this branch, because it's backwards compatible feature.
Sort of addresses some simple use-cases for #4105
```markdown
- Added `template` option to admin `batchActions`
```
=> Add ability to specify batch action confirmation template per action

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
I am targeting this branch, because it is affected by this bugfix.
Closes #5342 
```markdown
Fix crash on form pages that use `ModelAutocompleteType` and does not have a create route
```
=> Check "create" route existence in ModelAutocompleteType form field

src/Admin/AdminInterface.php, src/Controller/CRUDController.php
The assert comparing $form against the Form class demands a Form instance. I use a decorator class implementing the FormInterface. This causes the assert to fail unintentionally, as a FormInterface will be fine.
Because of code coverage issues, I simply removed the assert.
I am targeting this branch, because this is the oldest branch affected by this issue.
```markdown
Removed the assert against Form
=> Remove assert against Form in CRUDController

docs/cookbook/recipe_custom_action.rst, docs/cookbook/recipe_custom_view.rst, docs/cookbook/recipe_improve_performance_large_datasets.rst, docs/cookbook/recipe_persisting_filters.rst, docs/cookbook/recipe_sortable_listing.rst, docs/cookbook/recipe_workflow_integration.rst, docs/getting_started/the_form_view.rst, docs/reference/child_admin.rst, docs/reference/console.rst, docs/reference/form_types.rst, docs/reference/routing.rst, docs/reference/security.rst
We should not promote `admin.yaml` anymore and use/promote `config/services.yaml`
=> [Docs] fix config file paths, use .yaml instead of .yml and stop talking about admin.yml

src/Maker/AdminMaker.php
Fix for make:sonata:admin does not allow to change the AdminClass #5379 
Closes #5379 
```markdown
- Default values not getting overridden in `make:sonata:admin`
```
=> bug fix make:sonata:admin to allow overriding defaults

docs/reference/search.rst, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, src/Resources/config/core.xml, src/Search/SearchHandler.php, tests/Search/SearchHandlerTest.php
Assume you have an Entity Supplier named **Brandid**, you need to search for `Brandid` to find the result. Searching for `brandid` will not bring up results....
With this PR you can search for `Brandid` and `brandid` if `case_sensitive` is set to `false` and get the result.
```markdown
- Added possibility to search globally case-sensitive/case-insensitive
```
=> added option for global search: case_sensitive

src/Resources/skeleton/Admin.php.twig, src/Resources/skeleton/Admin.tpl.php, src/Resources/skeleton/AdminController.php.twig, src/Resources/skeleton/AdminController.tpl.php, tests/Fixtures/Admin/ModelAdmin.php, tests/Fixtures/Controller/ModelAdminController.php
Now that we dropped php 7, we should generate classes that look like what we recommend in our docs.
```markdown
- php 7-specific type hints in generated code
- strict_types declaration in generated code
```
=> Generate code that is more modern

src/Resources/translations/SonataAdminBundle.nl.xliff
Added missing Dutch translation for `toggle_navigation` and `flash_batch_no_elements_processed`.
I am targeting this branch, because it is BC.
```markdown
- Added 2 missing Dutch translations
```
=> Add Dutch translations for toggle_navigation and flash_batch_no_elements_processed

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminInterface.php
A class that extends one of ours, or implements one of our interface
but still uses legacy types in the signature of the methods it overrides
or implements will cause a crash at compile time: type hints in
signature do not cause autoloading, and thus the class alias will not be
created. To fix this, we trigger the autoload of the new type, so that
no deprecation is thrown when it in turns autoloads the old type.
That issue was reported here:
https://github.com/sonata-project/SonataAdminBundle/pull/5418#issuecomment-454128691
I guess I will need to update [my blog post](https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf).
```markdown
- Crash about incompatible signatures involving `ErrorElement`
```
@dmaicher please review
=> Trigger autoload to ensure BC

src/Admin/AbstractAdmin.php
We documented this as a possibility. For now, let us support it, and let
us decide later if we ask people to move away from it or if we should
embrace it.
Closes #5421 
```markdown
- crash when using `null` as an admin class name
```
=> Unofficially support null

src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
Check if `isImageAvailable` is defined in `list_outer_rows_mosaic.html.twig`.
I am targeting this branch, because it's bux fix.
Closes #[1525](https://github.com/sonata-project/SonataMediaBundle/issues/1525) (media bundle)
```markdown
- Crash when using `Metadata` class from block bundle
```
=> Check if isImageAvailable is defined

src/Admin/AdminHelper.php
I am targeting this branch, because bug fixes with BC.
Closes #1304 #1628
```markdown
- `sonata_type_collection` fields no longer deletes row when adding a new row
```
When we add new row the submit action is executed with PreSubmit and PostSubmit events, so the `Sonata\CoreBundle\Form\EventListener` is executed and remove rows where delete is checked.
To fix it, i save the 'delete' marked rows name in array, and unset the `_delete` fields in the request, before handleRequest and submit action, and backup the `_delete` fields value after setting collection
=> Fix sonata_type_collection fields delete row on new row add

docs/reference/security.rst
I am targeting this branch, because table with roles and service ids rendering not properly.
=> Fix Security Doc typo

docs/reference/routing.rst
I am targeting this branch, because according to https://twig.symfony.com/doc/2.x/filters/merge.html `merge` has typo, should be 
```twig
...|merge({'page': 1})
``` 
not 
```twig
...|merge('page': 1)
```
=> Generate routing in docs typo params to array

src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig
I am targeting this branch, because this is a backwards-compatible regression fix.
This is an additional fix for https://github.com/sonata-project/SonataMediaBundle/issues/1525. That error has been fixed in https://github.com/sonata-project/SonataAdminBundle/pull/5435
However solution is flawed. Since MediaAdmin creates `Sonata\BlockBundle\Meta\Metadata`, which doesn't have `isImageAvailable()` method, new condition always ends up being `false`. Therefore in mosaic view we always get a fallback image instead of real image thumbnail.
Closes https://github.com/sonata-project/SonataMediaBundle/issues/1525
```markdown
- Regression bug which causes SonataMediaBundle's Media list to show fallback image in mosaic view instead of real image preview
```
=> Fix displaying images in media list mosaic view

src/Admin/BaseFieldDescription.php
Call the method directly instead of invoking `__call()` at `BaseFieldDescription::getFieldValue()`
I am targeting this branch, because this is a minor improvement without any important impact on oldest branches.
See https://github.com/sonata-project/SonataAdminBundle/pull/5459#pullrequestreview-198791912.
=> Call the method directly instead of invoking `__call()` at `BaseFieldDescription::getFieldValue()`

docs/getting_started/creating_an_admin.rst
The link to the next chapter was missing at the end of the page so I added it
=> Added a link to the next chapter

src/Resources/views/Core/dashboard.html.twig
I am targeting this branch, because this is a minor improvement.
```markdown
- Changed `dashboard.html.twig` in order to avoid unnecessary iterations on block loops.
```
=> [Dashboard] Don't iterate over blocks if wanted condition is already reached

docs/cookbook/recipe_auto_configure_admin_classes.rst, docs/cookbook/recipe_workflow_integration.rst, docs/getting_started/the_form_view.rst
to be consistent throughout the docs
=> add blank lines after file paths in code examples

src/Resources/views/Form/form_admin_fields.html.twig
The `default` Twig filter considers defined `false` values as "undefined" because `false` is an `empty` value. That means boolean values fallbacks cannot be correctly handled with this filter.
That currenly prevents me from not displaying the label when I extend this block and purposely do a `{% set show_label = false %}` in my extension (`false|default(true) ==> true`)
I am targeting this branch, because it is a patch.
```markdown
- Fixed the `show_label` check in the `form_row` block.
=> fix(form-theme): form_row show_label check

src/Resources/views/Core/add_block.html.twig
I am targeting this branch, because  this feature is backwards compatible.
```markdown
- wrong HTML generated (top nav menu), if the user does not have rights for first or last module
```
Fixed top menu rendering. When user does not have rights for first or last admin module, wrong HTML was generated whitch breaks top menu and user block
=> fixed display top nav menu when user does not have rights for first or last module

src/Resources/views/CRUD/display_date.html.twig, src/Resources/views/CRUD/display_datetime.html.twig, src/Resources/views/CRUD/display_time.html.twig, src/Resources/views/CRUD/list_date.html.twig, src/Resources/views/CRUD/list_datetime.html.twig, src/Resources/views/CRUD/list_time.html.twig, src/Resources/views/CRUD/show_date.html.twig, src/Resources/views/CRUD/show_datetime.html.twig, src/Resources/views/CRUD/show_time.html.twig, tests/Twig/Extension/SonataAdminExtensionTest.php
Use `<time>` html tag when displaying fields of type date and datetime. This allows to print the UTC dates using the "datetime" and "title" attributes.
```markdown
- Changed the rendering for date, datetime and time properties in order to use `<time>` tags, which print the dates in UTC using `datetime` and `title` attributes, allowing to view the UTC date with the default browser tooltip.
```
Example of UTC date 2017-04-06T00:11:38+00:00 printed with `America/Argentina/Buenos_Aires` (UTC -3) timezone:
```
<time datetime="2017-04-06T00:11:38+00:00" title="2017-04-06T00:11:38+00:00">
05/04/2017 21:11:38
</time>
```
=> [WIP] Use "<time>" html tag when displaying fields of type date and datetime

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
Variables `_page` and `_per_page` get from request was a string. It was a problem with check it in `determinedPerPageValue`.
I am targeting this branch, because it is a patch.
Closes #5484
```markdown
- type int for _page and _per_page from request 
```
=> set type int to _page and _per_page from request

src/Admin/AbstractAdmin.php
I am targeting this branch, because it fixes the wrong display of batch checkbox field when list page is loaded with Ajax. As you can see in https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/base_list.html.twig#L133 we just ignore the display of the batch droplist.
```markdown
- Fixed display of batch checkbox when list page is loaded with Ajax
```
=> Fix batch checkbox display when list page is loaded through Ajax

docs/cookbook/recipe_delete_field_group.rst, docs/cookbook/recipe_icheck.rst, docs/cookbook/recipe_improve_performance_large_datasets.rst, docs/cookbook/recipe_persisting_filters.rst, docs/reference/advanced_configuration.rst, docs/reference/architecture.rst, docs/reference/batch_actions.rst, docs/reference/dashboard.rst, docs/reference/extensions.rst, docs/reference/field_types.rst, docs/reference/form_types.rst, docs/reference/routing.rst, docs/reference/search.rst, docs/reference/templates.rst
- ensure order in `.. configuration block::`: `yaml`, `xml`, `php`
- long lines
- American English ([Symfony-Docs are using it too](https://github.com/symfony/symfony-docs/pull/11196))
```diff
- behaviour
+ behavior
```
- no explicit use of `.. code-block:: php`, use `::` instead
These were detected with my tool and will be checked continously, if we can use GithubActions 👍
=> different fixes to be consistent

src/Controller/CRUDController.php, src/Resources/public/Admin.js
There are [some issues](https://github.com/sonata-project/SonataAdminBundle/pull/5314#issuecomment-477323631) after https://github.com/sonata-project/SonataAdminBundle/pull/5314.
I am targeting this branch, because is BC.
```markdown
- Fixed redirecting to a blank tab after saving an object
- Fixed modifying form values changing tabs
```
=> Fix redirect to tab when there is no tab explicitly selected

docs/reference/security.rst
Browsing through the documentation I got confused by the implementation of `sonata.admin.security.handler.role` because in the examples the FQDN are not escaped, and thus displaying ``AppAdminFooAdmin``  instead of ``App\Admin\FooAdmin``. Also I think the word `AppBundle` has been renamed to `App` in some but not all instances (causing the example to not work).
I am targetting this branch, because this documentation fix should not have any BC-breaks. 
No issues have been created for these documentation fixes.
=> Documentation fixes, correct FQDN and FQDN escaping

src/Controller/CRUDController.php
Since we are now using strict types, this minor fix will prevent the htmlspecialchars function from failing when the 1st parameter is a null value (the function assumes it to be a string, but this is not currently enforced).
I am targeting this branch, because issue #5513 exists in it, and this is the most recent branch.
Closes #5513 
```markdown
- Allow htmlspecialchars function within CRUDController to handle null valued parameters
```
=> Cast 1st htmlspecialchars parameter as string #5513

src/Action/SearchAction.php
Use `getSearchResultLink` instead of `generateObjectUrl('edit')` to prevent generating invalid URLs (when editing isn't available).
I am targeting this branch, because it is the most up to date and still features this bug.
```markdown
Changed the way the search action generates links to the results. It used to consider every item editable, but would throw an error if it wasn't the case. It now uses the `getSearchResultLink` that choses the best way to link to a search result; eg. `edit` if available, or `show`.
```
=> Fix links to un-editable results

src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_show.html.twig
I am targeting this branch, because i find the bootstrap js tab toggle will not work  when click add button more than 2 times.
```markdown
- Fix bootstrap tab toggle not work when click add button more than 2 times.
```
fix bootstrap js tab toggle not work when click add button more than 2 times
=> fix bootstrap js tab toggle not work when click add button more than 2 times

src/Model/ModelManagerInterface.php
Following from this issue https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/313, from the build of scrutinizer I was able to detect that namespace here is also wrong 
I am targeting this branch because this should not break anything.
```markdown
- Use proper namespace for Sonata\Exporter\Source\SourceIteratorInterface
```
=> Fix namespace of SourceIteratorInterface

src/Twig/Extension/SonataAdminExtension.php, tests/Twig/Extension/SonataAdminExtensionTest.php
As suggested in the code (see @TODO) the correct fallback for `de_DE` is missing.
After updating an old sonata based app, the moment locale could not be loaded correctly. 
It was looking for `de-de.js` which is not shipped by moment.js
I am targeting this branch, because it seems an patchable bug.
```markdown
- Add canonicalization fallback for missing moment.js de_DE locale
```
Edit: Wording on changelog message
=> Add moment locale fallback for de_DE

src/Resources/public/Admin.js
I am targeting this branch, because this is the main branch...
```markdown
- Fix in edit page, the footer with actions buttons will be stuck for Windows users and the last field will no longer be hidden
```
The class `stuck` is not removed on Windows (I tried with Chrome) when the page is at the end. The div `sonata-ba-form-actions` hides the last field. 
The cause for this problem is Windows` jQuery(window).scrollTop() + jQuery(window).height()` does not return an integer but a float...
=> Add round for scrollTop + height for Windows

src/Resources/views/CRUD/base_edit_form.html.twig
With #5260 The Tabs in the Edit Form doesn't work anymore because the controls and the ids are not equal any more
I am targeting this branch, because the Error was added into the 3.x branch with 3.48.2 release
```markdown
- Fixed Tabs in Edit Form
```
=> Fix tab name in base_edit_form

src/Resources/views/CRUD/history_revision_timestamp.html.twig
Use `<time>` html tag when displaying the audit revision timestamp. This allows to print the UTC dates using the "datetime" and "title" attributes. This change is a follow up of #5530.
```markdown
- Changed the rendering for the audit revision timestamp in order to use `<time>` tags, which print the dates in UTC using `datetime` and `title` attributes, allowing to view the UTC date with the default browser tooltip.
```
Example of UTC date 2017-04-06T00:11:38+00:00 printed with `America/Argentina/Buenos_Aires` (UTC -3) timezone:
```
<time datetime="2017-04-06T00:11:38+00:00" title="2017-04-06T00:11:38+00:00">
05/04/2017 21:11:38
</time>
```
=> Leverage `display_datetime.html.twig` from `history_revision_timestamp.html.twig`

src/Resources/views/CRUD/base_edit_form.html.twig
I am targeting this branch, because Twig 2.11 causes: "Template "@SonataAdmin/CRUD/base_edit_form.html.twig" cannot be used as a trait." error 
Closes #5564
```markdown
- Import the macros in the sonata_tab_content
```
=> [#5564] Fix "cannot be used as a trait" in twig 2.11

src/Resources/views/CRUD/base_edit_form.html.twig
"Template "@SonataAdmin/CRUD/base_edit_form.html.twig" cannot be used as a trait." error with Twig v2.11 has not been fixed by 3.49.0 release. This PR fixes that 🚀 
The solution proposed by @fabpot was to **move** this line to `sonata_tab_content` block.
Closes #5564
#5566
=> Fix "cannot be used as a trait" in twig 2.11

src/Admin/Pool.php, tests/Admin/PoolTest.php
I am targeting this branch, because these changes are fully BC.
```markdown
- Deprecated passing invalid admin codes for `Pool::getAdminByAdminCode()`
```
**TODO**:
https://github.com/sonata-project/SonataAdminBundle/blob/02b2f5176ce8b47b214b19067f49a2002c9573ad/src/Admin/Pool.php#L300
=> [Pool] Minor improvement at `Pool::getAdminByAdminCode()`

docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Use "auto" as password encoder instead of "bcrypt".
Using "bcrypt" as algorithm is deprecated since "symfony/security-bundle:4.3". See https://github.com/symfony/symfony/blob/v4.3.0/UPGRADE-4.3.md#securitybundle.
=> [Doc] Use "auto" as password encoder instead of "bcrypt"

src/Resources/views/CRUD/base_edit.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig
Don't truncate subjects to 15 characters at navbar.
```markdown
- Subject is now fully displayed at navbar. Before, it was using the same title as the `<title>` tag, which is truncated to 15 characters.
```
**BEFORE**:
**AFTER**:
=> Don't truncate subjects to 15 characters at navbar

composer.json, src/Resources/views/Block/block_admin_list.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig, src/Resources/views/CRUD/action_buttons.html.twig, src/Resources/views/CRUD/base_acl_macro.html.twig, src/Resources/views/CRUD/base_edit_form_macro.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/base_show_field.html.twig, src/Resources/views/CRUD/display_boolean.html.twig, src/Resources/views/CRUD/display_date.html.twig, src/Resources/views/CRUD/display_datetime.html.twig, src/Resources/views/CRUD/display_time.html.twig, src/Resources/views/CRUD/list_boolean.html.twig, src/Resources/views/CRUD/list_choice.html.twig, src/Resources/views/CRUD/list_url.html.twig, src/Resources/views/CRUD/show_choice.html.twig, src/Resources/views/CRUD/show_url.html.twig, src/Resources/views/CRUD/tree.html.twig, src/Resources/views/Core/add_block.html.twig, src/Resources/views/Core/search.html.twig, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig, src/Resources/views/Form/filter_admin_fields.html.twig, src/Resources/views/Form/form_admin_fields.html.twig, src/Resources/views/Form/silex_form_div_layout.html.twig, src/Resources/views/Menu/sonata_menu.html.twig, src/Resources/views/standard_layout.html.twig
Bump "twig/twig" to "^2.9" in order to replace usages of deprecated features.
I am targeting this branch, because the changes are considered BC.
Closes #5573
```markdown
- Bumped "twig/twig" dependency to "^2.9";
- Changed usages of `{% spaceless %}` tag, which is deprecated as of Twig 1.38 with `{% apply spaceless %}` filter;
- Changed usages of `{% for .. if .. %}`, which is deprecated as of Twig 2.10 with `filter` filter'.
```
**To Do**:
=> Bump "twig/twig" to "^2.9" in order to replace usages of deprecated features

docs/reference/architecture.rst, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Form/FormMapper.php, src/Show/ShowMapper.php, tests/Datagrid/DatagridMapperTest.php, tests/Datagrid/ListMapperTest.php, tests/Form/FormMapperTest.php, tests/Show/ShowMapperTest.php
Restrict mappers from configured role
I am targeting this branch, because these changes are fully BC.
Closes #5584.
```markdown
- Added "role" option for methods `ListMapper::add()`, `DatagridMapper::add()`, `ShowMapper::add()` and `FormMapper::add()`; in order to restrict the content rendering based on the provided role.
```
=> Restrict mappers from configured role

src/Resources/views/CRUD/base_edit.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/standard_layout.html.twig
Truncate navbar titles at 100 characters (follow up of #5593).
I am targeting this branch, because these changes are fully BC.
```markdown
- Truncate long titles at 100 characters at breadcrumb and navbar.
```
**BEFORE**:
**AFTER**:
=> Truncate navbar title at 100 characters

src/Resources/config/core.xml, tests/DependencyInjection/SonataAdminExtensionTest.php
I am targeting this branch, because there is no BC, I add alias for autowire compatibility.
Following PR #5039
```markdown
- Fixed deprecation notice when core services are injected in service through autowiring
```
=> Add alias in core.xml service definition

src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_edit_form_macro.html.twig
Do not escape HTML in edit form group descriptions.
I am targeting this branch, because there is no BC-break.
Closes #4901
Closes #5582
```markdown
- Edit form field group descriptions may again contain HTML.
```
=> Do not escape edit form group description HTML

src/Datagrid/ListMapper.php, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/base_list_flat_field.html.twig, tests/Datagrid/ListMapperTest.php
Ensure boolean values for "identifier" option passed to `ListMapper::add()`
Closes #4554.
```markdown
- Values to passed with the "identifier" option for `ListMapper::add()` are cast to boolean before using them to infer if the field must be used as identifier or not.
- Passing non boolean values to "identifier" option for `ListMapper::add()`.
```
=> Ensure boolean values for "identifier" option passed to `ListMapper::add()`

src/Admin/Pool.php, src/Datagrid/ListMapper.php, tests/Admin/PoolTest.php, tests/Datagrid/ListMapperTest.php
Resolve some "NEXT_MAJOR" comments from 3.x
I am targeting this branch, because these changes break BC.
Related to #5601.
```markdown
- Possibility to pass a non boolean value to "identifier" option for `ListMapper::add()`;
- Possibility to pass an invalid admin service as part of argument 1 for `Pool::getAdminByAdminCode()`.
```
=> Resolve some "NEXT_MAJOR" comments from 3.x

src/Admin/Pool.php, src/Block/AdminSearchBlockService.php, tests/Admin/PoolTest.php, tests/Block/AdminSearchBlockServiceTest.php
Deprecate some invalid arguments at `Pool::getAdminByAdminCode()`
I am targeting this branch, because these changes are fully BC.
Closes #5538.
```markdown
- The default value for "admin_code" setting  at `AdminSearchBlockService`.
- Passing a non string value as argument 1 to `Pool::getAdminByAdminCode()`;
- Passing a non valid admin hierarchy as argument 1 to `Pool::getAdminByAdminCode()`.
```
=> Deprecate some invalid arguments at `Pool::getAdminByAdminCode()`

src/Admin/AdminHelper.php, tests/Admin/AdminHelperTest.php, tests/Fixtures/Entity/Foo.php
Closes #5483 Hotfix
```markdown
-  Crash when clicking "add" on a collection
```
=> Hotfix of "Child _delete does not exist." error

src/Resources/public/css/layout.css
Adding some space between column header label and column header sorting icon to improve readability.
```markdown
- The visual aspect at column headers with sorting icons, in order to add some extra spacing between the column's title and its sorting icon.
```
**Before**: 
**After**:
=> Adding some space betwen column header label and column header sorting icon

tests/Admin/PoolTest.php
Fix wrong mocked return value for `Admin::getChild()` at `PoolTest`.
I am targeting this branch, because this change doesn't affect BC.
=> Fix wrong mocked return value for `Admin::getChild()` at `PoolTest`

docs/reference/templates.rst
I am targeting this branch, because it's just a documentation fix.
Closes #5577
=> Fix and update doc about template in order to not use the Twig namespaced syntax

docs/getting_started/creating_an_admin.rst
Method names will better reflect the reference of code instead of relying on line numbers which may shift if the code blocks change around.
Seen here: https://symfony.com/doc/3.x/bundles/SonataAdminBundle/getting_started/creating_an_admin.html
Replaces #5625
=> [docs] Fix line numbers describing CategoryAdmin class

composer.json
Update constraint for "twig/twig" to ^2.10.
See https://github.com/sonata-project/SonataAdminBundle/pull/5576#issuecomment-509216140.
```markdown
- Possibility to resolve Twig dependency to versions that don't support arrow functions on Twig filters.
```
=> Update constraint for "twig/twig" to ^2.10

src/Command/CreateClassCacheCommand.php, src/Command/ExplainAdminCommand.php, src/Command/GenerateAdminCommand.php, src/Command/GenerateObjectAclCommand.php, src/Command/ListAdminCommand.php, src/Command/SetupAclCommand.php
fix #5633. Add setName for all Commands in the bundle.
Closes #5633
```markdown
- Call setName method in configure part of Command, for backward compatibility wiht sf 2.8.x 
```
=> #5633 fix using Commands for symfony 2.8.x versions

src/Resources/views/CRUD/base_list.html.twig
Fix argument passed to `AbstractAdmin::toString()` at `base_list.htm.twig`.
The issue was introduced at #5595.
```markdown
- Error caused by passing a string instead object to `AbstractAdmin::toString()` from `base_list.htm.twig` when the admin's subject doesn't declare `__toString()` method.
```
=> Fix argument passed to `AbstractAdmin::toString()` at `base_list.htm.twig`

src/DependencyInjection/Compiler/ModelManagerCompilerPass.php, src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php
sometimes Symfony generates services with numeric ids (eg: `Symfony\Component\DependencyInjection\ServiceLocator`) and when iterating over the services ids, their service id is an int not a string. that triggers an error because strpos accpet only a string for its first argument when strict_types=1
I am targeting this branch, because this is a backward compatible fix
There's no corresponding issue
```markdown
- Fixed `ModelManagerCompilerPass` & `ObjectAclManipulatorCompilerPass` to avoid crashing when there's services with numerical ids
```
=> Fix when a service have a numeric id

src/Resources/views/Form/form_admin_fields.html.twig
ChoiceFieldMaskType's JavaScript in its twig template doesn't escape the field value, which breaks the JS when said value contains backslashes. The bug happens only if the ChoiceFieldMaskType field has a value already.
Closes #5637 
```markdown
- Fixed ChoiceFieldMaskType's twig template JavaScript using unescaped field value
```
=> fix ChoiceFieldMaskType script, escape field value

src/Admin/AbstractAdmin.php, src/Controller/CRUDController.php
Replace `get_class($this)` with `static::class`.
=> Replace `get_class($this)` with `static::class`

src/Resources/translations/SonataAdminBundle.ru.xliff
The wording of the sentence is incorrect from the point of view of the norms of the Russian language.
```markdown
- Fix typo in Russian translation
```
=> Fix typo in Russian translation

src/Resources/translations/SonataAdminBundle.it.xliff
Add translation for label_date_between key
Add missing italian translation for label_date_type_between
I am targeting this branch, because {reason}.
```markdown
- Fixed missing italian translation for label_date_type_between
```
=> Add missing italian translation

src/Admin/AccessRegistryInterface.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminInterface.php, src/Admin/LifecycleHookProviderInterface.php, src/Templating/TemplateRegistryInterface.php
This is a nice hack to propagate new method on our interfaces without breaking the API. If the user wants to use the new method, he should implement it and can benefit from a nice IDE autocompletion and code analysis.
I'm not sure if it's a good idea or not.
```markdown
- Use `@method` annotation to propagate new methods
```
=> Use @method annotation to propagate new methods

src/Resources/views/CRUD/batch_confirmation.html.twig, src/Resources/views/Pager/base_results.html.twig, src/Resources/views/Pager/simple_pager_results.html.twig
Replace deprecated `transchoice` tags with `trans`.
```markdown
- Usages of deprecated `transchoice` tags with `trans`
```
=> Replace deprecated `transchoice` tags with `trans`

src/Admin/AccessRegistryInterface.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminInterface.php, src/Admin/LifecycleHookProviderInterface.php, src/Templating/TemplateRegistryInterface.php
I am targeting this branch, because this is another fixup of #5671 😞 
The method signature was wrong: https://docs.phpdoc.org/references/phpdoc/tags/method.html#examples
Please check carefully, if I haven't made another mistake
=> Fixed @method signatures

src/Action/RetrieveAutocompleteItemsAction.php, src/Admin/BaseFieldDescription.php, src/Controller/CRUDController.php, src/Controller/PolyfillControllerTrait.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Route/RouteCollection.php, src/Twig/Extension/SonataAdminExtension.php, tests/Event/AdminEventExtensionTest.php
Replace calls to `call_user_func()` and `call_user_func_array()`.
=> Replace calls to `call_user_func()` and `call_user_func_array()`

src/Resources/views/CRUD/display_datetime.html.twig
I am targeting this branch, because this fix respects BC.
The bug was introduced with this PR: https://github.com/sonata-project/SonataAdminBundle/pull/5560
Revision list doesn't have `field_description` in template context. Therefore trying to open revision list with twig config `strict_variables: true` fails.
```markdown
- Fixed error when rendering revision list with Twig's `strict_variables` enabled
```
=> Fix error when showing revision list with strict variables enabled

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Adding a new item such as an image using the autocomplete form type could result in an exception, as an array was expected via the form, but a string was returned. Also, a variable decoding a JSON string was crashing the JavaScript on the page, while it was not being used.
I am targeting this branch, because I want to patch the recent version of Sonata as it's currently broken.
Closes #5426
```markdown
Fix JavaScript exception and incorrect form input type for Autocomplete form type
```
=> Fix Twig template Form Type Autocomplete

src/Resources/views/CRUD/batch_confirmation.html.twig, src/Resources/views/Pager/base_results.html.twig, src/Resources/views/Pager/simple_pager_results.html.twig
Use deprecated "transchoice" until we can bump "symfony/translation" to ^4.2.
Reverts #5669.
Closes #5686.
Closes #5688. 
```markdown
- Using `{% trans %}` Twig tag for pluralized catalogs with "symfony/translation" < 4.2.
```
=> [revert #5669] Use deprecated "transchoice"

src/Controller/CRUDController.php
The CsrfToken constructor requires the token to be `?string`. 
If the token is missing in the request we end up with
`Argument 2 passed to Symfony\Component\Security\Csrf\CsrfToken::__construct() must be of the type string or null, bool given, called in /var/www/html/vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php on line 1425`
The default value for the missing token should be `null`, not boolean `false`.
I am targeting this branch, because I think it's a bug.
```markdown
- `CRUDController::validateCsrfToken` to accept missing request token.
```
=> CRUDController::validateCsrfToken missing token

src/Resources/views/standard_layout.html.twig
Make truncable all breadcrumb fragments.
```markdown
- Broken layout on very large breadcrumb fragments.
```
**BEFORE:**
**AFTER:**
=> Make truncable all breadcrumb fragments

src/Controller/CRUDController.php
Allow `CRUDController::validateCsrfToken` to also validate CSRF from other sources, like the query string.
I am targeting this branch, so others can benefit from this function inside their custom actions. For instance one can generate a link to a custom action, with a csrf token to protect it.
```markdown
- `CRUDController::validateCsrfToken` to validate tokens not only from a POST request, but GET as well
```
=> Allow validate CSRF token from query string

src/Resources/views/standard_layout.html.twig
Don't truncate breadcrumb components when "safe_label" is used.
Follow up of https://github.com/sonata-project/SonataAdminBundle/pull/5695#issuecomment-534263031.
I've tried with some CSS alternatives like "text-overflow", but I haven't good results.
=> Don't truncate breadcrumb components when "safe_label" is used

docs/reference/dashboard.rst, src/Resources/views/Block/block_stats.html.twig
Allow to use pluralized translations with block stats widgets.
```markdown
- Allow to use pluralized translations with text provided through `sonata_admin.dashboard.blocks.{offset}.settings.text`.
```
```xml
<trans-unit id="admin.block.stats.results">
<source>admin.block.stats.results</source>
<target>{0} Results|{1} Result|]1,Inf[ Results</target>
</trans-unit>
```
=> Allow to use pluralized translations with block stats widgets

src/Resources/views/Block/block_stats.html.twig
Fix arguments passed to `transchoice()` Twig filter at `block_stats.html.twig`:
```
Argument 3 passed to Symfony\Bridge\Twig\Extension\TranslationExtension::transchoice() must be of the type array, string given
```
I am targeting this branch, because this change is a patch.
Issue introduced at #5690.
```markdown
- Arguments passed to `transchoice()` Twig filter at `block_stats.html.twig`
```
/cc @sonata-project/release-managers: the issue makes the admin dashboard unusable if the block stats are used with v3.54.0. My apologies.
=> Fix arguments passed to `transchoice()` Twig filter at `block_stats.html.twig`

src/Admin/AbstractAdmin.php, src/Form/Type/ChoiceFieldMaskType.php
Simplified checks for array and traversable values
```markdown
- Using array accessor in traversable objects which aren't implementing `\ArrayAccess` at `AbstractAdmin::buildForm()`.
```
=> Fixed checks for array and traversable values

docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
The `hasRole` method does not exist in `UserInterface` and also this shouldn't be part of the authentication but authorization (which is already in the `access_control` of `security.yml`).
Closes https://github.com/sonata-project/SonataAdminBundle/issues/5562
=> [Docs] Update recipe removing unexisting method

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Adding error-response for XHR requests
Current behaviour: when submitting form with AJAX (XHR) and if error occurs HTML will be returned instead of JSON.
I am targeting this branch, because features (BC?)
```markdown
Added JSON response from edit/create action when form is invalid.
```
=> added error-response when running request with XHR

src/Admin/AbstractAdmin.php
I am targeting this branch, because it's fix and it's BC.
Method \Sonata\AdminBundle\Admin\AbstractAdmin::buildTabMenu returns void, but in interface that class implementing it's returning value described as `ItemInterface|bool`, so i fixed it by returning expected value.
```markdown
- Changed returning values of method \Sonata\AdminBundle\Admin\AbstractAdmin::buildTabMenu to comply it's interface 
```
=> abstract-admin: Fixed method buildTabMenu to comply with it's interface

src/Action/DashboardAction.php, src/Action/SearchAction.php, tests/Action/DashboardActionTest.php, tests/Action/SearchActionTest.php, tests/Controller/CoreControllerTest.php
I cherry-picked the commits from https://github.com/sonata-project/SonataAdminBundle/pull/5510 that just remove extending from Controller from the actions which are `final`.
```markdown
- Removed extending from `Controller` in `DashboardAction` and `SearchAction` in favor of DI.
```
=> Remove extending from Controller in Dashboard and Search actions

tests/Action/AppendFormFieldElementActionTest.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Action/RetrieveFormFieldElementActionTest.php, tests/Action/SearchActionTest.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/AdminHelperTest.php, tests/Admin/BaseFieldDescriptionTest.php, tests/Admin/FieldDescriptionCollectionTest.php, tests/Controller/CoreControllerTest.php, tests/Controller/HelperControllerTest.php
I realised that there were some calls to `isInstanceOf` instead of `assertInstanceOf`. `isInstanceOf` is a constraint which just requires one parameter and does not perform an assertion. I didn't add something to the changelog as this is not useful to the end user.
=> Change some test calls from isInstanceOf to assertInstanceOf

src/Datagrid/Datagrid.php, tests/Datagrid/DatagridTest.php
Fix form validation in admin homepage.
Before the _per_page was an array with type and value but the type was HiddenType...
To fix this error : In AdminStatsBlockService, we inject _per_page via a new `Datagrid` function : setSimpleValue. So _per_page is now a scalar...
This change should fix https://github.com/sonata-project/SonataAdminBundle/issues/5457
=> Add scalar value for _per_page to Datagrid in AdminStatsBlockService

src/Resources/views/Form/form_admin_fields.html.twig
Add and remove the required attribute on fields shown or hidden by the choice mask field. At the moment you are unable to submit the form when one of the hidden fields is required. 
I am targeting this branch, because this is a bugfix and backwards compatible.
Closes #5706 
```markdown
Fixed `choice_field_mask_widget` to add or remove the html5 required validation when showing or hiding fields. 
```
=> Toggle required attribute when using choice_field_mask_widget.

src/Action/DashboardAction.php, src/Action/SearchAction.php, src/Resources/config/actions.xml, tests/Action/DashboardActionTest.php, tests/Action/SearchActionTest.php, tests/Controller/CoreControllerTest.php
I missed updating the service definition in https://github.com/sonata-project/SonataAdminBundle/pull/5723
Closes #5725
```markdown
- Fixed `DashboardAction` and `SearchAction` service definitions
```
=> Fix service definition for DashboardAction and SearchAction

docs/getting_started/creating_an_admin.rst
To make things simpler, I suggest that we add the basic Doctrine metadata on the class level just like it has been done on the class properties.
I also added a reference to the Doctrine documentation page.
Adding the $id might be nice, but as least now if you execute the `doctrine:schema:create` command, you will get a nice error message to tell you that something is wrong in your entity. Until now, the only message on a fresh install was that no entity was found.. how frustrating.
I added this on the current master branch but I think we might also push it to the next release as people starting with Symfony will likely use the 5 branch.
=> Add the basic doctrine metadata

composer.json
We rely on a `doctrine` service defined in that bundle, which means we
have a dependency on the bundle that cannot be seen by just examining
php code like composer-require-checker does.
That dependency is optional though, because not everyone is using the
ORM or ACLs. Using the conflict section is the best way to prevent
installation of version 2 while still not requiring installation of
version 3.
The error might be quite easy to fix, but the conflict I added should
stay, and just be modified to `>=3` when the error is fixed.
See:
- https://github.com/doctrine/DoctrineBundle/blob/d1f8a28fb45b6ff0b59f88df393575a4f89c3b66/Resources/config/dbal.xml#L67
- https://github.com/sonata-project/SonataAdminBundle/blob/3ab3cca373f76304149aa2ba0ef7da7d34c998b6/src/Resources/config/commands.xml#L20-L24 …
=> Prevent installing Doctrine bundle 2

src/Command/GenerateObjectAclCommand.php, tests/Command/GenerateObjectAclCommandTest.php
Since I cannot contribute to @Metabor's fork, a new PR for fixing the comments
See https://github.com/sonata-project/SonataAdminBundle/pull/5758
Fixes https://github.com/sonata-project/SonataAdminBundle/issues/5757
=> Fixes incompatible $registry argument in GenerateObjectAclCommand class when using DoctrineBundle:^2.0

composer.json
Compatibility issues are supposed to be fixed since #5768 was fixed.
```markdown
-  compatibility with `doctrine/doctrine-bundle` 2
```
=> Allow doctrine/doctrine-bundle 2

src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php, tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php
Since I removed that piece of code and the ORM/MongoDB/PHPCR are not updated accordingly, I think the best solution is to restore the ability of using string names. I'll try to trigger deprecations when using them and then remove completely in next major version.
Closes #5781
```markdown
- Ability of using string names and FQCNs to define filter types
```
=> Allow to use FQCN and strings names in filters

src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, src/Show/ShowMapper.php, tests/Datagrid/DatagridMapperTest.php, tests/Datagrid/ListMapperTest.php, tests/Form/FormMapperTest.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Show/ShowMapperTest.php
Actually, `$listMapper->add(...)` can throw a RuntimeException.
I don't think we expect the developper to try/catch this exception.
For me, it should be a LogicException, the InvalidArgumentException seems made for this.
```markdown
- Mapper methods now throw `LogicException` instead of `RuntimeException`
```
=> Use LogicException instead of Runtime exception

UPGRADE-3.x.md, src/Filter/FilterFactory.php, tests/Filter/FilterFactoryTest.php
Trigger a deprecation notice when using old string names in filters.
I am targeting this branch, because is BC.
```markdown
- The use of string names to reference filters
```
=> Trigger deprecation when using a string name as filter type

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig, src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Currently, the edit_modal and edit_many_script files are always included
even when there is no button displayed. That results in a heavier page.
I am targeting this branch, because the patch is backward compatible.
```markdown
- Include the `edit_modal` and `edit_many_script` templates only if there is at least one displayed button that need them (instead of always include them).
```
=> Include the edit modal and related script only when needed

src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, src/Show/ShowMapper.php, tests/Form/FormMapperTest.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Show/ShowMapperTest.php
I am targeting this branch, because this is a new feature.
Close https://github.com/sonata-project/SonataAdminBundle/issues/5775
```markdown
IfTrue and IfFalse apply correctly to tab and with functions
Nested IfTrue and IfFalse works as expected and does not throws exception anymore.
```
=> Apply iftrue and iffalse to tab and allow nested conditions

docs/reference/action_list.rst, src/Resources/views/CRUD/base_list_field.html.twig, tests/Action/SetObjectFieldValueActionTest.php, tests/Action/StatusMultiple.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Multiple editable field should be real multiple.
Now a multiple field is shown as multiple but edit is not a multiple and new value will be overridden, not append.
Closes #5767
```markdown
- Multiple editable fields now is a real multiple.
```
=> Multiple editable field should be real multiple

composer.json
Github keeps notifying us about
https://github.com/advisories/GHSA-xhh6-956q-4q69
=> Require secure versions of symfony/http-foundation

src/Resources/views/CRUD/Association/edit_many_script.html.twig
```markdown
- Toggle edit button `sonata_type_model_list_widget` after operations add/list/remove
```
After adding the value, sometimes you need to edit, but the edit button is available only after updating the object.
Example how this works:
=> Toggle edit button after operations add/list/remove

src/Form/Type/Filter/ChoiceType.php, src/Form/Type/Filter/DateRangeType.php, src/Form/Type/Filter/DateTimeRangeType.php, src/Form/Type/Filter/DateTimeType.php, src/Form/Type/Filter/DateType.php, src/Form/Type/Filter/NumberType.php, src/Form/Type/Operator/ContainsOperatorType.php, src/Form/Type/Operator/DateOperatorType.php, src/Form/Type/Operator/DateRangeOperatorType.php, src/Form/Type/Operator/EqualOperatorType.php, src/Form/Type/Operator/NumberOperatorType.php, tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
Another proposal for my issue (cf https://github.com/sonata-project/SonataAdminBundle/pull/5739) I try to solve
When using CallbackFilter, you may want to use the same operator than the ones Sonata offer in ChoiceFilter, NumberFilter, ... That's why I split these filter to create the OperatorType.
I am targeting this branch, because it's a new feature.
Usage:
```
->add(
'fooFilter',
CallbackFilter::class,
[
'callback' => [$this, 'myCallback'],
'operator_type' => ContainsOperatorType::class,
],
```
```markdown
- Added OperatorType usable in CallbackFilter
```
=> Add OperatorType

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
I am targeting this branch, because it is a bug fix that introduces no BC breaks.
Closes #5073
```markdown
- Fixed help messages not showing up in one to many inline tables.
```
=> Fix help messages not showing up in one to many inline tables.

src/Resources/public/Admin.js
This PR allows to use some select2 options in a sonata project.
For example, your attribute option in your form field could look like:
'attr' => [
'data-sonata-select2-maximumSelectionSize' => 1
]
I'm targeting 3.x because the change is backwards compatible as it adds an additional behaviour.
```markdown
- Make select2 search configurable
```
=> minimumResultsForSearch and maximumSelectionSize select2 options are configurable

src/Action/RetrieveAutocompleteItemsAction.php, src/Action/SetObjectFieldValueAction.php, src/Controller/CRUDController.php, tests/Action/AppendFormFieldElementActionTest.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Action/RetrieveFormFieldElementActionTest.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Block/AdminSearchBlockServiceTest.php, tests/Controller/CRUDControllerTest.php, tests/Controller/HelperControllerTest.php, tests/Functional/Controller/CRUDControllerTest.php, tests/Functional/Controller/DashboardActionTest.php, tests/Route/RouteCollectionTest.php
Use constant for Request methods and Response http status codes
I am targeting this branch, because these changes can also be applied before 3.x because the Request and Response are part of this project for a while
Closes #5826
=> 5826 - Use constant for Request methods and Response http status codes

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
I am targeting this branch, because it's a BC fix.
Should fix https://github.com/sonata-project/SonataAdminBundle/issues/5398
SonataPage compose feature is broken if you add 2 blocks of same kind
Each fields using this value through javascript are broken if they exist twice in the page
Closes #5398
```markdown
- Revert to trully unique uniqid for admins
```
=> Revert to trully unique uniqid

composer.json, src/Event/AdminEventExtension.php, src/Event/ConfigureEvent.php, src/Event/ConfigureMenuEvent.php, src/Event/ConfigureQueryEvent.php, src/Event/PersistenceEvent.php, src/Menu/MenuBuilder.php, tests/Event/AdminEventExtensionTest.php, tests/Menu/MenuBuilderTest.php
This is a follow-up for https://github.com/sonata-project/SonataAdminBundle/pull/5842.
Now that we dropped support for Symfony < 4.3 it simplifies the patch :blush: 
```markdown
- deprecations for event dispatching
```
=> fix symfony deprecations for event dispatching

src/DependencyInjection/SonataAdminExtension.php, tests/DependencyInjection/SonataAdminExtensionTest.php
The default templates are defined [in Configuration](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/Configuration.php#L332) and also [in the SonataAdminExtension](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/SonataAdminExtension.php#L100).
I run the testw before and after removing the code and it passed.
=> Remove duplicated default templates

src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php, tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php
Form aliases are not supported by symfony and we will remove them for filter elements too. ATM aliases are required. This PR makes them really optional.
```markdown
- Make filter alias optional
```
=> Make filter alias optional

src/Resources/views/Block/block_stats.html.twig, src/Resources/views/CRUD/batch_confirmation.html.twig, src/Resources/views/Pager/base_results.html.twig, src/Resources/views/Pager/simple_pager_results.html.twig
Since the minimum requirement is [`symfony/translation: ^4.3`](https://github.com/sonata-project/SonataAdminBundle/pull/5843) we can replace `transchoice` with `trans`.
```markdown
- Replaced the use of `transchoice` by `trans`
```
=> Replace transchoice with trans in templates

tests/Admin/AdminTest.php, tests/Route/DefaultRouteGeneratorTest.php
This makes these tests work on Windows
When running the tests on Windows there were lots of warnings regarding the non-existent `rm` command. Using `Symfony\Component\Filesystem\Filesystem::remove()` to remove test files fixes this problem.
I am targeting this branch, because it's only a test change and compatible with Linux.
```markdown
Running tests on Windows
```
=> Use Symfony\Component\Filesystem\Filesystem to remove test files

src/Resources/views/CRUD/list_choice.html.twig
Fix error in `src/Resources/views/CRUD/list_choice.html.twig` at line `43` if use list of ValueObject as values for entity.
```
Warning: Illegal offset type in isset or empty
```
This condition is failed if `val` is object:
```twig
{% if field_description.options.choices[val] is defined %}
```
Related #5767
```markdown
- Fix error of using list ValueObject as editable field in list fields.
```
=> Warning: Illegal offset type in isset or empty

tests/Controller/CRUDControllerTest.php
Whille checking this deprecation
```
1x: The "Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait" trait is considered internal. It may change without further notice. You should not use it from "Sonata\AdminBundle\Controller\CRUDController".
```
i had a look at the test for the controller.
It was using a ContainerInterface mock that actually does not behave like a real container instance at all. The mock was not adhering to the interface's contract. 
For example a PSR containe (and also the implementation from Symfony) should throw an exception by default if a service or parameter does not exist.
=> **The container mock simply returned null.**
So I don't think it makes sense to mock the container and over-complicate the test. Simply using a real container seems a lot better here.
I …
=> refactor CRUDControllerTest to use real container instance

src/Form/Type/Operator/EqualOperatorType.php
When making https://github.com/sonata-project/SonataAdminBundle/pull/5804 I think I made a mistake with the EqualOperatorType.
The EqualOperatorType was using yes/no label instead of is equal/is not equal labels.
I am targeting this branch, because BC-break free.
```markdown
Wording of EqualOperatorType
```
=> Fix wording of EqualOperatorType

src/Resources/views/Pager/base_links.html.twig
When creating custom actions that work like the 'list' action, the pager would always send the user back to the 'list' action.
This pull request replaces all occurrences of `'list'` in `base_links.html.twig` by `action`.
I am targeting this branch, because this is a patch/feature that is backwards compatible.
```markdown
- Fixed pager links in custom actions
```
=> Fix pager URLs when used in cutom actions

composer.json, tests/App/AppKernel.php
[symfony/templating](https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration) was deprecated in 4.3
```markdown
- `symfony/templating` dependency
```
=> Drop deprecated symfony/templating

UPGRADE-3.x.md, docs/reference/form_help_message.rst, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Resources/views/Form/form_admin_fields.html.twig, tests/Form/Extension/Field/Type/FormTypeFieldExtensionTest.php
After https://github.com/sonata-project/SonataAdminBundle/pull/5875, there is not need for `sonata_help` anymore. 
I modified the tests to move the code related to a new legacy test and also removed the doc that referenced `sonata_help` since `help` is documented in the Symfony docs.
```markdown
- The use of `sonata_help` in form types
```
=> Deprecate sonata_help in form types

UPGRADE-3.x.md, src/DependencyInjection/Compiler/ModelManagerCompilerPass.php, src/DependencyInjection/SonataAdminExtension.php, tests/App/AppKernel.php, tests/App/config/services.yml, tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php, tests/Fixtures/DoctrineBundle/Connection.php
Use tags for "sonata.admin.manager.*" services
Closes sonata-project/SonataDoctrineORMAdminBundle#924.
```markdown
- "sonata.admin.manager" tag to services implementing `ModelManagerInterface`.
```
=> Use "sonata.admin.manager" tag for services implementing `ModelManagerInterface`'

src/Action/GetShortObjectDescriptionAction.php, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/Pool.php, src/Controller/CRUDController.php, src/Resources/config/core.xml, src/Templating/TemplateRegistry.php, src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/TemplateRegistryExtension.php, tests/Action/DashboardActionTest.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/AdminTest.php, tests/Admin/PoolTest.php, tests/Controller/CRUDControllerTest.php, tests/Templating/TemplateRegistryTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php, tests/Twig/Extension/TemplateRegistryExtensionTest.php
This removes the deprecations of using templates in the Admin classes instead of the TemplateRegistry.
Refs: https://github.com/sonata-project/SonataAdminBundle/issues/5763
=> Remove deprecated code and NEXT_MAJOR related to templates

tests/Admin/AdminTest.php, tests/Controller/CRUDControllerTest.php, tests/Datagrid/ListMapperTest.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/Filter/FilterTest.php, tests/Form/Type/ChoiceFieldMaskTypeTest.php, tests/Form/Widget/FilterChoiceWidgetTest.php, tests/Form/Widget/FormChoiceWidgetTest.php, tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php, tests/Form/Widget/FormSonataNativeCollectionWidgetTest.php, tests/Menu/Integration/TabMenuTest.php
`assertAttributeSame` has no replacement so I removed it, because I don't think testing an object's internal is a great practice anyway. I managed to keep it in one occurence.
=> Address PHPUnit's warnings

src/DependencyInjection/Compiler/ModelManagerCompilerPass.php, tests/DependencyInjection/Compiler/ModelManagerCompilerPassTest.php
Iterate services with `getDefinitions()` instead of `getServiceIds()`.
Closes #5903.
```markdown
- Calling `ContainerBuilder::getDefinition()` with ids which have no associated definition.
```
=> Iterate services with `getDefinitions()` instead of `getServiceIds()`

src/Controller/CRUDController.php, src/Route/QueryStringBuilder.php
I am targeting this branch, because there is no breaking change.
Closes https://github.com/sonata-project/SonataAdminBundle/issues/5805
```markdown
Deprecate id param of Sonata Action
```
=> Deprecate id param in Sonata Action

composer.json
I don't see BC-break in symfony/contracts 2.0
```markdown
- Support for symfony/contracts 2.0
```
=> Add support for symfony/contracts 2.0

src/Resources/views/Form/form_admin_fields.html.twig
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/5878#issuecomment-590786579
```markdown
- Only trigger deprecations of sonata_help when it is actually used
```
=> Only trigger deprecations of sonata_help when it is actually using it

tests/Datagrid/ListMapperTest.php
It fails in https://github.com/sonata-project/SonataAdminBundle/pull/5917 because of this. It doesn't fail now because this test is skipped in `3.x`
=> Fix Regular expression in test

src/Resources/views/Pager/base_results.html.twig
When creating custom actions that work like the 'list' action, the "number of entries per page" dropdown would always send the user back to the 'list' action.
This pull request replaces all occurrences of `'list'` in `base_results.html.twig` by `action`.
I am targeting this branch, because this is a patch/feature that is backwards compatible.
See https://github.com/sonata-project/SonataAdminBundle/pull/5880 which fixes basically the same problem right next to this one.
```markdown
- Fixed "entries per page" dropdown links in custom actions
```
=> Fix entries per page dropdown URLs when used in custom actions

src/Security/Handler/RoleSecurityHandler.php, tests/Security/Handler/RoleSecurityHandlerTest.php
In Symfony `4.4` it is deprecated to call `isGranted` with an array of attributes
Refs: https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#security
```markdown
- Deprecation passing more than one attribute to isGranted
```
=> Fix deprecation passing more than one attribute to isGranted

src/Datagrid/Datagrid.php, tests/Datagrid/DatagridTest.php
`$this->query->setSortOrder(null)` is not valid.
```
/**
* @param string $sortOrder
*
* @return ProxyQueryInterface
*/
public function setSortOrder($sortOrder);
```
So I use the default value `'ASC'`.
```markdown
- `_sort_by` without `_sort_order` does not use invalid value anymore
```
=> Fix sortOrder default value

composer.json, docs/index.rst, docs/reference/configuration.rst, docs/reference/internationalization.rst, src/DependencyInjection/AbstractSonataAdminExtension.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, src/Resources/views/CRUD/Intl/display_currency.html.twig, src/Resources/views/CRUD/Intl/display_date.html.twig, src/Resources/views/CRUD/Intl/display_datetime.html.twig, src/Resources/views/CRUD/Intl/display_decimal.html.twig, src/Resources/views/CRUD/Intl/display_percent.html.twig, src/Resources/views/CRUD/Intl/history_revision_timestamp.html.twig, src/Resources/views/CRUD/Intl/list_currency.html.twig, src/Resources/views/CRUD/Intl/list_date.html.twig, src/Resources/views/CRUD/Intl/list_datetime.html.twig, src/Resources/views/CRUD/Intl/list_decimal.html.twig, src/Resources/views/CRUD/Intl/list_percent.html.twig, src/Resources/views/CRUD/Intl/show_currency.html.twig, src/Resources/views/CRUD/Intl/show_date.html.twig, src/Resources/views/CRUD/Intl/show_datetime.html.twig, src/Resources/views/CRUD/Intl/show_decimal.html.twig, src/Resources/views/CRUD/Intl/show_percent.html.twig, tests/DependencyInjection/SonataAdminExtensionTest.php
I was in the middle of dropping support of Symfony < 4.4 and adding support of 5 in `master` branch. The problem is that SonataIntlBundle doesn't support Symfony 5 and [looks like it's not easy because of SonataUserBundle](https://github.com/sonata-project/SonataIntlBundle/pull/278).
So I decided to [remove SonataIntlBundle dependency](https://github.com/sonata-project/SonataIntlBundle/issues/280). Right now [if the bundle is enabled, it will automatically load its templates to use localized information](https://github.com/sonata-project/SonataAdminBundle/search?q=SonataIntlBundle&unscoped_q=SonataIntlBundle). I basically copied the templates and then modified them to use `twig/intl-extra` functions.
This is not finished, I have to try it, but before going further, I would like to see if …
=> Drop SonataIntlBundle

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
See https://github.com/sonata-project/SonataAdminBundle/issues/5915
I am targeting this branch, because bugFix.
Closes #5915
What changelog should I use for Revert ? Removed ? Fixed ?
```markdown
deleteAction and batchAction does not use anymore the csrf_protection option from the editAction.
Stop calling the configureFormField in deleteAction and batchAction.
```
=> Manual revert of PR#5712

src/Security/Handler/AclSecurityHandler.php
Fixes some more deprecations. Same as #5924.
```markdown
- Deprecation passing more than one attribute to `isGranted`
```
=> Fix isGranted deprecation when using array

src/Resources/views/CRUD/base_list.html.twig
Following https://github.com/sonata-project/SonataAdminBundle/issues/5929, I want to introduce the ability of using `sortable => true` without a default column to sort the list.
This means that `$value['_sort_by']` can be 'not set'. 
```markdown
- Allow `_sort_by` filter to not be initially defined. 
```
=> Handle case without _sort_by value

src/Security/Handler/AclSecurityHandler.php
Move type checks to argument declarations.
I don't know why these checks weren't placed as type declarations originally.
Now, `\TypeError` is thrown instead of `\InvalidArgumentException` when arguments 1 or 2 passed to `AclSecurityHandler::__construct()` haven't the required type.
=> Move type checks to argument declarations

src/Resources/views/Core/dashboard.html.twig
Fix some Twig deprecations.
I am targeting this branch, because these changes only apply to `master`.
```markdown
- Removed deprecated `{% for .. if .. %}` Twig clauses.
```
=> Fix some Twig deprecations

src/Menu/Provider/GroupMenuProvider.php, tests/Menu/Provider/GroupMenuProviderTest.php
Fixes hopefully the last deprecations. Same as #5924 and #5952 
```markdown
- Deprecation passing more than one attribute to `isGranted`
```
=> Pass a single role to isGranted

src/Controller/CRUDController.php
Improve content type check for XHR requests at `CRUDController`.
It allows to find the required type even if multiple accepted types are provided:
```
application/json, application/xml;q=0.9, */*;q=0.8
```
Even, it could allow extra data, like q-factor weighting or API versioning:
```
application/json;version=2.0
```
```markdown
- Check for "application/json" presence at `Accept` HTTP header, even if multiple types are provided.
```
=> Improve content type check for XHR requests at `CRUDController`

docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Before:
```php
public function supports(Request $request): bool
{
if ($request->getPathInfo() != '/admin/login' || $request->getMethod() != 'POST') {
return false;
}
return true;
}
```
After:
```php
public function supports(Request $request): bool
{
return $request->attributes->get('_route') === 'admin_login' && $request->isMethod('POST');
}
```
And this is in line with the Symfony's style: see https://symfony.com/doc/current/security/guard_authentication.html#avoid-authenticating-the-browser-on-every-request
=> Simplify code, make it more strict

docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
PHPStan complains about `getLoginUrl`
```
------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Line   src/Security/AdminLoginAuthenticator.php
------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
89     Return type (Symfony\Component\HttpFoundation\RedirectResponse) of method App\Security\AdminLoginAuthenticator::getLoginUrl() should …
```
=> Fix bug with getLoginUrl()

docs/cookbook/recipe_sonata_admin_without_user_bundle.rst
Class `Symfony\Bundle\FrameworkBundle\Controller\Controller' is deprecated:
```
@deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.
```
=> Do not extend deprecated controller

composer.json, src/Bridge/Exporter/AdminExporter.php, src/Controller/CRUDController.php, src/Resources/config/core.xml, tests/Bridge/Exporter/AdminExporterTest.php, tests/Controller/CRUDControllerTest.php
Remove deprecations found in CRUDController
I am targeting this branch, because this is not BC.
```markdown
- Bump exporter to 2.1
- `$id` parameter in actions of `CRUDController`
- `sonata.admin.exporter` service
```
I was wondering if it's better to leave the action with empty parameters or add `Request $request`, I'd add the request.
=> Remove deprecations in CRUDController

src/DependencyInjection/AbstractSonataAdminExtension.php, src/DependencyInjection/SonataAdminExtension.php, tests/DependencyInjection/AbstractSonataAdminExtensionTest.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php, tests/Fixtures/DependencyInjection/DummySonataAdminExtension.php
[In AbstractSonataAdminExtension I added this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/AbstractSonataAdminExtension.php#L81):
```php
$useIntlTemplates = $container->getParameter('sonata.admin.configuration.use_intl_templates');
```
This is class is extended in other bundles, so the problem is that depending on the order of how the bundles are registered works or not (if the AdminBundle is registered first works).
Closes #5961
```markdown
- Accessing to a non-existing parameter when extending `AbstractSonataAdminExtension`
```
I only could come up with this solution, any other way/help is appreciated. ~I can't take a further look until this evening/night.~
=> Fix non-existent parameter

src/Admin/AdminHelper.php, tests/Admin/AdminHelperTest.php
When using `->add('foo.bar', CollectionType::class)` in PostAdmin, the adminHelper try to call the function `addBar` on Post entity instead of Foo entity.
After the PR, it will do `$post->getFoo()->addBar()`;
Closes #5738
```markdown
Class Helper addNewInstance take care about parentAssociation mapping.
```
=> Handle ParentAssociationMapping when looking for new instance

docs/reference/action_list.rst, src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php, tests/Admin/BaseAdminModelManagerTest.php
I recently found myself in this situation.
Admin A override createQuery.
Admin B extends A
Admin C extends A
Admin D extends A but override createQuery.
I needed to write in my createQuery method
```php
$query = $this->getModelManager()->createQuery($this->getClass());
foreach ($this->extensions as $extension) {
$extension->configureQuery($this, $query, $context);
}
```
to get a fresh new query.
But what if Sonata add something in the createQuery method ?
With the new `configureQuery` method.
I just need to override configureQuery method, and still will get all the new code in createQuery method.
```markdown
- Added `configureQuery` method for an easier way to override Admin list queries.
- Inheritance of the `createQuery` method.
```
=> Add configureQuery and make createQuery final

tests/Twig/Extension/UnicodeStringTest.php
Add missing `UnicodeStringTest` (#5983).
Seems that I forgot to stage this file while working at that PR.
Related to #5983.
=> Add missing `UnicodeStringTest`

docs/reference/dashboard.rst, tests/Admin/AdminTest.php, tests/Admin/BreadcrumbsBuilderTest.php
Modernize controller references.
=> Modernize controller references

src/Admin/AbstractAdmin.php, src/Model/ModelManagerInterface.php, tests/App/Admin/FieldDescription.php, tests/App/Datagrid/Datagrid.php, tests/App/Datagrid/Pager.php, tests/App/Datagrid/ProxyQuery.php, tests/App/Model/ModelManager.php, tests/Fixtures/Admin/TagAdmin.php
Add some missing return values in methods which are not intended to return `void`.
```markdown
- Fixed returning `void` in some methods which are intended to return a value or `null`.
```
=> Add some missing return values

src/Menu/Provider/GroupMenuProvider.php, src/Route/DefaultRouteGenerator.php, tests/Menu/Provider/GroupMenuProviderTest.php, tests/Route/DefaultRouteGeneratorTest.php
Fix type of argument 3 passed to `UrlGeneratorInterface::generateMenuUrl()`.
```markdown
- Type of argument 3 passed to `UrlGeneratorInterface::generateMenuUrl()`.
```
=> Fix argument type passed to `generateMenuUrl()`

src/Admin/AdminHelper.php
…st before resorting to callable check.
Fix relation function detection regression that occurred when switching to is_callable.
I am targeting this branch, because this is a BC break and affects the current published release.
Closes #6008
```markdown
- AdminHelper::addNewInstance to detect methods based on method_exists instead of callable to maintain previous BC behavior.
```
=> Update logic for detecting relations 

src/Model/ModelManagerInterface.php
This function is almost never used in the persistence bundle.
The only use was in the `getDefaultSortValues` function, but it won't be in 4.0.
Plus, the implementation does not respect the return typehint string:
- The doctrine orm return an array
- The mongo odm return a nullable string
```markdown
- Deprecate `getModelIdentifier` in favor of  `getIdentifierFieldNames` in `ModelManagerInterface`.
```
=> Deprecate getModelIdentifier

src/Form/Type/AdminType.php, tests/Form/Type/AdminTypeTest.php
I am targeting this branch, because BC (and bugfix).
When using
```
$formMapper->add(
'subscription.appendixes',
CollectionType::class,
['by_reference' => false],
['edit'   => 'inline', 'inline' => 'table']
)
```
The Admin type is building the following path `appendixes[0]` instead of `subscription.appendixes[0]`. This is because he's not using the parent association mappings.
Closes #5738 (which was closed too soon).
```markdown
- Admin Type is correctly using parentAssociationsMappings when using form with OneToOneToMany fields.
```
=> Handle parent association mappings

docs/reference/field_types.rst, src/Resources/views/CRUD/base_array_macro.html.twig, src/Resources/views/CRUD/list_array.html.twig, src/Resources/views/CRUD/show_array.html.twig, tests/Twig/Extension/SonataAdminExtensionTest.php
Generally here is just a prettifying of the array field type. I described new field options in the documentation.
Here is an example of how it can look now:
Inline view:
Screenshot from the translation tab of Symfony profiler:
with these options:
I am targeting this branch, because it extends current functionality and no breaking changes here.
Closes #5908.
```markdown
- Added new options (display, key_translation_domain and value_translation_domain) to the array field on Show and List pages.
```
=> Prettify array field on show and list actions

docs/reference/action_list.rst, src/Datagrid/ListMapper.php, tests/Datagrid/ListMapperTest.php
By default, even if an `associated_property` is set when adding a collection(?) field to `ListMapper`, sorting by column header is disabled in list view.
As we set the associated property to display it in the list, it would be nice if Sonata could guess we want to order on it.
I am targeting this branch, because it's feature.
```markdown
- Automatically set `sortable`, `sort_parent_association_mappings`, and `sort_field_mapping` when `associated_property` is set in `ListMapper::add` to enable sorting on `associated_property` by default.
```
=> Default sort on "associated_property"

src/Admin/AbstractAdmin.php, src/Admin/UrlGeneratorInterface.php, src/Route/DefaultRouteGenerator.php, src/Route/RouteGeneratorInterface.php, src/Twig/GlobalVariables.php
Replace `$absolute` argument names with `$referenceType` in order to be consistent with [`UrlGeneratorInterface`](https://github.com/symfony/routing/blob/0f562fa613e288d7dbae6c63abbc9b33ed75a8f8/Generator/UrlGeneratorInterface.php#L85).
Docblocks and default values at `RouteGeneratorInterface` were updated too.
Additionally, even if that's not related to the previous changes, I've removed useless class aliases at `AbstractAdmin` (`MenuItemInterface`, `MenuFactoryInterface`).
=> Replace `$absolute` arguments with `$referenceType`

tests/Controller/CRUDControllerTest.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
The removal of &MockObject is a known bug in PHP-CS-Fixer, but I am not
sure we can afford to wait for it to be fixed and released. Since this
was the only occurence of this in the project, I think it is acceptable
to drop it for now.
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4913
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4915
=> Apply latest cs fixes

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
Avoid collisions with cache keys at `AbstractAdmin::isGranted()`.
I'd like to reproduce the reported issue in the test case, but I can't find the way to generate the collisions between consecutive calls to `spl_object_hash()` inside the test case ([ref](https://3v4l.org/chGnr)).
Closes #5621.
```markdown
- Fixed collisions with cache keys at `AbstractAdmin::isGranted()`.
```
=> Avoid collisions with cache keys at `AbstractAdmin::isGranted()`

UPGRADE-3.x.md, tests/Datagrid/SimplePagerTest.php
I am targeting this branch, because deprecation.
Change already merged into master (4.x) in https://github.com/sonata-project/SonataAdminBundle/commit/1a40728ba8b7524ad34410ce217f236eb90af932
```markdown
- `SimplePager::getResults` will not return ArrayCollection in next major version (4.0)
```
Added deprecation notice to `SimplePager::getResults`
=> adding deprecation notices to SimplePager::getResults

src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/list_boolean.html.twig, src/Resources/views/CRUD/list_choice.html.twig
Fixed nesting Twig block definitions under a non-capturing nodes (deprecated since Twig 2.5.0).
Closes #5362.
```markdown
- Fixed nesting Twig block definitions under a non-capturing nodes.
```
=> Fix nesting a Twig block definition under a non-capturing node

src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, src/Form/Type/AdminType.php, tests/Admin/AdminHelperTest.php, tests/Admin/AdminTest.php, tests/Fixtures/Entity/Bar.php, tests/Form/Type/AdminTypeTest.php
I want to try to stop building form with null subject.
I am targeting this branch, because I tried to be BC.
Closes #5933
```markdown
- `$this->getSubject()` always return a value in `configureFormField`
```
=> Call getNewInstance before creating a form every time a subject is not already provided

src/Filter/FilterInterface.php
This fixes the documented return type of the `Sonata\AdminBundle\Filter\FilterInterface::getRenderSettings()`.
I am targeting this branch, because this is a back-compatible fix for 3.x.
Closes #6057
```markdown
- Fixed documented return type of `Sonata\AdminBundle\Filter\FilterInterface::getRenderSettings()`.
```
=> Use proper syntax for phpdoc

UPGRADE-4.0.md, src/Model/LockInterface.php, tests/Admin/Extension/LockExtensionTest.php
Since this interface is intended to be implemented by a model manager, `LockInterface` extends from `ModelManagerInterface`.
I am targeting this branch, because this change breaks BC.
```markdown
- Added extension from `ModelManagerInterface` to `LockInterface`
```
=> `LockInterface` extends from `ModelManagerInterface`

src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/base_show_field.html.twig, src/Show/ShowMapper.php
`false` was already half-supported.
There was a check 
```
if (!$fieldDescription->getLabel('sonata_deprecation_mute') && false !== $fieldDescription->getOption('label')) {
```
So when you use `label => false`, you have no label. When you use `null` you get the default label. But since there was no check in the twig, `false` was translated. So the profiler report a missing translation `''`. Plus it will lead to issue with symfony 5 since `trans` only allow string.
Since the label option can be false, I modify the signature of `getLabel`.
I also modified the previous check because it was overriding some falsy label, like `'0'`.
Closes #6064
```markdown
- `label => false` doesn't lead to a missing `''` translation in the profiler.
- `label => '0'` and …
```
=> Allow false as label

UPGRADE-3.x.md, src/Form/Type/AdminType.php, src/Resources/config/form_types.xml, tests/Form/Type/LegacyAdminTypeTest.php
Let's say I have a Father, multiple children and each child can have multiple dogs.
Let's say in a FatherAdmin, I add the following field in the `configureFormField` method.
```
$formMapper->add('child.dog', CollectionType, ...);
```
Of couse, there is a ChildAdmin and DogAdmin.
When I try to add a new dog to the child of some father, I can access the child/father data in the DogAdmin, thanks to some code in `AdminHelper::appendFormFieldElement`.
If I try to add a second dog without saving the first one, the whole collection is reloaded and the form is hydrated with the values already provided. But the AdminType::buildForm try to access the property in the database and get a `NoSuchIndexException`. In this situation, a newInstance of dog was created, but the child wasn't added to the dog …
=> Set ParentSubject to new Instance in FormType

tests/Form/Type/AdminTypeTest.php
Merging 3.x into master lead to test failure: https://github.com/sonata-project/SonataAdminBundle/pull/6073
One of the reason can be backport to 3.x.
=> Improve tests

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/BreadcrumbsBuilder.php, src/Controller/CRUDController.php, src/Route/DefaultRouteGenerator.php, src/Route/QueryStringBuilder.php, tests/Admin/AdminTest.php, tests/Controller/CRUDControllerTest.php, tests/Route/QueryStringBuilderTest.php
Targeting this branch, because BC.
First step of https://github.com/sonata-project/SonataAdminBundle/issues/6035
```markdown
- Deprecate the call of `AbstractAdmin::getParentFieldDescription` if the value is `null`. 
- Deprecate the call of `AbstractAdmin::getSubject` if the value is `null`.
- Deprecate the call of `AbstractAdmin::getListFieldDescription` if the value is `null`.
- Deprecate the call of `AbstractAdmin::getParent` if the value is `null`.
```
=> Add LogicException for getter with hasser

src/Controller/CRUDController.php, src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_show.html.twig, tests/App/Admin/EmptyAdmin.php, tests/App/config/services.yml, tests/Controller/CRUDControllerTest.php, tests/Functional/Controller/CRUDControllerTest.php
Technically it's possible to create/edit an object with no form field. I see no reason to throw a RuntimeException. Plus you can have use case with some data automatically set in PrePersist/PreUpdate method without anything to be filled by the user.
This PR allow to edit or create an object when the form has no field.
```markdown
- The possibility to edit/create an object without any field set in the configureFormField.
```
=> Allow to use empty create/edit form

src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php, src/Model/ModelManagerInterface.php, tests/Datagrid/DatagridTest.php
This two function should be in the Datagrid instead of be implemented 3 times the same way in the PersistenceBundle.
```markdown
- `Datagrid::getPaginationParameters` and `Datagrid::getSortParameters`
- `ModelManagerInterface::getPaginationParameters` and `ModelManagerInterface::getSortParameters`
```
=> Move function from ModelManager to Datagrid

src/Controller/CRUDController.php
Now the list of extra parameters is hardwired into the `CRUDController::renderWithExtraParams()` method. Parameters cannot be used in another method.
For example, i want to use the resolve template method and i have to duplicate the parameters from the method. If the list of these parameters changes in SonataAdminBundle, then in my project such methods will break.
```php
public function votesAction(int $id, Request $request): Response
{
// ...
$parameters = [
'action' => 'votes',
'object' => $object,
];
if (!$this->isXmlHttpRequest()) {
$parameters['breadcrumbs_builder'] = $this->get('sonata.admin.breadcrumbs_builder');
}
$parameters['admin'] = $parameters['admin'] ?? $this->admin;
$parameters['base_template'] = $parameters['base_template'] ?? $this->getBaseTemplate(); …
```
=> Allow reuse render extra parameters

UPGRADE-3.x.md, src/Admin/BaseFieldDescription.php, src/Model/ModelManagerInterface.php, src/Twig/Extension/SonataAdminExtension.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Closes #5907
```markdown
- Accessing to a non existing value when adding field to `showMapper` and `listMapper`.
```
=> Trigger deprecation when no value is found in list and show. Throw exception in next major.

composer.json, src/Admin/AdminHelper.php, src/Admin/BaseFieldDescription.php, src/Controller/CRUDController.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
Since [doctrine/inflector 1.4](https://github.com/doctrine/inflector/releases/tag/1.4.0), the API is deprecated, this PR updates the calls removing lots of deprecations and allows 2.0 version.
```markdown
- Update `doctrine/inflection` to ^1.4 || ^2.0
```
=> Bump doctrine/inflector to 1.4

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/Model/DatagridManagerInterface.php, src/Model/ModelManagerInterface.php, tests/Admin/AdminTest.php
I am targeting this branch, because I tried to be BC.
I tried to fix the issue explained here: https://github.com/sonata-project/SonataAdminBundle/issues/5929#issuecomment-599972301
ATM, the modelManager provide a `getSortValues` method, but it's overriden by the `datagridValues`. So I would recommend to deprecate `datagridValues` and provide a `getDefaultSortValues` instead.
And the `perPageOptions` should come from the modelManager since he's already providing the `_per_page` value.
The `maxPerPage` property seems to be a duplicate of the datagridValues[`_per_page`].
~~I need to test this on my project.~~
Edit: I tested it on my project and:
- The actual state of the PR seems to breaks nothing.
- If I update all the "Next_major" code, and I implement the `getDefaultPerPageOptions` in …
=> Allow correctly modelManager to configure sortValues and perPageOptions.

src/Resources/public/Admin.js
the first element of each collection starts with index `1` and not with `0`
ex:
```
my_form.my_collection[1]...
```
Form component works well and generates the child Form at position `1`:
but on the validation process, validator validates a hydrated main object which has `object.myCollecton` array field that starts with index `0`, so a generated error is attached for the wrong path: 
```
data.my_collection[0]...
```
What do you think about starting with index `0` for the first collection item?  
```markdown
- [Collection][JS] update index of the first element in collection from 1 to 0 
```
=> [Collection] initialize counter to -1 for starting items from 0

src/DependencyInjection/Configuration.php
When `sonata_admin.options.legacy_twig_text_extension` is not set to `false` the following deprecation message is logged:
> Using `true` as value for "sonata.admin.configuration.legacy_twig_text_extension" option is deprecated since sonata-project/admin-bundle 3.64.You should set it to `false`, which will be the default value since version 4.0.
The configuration option mentioned is the name of the container parameter, not the configuration variable. This makes it a little hard for users to address this deprecation. Also, because of string concatenation a space is missing between the two sentences.
This PR fixes those two minor issues.
```markdown
- Reference to configuration option in `legacy_twig_text_extension` deprecation …
```
=> Improve deprecation message for legacy_twig_text_extension

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
I found this two calls to the deprecated method.
```markdown
- Call to deprecated `trans` method of `AbstractAdmin`
```
=> Remove calls to the deprecated trans method

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
I am targeting this branch, because maybe BC.
When I tried, this works well and didn't change the rendering of other field of the CollectionType. But I don't know enough this code/these options to be sure that this was not here for a reason.
For what I understood, both inline and edit value are not needed. The form render is not realized by sonata but the FormType::class used. So these value seems to be never used because no FormType has a edit option or an inline option.
It was just used by CKeditor, by chance, since CKeditor has an inline options.
I get
Instead of
Closes #6101
Closes #5604
```markdown
- Render of CKeditor field when embedded in a collection with the `inline => natural` option.
```
=> Fix inline view with CKeditor field

src/Resources/views/CRUD/base_show_compare.html.twig, src/Resources/views/CRUD/base_show_field.html.twig, src/Twig/Extension/SonataAdminExtension.php, tests/Fixtures/Resources/views/CRUD/custom_show_field.html.twig, tests/Twig/Extension/SonataAdminExtensionTest.php
Make consistent variables between `renderViewElement()` and `renderViewElementCompare()`.
Since both methods deal with the same templates, they should expose the same context.
I found an issue with the comparison view in conjunction with a virtual field and a custom template, where the variable `object` is required. In that scenario everything is working fine with the `showAction` and the `historyViewRevisionAction` actions, but the `historyCompareRevisionsAction` action is throwing an exception because the variable `object` is not available there.
```php
$showMapper->add('my_custom_field', 'virtual_field', [
'template' => 'admin/CRUD/show_my_custom_field.html.twig',
])
```
```twig
{# admin/CRUD/show_my_custom_field.html.twig #}
{% extends '@SonataAdmin/CRUD/base_show_field.html.twig' %} …
```
=> Make consistent variables between `renderViewElement()` and `renderViewElementCompare()`

UPGRADE-3.x.md, docs/reference/action_list.rst, docs/reference/action_show.rst, docs/reference/field_types.rst, src/DependencyInjection/AbstractSonataAdminExtension.php, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/display_time.html.twig, src/Templating/TemplateRegistry.php
This allow to be used in project or others bundle.
Maybe these constant are better somewhere else, you'll say.
This will avoid using non-existent field type, like
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Guesser/TypeGuesser.php#L36
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Guesser/TypeGuesser.php#L68
I also updated lot of documentation.
```markdown
- Added `TemplateRegistry::TYPE_*` constant to be used instead of string value.
- Added `format` option for `time` field type.
- Deprecated `smallint` type for template ; use `integer` instead.
- Deprecated `bigint` type for template ; use `integer` instead.
- Deprecated `decimal` type for template ; use `float` instead.
- Deprecated …
```
=> Expose field type constant and update documentation

docs/reference/configuration.rst, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Configuration.php
When `label_catalogue` wasn't set, the fallback value was `SonataAdminBundle` instead of using the default label catalogue value.
Same for `icon`.
I am targeting this branch, because it's a bug fix.
```markdown
- Menu item `label_catalogue` correctly use the default value `default_label_catalogue`
- Menu item `icon` correctly use the default value `default_icon`
```
=> Fix label catalogue default value for group

src/Resources/public/css/styles.css, src/Resources/views/standard_layout.html.twig
I have disabled iCheck because it conflicts with some of the React components I've added to my admin pages.
In styles.css some of the bootstrap styling is overridden to make iCheck checkboxes display properly, as Bootstrap uses negative margins and padding to style checkboxes and radio buttons. However, these overrides are still present when iCheck is disabled, causing the following layout bug:
This PR adds a body class when iCheck is enabled (also done for Select2 for completeness) and activates the CSS override only when this class is present.
```markdown
- Body classes `sonata-icheck` and `sonata-select2` when iCheck or Select2 are enabled.
- Styling of checkboxes and radio buttons when iCheck is disabled.
```
=> Fix checkbox/radio button layout when iCheck is disabled

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
This adds the missing translation filter to previous PR  #5800 
I am targeting this branch, because this simply adds the missing filter in twig, it does not change any code.
Adds missing translation to #5073 , otherwise this was already fixed.
```markdown
- Added trans-filter to inline help message.
```
=> add translation filter to output only translated help messages

src/Admin/AbstractAdmin.php, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, src/Admin/ParentAdminInterface.php, src/Admin/Pool.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Model/AuditManager.php, src/Model/AuditManagerInterface.php, src/Twig/Extension/SonataAdminExtension.php, tests/Admin/PoolTest.php
End of https://github.com/sonata-project/SonataAdminBundle/pull/6050 and https://github.com/sonata-project/SonataAdminBundle/pull/6104
Closes #6035.
```markdown
- Added `FieldDescriptionInterface::getParent()`.
- Added `FieldDescriptionInterface::getAssociationAdmin()`.
- Added `FieldDescriptionInterface::getAdmin()`.
- Calling `AbstractAdmin::getChild()` when there is no child.
- Calling `BaseFieldDescription::getParent()` when there is no parent.
- Calling `BaseFieldDescription::getAssociationAdmin()` when there is no association admin.
- Calling `BaseFieldDescription::getAdmin()` when there is no admin.
- Calling `Pool::getAdminByClass()` when there is no admin for the class.
```
=> Force to use hasser before getter

UPGRADE-3.x.md, composer.json, docs/cookbook/recipe_customizing_a_mosaic_list.rst, src/Resources/views/CRUD/base_edit.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/CRUD/list_html.html.twig, src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig, src/Resources/views/CRUD/show_html.html.twig, src/Resources/views/standard_layout.html.twig, src/Twig/Extension/StringExtension.php, src/Twig/Extension/UnicodeString.php, tests/Twig/Extension/SonataAdminExtensionTest.php
[Symfony 5.1 was released](https://github.com/symfony/symfony/releases/tag/v5.1.0) one week ago, so we can use `truncate` method from `u` filter ([preserving the last word](https://github.com/symfony/symfony/pull/35649)).
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/5865
```markdown
- Changed use of `truncate` filter with `u` filter.
- Deprecated `Sonata\AdminBundle\Twig\Extension\UnicodeString` in favor of `Symfony\Component\String\UnicodeString`.
- Deprecated `sonata_truncate` in favor of `u.truncate`.
```
Since [our StringExtension is internal](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Twig/Extension/StringExtension.php#L26)... can we remove it? The problem I see is that I guess using …
=> Replace truncate filter with u.truncate

src/Form/FormMapper.php, tests/App/Admin/FooAdmin.php
Avoid a call to `AbstractAdmin::getFormFieldDescription` in `FormMapper::add`. Instead call the already fetched form field description. This prevents an infinite recursion when the 'help' option is used to map form fields.
Added a naive test by modifying the fixtures. If there is a more proper way to test this bug then I am open to feedback. 
I am targeting this branch, because this is a small bug fix suitable for a patch release.
Closes #6142.
```markdown
- Infinite recursion error when mapping form fields with a help option set.
```
=> Prevent infinite recursion when mapping form fields with a help message

src/Form/FormMapper.php
When looking at #6143 I noticed that the FormMapper uses convoluted logic to set the help text in a field description.
As this is a simple refactoring with no visible effect to the user I think no changelog entry should be added.
=> Simplify setting help in field description (minor)

src/Action/RetrieveAutocompleteItemsAction.php, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, tests/Admin/AdminTest.php, tests/Fixtures/Admin/AvoidInfiniteLoopAdmin.php
I am targeting this branch, because I think I have found a BC-way to fix the bug (https://github.com/sonata-project/SonataAdminBundle/issues/6142) which can easily occur and create infinite loop.
Currently methods `getFormFieldDescriptions`, `getFormFieldDescription` and `hasFormFieldDescription` are calling `this->buildForm`.
But the `buildForm` method is calling lot of things, as shown in the issue, we may find
```
if (null !== $help) {
$this->admin->getFormFieldDescription($name)->setHelp($help);
}
```
in the FormMapper->add, or
```
$formMapper->setHelps(['name' => 'help_page_name']);
```
in the SonataPageBundle configureFormField method witch lead to a `hasFormFieldDescriptions` call.
The developper could also possibly use the `getFormFieldDescriptions`, `getFormFieldDescription` and …
=> Stop building show/list/form when accessing fieldDescription

src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, src/Resources/config/twig_string.xml, src/Twig/Extension/DeprecatedTextExtension.php, src/Twig/Extension/StringExtension.php, tests/DependencyInjection/SonataAdminExtensionTest.php
This issue resolve problem with missing TextExtension after drop CoreBundle and upgrate sonata-project/twig-extensions to 1.x when `sonata_admin.options.legacy_twig_text_extension` is set to __true__. It is resolve by copy truncate function to new `DeprecatedTextExtension` class.
I am targeting this branch, because this change repsect BC.
```markdown
- Deprecated `sonata_admin.options.legacy_twig_text_extension` configuration
```
=> Fix BC after drop twig/extensions

src/Resources/translations/SonataAdminBundle.ar.xliff, src/Resources/translations/SonataAdminBundle.bg.xliff, src/Resources/translations/SonataAdminBundle.ca.xliff, src/Resources/translations/SonataAdminBundle.cs.xliff, src/Resources/translations/SonataAdminBundle.de.xliff, src/Resources/translations/SonataAdminBundle.es.xliff, src/Resources/translations/SonataAdminBundle.eu.xliff, src/Resources/translations/SonataAdminBundle.fa.xliff, src/Resources/translations/SonataAdminBundle.hr.xliff, src/Resources/translations/SonataAdminBundle.hu.xliff, src/Resources/translations/SonataAdminBundle.it.xliff, src/Resources/translations/SonataAdminBundle.ja.xliff, src/Resources/translations/SonataAdminBundle.lb.xliff, src/Resources/translations/SonataAdminBundle.lt.xliff, src/Resources/translations/SonataAdminBundle.lv.xliff, src/Resources/translations/SonataAdminBundle.no.xliff, src/Resources/translations/SonataAdminBundle.pl.xliff, src/Resources/translations/SonataAdminBundle.pt.xliff, src/Resources/translations/SonataAdminBundle.pt_BR.xliff, src/Resources/translations/SonataAdminBundle.ro.xliff, src/Resources/translations/SonataAdminBundle.ru.xliff, src/Resources/translations/SonataAdminBundle.sk.xliff, src/Resources/translations/SonataAdminBundle.sl.xliff, src/Resources/translations/SonataAdminBundle.sv_SE.xliff, src/Resources/translations/SonataAdminBundle.tr.xliff, src/Resources/translations/SonataAdminBundle.uk.xliff, src/Resources/translations/SonataAdminBundle.zh_CN.xliff
```markdown
- Added `ar` translations for btn_advanced_filters, link_edit, title_show, flash_lock_error, flash_batch_no_elements_processed, form_not_available, td_compare, td_role, label_compare_revision, list_results_count_prefix, noscript_warning, message_form_group_empty, link_filters, stats_view_more, title_select_subclass, no_subclass_available, label_unknown_user, read_more, read_less, toggle_navigation.
- Added `bg` translations for link_edit, title_show, flash_batch_no_elements_processed, read_more, read_less, toggle_navigation.
- Added `ca` translations for link_edit, flash_batch_no_elements_processed, toggle_navigation.
- Added `cs` translations for sonata_administration, link_edit, title_show, admin, flash_batch_no_elements_processed, …
```
=> Add missing translations

.github/workflows/qa.yaml, composer.json, phpstan-baseline.neon, phpstan.neon.dist
I am targeting this branch, because {reason}.
- added dev dependencies (some code, for example src/SonataAdminBundle.php, uses other package dependencies (Mopa\Bundle\BootstrapBundle).
Phpstan can't parse the class and throws error)
- added github workflow (mostly copy/paste the existing in 4.x version)
- ignore some classes (mostly because of "Class Symfony\Component\Form\Extension\Core\ChoiceList\SimpleChoiceList not found."; ignored template files)
No code was touched, so that I'm only adding phpstan as dependency in this PR.
Closes #6152 
reoprening of #6153 (I messed up with github actions + force pushing + behavior of this on the PR)
=> Added phpstan to v3

src/Twig/Extension/StringExtension.php
Targeting this branch, because BC.
Closes #6158
```markdown
- Allow null argument for StringExtension construct
```
=> Allow null param for StringExtension construct

tests/App/AppKernel.php, tests/Export/ExporterTest.php, tests/Fixtures/TestExtension.php, tests/Form/Extension/ChoiceTypeExtensionTest.php, tests/Form/Widget/BaseWidgetTest.php, tests/Resources/XliffTest.php
Unit tests is broken. Apparently after updating the SonataCoreBundle.
* [`AbstractWidgetTestCase::getEnvironment()`](https://github.com/sonata-project/form-extensions/blob/1.x/src/Test/AbstractWidgetTestCase.php#L64)
* [`AbstractWidgetTestCase::getRenderingEngine()`](https://github.com/sonata-project/form-extensions/blob/1.x/src/Test/AbstractWidgetTestCase.php#L100)
* [`AbstractWidgetTestCase::getTemplatePaths()`](https://github.com/sonata-project/form-extensions/blob/1.x/src/Test/AbstractWidgetTestCase.php#L81)
```markdown
- fix unit tests
```
=> Fix unit tests

composer.json, src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php, src/SonataAdminBundle.php, tests/App/AppKernel.php, tests/DependencyInjection/Compiler/TwigStringExtensionCompilerPassTest.php, tests/SonataAdminBundleTest.php
`sonata-project/intl-bundle` and `twig/intl-extra` register `format_datetime` what make them in conflict. 
`twig/extra-bundle` require-dev `twig/intl-extra` and auto-register it in twig. This will not allow use last SonataAdminBundle releases with some bundles like `ecommerce`.
Closes #6169.
```markdown
- Chenge `twig/extra-bundle` from `require` to `suggest`
- Fix error with missing `u` filter when `twig/extra-bundle` is not registred
```
=> Make `twig/extra-bundle` optional

src/DependencyInjection/SonataAdminExtension.php, src/Resources/config/core.xml, src/Translator/Extractor/AdminExtractor.php, src/Translator/Extractor/JMSTranslatorBundle/AdminExtractor.php, tests/DependencyInjection/SonataAdminExtensionTest.php, tests/Translator/Extractor/AdminExtractorTest.php, tests/Translator/Extractor/JMSTranslatorBundle/AdminExtractorTest.php
The current `AdminExtractor` is using `JMSTranslationBundle`. I added a new `AdminExtractor` that uses [`translation.extractor` Symfony tag](https://symfony.com/doc/current/reference/dic_tags.html#translation-extractor), so there is no need of the JMS bundle dependency.
The class is a copy of the other one with some changes. The old one implements `TranslatorInterface` so it's injected to the admin instances and when `AdminInterface::trans` is called, it registers it into the catalogue. Since `AdminInterface::trans` is deprecated, the new extractor does not look into these calls anymore, just to the ones made by the `LabelTranslatorStrategy`.
```markdown
- Added new `AdminExtractor` to extract translations from the Admin classes
- …
```
=> Add AdminExtractor

src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Currently, the tabs in a one-to-many form are not correctly translated. The groups `name` is used, instead of the `label` (like in the other templates). This is wrong especially when using the `translate_group_label: true` option.
This is BC because the `label` contains the `name` by default (see https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Mapper/BaseGroupedMapper.php#L79).
I am targeting this branch, because it's a BC bug fix.
```markdown
- Fix form one-to-many tabs translations
```
**Before**
**After**
=> Fix form one-to-many tabs translations

src/Action/RetrieveAutocompleteItemsAction.php, src/Action/SetObjectFieldValueAction.php, src/Admin/AbstractAdmin.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Action/SetObjectFieldValueActionTest.php, tests/App/Admin/FieldDescription.php, tests/Controller/HelperControllerTest.php, tests/Fixtures/Admin/FieldDescription.php
It seems that the change from `getTargetEntity()` to `getTargetModel()` in #6108 was not fully implemented in the rest of the code. This changeset fixes some deprecation notices I get on runtime and some notices about test classes not implementing `FieldDescriptionInterface`.
I think this internal change does not need a changelog entry.
=> Process deprecation of FieldDescriptionInterface::getTargetEntity()

src/Action/DashboardAction.php, src/Admin/BaseFieldDescription.php, src/Admin/Pool.php, src/Datagrid/Datagrid.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Object/Metadata.php, src/Security/Handler/AclSecurityHandler.php, src/Security/Handler/RoleSecurityHandler.php, src/Util/AdminObjectAclData.php
Multiple values are expected to be a not nullable array but are not explicitly set to `[]` by default.
This gave me error when I tried to use the master branch since getter was expecting to return an array.
```markdown
- Fixed default `[]` value for every non-nullable array class properties
```
=> Add default value for array properties

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
From
To
```markdown
- Fixed design of validation message error when using a inline table collection.
```
=> Fix design of validation message error for collection

docs/reference/advanced_configuration.rst, src/Resources/views/Menu/sonata_menu.html.twig
Allow to use parameters/placeholders in (sidebar) menu label.
translations/messages.en.yaml
```yaml
item_label_translation: Translatable label with %placeholder%.
```
Menu builder:
```php
$group->addChild('item', [
'label' => 'item_label_translation',
'labelAttributes' => ['%placeholder%' => 'dynamic_value']
]);
```
```markdown
- Allow to use parameters/placeholders in (sidebar) menu label translation.
```
=> Menu label translation

src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php
Targeting this branch, because the typehint was added in master.
SonataDoctrineOrmBundle call this setter with a possible null value.
Since the template is `null` by default, I updated the phpdoc and I don't see any problem with allowing to set `null`.
=> Allow to set a null template

src/Action/RetrieveAutocompleteItemsAction.php, src/Action/SetObjectFieldValueAction.php, src/Admin/AbstractAdmin.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6187#issuecomment-660012644
`FieldDescriptionInterface::getTargetModel` is not yet in the interface, this PR checks if that method exists and if not it calls the deprecated `FieldDescriptionInterface::getTargetEntity`.
Any suggestion for a cleaner way is accepted!
```markdown
- Fixed checking if `FieldDescriptionInterface::getTargetModel()` exists before calling it.
```
=> Use FieldDescriptionInterface::getTargetModel if exists

src/Resources/config/block.xml, tests/Block/AdminSearchBlockServiceTest.php
Added missing argument ($templateRegistry > sonata.admin.global_template_registry) for sonata.admin.block.search_result service.
I am targeting this branch, because this argument was added (but not set?) in master.
```markdown
- Added missing argument ($templateRegistry > sonata.admin.global_template_registry) for sonata.admin.block.search_result service.
```
=> Added missing argument for sonata.admin.block.search_result

src/Manipulator/ObjectManipulator.php, tests/Manipulator/ObjectManipulatorTest.php
Closes #6218.
```markdown
- Allow to use AdminType with unidirectional field.
```
=> Handle field without mappedBy

src/Resources/views/CRUD/Association/edit_many_script.html.twig
**Exception:**
An exception has been thrown during the rendering of a template ("Admin "..." has no active subclass."). 
This exception is thrown after adding a ModelType field the the admin.
I am targeting this branch, because "The error is introduced in master, but a deprecation is introduce in 3.x.".
```markdown
- Admin has no active subclass exception in *edit_many_script.html.twig* after adding a ModelType field.
```
=> Edit many script error without subclass gives an exception

docs/cookbook/recipe_file_uploads.rst, docs/cookbook/recipe_knp_menu.rst, docs/cookbook/recipe_lock_protection.rst, docs/cookbook/recipe_select2.rst, docs/cookbook/recipe_sonata_admin_without_user_bundle.rst, docs/cookbook/recipe_sortable_sonata_type_model.rst, docs/cookbook/recipe_workflow_integration.rst, docs/getting_started/creating_an_admin.rst, docs/getting_started/installation.rst, docs/getting_started/the_form_view.rst, docs/index.rst, docs/reference/action_list.rst, docs/reference/advanced_configuration.rst, docs/reference/architecture.rst, docs/reference/conditional_validation.rst, docs/reference/field_types.rst, docs/reference/form_types.rst, docs/reference/security.rst, docs/reference/troubleshooting.rst
I've run the Sphinx link check on the documentation and fixed most links and references to the core bundle.
I want to update https://sonata-project.org/bundles/core/master/doc/reference/form_types.html#sonata-type-translatable-choice as well, but I don't know where the new docs are located.
I have changed the links to the Symfony documentation to Symfony version 4.4 as this is the version supported by Sonata 3.
Doc changes don't need a changelog update.
=> Fix links in documentation

src/Action/SetObjectFieldValueAction.php, src/Resources/views/CRUD/base_list_field.html.twig, tests/Action/Bafoo.php, tests/Action/SetObjectFieldValueActionTest.php
The `date` and `datetime` field has a `timezone` option that is used as second argument for Twig's `date` function ([doc](https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/action_list.html#available-types-and-associated-options)).
It seems wrong to me that the date is displayed in one time zone, and is being live-edited in another time zone. Due to the difference between the server time zone and the time zone specified in the options, we can get completely different dates, which can lead to administrative errors.
I assume that the time zone is used so that the administrator can specify his time zone and not look at all the dates in the server time zone. This is useful because JavaScript calendars do not know in which time zone the server is located and display the …
=> Show and edit date in the same timezone

src/Action/SetObjectFieldValueAction.php, src/Resources/views/CRUD/base_list_field.html.twig, tests/Action/SetObjectFieldValueActionTest.php
~~In PR #6071 added hendleing a `datetime` field type to `SetObjectFieldValueAction`, but this type is not really editable.~~
Unfortunately, i want to say that it is not possible to use the datetime type as editable due to the conflict of dependencies in [X-editable](https://vitalets.github.io/x-editable/). Attempting to use the datetime type as editable will result in an error in JavaScript at [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/public/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js#L6552).
```
Uncaught TypeError: Cannot read property 'parseFormat' of undefined
at DateTime.initPicker (bootstrap-editable.min.js:6554)
at new DateTime (bootstrap-editable.min.js:6522)
at Object.createInput (bootstrap-editable.min.js:859) …
```
=> Can't use datetime field type as editable

docs/.doctor-rst.yaml, docs/reference/action_list.rst, src/Twig/Extension/SonataAdminExtension.php, tests/Twig/Extension/SonataAdminExtensionTest.php
I am trying to show additional fields in the list view. These fields are not part of the entity. Adding the field is no problem thanks to `configureQuery()`. However, Doctrine2 returns an array instead of an object when additional columns are present in the result set.
This was discussed previously in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/399 and https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/501 with no result. The direction in those issues was to use a DTO. This PR does not add support for DTO's but for the arrays that Doctrine2 returns.
As mentioned briefly in #6198 I found several issues with the method `SonataAdminExtension::getValueFromFieldDescription()`:
- It contains an unused third parameter.
- It is public for no reason.
- …
=> Add support for arrays containing additional database values in list views

UPGRADE-3.x.md, src/Model/ModelManagerInterface.php
Taking a look at the method [`ModelManager::getParentFieldDescription()` from SonataDoctrineMongoDBAdminBundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Model/ModelManager.php#L243) (and the one in [SonataDoctrineORMBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L315)), looks like they are not used anymore, in fact, the first parameter they receive (`$parentAssociationMapping`) is an array and then there is this code (which would fail because of using an `array` as a key):
```php
$associatingMapping = $metadata->associationMappings[$parentAssociationMapping];
```
This method was added in https://github.com/sonata-project/SonataAdminBundle/commit/b0df44f9894b08ea1ac526231990547919da375f, and …
=> Deprecate getParentFieldDescription from ModelManagerInterface

docs/getting_started/installation.rst
Update install doc dependancies
I am targeting this branch 3.x, because it related to a change occured in 3.69.0 version.
Closes #6173.
=> Update required dependancies in install doc after SonataCoreBundle became optionnal #6173

src/Block/AdminListBlockService.php, src/Block/AdminSearchBlockService.php, src/Block/AdminStatsBlockService.php, src/Resources/config/block.xml, tests/Block/DeprecatedAdminListBlockServiceTest.php, tests/Block/DeprecatedAdminSearchBlockServiceTest.php, tests/Block/DeprecatedAdminStatsBlockServiceTest.php
Similar to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1067
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6212
```markdown
- Passing `null` or an instance of `EngineInterface` as argument 2 when instantiating `Sonata\AdminBundle\Block\AdminListBlockService`, `Sonata\AdminBundle\Block\AdminSearchBlockService` or `Sonata\AdminBundle\Block\AbstractBlockService` 
```
=> Prepare support for block 4

src/Translator/Extractor/AdminExtractor.php, tests/Translator/Extractor/AdminExtractorTest.php
After #6040 was added commands like `php bin/console debug:translation` execute methods on Admin class instances to extract translatable strings.
One of the methods is `getForm`, which calls `configureFormFields`. To tailor my forms I access `$this->getSubject()` in several of these methods. I hope this is not unusual or against best practices.
When the AdminExtractor calls `getForm()` no subject is present.
I added this code to make sure a basic model is available:
```php
$admin->setSubject($admin->getNewInstance());
```
Closes #6221.
```markdown
- AdminExtractor sets subject created by `getNewInstance()` on Admin instance before extracting translatable strings.
```
=> Set subject on admin instance when extracting translatable strings

docs/reference/child_admin.rst
When adding items to the tab menu according to the documentation the built-in functionality of Knp Menu to highlight the current item is not used. The reason is that only works when using `generateMenuUrl` to add the menu item.
I've updated the documentation to reflect this.
I am targeting this branch, because it's a documentation change.
=> Improve child admin documentation wrt URL generation

composer.json, src/Controller/CRUDController.php, src/Resources/views/CRUD/Association/edit_many_script.html.twig, tests/Controller/CRUDControllerTest.php
The modeltype save request gives a 406 (Not acceptable) error in my browser. This is causes because my browser sends an wildcard Accept header `*/*` and the code checks on an exact match of `application/json`. To fix this I set the accept header before the ajax request.
I am targeting this branch, because the deprecation is introduce in **3.x** and the error is given in the master branch.
```markdown
- Set the Accept header for ajaxSubmit in `Resources/views/CRUD/Association/edit_many_script.html.twig` to  "application/json" to prevent 406 (Not acceptable)  error.
- CRUDController::handleXmlHttpRequestErrorResponse also accepts the wildcard Accept header  "*/*".
- CRUDController::handleXmlHttpRequestSuccessResponse also accepts the wildcard Accept header  "*/*".
```
=> Add correct accept header to ajaxSubmit to prevent 406 error

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Resources/views/CRUD/base_list.html.twig, tests/Admin/AdminTest.php
Change the UX-behavior to stop hidding default filter and considering them as normal filters.
Closes #6217.
Closes #6137.
Closes #5745.
```markdown
- Stop to hide default filters in order to provide a more natural UX-behavior.
- Abstract:: isDefaultFilter method.
```
=> Show applied filter

.phpstan/phpstan-baseline.neon, UPGRADE-3.x.md, docs/cookbook/recipe_image_previews.rst, docs/reference/form_help_message.rst, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, src/Form/FormMapper.php, src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig, src/Resources/views/CRUD/base_standard_edit_field.html.twig, src/Resources/views/Form/form_admin_fields.html.twig, tests/Admin/BaseFieldDescriptionTest.php, tests/App/AppKernel.php, tests/Functional/Controller/CRUDControllerTest.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6206#issuecomment-660129939
I haven't seen any use case rather than showing help messages in form fields.
Closes #6207.
```markdown
- Deprecated `BaseFieldDescription::setHelp()` and `BaseFieldDescription::getHelp()`.
- Deprecated passing `help` option to `BaseFieldDescription::setOptions()`.
- Deprecated `FormMapper::setHelps()` and `FormMapper:: addHelp()`.
- Deprecated passing `help` option to `FormMapper::add()` third argument containing HTML code without also passing `help_html` with `true` value.
```
I have to check if it works fine with nested fields.
=> Deprecate help option in FieldDescription

UPGRADE-3.x.md, src/Resources/views/CRUD/base_filter_field.html.twig, src/Resources/views/CRUD/base_inline_edit_field.html.twig, src/Resources/views/CRUD/base_standard_edit_field.html.twig, src/Resources/views/CRUD/edit_array.html.twig, src/Resources/views/CRUD/edit_boolean.html.twig, src/Resources/views/CRUD/edit_file.html.twig, src/Resources/views/CRUD/edit_integer.html.twig, src/Resources/views/CRUD/edit_sonata_type_immutable_array.html.twig, src/Resources/views/CRUD/edit_string.html.twig, src/Resources/views/CRUD/edit_text.html.twig
I think these templates are not used anymore. The PR is draft because I still have to check better, but just in case someone has some knowledge about this. 
It makes sense to have templates for `list` and `show` for each field, but `edit` fields are configured through [`form_admin_fields.html.twig`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/Form/form_admin_fields.html.twig) and in the persistence bundles, that's why I think they are not used.
```markdown
- Deprecated `base_filter_field.html.twig` template
- Deprecated `base_inline_edit_field.html.twig` template
- Deprecated `base_standard_edit_field.html.twig` template
- Deprecated `edit_array.html.twig ` template
- Deprecated `edit_boolean.html.twig` …
```
=> Deprecate unused form templates

src/Guesser/TypeGuesserChain.php, src/Guesser/TypeGuesserInterface.php
Checking phpstan for the MongoDB Admin Bundle, I got this (among others):
```php
------ -------------------------------------------------------------------------------------------------------------
Line   Builder/DatagridBuilder.php
------ -------------------------------------------------------------------------------------------------------------
121    Call to an undefined method Symfony\Component\Form\Guess\Guess::getType().
123    Call to an undefined method Symfony\Component\Form\Guess\Guess::getOptions().
------ -------------------------------------------------------------------------------------------------------------
```
The problem here is that the `TypeGuesserInterface::guessType()` returns `Guess|null`, but looking at the implementation of the …
=> Return TypeGuess instead of Guess on TypeGuesserInterface::guessType

.phpstan/phpstan-baseline.neon, composer.json, src/SonataAdminBundle.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Since https://github.com/sonata-project/SonataAdminBundle/pull/6212 the only package preventing this is `mopa/bootstrap-bundle`, that was added in https://github.com/sonata-project/SonataAdminBundle/pull/6154 to pass phpstan check, I've removed the dependency and check if the class exist. 
```markdown
- Added compatibility with Twig 3.
```
~**Edit**: I'll take a look later at phpstan~
=> Allow Twig 3

src/Resources/views/CRUD/base_list.html.twig
Added support for label_translation_parameters in filter fields.
```markdown
- Support for 'label_translation_parameters' in filter form types
```
=> Added support for label_translation_parameters

src/Controller/CRUDController.php
Exception:
_Argument 4 passed to Sonata\AdminBundle\Admin\AbstractAdmin::preBatchAction() must be of the type bool, string given, called in /projects/sonata-sandbox/vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php on line 452_
I am targeting this branch, because there is the typehint added.
```markdown
- Cast $allItems to an boolean to prevent typehint error.
```
=> Batch action $allItems needs to be an boolean

composer.json, tests/App/AppKernel.php
This is to prevent a deprecation on the tests, but also to avoid broken builds: https://github.com/sonata-project/SonataAdminBundle/pull/6263
I think something went wrong on last release of SonataDoctrineBundle
=> Fix deprecation with SonataDoctrineBundle location

src/Route/RouteCollectionInterface.php
I am targeting this branch, because this is pedantic but this interface was introduced on master.
=> Improve description of RouteCollectionInterface::actionify()

docs/reference/routing.rst
This removes oppressive language from the code.
There is a default permission of `MASTER` which may want to be considered for changing, but this would be a BC break and may be something people are comfortable keeping given the context it is used in.
I am targeting this branch, because the change is back-compatible.
Closes #6185.
=> Remove oppressive language

composer.json, src/Command/GenerateObjectAclCommand.php, tests/Command/GenerateObjectAclCommandTest.php
This PR adds support for `doctrine/common` 3. It follows the upgrade instructions in Doctrine's [release notes](https://github.com/doctrine/common/releases/tag/3.0.0).
I am targeting this branch, because the change is back-compatible.
Closes #6121.
```markdown
- Added support for `doctrine/common` 3.
```
=> Add doctrine/common 3 support

src/Datagrid/ProxyQueryInterface.php, tests/App/Datagrid/ProxyQuery.php
This was introduced by https://github.com/sonata-project/SonataAdminBundle/pull/6257/files
getSingleScalarResult can return anything (int, bool, string, DateTime, ...).
I also think we should deprecate this method in 3.x and remove it in 4.0, because we don't use it in the project so there is no need to require it in the interface. WDYT @sonata-project/contributors ?
=> Fix ProxyQueryInterface return typehint

src/Datagrid/ProxyQueryInterface.php, tests/App/Datagrid/ProxyQuery.php
Following https://github.com/sonata-project/SonataAdminBundle/pull/6290
During my work on https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1073, I got errors because `null` is not allowed. But if the value is not set, it's `null`.
There is no need for a changelog since it's on master branch, and related to https://github.com/sonata-project/SonataAdminBundle/pull/6257/files
=> Fix proxy query return typehint 

UPGRADE-3.x.md, src/Datagrid/ProxyQueryInterface.php, tests/App/Datagrid/ProxyQuery.php
This method is not used by SonataAdmin, so I see no reason to require his implementation in the interface.
And I feel like it's too much doctrine-oriented. 
```markdown
- Deprecated `Sonata\AdminBundle\Datagrid\ProxyQueryInterface::getSingleScalarResult`
```
=> Deprecate getSingleScalarResult method

UPGRADE-3.x.md, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/DataTransformer/ModelsToArrayTransformer.php, src/Form/EventListener/MergeCollectionListener.php, src/Model/ModelManagerInterface.php, tests/App/Model/ModelManager.php
Closes #6024.
```markdown
- Deprecated `Sonata\AdminBundle\Model\ModelManagerInterface` collection-related methods.
```
=> Deprecate ModelManagerInterface collection-related methods

src/Controller/CRUDController.php
I am targeting this branch, because 3.x and the master branch are containing this problem.
```markdown
- "Notice: Undefined index: idx" if there are no list items are selected.
```
=> Prevent error "Notice: Undefined index: idx" if there are no list items are selected.

src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/DataTransformer/ModelsToArrayTransformer.php
=> Fix psalm build

src/Admin/AbstractAdmin.php, src/Form/ChoiceList/ModelChoiceLoader.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Model/AuditManager.php, src/Model/AuditManagerInterface.php, src/Model/AuditReaderInterface.php, src/Model/DatagridManagerInterface.php, src/Model/LockInterface.php, src/Model/ModelManagerInterface.php, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/Pager/base_links.html.twig, tests/Admin/BaseAdminModelManagerTest.php, tests/Admin/Extension/LockExtensionTest.php, tests/App/Model/ModelManager.php, tests/Controller/CRUDControllerTest.php, tests/Form/DataTransformer/ModelToIdTransformerTest.php, tests/Form/Type/ModelListTypeTest.php
I am targeting this branch, because this is a BC break.
```markdown
- Narrow the API for classes declared under the `Sonata\AdminBundle\Model\` namespace.
```
I have applied PHPStan level 8 when doing it and all of the errors related to the typehints are done.
=> Narrow Model API

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Avoid to mutate original request on `CRUDController::batchAction()`.
Follow up of #6271.
```markdown
- Fixed mutating the original request at `CRUDController::batchAction()`.
```
=> Avoid to mutate original request on `CRUDController::batchAction()`

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php, tests/Fixtures/Controller/BatchAdminController.php
Fix allowing valid action names in `CRUDController::batchAction()`.
Currently, actions like "do-something" or "do_something" are being interpreted as "dosomething", leading to a `\RuntimeException` exception:
```php
// App/Admin/MyAdmin.php
public function getBatchActions()
{
$actions = parent::getBatchActions();
$actions['do_something'] = [
'label' => 'bulk_action.do_something',
'ask_confirmation' => true,
];
return $actions;
}
```
```
The `dosomething` batch action is not defined
```
See https://github.com/sonata-project/SonataAdminBundle/pull/6251#discussion_r465252211.
Issue introduced at #6251.
```markdown
- Fixed allowing valid action names in `CRUDController::batchAction()`.
```
=> Fix allowing valid action names in `CRUDController::batchAction()`

UPGRADE-3.x.md, src/Admin/BaseFieldDescription.php, src/Form/FormMapper.php, src/Resources/views/Form/form_admin_fields.html.twig, tests/Functional/Controller/CRUDControllerTest.php
I am targeting this branch, because receive too many deprecation notices and in upgrades was not actual instructions.
Closes #6319.
Addition for #6215.
```markdown
- Remove unnecessary span wrapper for field help. Merge styles with paragraph.
- Prevent too many deprecation notices.
```
=> Fix help deprecation

composer.json, src/Action/RetrieveAutocompleteItemsAction.php, src/Admin/AbstractAdmin.php, src/Controller/CRUDController.php, tests/Admin/AdminTest.php, tests/Controller/CRUDControllerTest.php
I propose to allow symfony/http-foundation and symfony/validator 5.1. 
I am targeting this branch, because its BC and would be nice to have 3.x fully support symfony 5.1 soon.
```markdown
- support for symfony/http-foundation and symfony/validator 5.1
```
=> allow symfony/http-foundation and symfony/validator 5.1

composer.json, src/Guesser/TypeGuesserChain.php
To fix phpstan, https://github.com/symfony/symfony/pull/37725 was release in 4.4.12
=> Bump symfony/form to 4.4.12

src/Action/AppendFormFieldElementAction.php, src/Action/GetShortObjectDescriptionAction.php, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/UrlGeneratorInterface.php, src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Admin/AdminTest.php, tests/App/Datagrid/Pager.php, tests/Controller/HelperControllerTest.php
I'm introducing deprecation related to this PR: https://github.com/sonata-project/SonataAdminBundle/pull/6304
```markdown
- Passing another type than `object` to `AbstractAdmin::toString`
- Passing `null` to `AbstractAdmin::getUrlSafeIdentifier`, `AbstractAdmin::getNormalizedIdentifier`, `AbstractAdmin::getId`
- Using `GetShortObjectDescriptionAction` with an empty objectId. 
```
=> Restrict param type of AdminInterface identifiers methods

src/Form/FormMapper.php, tests/Form/FormMapperTest.php
I am targeting this branch, because im think that no needed handle field if role no granted.
Closes #6338.
```markdown
-  Prevent `addFormFieldDescription` if field role no granted
```
=> Prevent addFormFieldDescription if field role no granted

docs/reference/action_export.rst, src/Admin/AbstractAdmin.php
All extension points are protected and start with `configure*`. This PRs adds a new one for export fields, so you can define custom fields and can use admin extensions.
I am targeting this branch, because this feature is BC.
```markdown
- Add `AbstractAdmin::configureExportFields` extension point
```
=> Add AbstractAdmin::configureExportFields extension point

src/Mapper/BaseGroupedMapper.php
I am targeting this branch, because bug fix.
```markdown
- The default `group` now correctly use the admin translation domain when using the admin label.
```
=> Fix admin label translation domain

src/Admin/AbstractAdmin.php, src/Mapper/BaseGroupedMapper.php
@sonata-project/contributors 
In master, the `AdminInterface::getLabel()` method return `?string` instead of `string`.
That's why I had to change the check 
```
if (null === $label) {
$this->with('default', ['auto_created' => true]);
} else {
$this->with($label, [
'auto_created' => true,
'translation_domain' => $this->admin->getTranslationDomain(),
]);
}
```
=> Merge 3.x into Master

composer.json, src/Form/Extension/ChoiceTypeExtension.php, src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Form/Extension/Field/Type/MopaCompatibilityTypeFieldExtension.php
~Splitting https://github.com/sonata-project/SonataAdminBundle/pull/6263 in small chunks. In this case adding support for symfony/form 5.1.~
I am targeting this branch, because ~it would be nice to have Symfony 5 support in 3.x~ it is BC break.
```markdown
- Added support for `symfony/form` 5.1.
```
=> Add support for symfony/form 5.1

docs/cookbook/recipe_sortable_sonata_type_model.rst, src/Form/DataTransformer/ArrayToModelTransformer.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/DataTransformer/ModelToIdTransformer.php, src/Form/DataTransformer/ModelsToArrayTransformer.php, src/Util/AdminAclManipulator.php, src/Util/AdminAclManipulatorInterface.php, src/Util/AdminObjectAclData.php, src/Util/AdminObjectAclManipulator.php, src/Util/FormBuilderIterator.php, src/Util/ObjectAclManipulator.php, src/Util/ObjectAclManipulatorInterface.php
```markdown
- Add type hints to data transformers
- Add type hints to util classes
- Allow null transformation in ModelsToArrayTransformer
```
=> Add type hints to data transformers

docs/reference/action_list.rst, src/Action/SetObjectFieldValueAction.php, src/Controller/HelperController.php, src/Form/DataTransformer/BooleanToStringTransformer.php, src/Form/DataTransformerResolver.php, src/Form/DataTransformerResolverInterface.php, src/Resources/config/actions.php, src/Resources/config/core.php, src/Resources/config/form_types.php, tests/Action/Bar.php, tests/Action/Baz.php, tests/Action/Foo.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Controller/HelperControllerTest.php, tests/Form/DataTransformer/BooleanToStringTransformerTest.php, tests/Form/DataTransformerResolverTest.php
Allow use [Symfony Data Transformers](https://symfony.com/doc/current/form/data_transformers.html) in `configureListFields()` like:
```php
class TestimonialAdmin extends BaseAdmin
{
// ...
protected function configureListFields(ListMapper $list_mapper): void
{
$list_mapper
->add('permission', 'choice', [
'label' => 'Permission',
'editable' => true,
'choices' => Permission::change(),
'template' => '@Frontend/Testimonial/admin/list_permission.html.twig',
'catalogue' => 'messages',
'data_transformer' => new PermissionDataTransformer(),
]);
}
}
```
Closes #5693
```markdown
- Allow use Symfony Data Transformers in list fields editable
```
=> Data Transformers in list fields editable

UPGRADE-3.x.md, src/Datagrid/ProxyQueryInterface.php, tests/App/Datagrid/ProxyQuery.php
Apparently [`getUniqueParameterId`](https://github.com/search?q=org%3Asonata-project+getUniqueParameterId&type=code) and [`entityJoin`](https://github.com/search?q=org%3Asonata-project+entityJoin&type=code) are only used in the ORM Bundle, in the other persistence bundles (also not maintained ones) the implementation is empty because they are not useful.
- [SonataAdminSearchBundle](https://github.com/sonata-project/SonataAdminSearchBundle/blob/d1687b05e57624c277ea46069c035bc945ed9997/src/ProxyQuery/ElasticaProxyQuery.php#L180-L188)
- [SonataDoctrinePhpcrAdminBundle](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/635efa07b866347b3b07a462d34a1c63324702e5/src/Datagrid/ProxyQuery.php#L303-L309)
- [SonataDoctrineMongoDBAdminBundle](https://github.com/sonata-project/Sonata …
=> Deprecate ORM related functions on ProxyQueryInterface

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php
Based on https://github.com/sonata-project/SonataAdminBundle/pull/6383#discussion_r487524505 I made some research and I found what can be improve. 
- service: `admin_code` // Admin object
- service `admin_code.template_registry` // TemplateRegistry object dedicated for specify Admin  
It mean We should be able to get `TemplateRegistry` object directly from admin, becouse we can get it from container. 
I also remove some unnecessary `NEXT_MAJOR` 
```markdown
- `Sonata\AdminBundle\Admin\AbstractAdmin::hasTemplateRegistry(): bool`
- `Sonata\AdminBundle\Admin\AbstractAdmin::setTemplates()`
- `Sonata\AdminBundle\Admin\AbstractAdmin::setTemplate()`
```
=> Fix TemplateRegistry usages

src/Form/ChoiceList/ModelChoiceLoader.php, src/Model/ModelManagerInterface.php, tests/App/Model/ModelManager.php, tests/Form/ChoiceList/ModelChoiceLoaderTest.php
Closes #6273.
```markdown
- Added `ModelManagerInterface::supportsQuery()`
- Create a new instance of ModelChoiceLoader with a query unsupported by the modelManager
```
=> Add ModelManagerInterface::supportsQuery

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Templating/TemplateRegistryAwareInterface.php
```markdown
-  `Sonata\AdminBundle\Templating\TemplateRegistryAwareInterface` with `getTemplateRegistry()`, `hasTemplateRegistry()` and `setTemplateRegistry()` methods
```
=> Add TemplateRegistryAwareInterface

docs/reference/configuration.rst, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, src/Resources/views/standard_layout.html.twig, tests/DependencyInjection/SonataAdminExtensionTest.php
Added the option `skin` to load different Admin LTE skins, making the `body` class configurable and thus allowing you to change the skin without the need to overriding the `body_attributes` block.
I am targeting this branch, because this option is currently missing.
Closes #6368.
```markdown
- Added option to load different Admin LTE skins
```
=> Added option to load different Admin LTE skins

src/Datagrid/ProxyQueryInterface.php
This is already fixed on master.
```markdown
- Fixed ProxyQueryInterface::getSortBy and ProxyQueryInterface::getSortOrder phpdoc
```
=> Fix getSortBy/getSortOrder phpdoc

src/Action/SetObjectFieldValueAction.php
First step of https://github.com/sonata-project/SonataAdminBundle/issues/6404
I know @jordisala1991 Made a great work about typehint.
I will review every folders.
```markdown
- The fourth argument of the `SetObjectFieldValueAction::__construct` method is now mandatory.
```
=> Add missing typehint for actions

UPGRADE-4.0.md, src/Block/AdminListBlockService.php, src/Block/AdminSearchBlockService.php, tests/Block/AdminListBlockServiceTest.php, tests/Block/AdminSearchBlockServiceTest.php
This code was implemented to be BC.
```markdown
- The third argument of the `AdminListBlockService::__construct` method is now mandatory.
- The fourth argument of the `AdminListBlockService::__construct` method is now mandatory.
```
=> Set TemplateRegistry as a mandatory parameter for block services.

src/Form/Type/ModelType.php
Since SonataAdminBundle 3.75 the argument to `MergeCollectionListener`s constructor is deprecated. `Sonata\AdminBundle\Form\Type\ModelType` sets this argument, causing a deprecation notice.
I am targeting this branch, because it's a backwards compatible change.
```markdown
- Deprecation notice in `MergeCollectionListener` when using the `ModelType` form type with the `model_manager` option set.
```
=> Prevent deprecation notice in constructor of MergeCollectionListener

UPGRADE-3.x.md, src/Command/GenerateObjectAclCommand.php, src/Resources/config/commands.php, tests/Command/GenerateObjectAclCommandTest.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6407#discussion_r494063621
If we use FQCN notation for the `user_model` option in `GenerateObjectAclCommand`, there is no need for the `$registry` dependency.
```markdown
- Deprecate using shortcut notation for user_model in favor of FQCN in `GenerateObjectAclCommand`
```
=> Deprecate using shortcut notation for user_model in favor of FQCN

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig
Currently, inline table / tabs collection labels will get the translation domain in this order : 
- the admin one
- if it's empty, the field options one.
I think it should be the opposite ? Check the option first, and fallback to the admin.
I am targeting this branch, because it's a bugfix.
- Fixed incorrect inline table / tabs collection translation domain
=> Fix inline table collection translation domain

src/Resources/config/twig.php, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/Pager/base_links.html.twig, src/Twig/Extension/PaginationExtension.php, tests/App/Admin/FooAdmin.php, tests/App/Model/ModelManager.php, tests/Twig/Extension/PaginationExtensionTest.php
These deprecations were introduced in 3.66.
This replaces calls to `ModelManagerInterface::getPaginationParameters` for `DatagridInterface::getPaginationParameters` and
`ModelManagerInterface::getSortParameters` for `DatagridInterface::getSortParameters`.
I don't know if there is a way to use a twig function just internally.
```markdown
- Remove calls to deprecated method `ModelInterface::getPaginationParameters()`.
- Remove calls to deprecated method `ModelInterface::getSortParameters()`.
```
=> Fix calls to deprecated methods

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
Even when a child admin instance implements the `isCurrentChild()` method, `getCurrentChildAdmin()` will try to call the deprecated method `getCurrentChild()` anyway, causing this deprecation notice:
>  User Deprecated: The Sonata\AdminBundle\Admin\AbstractAdmin::getCurrentChild() method is deprecated since version 3.65 and will be removed in 4.0. Use Sonata\AdminBundle\Admin\AbstractAdmin::isCurrentChild() instead.
I changed the code such that `getCurrentChildAdmin()` only calls `getCurrentChild()` when `isCurrentChild()` is not implemented.
I am targeting this branch, because it's a backwards compatible improvement.
```markdown
- Superfluous deprecation notice in `getCurrentChild()` when calling `getCurrentChildAdmin()`.
```
=> Prevent deprecation notice when AdminInterface.isCurrentChild is implemented

src/Resources/public/Admin.js
Moved `jQuery(this).confirmExit()` to `window.load` to allow custom fields that edit the DOM which causes the form to always be marked as "changed". By moving this script to the `window.load` event you can add custom scripts before `confirmExit` is initialized. 
I am targeting this branch, because it enhances an existing feature.
```markdown
- Moved confirmExit to window.load
```
=> Moved confirmExit to window.load

src/Mapper/BaseMapper.php
This is the only missing typehint in the Mapper directory.
I added a comment to explain why.
=> Add next major comment about typehint

src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/DataTransformer/ModelsToArrayTransformer.php, src/Util/TraversableToCollection.php, tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php, tests/Form/DataTransformer/ModelsToArrayTransformerTest.php, tests/Util/TraversableToCollectionTest.php
Replace multiple DB transactions with a single one.
Closes #6280.
```markdown
- Changed multiple calls to `ModelManagerInterface::find()` with `ModelManagerInterface::findBy()` in order to avoid multiple transactions.
```
=> Replace multiple DB transactions with a single one

UPGRADE-3.x.md, docs/cookbook/recipe_image_previews.rst, src/Admin/AbstractAdmin.php, src/Admin/Pool.php, src/Mapper/BaseGroupedMapper.php, tests/Admin/PoolTest.php, tests/Mapper/BaseGroupedMapperTest.php
The [code that uses this method is already deprecated](https://github.com/sonata-project/SonataAdminBundle/search?p=1&q=getContainer). 
Deprecating this method would lead to better design, forcing the user to use dependency injection instead of getting the container from the `Pool` service.
Another further refactoring could be to inject a ServiceLocator instead of the whole container.
```markdown
- Deprecated `Pool::getContainer()` method.
```
=> Deprecate Pool::getContainer method

src/Resources/public/Admin.js
I am targeting this branch, because would like make better sonata-admin.
Closes #6430.
```markdown
- Solve problem with unset batch checkbox`s after back via browser history
```
=> Solve problem with unset batch checkbox`s after back via browser history

src/EventListener/AssetsInstallCommandListener.php
This is a follow up of #6404  to add param & return type hints.
```markdown
- Added parameter and return type hints to `AssetsInstallCommandListener`
```
=> [EventListener] Add param & return type hints to a file in EventListener dir

phpstan-baseline.neon, src/Command/GenerateObjectAclCommand.php, src/Resources/config/commands.php, tests/Command/DeprecatedGenerateObjectAclCommandTest.php, tests/Command/GenerateObjectAclCommandTest.php
Some deprecation and some tests updates were missing in https://github.com/sonata-project/SonataAdminBundle/pull/6413
```markdown
- Deprecate Passing a third argument to `GenerateObjectAclCommand::__construct()`
```
=> Add deprecation when injecting registry in command

src/Model/ModelManagerInterface.php
Narrow allowed types for ids passed to `find()` and `addIdentifiersToQuery()` in `ModelManagerInterface`.
Related to sonata-project/SonataDoctrineORMAdminBundle#1136.
=> Narrow allowed types for ids passed to `find()` and `addIdentifiersToQuery()` in `ModelManagerInterface`

src/Show/ShowMapper.php, src/Translator/Extractor/AdminExtractor.php, src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/TemplateRegistryExtension.php, src/Twig/GlobalVariables.php
```markdown
- Added phpdoc type hints to `ShowMapper`
- Added phpdoc type hints to `AdminExtractor`
- Added phpdoc type hints to `SonataAdminExtension`
- Added phpdoc type hints to `TemplateRegistryExtension`
- Added phpdoc type hints to `GlobalVariables`
=> Add phpdoc type hints

UPGRADE-3.x.md, docs/reference/security.rst, src/Controller/CRUDController.php, src/DependencyInjection/Compiler/CheckAclUserManagerCompilerPass.php, src/DependencyInjection/SonataAdminExtension.php, src/Util/AdminAclUserManagerInterface.php, tests/Controller/CRUDControllerTest.php, tests/DependencyInjection/Compiler/CheckAclUserManagerCompilerPassTest.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6476#issuecomment-707317147
The idea is introducing `AdminAclUserManagerInterface` which the service configured under `sonata_admin.security.acl_user_manager` must implement. If it's ok, I'll add the upgrade note.
```markdown
- Deprecated not configuring `acl_user_manager` service explicitly when using `friendsofsymfony/user-bundle`.
- Deprecated configuring `acl_user_manager` service without implementing `AdminAclUserManagerInterface`.
```
=> Deprecate acl_user_manager without implementing AdminAclUserManagerInterface

src/Resources/views/Core/tab_menu_template.html.twig, src/Resources/views/Menu/sonata_menu.html.twig, src/Resources/views/standard_layout.html.twig, tests/App/Admin/FooAdmin.php
I am targeting this branch, because it is a bug fix.
Closes #6031
```markdown
- Call \Knp\Menu\MenuItem::getLabel() method directly in twig template to avoid a possible side effect from \ArrayAccess.
```
\Knp\Menu\MenuItem in knplabs/knp-menu-bundle implements \ArrayAccess and defines its offsetGet method as follows:
```php
/**
* Implements ArrayAccess
*/
public function offsetGet($name)
{
return $this->getChild($name);
}
public function getChild($name)
{
return isset($this->children[$name]) ? $this->children[$name] : null;
}
```
It has a property `$label` with its getter: 
```php
/**
* Label to output, name is used by default
*
* @var string|null
*/
protected $label;
public function getLabel()
{
return (null !== $this->label) ? $this->label : $this->name;
}
```
If a MenuItem object has a …
=> Fix \Knp\Menu\MenuItem @Label issue

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
No request is needed to set default values. 
Closes #6162
```markdown
Setting default values ​​for filters and sorting even without a request
```
=> Set defaults filters without request

UPGRADE-3.x.md, src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Fix return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`.
Closes #6046.
Closes #6098.
```markdown
- Fixed return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`.
- Deprecated `Sonata\AdminBundle\Controller\CRUDController::getRestMethod()` method in favor of `Symfony\Component\HttpFoundation\Request::getMethod()`.
```
=> Fix return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`

src/Admin/Pool.php, tests/Admin/PoolTest.php
BC
Closes #6505.
```markdown
- Pool support of group without admin  
```
=> Handle item without admin key

src/Admin/AbstractAdmin.php, src/Admin/Pool.php, tests/Admin/PoolTest.php
This is BC
Closes #6181 
```markdown
- Added `Pool::hasSingleAdminByClass()`
```
=> Improve error message in case of multiple admins for same entity

UPGRADE-3.x.md, src/Command/Validators.php, tests/Command/ValidatorsTest.php
Deprecate `Validators::validateEntityName()`.
```markdown
- Method `Validators::validateEntityName()`.
```
=> Deprecate `Validators::validateEntityName()`

src/Form/DataTransformer/ModelsToArrayTransformer.php, tests/Form/DataTransformer/ModelsToArrayTransformerTest.php
Avoid to pass empty array as argument 3 for implementations of `ModelManagerInterface::addIdentifiersToQuery()`.
Closes #6508.
```markdown
- Passing an empty array as argument 3 for implementations of `ModelManagerInterface::addIdentifiersToQuery()`.
```
=> Avoid to pass empty array as argument 3 for implementations of `ModelManagerInterface::addIdentifiersToQuery()`

src/Translator/BCLabelTranslatorStrategy.php, src/Translator/Extractor/AdminExtractor.php, src/Translator/FormLabelTranslatorStrategy.php, src/Translator/LabelTranslatorStrategyInterface.php, src/Translator/NativeLabelTranslatorStrategy.php, src/Translator/NoopLabelTranslatorStrategy.php, src/Translator/UnderscoreLabelTranslatorStrategy.php, tests/Admin/AdminTest.php
```markdown
- Added parameter and return type hints to all files in the Translator dir
=>  [Translator] Add param & return type hints to all files in the Translator dir

src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/TemplateRegistryExtension.php, src/Twig/GlobalVariables.php
```markdown
- Added parameter and return type hints to all files in the Twig dir
=> [Twig] Add param & return type hints to all files in the Twig dir

psalm-baseline.xml, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, tests/Admin/AdminTest.php, tests/Admin/BaseFieldDescriptionTest.php, tests/App/Model/ModelManager.php, tests/Datagrid/DatagridMapperTest.php, tests/Datagrid/ListMapperTest.php, tests/Form/FormMapperTest.php, tests/Show/ShowMapperTest.php
BC
Related to discuss: https://github.com/sonata-project/SonataAdminBundle/pull/6501#discussion_r507513934
```markdown
- Instantiate a FieldDescription without passing the name as first argument
```
=> Require name to instantiate a Field description

src/Resources/views/CRUD/base_list.html.twig
```markdown
- html with a links in no_result_content
```
The `go_to_the_first_page` link appears when there are more results.
The `button_create` link only appears if it is not AJAX.
=> change html with a links in no_result_content

src/Filter/FilterInterface.php, tests/Fixtures/Filter/FooFilter.php
This method is not used in SonataAdmin so we don't have to require this signature in our Interface.
Persistence bundle are done this way: 
```
abstract class Filter extends BaseFilter
{
/**
* @var bool
*/
protected $active = false;
public function apply($queryBuilder, $value)
{
$this->value = $value;
if (\is_array($value) && \array_key_exists('value', $value)) {
list($alias, $field) = $this->association($queryBuilder, $value);
$this->filter($queryBuilder, $alias, $field, $value);
}
}
```
They just have to add 
```
abstract function filter(...)
```
With specific signature. ($alias is only useful for ORM bundle for instance)
Closes #6269.
```markdown
- Deprecate `FilterInterface::filter()` method
```
=> Deprecate FilterInterface::filter method

src/Resources/views/CRUD/Association/edit_one_to_many_inline_table.html.twig
I am targeting this branch, because it fixes a bug introduced in 3.77.0 (https://github.com/sonata-project/SonataAdminBundle/pull/6401).
Closes https://github.com/sonata-project/SonataAdminBundle/issues/6522
```markdown
- fixed BC break with getting the translation domain for nested fields on a one-to-many inline edit table view
```
=> fix issue with translation domain

src/Resources/views/CRUD/base_edit.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/standard_layout.html.twig
Restore missing ellipsis in truncated words.
#6132 replaces our own string "truncate" implementation with the one provided by [`symfony/string`](https://github.com/symfony/string/blob/90c2a5103f07feb19069379f3abdcdbacc7753a9/AbstractString.php#L631), but the ellipsis in the `truncate()` method has an empty string as default value there instead of the ellipsis we were using before.
Related to #6132.
```markdown
- Missing ellipsis in some truncated word.
```
=> Restore missing ellipsis in truncated words

src/Guesser/TypeGuesserChain.php, src/Guesser/TypeGuesserInterface.php
```markdown
- Added parameter and return type hints to `TypeGuesserInterface` and `TypeGuesserChain`
=> [Guesser] Add type hints to files in the Guesser dir

composer.json, phpstan-baseline.neon, src/Builder/FormContractorInterface.php, src/Form/FormMapper.php, src/Form/Type/AdminType.php, tests/Form/FormMapperTest.php, tests/Form/Type/AdminTypeTest.php
This is related to https://github.com/sonata-project/SonataAdminBundle/issues/6426#issuecomment-702330648
I need to know the CollectionType value of `by_reference` in the AdminType.
The options are passed to the AdminType here:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/FormContractor.php#L172-L180
So I need to change the signature of `getDefaultOptions` to allow passing the `formOptions`.
But then I have two solutions: 
- Option 1: Adding a new `symfony_form_options` option to the AdminType, then in the FormContractor I will add 
```
$options['symfony_form_options'] => $formOptions
```
And then I access to `by_reference` with `$options['symfony_form_options']['by_reference'] ?? true`.
- Option 2: Using the `by_reference` option of the AdminType, …
=> Access to CollectionType options in AdminType

src/Menu/MenuBuilder.php
```markdown
- Added return type hint to the method `createSidebarMenu` in `MenuBuilder`
=> [Menu] Add return type hint to a method

src/Resources/public/css/styles.css, src/Resources/views/CRUD/base_list.html.twig
Now, I have a filter list with a limited height and a scroll bar.
Closes #6528.
```markdown
- Added the ability to scroll the filter list dropdown
```
=> Add scroll to filter dropdown

src/Resources/config/core.php
Fix the DI config for `Sonata\AdminBundle\Admin\AdminHelper`.
Closes #6531
=> Fix DI config for AdminHelper

src/Util/AdminAclManipulator.php, src/Util/AdminAclManipulatorInterface.php, src/Util/AdminObjectAclData.php, src/Util/AdminObjectAclManipulator.php, src/Util/FormBuilderIterator.php, src/Util/FormViewIterator.php, src/Util/ObjectAclManipulator.php, src/Util/ObjectAclManipulatorInterface.php
```markdown
- Added parameter and return type hints to files in the Util directory
=> [Util] Add type hints to files in Util directory

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php
* Use list syntax for method and args at `AddDependencyCallsCompilerPass::fixTemplates()`;
* Add "NEXT_MAJOR" comments in order to change the visibility of some methods to private;
* Use spaceship operator in `sort()` callback at `AddDependencyCallsCompilerPass::process()`;
* Add missing type declarations in some anonymous functions at `AddDependencyCallsCompilerPass::process()`.
I am targeting this branch, because these changes are pedantic.
=> Pedantic changes in `AddDependencyCallsCompilerPass::fixTemplates()`

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Model/DatagridManagerInterface.php, src/Model/ModelManagerInterface.php, tests/App/Model/ModelManager.php
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1144#issuecomment-703819774
Imho, this does not need to be modelManager-dependant.
WDYT ?
```markdown
- `DatagridManagerInterface` with no replacement
```
=> Deprecate DatagridManagerInterface

src/Form/ChoiceList/ModelChoiceLoader.php, src/Form/Type/ModelType.php, tests/Form/Type/ModelTypeTest.php
I am targeting this branch, because would like make better our admin.
Closes #6517.
```markdown
- Prevent load entities when pass empty choices for ModelType. Use null for native loading.
```
=> Prevent load entities when pass empty choices for ModelType

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Exporter/DataSourceInterface.php, src/Model/ModelManagerInterface.php, tests/Admin/AdminTest.php, tests/App/Exporter/DataSource.php, tests/App/config/services.yml
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1144
```markdown
- Added DataSourceInterface
- Deprecate not setting a DataSourceInterface to an Admin
- Deprecate `ModelManagerInterface::getDataSourceIterator()`
```
=> Add DataSourceInterface

src/Manipulator/ObjectManipulator.php, tests/Manipulator/ObjectManipulatorTest.php
Now the `ObjectManipulator` does not work correctly if you pass it a DTO without setters and getters and only with public properties.
https://github.com/sonata-project/SonataAdminBundle/pull/6171/files#r510937030
Not sure if this is related, but i got this exception after a recent update:
```
RuntimeException: Method PlaylistRelationAdminView::setPlaylist() does not exist.
#22 /vendor/sonata-project/admin-bundle/src/Manipulator/ObjectManipulator.php(106): Sonata\AdminBundle\Manipulator\ObjectManipulator::callSetter
#21 /vendor/sonata-project/admin-bundle/src/Manipulator/ObjectManipulator.php(67): Sonata\AdminBundle\Manipulator\ObjectManipulator::setObject
#20 /vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php(3566): Sonata\AdminBundle\Admin\AbstractAdmin::appendParentObject …
```
=> Allow usage object properties to get/set instance in ObjectManipulator

tests/Form/AbstractLayoutTest.php, tests/Form/AdminLayoutTestCase.php
This adds some tests for the twig blocks defined for forms based on https://github.com/symfony/symfony/blob/e68da40f5649bb0266c74c2e1e4bbf83f9c6bb13/src/Symfony/Component/Form/Tests/AbstractLayoutTest.php#L64 and https://github.com/phiamo/MopaBootstrapBundle/blob/7df89019daed24008d4117217c8cb4df972d2751/Tests/Form/AbstractDivLayoutTest.php
So we can add tests to PRs like https://github.com/sonata-project/SonataAdminBundle/pull/6547 more easily.
=> Add tests for form layout

UPGRADE-3.x.md, src/Admin/Pool.php, src/Resources/config/core.php, src/Templating/AbstractTemplateRegistry.php, src/Templating/MutableTemplateRegistry.php, src/Templating/MutableTemplateRegistryAwareInterface.php, src/Templating/MutableTemplateRegistryInterface.php, src/Templating/TemplateRegistry.php, src/Templating/TemplateRegistryAwareInterface.php, src/Templating/TemplateRegistryInterface.php, tests/Templating/MutableTemplateRegistryTest.php, tests/Templating/TemplateRegistryTest.php
Global templates should not be changeable in global template registry after created. This PR will add `NEXT_MAJOR` for do it. 
`Pool` should have `TemplateRegistryInterface`.
`Admin` should have `MutableTemplateRegistryInterface`.
```markdown
- Added `Sonata\AdminBundle\Templating\AbstractTemplateRegistry`
- Added `Sonata\AdminBundle\Templating\MutableTemplateRegistry` 
- Added `Sonata\AdminBundle\Templating\MutableTemplateRegistryAwareInterface`
- Changed `Sonata\AdminBundle\Templating\TemplateRegistryAwareInterface` to handle instances of `TemplateRegistryInterface`.
- Deprecated `Sonata\AdminBundle\Templating\TemplateRegistry:setTemplate()`
- Deprecated `Sonata\AdminBundle\Templating\TemplateRegistry:setTemplates()`
```
=> Make TemplateRegistry not mutable

src/Resources/views/CRUD/base_list.html.twig
Avoid toggle filter button to be shown when the filter is hidden.
When an admin is child, a filter pointig to its parent is automatically added at [`AbstractAdmin::buildDatagrid()`](https://github.com/sonata-project/SonataAdminBundle/blob/0ecbf244051afc20869c0afb09597fb143ce46c4/src/Admin/AbstractAdmin.php#L942-L960) using the value from `getParentAssociationMapping()` as name. This filter is rendered as hidden, but since it's considered active, the toggle button used to remove the filter is shown.
This change uses the "show_filter" option to determine if this button must be shown.
```markdown
- Showing toggle filter button when the filter is hidden in the admin list.
```
=> Avoid toggle filter button to be shown when the filter is hidden

src/Admin/AdminExtensionInterface.php
It is present in all other similar methods.
=> Add missing generic phpdoc

phpstan-baseline.neon, src/Datagrid/DatagridMapper.php, tests/Admin/AdminTest.php, tests/Datagrid/DatagridMapperTest.php
When investigating in https://github.com/sonata-project/SonataAdminBundle/pull/6570
I discovered that we have this code
https://github.com/sonata-project/SonataAdminBundle/blob/f2dba48d52ecd60186a7f4f530131f9fd4e1ed62/src/Show/ShowMapper.php#L93-L95
In every mapper, except the Datagrid one.
For the datagridbuilder, it's in the persistence bundle for no reason
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L173-L175
So I add this code here, and we'll be able to remove it from every persistence bundle.
```markdown
- If no label is provided to the filter, the default label is used following the label translator strategy
```
=> Set default label to filter if null

src/Admin/AbstractAdmin.php, src/Filter/Filter.php, src/Filter/FilterInterface.php
Fix the parent filter label in relation to the return type of Sonata\AdminBundle\Filter\Filter::getLabel() must be of the type string or null, not bool.
- Inconsistencies with wrong type passed to Sonata\AdminBundle\Filter\Filter::getLabel()
=> Change parent filter label for child admin to be NULL

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/UrlGeneratorInterface.php, src/Model/ModelManagerInterface.php
Allow null as return type for getUrlSafeIdentifier, getNormalizedIdentifier, and id.
- One on SonataDoctrineORM@3.x to remove the deprecation in getNormalizedIdentifier. [SonataDoctrineORMAdminBundle/pull/1194](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1194)
- One on SonataDoctrineORM@master to remove the exception and return null instead. [SonataDoctrineORMAdminBundle/pull/1195](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1195)
Closes #6535
=> Id method allow return null

src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/CRUD/Association/list_many_to_one.html.twig, src/Resources/views/CRUD/Association/list_one_to_one.html.twig, src/Resources/views/CRUD/Association/show_one_to_one.html.twig
In next major only object will be allowed as argument for the `id` method and it seems `null` was passed.
Related to discussion: https://github.com/sonata-project/SonataAdminBundle/pull/6573#discussion_r519220677
Seems Pedantic to me.
=> Add null check before calling the id method

src/Form/Type/AdminType.php, tests/Form/Type/AdminTypeTest.php
I am targeting this branch, because bug fix.
Related to #6564.
See https://github.com/sonata-project/SonataAdminBundle/issues/6564#issuecomment-721078947
Then persistence bundle should pass `collection_by_reference` instead of  `by_reference`.
```markdown
- Added `collection_by_reference` option for AdminType
- `collection_by_reference` is used instead of `by_reference` in AdminType in order to know which call should be used between `ObjectManipulator::addInstance` and `ObjectManipulator::setObject`.
```
=> Avoid conflict with by_reference option

src/Resources/views/CRUD/Association/edit_many_script.html.twig
In next major only object will be allowed as argument for the `id` method, so we need to skip short object information call if object is missing. I find out this when working on [SonataDoctrineORMAdminBundle/pull/1193](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1193). This is happen if delete button of `ModelListType` is used.
=> Fix not to call an id method without object.

src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, tests/Datagrid/DatagridTest.php
```markdown
- Added parameter type hints to `PagerInterface` and `Pager`.
=> [Datagrid] Allow only int on setPage & setMaxPerPage

UPGRADE-3.x.md, src/Datagrid/Datagrid.php
If the filter value is empty, but the filtering type has been changed from the default value, then this is an indication that the user wants to search by empty value.
At this level, we cannot determine whether a search can be performed on an empty value and therefore delegate it to filters.
Part of fix for #3569.
```markdown
- Delegate filter query by empty value to filters.
```
=> Delegate filter query by empty value to filters

UPGRADE-3.x.md, src/Form/Type/Operator/StringOperatorType.php, tests/Form/Type/Operator/StringOperatorTypeTest.php
I am targeting this branch, because BC. This is a new feature.
There is contains and not contains operator, but only the equal operator.
```markdown
- `NOT_EQUAL` operator for `StringOperatorType`
```
=> Add NOT_EQUAL operator for StringOperatorType

UPGRADE-3.x.md, src/Block/AdminSearchBlockService.php, src/Resources/config/block.php, src/Resources/views/Block/block_search_result.html.twig, tests/Block/AdminSearchBlockServiceTest.php
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6589
```markdown
- Not passing 'show', 'hide' or 'fade' as argument 4 to `Sonata\AdminBundle\Block\AdminSearchBlockService()`
```
=> Add deprecation for not passing empty boxes option

src/Datagrid/Datagrid.php, tests/Datagrid/DatagridTest.php
Bug reported https://github.com/sonata-project/SonataAdminBundle/pull/6590
I am targeting this branch, because bug fix.
```markdown
- Apply filter even if the operator is not provided.
```
=> Apply filter even if the operator is not provided

src/Admin/AdminInterface.php, src/Templating/MutableTemplateRegistryAwareInterface.php
When working on merge 3.x into master, I had to make this change because the signature wasn't compatible.
The issue didn't appear on 3.x because we were just using `@method`.
I am targeting this branch, because I consider this as a bug fix.
But I have some questions (cc @wbloszyk) 
- Shouldn't `MutableTemplateRegistryAwareInterface` extends `TemplateRegistryAwareInterface` this way ?
```
interface MutableTemplateRegistryAwareInterface extends TemplateRegistryAwareInterface
{
/**
* @return MutableTemplateRegistryInterface
*/
public function getTemplateRegistry(): TemplateRegistryInterface;
/**
* @param TemplateRegistryInterface
*/
public function setTemplateRegistry(TemplateRegistryInterface $templateRegistry): void;
}
```
- The `TemplateRegistryAwareInterface` is not used at all after …
=> Fix AdminInterface Inheritance

src/Templating/MutableTemplateRegistryAwareInterface.php
I don't know why I made this change in https://github.com/sonata-project/SonataAdminBundle/pull/6597
But it seems wrong to me now.
One clue is the fact that the `@method` and the `NEXT_MAJOR` comment doesn't use the same typehint.
=> Fix @method annotation for MutableTemplateRegistryAwareInterface

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminInterface.php, src/Admin/LifecycleHookProviderInterface.php
=> [3.x] Add deprecation notices related to validate methods

src/Resources/config/actions.php, src/Resources/config/routing/sonata_admin.xml
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6610#discussion_r528924541
```markdown
- Referencing to DashboardAction and SearchAction by FQCN class instead of id.
```
=> Avoid FQCN for controller id

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/Admin/AdminInterface.php, src/Model/ModelManagerInterface.php, src/Templating/TemplateRegistry.php, tests/Admin/AdminTest.php
We've been referencing `sonata-admin/x`, now it's corrected to `sonata-project/x`.
In https://github.com/sonata-project/SonataAdminBundle/pull/6618 there were missing some NEXT_MAJOR comments and also the deprecated version was specified and there hasn't been released yet.
=> Fix sonata-project name and some comments and deprecations

docs/reference/search.rst, src/DependencyInjection/Compiler/AdminSearchCompilerPass.php, src/Search/SearchHandler.php, src/SonataAdminBundle.php, tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php, tests/Search/SearchHandlerTest.php, tests/SonataAdminBundleTest.php
Allow to disable the global search by admin.
Closes #6102.
```markdown
- `AdminSearchCompilerPass` in order to configure which admins must support search.
- Support for `global_search` attribute in `sonata.admin` tags, which admits boolean values.
```
=> Allow to disable the global search by admin

tests/Form/AbstractLayoutTestCase.php, tests/Form/AdminLayoutTest.php
In https://github.com/sonata-project/SonataAdminBundle/pull/6563 I wrongly named the files, the file name with tests was ending in TestCase.php and it did not run tests by PHPUnit.
Just in case, the [previous job](https://github.com/sonata-project/SonataAdminBundle/runs/1452354017): `Tests: 1798, Assertions: 4944, Skipped: 14.`
And [this one](https://github.com/sonata-project/SonataAdminBundle/pull/6627/checks?check_run_id=1457748369): `Tests: 1801, Assertions: 4947, Skipped: 14.`.
=> Fix file name in tests

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Change the visibility of the CRUDController methodes `handleXmlHttpRequestSuccessResponse` and  `handleXmlHttpRequestErrorResponse` from private to protected to allow overriding.
In my application I want to extend the Xml Http response, but there is no way to override it. The only option is to override the editAction but that's not desirable.
I am targeting this branch, because the change is not backwards compatible.
```markdown
- `CRUDController::handleXmlHttpRequestSuccessResponse` method is now protected
- `CRUDController::handleXmlHttpRequestErrorResponse` method is now protected
```
=> Make handle xml http request response protected

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
This PR corrects several issues at once.
> Key "all_elements" for array with keys "idx, action, won" does not exist.
Error in [`SonataAdminBundle:CRUD:batch_confirmation.html.twig`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/batch_confirmation.html.twig#L35)
```twig
<div class="box-body">
{% if data.all_elements %} {# at this line #}
{{ 'message_batch_all_confirmation'|trans({}, 'SonataAdminBundle') }}
{% else %}
{% trans with {'%count%': data.idx|length} from 'SonataAdminBundle' %}message_batch_confirmation{% endtrans %}
{% endif %}
</div>
```
The problem is due to the fact that the `all_elements` is a [checkbox](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/base_list.html.twig#L175) and if it is not …
=> Explicitly cast types in CRUDController::batchAction()

docs/getting_started/creating_an_admin.rst
The note/paragraph points to a non-existing page related to a bundle which is abandoned and no longer maintained (SonataAutoConfigureBundle).
=> [Docs] Remove note with a broken link

src/Resources/views/Form/form_admin_fields.html.twig, tests/Form/AdminLayoutTest.php
Implement the Symfony row_attr for form_row containter attributes.
Useful if you need to add extra classes or data attributes on the container. For example:
```php
$builder->add('period', DateRangeType::class, [
...
'field_options_start' => [
...
'row_attr' => [
'class' => 'col-md-6'
],
],
'field_options_end' => [
...
'row_attr' => [
'class' => 'col-md-6'
],
]
]);
```
Output:
```html
<div class="form-group col-md-6" id="sonata-ba-field-container-s5f996c9e7f416_feature_type_14_feature_126_period_start">
</div>
```
I am targeting this branch, because it's useful from 3.x.
```markdown
- Added `row_attr` to the form_row container.
```
=> Make it possible to add extra form_row container attributes

UPGRADE-3.x.md, src/Action/SetObjectFieldValueAction.php, src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, src/Admin/Pool.php, src/Resources/config/actions.php, src/Resources/config/core.php, src/Resources/config/twig.php, src/Twig/Extension/SonataAdminExtension.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/AdminHelperTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Ref: https://github.com/sonata-project/SonataAdminBundle/issues/6624
PropertyAccesor was added to Pool in order to reuse it for performance reasons in https://github.com/sonata-project/SonataAdminBundle/pull/3488.
In https://github.com/symfony/symfony/pull/16838 cache was added to the component, so there is no need to reuse it thought the Pool service and it can be injected into the services.
```markdown
- Deprecated `Pool::getPropertyAccessor()` method.
- Deprecated not passing and instance of `PropertyAccessor` as argument 1 to `Sonata\AdminBundle\Admin\AdminHelper` constructor.
- Deprecated not passing and instance of `PropertyAccessor` as argument 5 to `Sonata\AdminBundle\Action\SetObjectFieldValueAction` constructor.
- …
```
=> Deprecate Pool::getPropertyAccessor() method

src/Form/Type/AdminType.php
Constructing a `PropertyAccessor` should be done through `PropertyAccess`.
EDIT: I added `PropertyAccessorBuilder::disableMagicMethods` first, but this is only available in `symfony/property-access` 5, I've changed it to `PropertyAccessorBuilder::disableMagicCall`.
PHPStan was complaining about this code: https://github.com/sonata-project/SonataAdminBundle/pull/6637/checks?check_run_id=1472741426 (because the release of Symfony 5.2)
=> Create PropertyAccessor through builder

src/Resources/public/Admin.js
Replace jQuery(window).load with jQuery(window).on('load', handler)
#6629
This is a simple PR to replace the deprecated (since jQuery 1.8) and removed (since jQuery 3.0) usage of jQuery.load(handler) with jQuery.on('load', handler).
I am targeting this branch, because I would like our Sonata projects to have better compatibility with newer versions of jQuery.
Closes #6629.
```markdown
- Replaced jQuery "load()" with "on()" in Admin.js
```
=> #6629 Replace jQuery "load" with "on"

docs/cookbook/recipe_overwrite_admin_configuration.rst, docs/reference/advanced_configuration.rst, docs/reference/architecture.rst, docs/reference/configuration.rst, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Configuration.php, tests/DependencyInjection/ConfigurationTest.php
```markdown
- Option to globally override the data source of all the admin
```
=> Add data source in configuration and documentation

src/Resources/views/CRUD/display_currency.html.twig, src/Resources/views/CRUD/display_percent.html.twig, src/Resources/views/CRUD/list_currency.html.twig, src/Resources/views/CRUD/list_percent.html.twig, tests/Twig/Extension/SonataAdminExtensionTest.php
When using this code:
```
protected function configureListFields(ListMapper $listMapper): void
{
$listMapper
->add('rate', TemplateRegistry::TYPE_PERCENT);
}
```
And the value of "rate" is NULL, the current return value is "0 %". I think the value must be "\&nbsp;" for NULL and "0 %" for 0. Also return "\&nbsp;" when currency is NULL.
Same change for configureShowFields.
I am targeting this branch, because it's BC.
```markdown
Twig templates: "list_percent", "show_percent", "list_currency" and "show_currency"
```
=> When "percent" field is NULL, show non breaking space instead of 0

UPGRADE-3.x.md, docs/reference/action_list.rst, docs/reference/form_types.rst, src/Datagrid/SimplePager.php, src/Filter/FilterInterface.php, src/Model/ModelManagerInterface.php, tests/Fixtures/Filter/FooFilter.php
I think it's pedantic.
We should always call the `ProxyQueryInterface` param the same way ; and most of the time it's called `$query`.
Even if the method `filter` is deprecated, the param shouldn't be called `$queryBuilder` then.
I also improve the `phpdoc` for
```
public function apply($query, $value);
```
and I'm wondering if we shouldn't use a better name than `$value`, since it's an array with this shape
```
array{type?: string, value?: mixed}
```
`$filter` ? `$data` ? Keeping this way ?
=> Rename ProxyQueryInterface param and improve phpdoc

UPGRADE-3.x.md, src/Model/ModelManagerInterface.php
I am targeting this branch, because it's a feature.
Closes #6519 
```markdown
- Removed alias from `ModelManagerInterface::createQuery` method
```
=> Removed alias from ModelManagerInterface::createQuery

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Configuration.php, tests/Admin/AdminTest.php
```markdown
- `AbstractAdmin::$validator` property
- `AdminInterface::getValidator` method specification
- `AdminInterface::setValidator` method specification
- `AbstractAdmin::getValidator` method implementation
- `AbstractAdmin::setValidator` method implementation
- `AddDependencyCallsCompilerPass` - validator related keys
- `DependencyInjection/Configuration` - validator related config option
```
=> [3.x] Add validator related deprecation notices

UPGRADE-3.x.md, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, src/Builder/BuilderInterface.php, tests/Admin/BaseFieldDescriptionTest.php, tests/Fixtures/Admin/FieldDescription.php
Mapping should not be changed in the FieldDescriptionInterface once it is set, deprecating these methods forces to set these mapping attributes when constructing the object.
It is also related to https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/461
`FieldDescriptionInterface::setMappingType` [looks like it is not being used](https://github.com/search?q=org%3Asonata-project+setMappingType&type=code) (it makes sense because the mapping type is being set when the field mapping is set).
Not sure how to handle these method making then `abstract protected` in the next major version.
```markdown
- Added 3 new arguments to `BaseFieldDescription::__construct()` to do create a FieldDescription with the mapping.
- …
```
=> Deprecate mapping setters from FieldDescriptionInterface

UPGRADE-3.x.md, src/Admin/Pool.php, src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php, src/DependencyInjection/SonataAdminExtension.php, src/Resources/config/core.php, src/Resources/config/twig.php, src/Resources/views/Block/block_admin_list.html.twig, src/Resources/views/CRUD/base_acl.html.twig, src/Resources/views/CRUD/base_acl_macro.html.twig, src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig, src/Resources/views/Core/add_block.html.twig, src/Resources/views/Core/dashboard.html.twig, src/Resources/views/Core/search.html.twig, src/Resources/views/Menu/sonata_menu.html.twig, src/Resources/views/standard_layout.html.twig, src/SonataConfiguration.php, src/Twig/Extension/GroupExtension.php, src/Twig/GlobalVariables.php, tests/Admin/PoolTest.php, tests/SonataConfigurationTest.php, tests/Twig/Extension/GroupExtensionTest.php, tests/Twig/GlobalVariablesTest.php
Part of https://github.com/sonata-project/SonataAdminBundle/issues/6624
This class (I wasn't sure in which folder should go) will handle configuration for sonata which is currently holded by Pool class.
It adds a global twig `sonata_config` variable in order to replace the current `sonata_admin` variable whose name could mislead to think that is some kind of admin.
`sonata_admin` is registered as global twig variable in:
https://github.com/sonata-project/SonataAdminBundle/blob/ea9f3a47bee1d47e6ee74d53cb3103747ec326ec/src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php#L27-L31
https://github.com/sonata-project/SonataAdminBundle/blob/ea9f3a47bee1d47e6ee74d53cb3103747ec326ec/src/Resources/config/core.php#L216-L223
All `GlobalVariables` methods have been deprecated:
- `url` and …
=> Introduce SonataConfiguration class

docs/reference/configuration.rst, docs/reference/extensions.rst, psalm-baseline.xml, src/DependencyInjection/Compiler/ExtensionCompilerPass.php, src/DependencyInjection/Configuration.php, tests/DependencyInjection/Compiler/ExtensionCompilerPassTest.php
Is is now possible to register a global admin extension via the configuration. This was only possible for tags.
The next step (new PR) is to allow all extension configuration for tags.
I am targeting this branch, because this feature is BC.
```markdown
- Add support for global admin extensions via config
```
=> Add support for global admin extensions via config

src/Admin/Pool.php, tests/Admin/PoolTest.php
The parameters passed to `sprintf` were in the wrong order, I should've added the `expectDeprecation` in https://github.com/sonata-project/SonataAdminBundle/pull/6640.
=> Fix trigger_error messages

src/Resources/views/CRUD/base_show_field.html.twig, src/Twig/Extension/SonataAdminExtension.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Currently, when rendering the entity compare view in the history action, only the current (first) entity object will be passed to the view, even when it is going to render the value of the comparing (secondary) entity object. This means that the `field` block of the show field template will receive the first entity (the base object) along with the secondary value (value to compare) when the secondary value is going to be rendered. This can cause problem if the template does not solely rely on the value but also the object for the correct output. This PR fixes this.
I am targeting this branch, because it is backward-compatible. Note that after applying the patch, the block `field_compare` in template `base_show_field.html.twig` will assume the the existence of the `object_compare` …
=> Fix incorrect object passed to the view when rendering the history compare action

UPGRADE-3.x.md, src/Admin/Pool.php, src/Twig/Extension/GroupExtension.php, tests/Admin/PoolTest.php
I was trying to manual merge `3.x`, but phpstan failed because the array specified in `GroupExtension` is different from https://github.com/sonata-project/SonataAdminBundle/blob/8c0d58a24e4e02dba56eea168d1e3564d4ac5c85/src/Admin/Pool.php#L108-L111
So I added more specific info.
~Not sure if should be `pedantic` or if I should add a changelog.~
~While doing this I found that `Pool::getGroups()` method maybe it's not used because the code doesn't make sense with the current groups.~ https://github.com/sonata-project/SonataAdminBundle/pull/6659#issuecomment-739559129
```markdown
- Deprecated `Pool::getGroups()` method.
- Deprecated `Pool::hasGroup()` method.
- Deprecated `Pool::getAdminsByGroup()` method.
```
=> Deprecate some Pool methods related to groups and fix array shapes

UPGRADE-3.x.md, src/Filter/Filter.php, tests/Filter/FilterTest.php, tests/Fixtures/Filter/FooFilter.php
I discovered that our persistence bundle override the `isActive` method
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Filter/Filter.php#L37
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Filter/Filter.php#L43
And the `setValue`/`getValue` are not used.
```markdown
- Added `Sonata\AdminBundle\Filter\Filter::active` property.
- `Sonata\AdminBundle\Filter\Filter::getValue()`
- `Sonata\AdminBundle\Filter\Filter::setValue()`
```
=> Deprecate AbstractFilter value property

src/Datagrid/ListMapper.php, tests/Datagrid/ListMapperTest.php
Related to https://github.com/sonata-project/SonataAdminBundle/issues/6649
Closes #6649.
```markdown
- Fixed disallowing sorting in a field defined with a closure in `associated_property`.
```
=> Disable sorting for an associated_property callable

tests/Util/AdminObjectAclManipulatorTest.php
We were using `$this->data` in a test extending from `TestCase` and `$data` it is a private attribute of `TestCase`, so this PR changes this variable name to `aclData` to avoid name collision.
PHPStorm was complaining about this.
=> Fix property name in test

src/Admin/AdminHelper.php, src/Util/FormBuilderIterator.php, tests/Admin/AdminHelperTest.php, tests/Util/FormBuilderIteratorTest.php
Triggered by https://github.com/sonata-project/SonataAdminBundle/pull/6689#discussion_r540314983
`AdminHelper::getChildFormBuilder()` method was iterating only over the first level of form builder. It is needed a
`RecursiveIteratorIterator` for a tree traversal as `AdminHelper::getChildFormView()` method does.
It also fixes FormBuilderIterator prefix property when traversing children, now the current prefix is passed to the
children to create its key.
```markdown
- Deprecated passing other type than `string` or `null` as argument 2 constructing `FormBuilderIterator`.
- Fixed iterating over children names in `AdminHelper::getChildFormBuilder` recursively.
```
When merging with `4.x`, …
=> Fix iterating over children in form builder

tests/Controller/CRUDControllerTest.php, tests/Fixtures/Util/DummyDomainObject.php
In the next major version this class will be final, this replaces a mock with an instance of `AdminObjectAclManipulator`.
=> Use instance of AdminObjectAclManipulator

tests/Action/SearchActionTest.php, tests/Block/AdminSearchBlockServiceTest.php
Following https://github.com/sonata-project/SonataAdminBundle/pull/6705
Apparently after this, only `Pool` and `AdminHelper` are the ones remaining from https://github.com/sonata-project/SonataAdminBundle/pull/6543#issue-510215361
=> Use instance of SearchHandler in tests

src/Resources/views/Pager/base_links.html.twig
See https://github.com/sonata-project/SonataAdminBundle/pull/6640#issuecomment-741618229
There was one use left that was not changed.
```markdown
- Fixed using `admin_pool` to fetch an option instead of `sonata_config`.
```
=> Use sonata_config instead of admin_pool

src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, src/Datagrid/SimplePager.php, src/Resources/views/Block/block_stats.html.twig, tests/App/Datagrid/Pager.php, tests/Datagrid/PagerTest.php
Closes #6294
```markdown
- `getPage()` to the PagerInterface.
- `getFirstPage()` to the PagerInterface.
- `getLastPage()` to the PagerInterface.
- `getNextPage()` to the PagerInterface.
- `getPreviousPage()` to the PagerInterface.
- `isFirstPage()` to the PagerInterface.
- `isLastPage()` to the PagerInterface.
- `getNbResults()` to the PagerInterface.
- `getLinks()` to the PagerInterface.
- `haveToPaginate()` to the PagerInterface.
- `getQuery()` to the PagerInterface.
- `AbstractPager::getCurrentMaxLink()`
- `AbstractPager::getMaxRecordLimit()` 
- `AbstractPager::setMaxRecordLimit()`
- `AbstractPager::getCursor()`
- `AbstractPager::setCursor()`
- `AbstractPager::getObjectByCursor()`
- `AbstractPager::getCurrent()`
- `AbstractPager::getNext()`
- …
```
=> Add some methods, coming from AbstractPager and used in twig to PagerInterface

src/Resources/views/CRUD/Association/edit_many_to_many.html.twig
When working with adding and removing entities from the CollectionType field, it can happen that the array index not starts with 0 but has an length > 0. This leads to an error since that index 0 is unset. So using twig first function here to handle this case.
I am targeting this branch, because this branch contains the error this patch will fix. Its backwards compatible.
```markdown
- Replaced 'array[0]' by 'array|first' to fix edit_many_to_many template when children index does not start with 0.
```
=> Improves getting of first array element

UPGRADE-3.x.md, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, tests/Admin/BaseFieldDescriptionTest.php
Similar to https://github.com/sonata-project/SonataAdminBundle/pull/6648
IMHO: the fieldName should be immutable.
And I don't see usage of the `setFieldName` method.
```markdown
- one argument to `BaseFieldDescription::construct()` to set the field name.
- `FieldDescriptionInterface::setFieldMapping()`
- `BaseFieldDescription::setFieldMapping()`
```
=> Deprecate field name setter from FieldDescriptionInterface

src/Admin/AbstractAdmin.php
I got this weird error recently.
```markdown
- Stop throwing an exception when the `_per_page`  filter parameter is not set
```
=> Check for _per_page existence

src/Action/DashboardAction.php, src/Action/SearchAction.php, src/Block/AdminListBlockService.php, src/Block/AdminSearchBlockService.php, src/Block/AdminStatsBlockService.php, src/Controller/CRUDController.php, tests/Action/SearchActionTest.php, tests/Controller/CRUDControllerTest.php
Since `sonata-project/admin-bundle` 3.83, `Pool` is just used as an Admin registry, before this, `admin_pool` was used to access to global options from Twig, but now there is a global Twig `sonata_config` variable to access to those options.
Here are the usages of `admin_pool`: https://github.com/sonata-project/SonataAdminBundle/search?p=1&q=admin_pool
So there is no need to pass an instance of `Pool` to Twig templates anymore, the pool is not supposed to be used in templates.
What I don't know is in which file should I add that in `4.0` these variables are not going to be available, just in the changelog when removing those lines in `4.x` branch?
=> Remove passing admin_pool to twig templates in next major version

UPGRADE-3.x.md, src/Route/RouteCollection.php, src/Route/RouteCollectionInterface.php
Related https://github.com/sonata-project/SonataAdminBundle/issues/6698
This interface was added in 4.x branch, this commit imports it removing type and return declarations to make it compatible with `RouteCollection` which implements this interface.
In sonata 4 `AbstractAdmin::configureRoutes()` method receives a `RouteCollectionInterface`, importing this interface in 3.x would allow users to update their code and define this method as in 4, easing the upgrading process.
This would only work for users with PHP >= 7.4 because contravariance was fully support since that version, to me this is fine, but we could remove `AbstractAdmin::configureRoutes()` and `AdminExtensionInterface::configureRoutes()` methods and add some `method_exists` checks and reintroduce these methods in `4.x` branch. …
=> Add RouteCollectionInterface

src/Form/FormMapper.php
Pedantic.
Currently, with
```
->add('foo.barBaz`)
```
and the label underscore strategy.
The show label is `show.label_foo_bar_baz`.
The form label is `form.label_foo__bar_baz`.
The issue is that for the form, `.` are forbidden and replaced by `__`.
But we should use the given name for the label, instead of the new sanitized one.
This will add consistency in next major. I don't fix it in 3.x to avoid people to rewrite every label.
=> Fix form label in next major

UPGRADE-3.x.md, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php
When working on an issue of SonataDoctrineORMAdminBundle, I discovered that `getFieldValue` was in the interface, but to me it's a method implemented in BaseFieldDescription to help the `getValue` implementation.
So I propose to restrict the visibility of this method.
```markdown
- `FieldDescriptionInterface::getFieldValue()`
```
=> Remove public access for getFieldValue

phpstan-baseline.neon, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, src/Datagrid/SimplePager.php, src/DependencyInjection/Admin/AbstractTaggedAdmin.php, src/DependencyInjection/Admin/TaggedAdminInterface.php, src/Filter/Filter.php, src/Security/Handler/AclSecurityHandlerInterface.php, src/Security/Handler/SecurityHandlerInterface.php, src/Util/AdminObjectAclData.php, src/Util/FormBuilderIterator.php, src/Util/FormViewIterator.php, tests/Datagrid/PagerTest.php, tests/Util/FormBuilderIteratorTest.php
I am targeting this branch, because BC. Because the TaggedAdminInterface is not released.
After the merge, I will edit the previous changelog.
Moving `getListModes` to `AbstractTaggedAdmin` is consistent with others changes and allow to restrict the visibility of the `listModes` property to private in nextMajor.
I also
- Update the 3.x comments since I'm fixing conflicts
- Fix some issues I find during the merge from 3.x into master
```markdown
- Added `AbstractTaggedAdmin::getListModes()`.
- Added `TaggedAdminInterface::getListModes()`.
```
=> Move getter from TaggedAdminInterface to AdminInterface

composer.json, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php, src/Admin/Extension/LockExtension.php, src/Event/AdminEventExtension.php
I'm not sure about this, if generics should apply to `AdminExtensionInterface`. I've made this PR since I was looking at [`AbstractTranslatableAdminExtension`](https://github.com/sonata-project/SonataTranslationBundle/blob/cdf35c8574751d86792c8ac60ca1c2ae5d37be75/src/Admin/Extension/AbstractTranslatableAdminExtension.php) and looks like `@phpstan-extends AbstractAdminExtension<TranslatableInterface>` could apply there.
```markdown
- Added generics to `AdminExtensionInterface`.
```
=> Add generics to AdminExtensionInterface

src/Resources/views/CRUD/Association/edit_many_script.html.twig
After updating to 3.84 I found some Twig runtime error related to missing "admin" variable. Probably one extra check will fix the issue or someone with more experience can suggest better solution.
I am targeting this branch, because of BC.
```markdown
Variable "admin" does not exist in `CRUD/Association/edit_many_script.html.twig`
```
=> Fix - Variable "admin" does not exist.

UPGRADE-3.x.md, src/Action/SearchAction.php, src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, src/Datagrid/SimplePager.php, src/Resources/views/Block/block_search_result.html.twig, src/Resources/views/Block/block_stats.html.twig, tests/App/Datagrid/Pager.php, tests/Datagrid/PagerTest.php, tests/Datagrid/SimplePagerTest.php
Closes #6710
```markdown
- Added `PagerInterface::countResults`
- `PagerInterface::getNbResults()` in favour of `countResults()`
- `PagerInterface::setNbResults(...)`
- `PagerInterface::$nbResults`
```
=> deprecate PagerInterface::getNbResults() in favour of countResults()

src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/Pager/base_results.html.twig, src/Resources/views/Pager/simple_pager_results.html.twig
Follow-up for https://github.com/sonata-project/SonataAdminBundle/pull/6732#issuecomment-755198595
=> fix missing places for deprecating Pager::getNbResults()

src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, src/Show/ShowMapper.php, tests/Form/FormMapperTest.php, tests/Show/ShowMapperTest.php
BC
```markdown
- `Added BaseGroupMapper::removeGroup()`
- `Added BaseGroupMapper::removeTab()`
```
=> Add removeTab method

composer.json, src/Admin/Pool.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Resources/config/core.php
The ServiceLocator will only have admin services and there is no need to make admin services public anymore.
I am targeting this branch, because this is BC break.
Closes #6624.
```markdown
- Admin services are not made public anymore.
```
=> Inject a ServiceLocator to Pool instead of container

UPGRADE-3.x.md, docs/reference/action_list.rst, docs/reference/action_show.rst, docs/reference/field_types.rst, src/Action/SetObjectFieldValueAction.php, src/Admin/FieldDescriptionInterface.php, src/DependencyInjection/AbstractSonataAdminExtension.php, src/Form/DataTransformerResolver.php, src/Resources/views/CRUD/base_list_field.html.twig, src/Templating/TemplateRegistryInterface.php, tests/App/Admin/FooAdmin.php, tests/App/Admin/TranslatedAdmin.php
They have been moved to `FieldDescriptionInterface` since they are the values of `FieldDescriptionInterface::getType()`.
In the future, maybe we can create classes for each type and have some configuration and logic in there instead of having it in the associated template.
Closes #6749.
```markdown
- Deprecated `TemplateRegistryInterface::TYPE_*` constants, they have been moved to `FieldDescriptionInterface`.
```
=> Move TemplateRegistryInterface::TYPE_* constants

UPGRADE-3.x.md, src/Controller/CRUDController.php
In next major version, the controller will be configured with an external call from an event listener instead of using setContainer method.
For more context: https://github.com/sonata-project/SonataAdminBundle/pull/6615
```markdown
- Deprecated `CRUDController::configure()` method, to configure the associated admin, you should call `CRUDController::configureAdmin()` instead.
```
=> Deprecate CRUDController::configure() method

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Resources/public/Admin.js, src/Resources/views/CRUD/base_list.html.twig
I am targeting this branch, because created new feature for SonataAdminBundle: **Only changed filters will be submitted. Made admin`s urls shorter as possible.**
Closes #6642.
```markdown
- Added `AbstractAdmin::getDefaultFilterParameters()` to get default filter parameters.
- Only changed (non default, non empty) filters will be submitted.
```
=> Unchanged filters params

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Resources/config/core.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
The arguments are wrong because they are already arrays.
Projects should not fail because these arguments are overriden by the method calls:
```php
$pool->addMethodCall('setAdminServiceIds', [$admins, 'sonata_deprecation_mute']);
$pool->addMethodCall('setAdminGroups', [$groups, 'sonata_deprecation_mute']);
$pool->addMethodCall('setAdminClasses', [$classes, 'sonata_deprecation_mute']);
```
```markdown
- Fixed `Pool` definition arguments.
```
=> Some Pool definition fixes

src/DependencyInjection/Admin/AbstractTaggedAdmin.php
They were removed, I added patch as I'm getting phpstan errors:
```
Method App\Admin\FooAdmin::__construct() has parameter $baseControllerName with no typehint specified.
Method App\Admin\FooAdmin::__construct() has parameter $code with no typehint specified.
```
```markdown
- Added missing phpdoc type declarations.
```
=> Add missing phpdoc type declarations

src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php
DoctrineORMBundle need the Query to implement the DoctrineORMBundle\Datagrid\ProxyQueryInterface.
This will allow the Pager to restrict the type of the $query.
```markdown
- Add generics to `PagerInterface`.
```
=> Add generic for PagerInterface

docs/reference/advanced_configuration.rst, docs/reference/configuration.rst, psalm-baseline.xml, psalm.xml, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, src/Maker/AdminMaker.php, src/Resources/config/makers.php, src/Resources/skeleton/AdminController.tpl.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php
This is a follow-up of https://github.com/sonata-project/SonataAdminBundle/pull/5307.
```markdown
- Added `default_controller` to configure the default controlled used by the admins.
```
=> Added default_controller configuration option

UPGRADE-3.x.md, src/Action/SetObjectFieldValueAction.php, src/Resources/config/twig.php, src/Twig/Extension/CanonicalizeExtension.php, src/Twig/Extension/RenderElementExtension.php, src/Twig/Extension/SecurityExtension.php, src/Twig/Extension/SonataAdminExtension.php, src/Twig/Extension/XEditableExtension.php, tests/Controller/HelperControllerTest.php, tests/Twig/Extension/CanonicalizeExtensionTest.php, tests/Twig/Extension/RenderElementExtensionTest.php, tests/Twig/Extension/SecurityExtensionTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php, tests/Twig/Extension/XEditableExtensionTest.php
Closes #6639.
```markdown
- Added `Sonata\AdminBundle\Twig\Extension\SecurityExtension`
- Added `Sonata\AdminBundle\Twig\Extension\CanonicalizeExtension`
- Added `Sonata\AdminBundle\Twig\Extension\XEditableExtension`
- Added `Sonata\AdminBundle\Twig\Extension\RenderElementExtension`
- Deprecated `SonataAdminExtension::MOMENT_UNSUPPORTED_LOCALES` constant
- Deprecated `SonataAdminExtension::setXEditableTypeMapping()` method
- Deprecated `SonataAdminExtension::getXEditableType()` method
- Deprecated `SonataAdminExtension::getXEditableChoices()` method
- Deprecated `SonataAdminExtension::getCanonicalizedLocaleForMoment()` method
- Deprecated `SonataAdminExtension::getCanonicalizedLocaleForSelect2()` method
- Deprecated …
```
=> [Twig] Split SonataAdminExtension

UPGRADE-3.x.md, src/Form/Type/Operator/DateOperatorType.php
I recommend deprecating these two constants. 
The UX is weird because you can still provide a value when you selected these types.
I recommend instead using a specific filter for null values like the `NullFilter` of DoctrineORMAdminBundle.
```markdown
- Deprecate `DateOperatorType::TYPE_NULL` and `DateOperatorType::TYPE_NOT_NULL`
```
=> Deprecate DateOperatorType::TYPE_NULL and TYPE_NOT_NULL

UPGRADE-3.x.md, phpstan-baseline.neon, src/Action/RetrieveAutocompleteItemsAction.php, src/Action/SearchAction.php, src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php, src/Datagrid/Pager.php, src/Datagrid/PagerInterface.php, src/Datagrid/SimplePager.php, src/Resources/views/Block/block_search_result.html.twig, src/Resources/views/CRUD/base_list.html.twig, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/App/Datagrid/Pager.php, tests/Datagrid/DatagridTest.php, tests/Datagrid/SimplePagerTest.php
I just discover that
```
count($pager->getResults()) !== $pager->countResults()
```
And I think it's misleading.
`getResults` is returning the results of the current page, so I think it's better to rename this function.
I also close #6620
```markdown
- Added `PagerInterface::getCurrentPageResults()`
- Added `PagerInterface::getResults()`
```
=> Deprecate getResults in favor of getCurrentPageResults

src/Resources/translations/SonataAdminBundle.bs.xliff, src/Resources/translations/SonataAdminBundle.sr_Cyrl.xliff, src/Resources/translations/SonataAdminBundle.sr_Latn.xliff
```markdown
- Translation file for `bs` (Bosnian).
- Translation files for `sr_Latn` & `sr_Cyrl` (Serbian Latin & Cyrillic script).
```
=> Add Serbian (Lat & Cyrl) & Bosnian translation

composer.json, src/DependencyInjection/Compiler/AdminMakerCompilerPass.php, src/Maker/AdminMaker.php, src/SonataAdminBundle.php, tests/DependencyInjection/Compiler/AdminMakerCompilerPassTest.php, tests/Maker/AdminMakerTest.php, tests/SonataAdminBundleTest.php
The third argument of `AdminMaker` could be a service name:
https://github.com/sonata-project/SonataAdminBundle/blob/d3f9b58fa7cdf0c02128c09a89c0f4ae8415b1df/src/Resources/config/makers.php#L27
This PR adds a compiler pass which retrieves this parameters and check if it is a service, in that case, it replaces the argument 3 by the class name of the service definition.
```markdown
- Fixed using admin maker command having a default controller service.
```
=> Fix argument 3 of AdminMaker

src/Admin/AbstractAdmin.php, src/Templating/MutableTemplateRegistry.php, src/Templating/MutableTemplateRegistryAwareInterface.php, tests/Templating/MutableTemplateRegistryTest.php
This PR will revert some deprecations to allow override `Admin` templates in old way.
Also override templates by `TemplateRegistry::setTemplates()` should not replace but override it. People can call it in own code and break application working.
```markdown
- Added `Sonata\AdminBundle\Templating\MutableTemplateRegistryAwareInterface::setTemplate()`
- Added `Sonata\AdminBundle\Templating\MutableTemplateRegistryAwareInterface::setTemplates()`
- Removed deprecations for `Sonata\AdminBundle\Admin\AbstractAdmin::setTemplate()`
- Removed deprecations for `Sonata\AdminBundle\Admin\AbstractAdmin::setTemplates()`
```
=> Fix admin template setters

.github/workflows/test.yaml, composer.json
Closes #6739
Then https://github.com/sonata-project/dev-kit/pull/1355 can be merged
```markdown
- Allow PHP 8
```
=> Allow PHP8

src/Form/DataTransformer/ModelToIdPropertyTransformer.php, tests/Form/DataTransformer/ModelToIdPropertyTransformerTest.php
Related to https://github.com/sonata-project/SonataAdminBundle/issues/6779 (fix needs to be merged into master first).
```markdown
- fixed phpdoc for `Sonata\AdminBundle\Form\DataTransformer\ModelToIdPropertyTransformer::$property` which can be `string[]` as well
```
=> fix phpdoc for ModelToIdPropertyTransformer::$property + add test

src/Admin/AbstractAdmin.php
This is pedantic.
All these exceptions are not meant to be caught, but should lead to a developer code modifcation.
So we should use \LogicException instead of \RuntimeException.
=> Remove RuntimeException (mostly in NEXT_MAJOR comment)

src/DependencyInjection/AbstractSonataAdminExtension.php
Fix default "show" template for type "float" from SonataIntlBundle.
If SonataIntlBundle is available, when using the "float" type in the "show" view, the extension is picking the template for the "list" view (`@SonataIntl/CRUD/list_decimal.html.twig`). This PR fixes that, using the right template for the "show" view (`@SonataIntl/CRUD/show_decimal.html.twig`).
```markdown
- Default "show" template for type "float" from SonataIntlBundle.
```
=> Fix default "show" template for type "float" from SonataIntlBundle

phpstan-baseline.neon, src/Admin/AdminHelper.php, tests/Admin/AdminHelperTest.php
Fix form rendering of nested Admin properties.
I am targeting this branch, because everything is backwards compatible.
Closes #6777.
```markdown
How `AdminHelper::appendFormFieldElement` renders nested forms.
```
=> fix nested admin (one-to-one-to-many relation) that opens inline (fixes #6777)

src/Admin/Pool.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, tests/Block/AdminListBlockServiceTest.php
I am targeting this branch, because this breaks BC.
```markdown
- Add final modifier to `Pool` class.
```
PS: @wbloszyk I'm not updated with the template changes, can we remove all template related methods from `Pool`? All of them are deprecated, but this one:
https://github.com/sonata-project/SonataAdminBundle/blob/28f49a881015e0df91602214fe94dd754ddcdf38/src/Admin/Pool.php#L370-L376
So I guess we can remove it, but just in case.
=> Make Pool final

UPGRADE-3.x.md, src/Admin/Pool.php, src/Resources/config/core.php, tests/Action/DashboardActionTest.php
Based on the comments: https://github.com/sonata-project/SonataAdminBundle/pull/6792#issuecomment-764102492
This deprecates `Pool::setTemplateRegistry` in `3.x`.
```markdown
- Deprecated `Pool::setTemplateRegistry()` method.
```
=> Deprecate Pool::setTemplateRegistry

src/Admin/BaseFieldDescription.php, tests/Admin/BaseFieldDescriptionTest.php
It will solve https://github.com/sonata-project/SonataAdminBundle/issues/6795 and we will rely on propertyAccessor implementation instead of a custom one.
We're loosing the parameters option but I'm not sure it's used and it's solvable by using a custom template instead.
```markdown
- FieldDescription `parameters` option.
```
=> Use propertyAccessor for BaseFieldDescription::getFieldValue

phpstan-baseline.neon, phpstan.neon.dist, src/Admin/FieldDescriptionCollection.php, src/Datagrid/SimplePager.php, src/Twig/Extension/SonataAdminExtension.php
During last update (to level 5) https://github.com/sonata-project/SonataAdminBundle/pull/6277#issue-466353939 I thought that it will be last one, because level 6 gives 983 errors in 136 files. But now I've discovered that, you can enable rules partially and found config folder (https://github.com/phpstan/phpstan-src/tree/master/conf) of PHPStan, where it describes each level. I'll do smallest possible rule adding, since it can take long time to merge big PRs.
I am targeting this branch, because it's not BC break.
Half way to phpstan level 6
`Pedantic` PR.
------------------
This is how config looks with error count
```neon
includes:
- phpstan-baseline.neon
parameters:
parallel:
processTimeout: 300.0
level: 5
paths:
- src
excludes_analyse:
- src/Resources/**.tpl.php
scanFiles:
- …
```
=> - partially move PHPStan to level6

src/Admin/AbstractAdmin.php, src/Route/RouteCollection.php, src/Route/RouteCollectionInterface.php
Currently, I don't see any way to get the routeName of the postAdmin list.
It's computed as `sprintf('%s_%s', $this->baseRouteName, $name);` in `RouteCollection::add` and it's done the same way in the AbstractAdmin.
- I would like to avoid writing the same thing in my code, I think the developer should rely in a method instead
- In the Sonata code, it should be implemented only once
I'm not sure about the name of the method and where to put it.
Now you can do `$this->admin->getRoutes()->getRouteName('show')`.
I would have prefer to do `$this->admin->getRouteName('show')` but then it would be harder to call it in `RouteCollection`.
```markdown
- Added `RouteCollection::getRouteName`
- Added `RouteCollectionInterface::getRouteName`
```
=> Add RouteCollection::getRouteName

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php
The form options could allow some logic, for instance it could depends on the roles. It's not possible with a property, it will be with a method.
```markdown
- Added some `Sonata\AdminBundle\Admin\AbstractAdmin::configureFormOptions()` to do great stuff.
- Deprecated `Sonata\AdminBundle\Admin\AbstractAdmin::formOptions` property. 
```
=> replace formOptions property by configureFormOptions method

src/Resources/views/CRUD/base_list.html.twig
```markdown
- Stop displaying the filter dropdown with no usable filters
```
=> Fix display of select filter list with no choice

src/Resources/views/CRUD/base_list.html.twig
```markdown
- A block `table` to override the whole datagrid table in the `base_list.html.twig`
```
=> Allow to override the whole list table

src/Resources/views/CRUD/base_list.html.twig
```markdown
- Do not add a '-' between the export button and the pager results if there is no pager results.
```
=> Do not add '-' when there is nothing on the right side

src/Datagrid/ProxyQueryInterface.php, src/Datagrid/SimplePager.php, tests/App/Datagrid/ProxyQuery.php, tests/Datagrid/SimplePagerTest.php
Closes #6260.
```markdown
- `ProxyQueryInterface::execute(array $params = [], ?int $hydrationMode = null)` signature to `ProxyQueryInterface::execute()`
```
=> Remove param from ProxyQueryInterface::execute

src/Datagrid/DatagridMapper.php, tests/Datagrid/DatagridMapperTest.php
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1297
The field_name option shouldn't be set by default, in order to let the persistence bundle to set it correctly this way:
```
$fieldDescription->setOption('field_name', $fieldDescription->getOption('field_name', $fieldDescription->getFieldName()));
```
I tried in DoctrineORMAdmin to comment the code I removed here, and the functional tests are working.
=> Remove default field_name value

src/SonataConfiguration.php
fixes
``` 
------ ------------------------------------------------------------------------------------------ 
Line   SonataConfiguration.php                                                                   
------ ------------------------------------------------------------------------------------------ 
67     PHPDoc tag @var does not specify variable name.                                           
67     PHPDoc tag @var has no value type specified in iterable type array.                       
💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type  
------ ------------------------------------------------------------------------------------------ 
```
=> fix phpstan error

UPGRADE-3.x.md, docs/getting_started/the_list_view.rst, docs/reference/architecture.rst, src/Admin/AbstractAdmin.php, src/Datagrid/DatagridMapper.php, tests/Datagrid/DatagridMapperTest.php
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6828
Currently there is two way to pass `field_type` and `field_options`
- Directly in the filterOption param
- By the filterType and filterOptions param
It creates issues when both are used. One way to do things is better.
So I propose to migrate the `DatagridMapper::add` method from 6 to 4 parameters.
```markdown
- From `DatagridMapper::add($name, $type, $filterOptions = [], $fieldType = null, $fieldOptions = null, $fieldDescriptionOptions = [])` to `DatagridMapper::add($name, $type, $filterOptions = [], $fieldDescriptionOptions = [])`
```
=> Deprecate old datagridMapper signature

UPGRADE-3.x.md, docs/reference/action_list.rst, src/Admin/BaseFieldDescription.php, tests/Admin/BaseFieldDescriptionTest.php
Closes #6831.
Closes #6741.
```markdown
- `FieldDescription` `accessor` option
- `FieldDescription` `code` option
```
=> Add accessor property instead of code

src/Admin/AdminHelper.php
I am targeting this branch, because we should make it `@internal` on master
See https://github.com/sonata-project/SonataAdminBundle/issues/5791#issuecomment-770267212
```markdown
- class `Sonata\AdminBundle\Admin\AdminHelper` is now marked `@internal` 
```
=> make AdminHelper @internal

src/Filter/Filter.php, src/Form/Type/Filter/ChoiceType.php, src/Form/Type/Filter/DateRangeType.php, src/Form/Type/Filter/DateTimeRangeType.php, src/Form/Type/Filter/DateTimeType.php, src/Form/Type/Filter/DateType.php, src/Form/Type/Filter/DefaultType.php, src/Form/Type/Filter/NumberType.php, tests/Datagrid/DatagridMapperTest.php, tests/Filter/FilterTest.php
`DatagridMapper::add` used a nullable `$fieldOptions` param in order to default to `['required' => false]` thanks to 
```
public function getFieldOptions()
{
return $this->getOption('field_options', ['required' => false]);
}
```
But this is not needed for two reasons:
- The Filter are already adding this option: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/Filter/ChoiceType.php#L81
- The persistence bundle is already adding this option: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L179
=> Since it's already set in the filter, I recommend to remove this line in the persistence bundle in order to only rely on the filter.
I also added this option to the …
=> Clean up the way `required` => false is set

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php
There is an `alterNewInstance` for extensions, but not for the `AbstractAdmin`.
I think we should provide one instead of allowing to override `getNewInstance`.
```markdown
- Added `AbstractAdmin::alterNewInstance()`
- Overriding `AbstractAdmin::getNewInstance()`
```
=> Declare getNewInstance as final in favor of alterNewInstance

phpstan-baseline.neon, src/Admin/BaseFieldDescription.php, tests/Admin/BaseFieldDescriptionTest.php
Fix BC.
No changelog needed since the version is not released.
=> Avoid error when a wrong code is provided

src/Resources/public/Admin.js
Parse JSON responses on `Admin.setup_xeditable()`.
Closes #6569.
```markdown
- Handling of JSON responses at `Admin.setup_xeditable()`.
```
=> [#6569] Parse JSON responses on `Admin.setup_xeditable()`

src/Admin/AbstractAdmin.php, src/Admin/Pool.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Exception/AdminClassNotFoundException.php, src/Exception/AdminCodeNotFoundException.php, src/Exception/TooManyAdminClassException.php, tests/Admin/PoolTest.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
BC
Closes #6266
```markdown
- `Pool::getAdminByFieldDescription()`
- `AdminClassNotFoundException`
- `AdminCodeNotFoundException`
- `TooManyAdminClassException`
- A tag attribute `default: true` for the tag `sonata.admin` to define a default admin for a specific class
- `Pool::hasSingleAdminByClass()`
```
=> Add an option to define a default admin

src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, tests/Action/AppendFormFieldElementActionTest.php, tests/Action/Baz.php, tests/Action/RetrieveFormFieldElementActionTest.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Admin/AdminTest.php, tests/Admin/BreadcrumbsBuilderTest.php, tests/Datagrid/ListMapperTest.php, tests/Fixtures/Admin/PostCategoryAdmin.php, tests/Fixtures/Admin/TagAdmin.php, tests/Form/Type/AdminTypeTest.php, tests/Menu/Matcher/Voter/AdminVoterTest.php, tests/Menu/Provider/GroupMenuProviderTest.php, tests/Twig/Extension/GroupExtensionTest.php
Related to https://github.com/sonata-project/SonataAdminBundle/issues/5791
A lot of public method of the AbstractAdmin shouldn't be extended for different reason
- Some of them have a `protected configureFoo()` method provided for this
- Some of them are calling directly a service `return $this->service->method()`, so the service should be overridden instead.
- It does not make sens for some
Making these method final let me discovering we were often mocking AbstractAdmin instead of the Interface ; so I fixed the tests.
I didn't add final everywhere, this PR is big enough IMHO, I prefer to follow in another one.
Basically I'd like to add final to as much public method of AbstractAdmin as possible, if someone need to configure/override something, it should be done in a configure method or a …
=> Add Final to multiple methods from the AbstractAdmin

src/Admin/AbstractAdmin.php, src/Admin/Pool.php
Bug fix.
```markdown
- Handle case when `attachAdminClass` does not find an admin to attach.
```
=> Handle case of Admin not found

src/Admin/AbstractAdmin.php, src/Admin/LifecycleHookProviderInterface.php
I don't see why these methods are public.
Even the interface say that `update` should call `preUpdate` and `postUpdate`.
```markdown
- Visibility of `AbstractAdmin::preUpdate()` from public to protected
- Visibility of `AbstractAdmin::preCreate()` from public to protected
- Visibility of `AbstractAdmin::preDelete()` from public to protected
- Visibility of `AbstractAdmin::postUpdate()` from public to protected
- Visibility of `AbstractAdmin::postCreate()` from public to protected
- Visibility of `AbstractAdmin::postDelete()` from public to protected
- `LifecycleHookProviderInterface::preUpdate()`
- `LifecycleHookProviderInterface::preCreate()`
- `LifecycleHookProviderInterface::preDelete()`
- `LifecycleHookProviderInterface::postUpdate()`
- `LifecycleHookProviderInterface::postCreate()`
- …
```
=> Restrict visibility of pre/post methods

src/Admin/LifecycleHookProviderInterface.php
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6863
```markdown
- `LifecycleHookProviderInterface::preUpdate()`
- `LifecycleHookProviderInterface::preCreate()`
- `LifecycleHookProviderInterface::preDelete()`
- `LifecycleHookProviderInterface::postUpdate()`
- `LifecycleHookProviderInterface::postCreate()`
- `LifecycleHookProviderInterface::postDelete()`
```
=> Deprecate pre and post method of LifecycleHookProviderInterface

src/Admin/AbstractAdmin.php, src/Resources/public/Admin.js
Closes #6865.
```markdown
- Fix lost filter value when only type submitted
- Allow submit empty value when default filter non empty
- Invisible disabling filters (using remove name)
```
=> Fix submit filters

docs/reference/routing.rst, src/Admin/AbstractAdmin.php, src/Admin/AdminExtensionInterface.php
This allow to declare `getPersistentParameters` as final.
This prevents the developer to override incorrectly the method and loosing the benefit of the extensions.
For instance, if you look at the doc I updated, the override was losing the code.
```
foreach ($this->getExtensions() as $extension) {
$params = $extension->getPersistentParameters($this);
// NEXT_MAJOR: Remove this check, since return typehint is added
if (!\is_array($params)) {
throw new \RuntimeException(sprintf(
'The %s::getPersistentParameters must return an array',
\get_class($extension)
));
}
$parameters = array_merge($parameters, $params);
}
```
Plus it add consistency: You want to override somethings ? Use the protected method `configure*`.
```markdown
- `AbstractAdmin::configurePersistentParameters()`
- …
```
=> Add a configurePersistentParameters method

src/Admin/AbstractAdmin.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Admin/AdminTest.php, tests/Admin/Extension/LockExtensionTest.php, tests/Block/AdminSearchBlockServiceTest.php, tests/Twig/Extension/RenderElementExtensionTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php
Follow up of https://github.com/sonata-project/SonataAdminBundle/pull/6848
I didn't add final to `public function getPersistentParameters()` because there is no way to add persistent parameters directly in the AbstractAdmin class (even if this is possible in the extensions).
```
public function getPersistentParameters(): array
{
$parameters = [];
foreach ($this->getExtensions() as $extension) {
$params = $extension->getPersistentParameters($this);
$parameters = array_merge($parameters, $params);
}
return $parameters;
}
```
Maybe we could add a configurePersistentParameters and rename the method in the extension...
=> Add final to methods of AbstractAdmin

src/Admin/AbstractAdmin.php, src/Admin/AdminExtensionInterface.php, src/Admin/MenuBuilderInterface.php
There are some method signatures that does not specify the generic type of the `AdminInterface`. Some types are wrong. 
From the API perspective, you can not determine the type of the child admin. It could be of any type.
```markdown
- Add generic information for child admins
```
=> Add generic information for child admins

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Model/ModelManagerInterface.php, src/Util/Instantiator.php, tests/Admin/AdminTest.php, tests/App/Admin/FooAdmin.php, tests/App/Admin/TranslatedAdmin.php, tests/App/Model/ModelManager.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6850#issuecomment-779792471
In 4.0, if a user wants to override the way in which their objects are created, they will have to override `ModelManagerInterface::getModelInstance` for each class. 
The code from `ModelManagerInterface::getModelInstance()` in our persistence bundles (which has been copied to `Instantiator::instantiate()`), is not persistence related.
So this PR adds a `AdminInterface::createNewInstance()` method which the user can override to use a factory, service or any other pattern to create their objects.
```markdown
- Added `AbstractAdmin::createNewInstance()` to allow the user to customize how to create their objects.
- Deprecated …
```
=> Add AbstractAdmin::createNewInstance method

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
`CRUDController->checkParentChildAssociation()` checks if the associated item of the child admins subject equals the parent admins subject. This doesn't work when the parent relations is many-to-many as the child property will be a Collection and not the parent item itself. In that case, the parent item must be searched in this collection.
I am targeting this branch, because its a backwards compatible fix.
```markdown
- Prevent false deprecation notice when accessing an item in a child admin that has a Many to Many relationship with the parent item.
```
=> Prevent false deprecation error for n to m associations

src/Filter/FilterInterface.php
I think types right now are all `int`, should we change it? or just add `string|int`.
e.g:
https://github.com/sonata-project/SonataAdminBundle/blob/6a7c3067a977b8436572700c2a8ab284a268e4f2/src/Form/Type/Operator/DateOperatorType.php#L23-L27
=> Fix FilterInterface::apply phpdoc

src/Form/Type/Filter/DateRangeType.php, src/Form/Type/Filter/DateTimeRangeType.php, src/Form/Type/Filter/DateTimeType.php, src/Form/Type/Filter/DateType.php, tests/Form/Type/Filter/DateTimeRangeTypeTest.php
Use `DateType::HTML5_FORMAT` constants as values for "format" and "date_format" form options.
I am targeting this branch, because these changes are pedantic and respect BC.
=> Use `DateType::HTML5_FORMAT` constants as values for "format" and "date_format" form options

src/Resources/views/CRUD/Association/edit_many_script.html.twig
Display errors from XHR requests at `edit_many_script.html.twig`.
```markdown
- Show XHR errors on "one to many" and "many to many" forms.
```
This is an example of how the error messages are shown:
=> Display errors from XHR requests at `edit_many_script.html.twig`

src/Resources/public/Admin.js
Closes #6894.
```markdown
- Fix computing changed filter values
```
=> Improve computing changed filter values

src/Resources/views/Form/form_admin_fields.html.twig
In the template we are sometimes using a `name` option to replace the label.
This seems useless. You should just use the `label` property instead.
```markdown
- Passing a fieldDescription option `name`
```
=> Deprecate name option

src/Admin/AbstractAdminExtension.php
This introduce a BC break, see https://github.com/sonata-project/SonataAdminBundle/pull/6897#issuecomment-788771235
Anyway, this method is not needed until master ; and I already fixed it in master.
=> Revert https://github.com/sonata-project/SonataAdminBundle/pull/6897

tests/Action/GetShortObjectDescriptionActionTest.php, tests/Controller/CRUDControllerTest.php, tests/Controller/HelperControllerTest.php
`AbstractAdmin::getObject()` does not return boolean values.
I am targeting this branch, because these chages are pedantic.
=> `AbstractAdmin::getObject()` does not return boolean values

src/Filter/FilterInterface.php
Since we're doing isset or `??` checks, we can allow to pass a `null` type.
This way, both
```
['type' => null, 'value' => 'foo']
['value' => 'foo']
```
are valids.
=> Allow null type for filter

src/Admin/AbstractAdminExtension.php
Fixes #6873
```markdown
- Added `AbstractAdminExtension::configurePersistentParameters()` method stub
```
=> Add missing method to AbstractAdminExtension

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
Update actions from `CRUDController` in order to assert that referenced objects exist.
Given a route like "/country/21/state/create" (where `StateAdmin` is a child of `CountryAdmin`) these changes allows the child admin route to ensure that the object referenced by the parent admin exists.
This way, the code at the child admin can rely on the existence of a proper object in its ancestor hierarchy:
```php
// StateAdmin.php
if ($this->isChild()) {
$parentAdmin = $this->getParent();
$parentObject = $parentAdmin->getObject($this->request->get($parentAdmin->getIdParameter()));
// This call can be made safely, since the check about the resource existence is done in the controller.
$parentObject->doSomething();
}
```
```markdown
- …
```
=> Update actions from `CRUDController` in order to assert that referenced objects exist

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php
Closes https://github.com/sonata-project/SonataAdminBundle/issues/6921
```markdown
- Added extension point `AbstractAdmin::configureFilterParameters` to configure/modify filter parameters
```
=> add extension point to configure/modify filter parameters

UPGRADE-3.x.md, src/Controller/CRUDController.php, src/Resources/views/CRUD/base_history.html.twig, src/Route/PathInfoBuilder.php, tests/Controller/CRUDControllerTest.php, tests/Form/Type/Operator/StringOperatorTypeTest.php
Use camel case for arguments and variables at `CRUDController::historyCompareRevisionsAction()`.
```markdown
- Route parameters "baseRevision" and "compareRevision" for `CRUDController::historyCompareRevisionsAction()`.
- Route parameters "base_revision" and "compare_revision" for `CRUDController::historyCompareRevisionsAction()`.
```
=> Use camel case for arguments and variables at `CRUDController::historyCompareRevisionsAction()`

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/BaseFieldDescription.php, src/Admin/FieldDescriptionInterface.php, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/DependencyInjection/Admin/AbstractTaggedAdmin.php, src/DependencyInjection/Admin/TaggedAdminInterface.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/FieldDescription/FieldDescriptionFactoryInterface.php, src/FieldDescription/TypeGuesserChain.php, src/FieldDescription/TypeGuesserInterface.php, src/Form/FormMapper.php, src/Guesser/TypeGuesserChain.php, src/Guesser/TypeGuesserInterface.php, src/Model/ModelManagerInterface.php, src/Show/ShowMapper.php, tests/Admin/AdminTest.php, tests/App/FieldDescription/FieldDescriptionFactory.php, tests/App/Model/ModelManager.php, tests/App/config/services.yml, tests/Datagrid/DatagridMapperTest.php, tests/Datagrid/ListMapperTest.php, tests/FieldDescription/TypeGuesserChainTest.php, tests/Form/FormMapperTest.php, tests/Show/ShowMapperTest.php
For background: #6761 and #6701.
First of all, I had this half done, so I've "finished", I'm fine postponing this for `5.0` if we think this shouldn't be done now (and if this is fine ofc).
The idea of this is basically to move responsibility of creating a `FieldDescription` from `ModelManagerInterface` to `FielDescriptionFactoryInterface`.
And also there is a new `Sonata\AdminBundle\FieldDescription\TypeGuesserInterface` that will guess the FieldDescription type base on a `FieldDescriptionInterface` properties instead of rely on `ModelManagerInterface`.
I've created https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/531 (unfinished) as example of implementation.
Closes #6761 and #6701.
```markdown
- Added …
```
=> Introduce field description factory

src/Filter/FilterInterface.php
```markdown
- Fix wrong phpstan param on `FilterInterface::filter() method`
```
=> Fix wrong phpstan param

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Resources/views/Button/acl_button.html.twig, src/Resources/views/Button/edit_button.html.twig, src/Resources/views/Button/history_button.html.twig, src/Resources/views/Button/show_button.html.twig, tests/Admin/AdminTest.php
I am targeting this branch, because BC
```markdown
- `AbstractAdmin::buildForm()`
- `AbstractAdmin::buildDatagrid()`
- `AbstractAdmin::buildShow()`
- `AbstractAdmin::buildList()`
- `AbstractAdmin::canAccessObject()` in favor of `AbstractAdmin::hasAccess()`
- `AdminInterface::canAccessObject()`
- `AdminInterface::configureActionButtons()` and `AbstractAdmin::configureActionButtons()` will become protected
```
=> Deprecate some AbstractAdmin methods

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php
```markdown
- `AbstractAdmin::configureActionButtons()`
- `AdminExtensionInterface::configureActionButtons()`
- `AbstractAdminExtension::configureActionButtons()`
- Overriding `AbstractAdmin::getActionButtons()`
```
=> Add extension point for dashboardButtons

src/Admin/AbstractAdmin.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Admin/AdminTest.php, tests/Controller/CRUDControllerTest.php, tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php
I am targeting this branch, because {reason}.
Closes #{put_issue_number_here}.
Remaining public and non final methods:
- getExportFormats
- preBatchAction
- getRouterIdParameter
- getIdParameter
- getObjectIdentifier
- toString
- id
- getPerPageOptions
- getObjectMetadata
We should provide a `configureDashboardActions`.
=> Restrict API

src/Search/SearchHandler.php, tests/Search/SearchHandlerTest.php
Global search uses OR conditions to combine multiple filters on the same admin. When an admin contains default filters the global search has no effect because either the default filter or the global search filter must match. As such, the default filters will be removed before global searching.
Example:
I have a default boolean filter on the field active with value 1. I have two global search enabled filters called name and code.
I search on `Test`.
In the current situation the query will become:
`WHERE active = 1 OR name LIKE '%Test%' OR code LIKE '%Test%'`
This returns all items with `active = 1`, effectively ignoring the global search parameter.
Ideally this would be:
`WHERE active = 1 AND (name LIKE '%Test%' OR code LIKE '%Test%')`
But this requires extensive changes to the code, …
=> Reset default filters in global search

src/Admin/AbstractAdmin.php, src/Model/ModelManagerInterface.php
Adds some phpdoc related to FieldDescriptionOptions, ref: https://github.com/sonata-project/SonataAdminBundle/pull/6854#discussion_r590671429
=> Add missing phpdoc

UPGRADE-4.0.md, src/Admin/AbstractAdmin.php, src/Builder/BuilderInterface.php, src/Builder/DatagridBuilderInterface.php, src/Builder/ListBuilderInterface.php, src/Builder/ShowBuilderInterface.php, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Form/FormMapper.php, src/Show/ShowMapper.php, tests/Admin/AdminTest.php, tests/App/Builder/DatagridBuilder.php, tests/App/Builder/FormContractor.php, tests/App/Builder/ListBuilder.php, tests/App/Builder/ShowBuilder.php, tests/Datagrid/DatagridMapperTest.php, tests/Show/ShowMapperTest.php
Since the introduction of the fieldDescriptionFactory by @franmomu, the Admin is supposed to be set on the FieldDescription. So it does not make any sens to have both the field and the admin in the param of these methods.
Is there a BW way to do this ? @sonata-project/contributors ?
=> Remove Admin from Builder signature

docs/cookbook/recipe_custom_action.rst, docs/cookbook/recipe_sortable_listing.rst, docs/cookbook/recipe_virtual_field.rst, src/Admin/AbstractAdmin.php, src/Admin/FieldDescriptionCollection.php, src/Datagrid/ListMapper.php, src/Resources/skeleton/Admin.tpl.php, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_list_flat_inner_row.html.twig, src/Resources/views/CRUD/base_list_inner_row.html.twig, src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig, tests/Admin/FieldDescriptionCollectionTest.php, tests/Datagrid/ListMapperTest.php, tests/Fixtures/Admin/ModelAdmin.php
BC
As you can see, we're using `_actions` for the name of actions, but `batch` and `select` for the others.
It could create a conflict if someone want to display an entity which has a `select` field.
So I recommend to prefix by `_` in Next major.
```markdown
- Added constant `ListMapper::NAME_ACTIONS`
- Added constant `ListMapper::NAME_SELECT`
- Added constant `ListMapper::NAME_BATCH`
- Relying on the code `_select` or `_batch` to determine if a field description is a `select` or a `batch` one. You should rely on the name `ListMapper::NAME_SELECT` or `ListMapper::NAME_BATCH` instead.
```
=> Use constant for batch, select and actions fields

src/Resources/views/standard_layout.html.twig
The navigation role is unnecessary for element nav.
```markdown
Remove the navigation role from nav.
```
=> Remove the navigation role from nav

UPGRADE-3.x.md, src/Admin/AbstractAdmin.php, src/Admin/MenuBuilderInterface.php
`buildSideMenu` was already removed in master.
`buildTabMenu` is only used in AbstractAdmin so shouldn't be in the public API.
All other build method are private so this will be consistent.
```markdown
- `MenuBuilderInterface` interface.
- `AbstractAdmin::buildSideMenu()`
- `AbstractAdmin::buildTabMenu()`
```
=> Deprecate MenuBuilderInterface

UPGRADE-3.x.md, src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php, src/Filter/FilterFactory.php, tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php, tests/Filter/FilterFactoryTest.php, tests/Fixtures/Filter/BarFilter.php
These changes force the user to register filters as services so in next major version a service locator could be used instead of the complete container.
```markdown
- Deprecated not registering filters as a service.
```
=> Deprecate not registering filters

psalm.xml, src/Admin/BaseFieldDescription.php, src/Builder/AbstractFormContractor.php, src/FieldDescription/FieldDescriptionInterface.php, src/Resources/views/Form/form_admin_fields.html.twig, tests/App/Admin/FieldDescription.php, tests/App/Builder/FormContractor.php, tests/Builder/AbstractFormContractorTest.php, tests/Fixtures/Admin/FieldDescription.php, tests/Form/AbstractLayoutTestCase.php, tests/Form/Widget/BaseWidgetTest.php
This is something I had in mind for a while, because there are some code duplication in the persistence bundles.
It's a follow-up of https://github.com/sonata-project/SonataAdminBundle/pull/3971, the `AbstractFormContractor` and `FieldDescription` part.
After this I think we can move some more duplicated code from builders here, that would also make easier to create a persistence bundle.
```markdown
- Added `FieldDescriptionInterface::describesAssociation`, `FieldDescriptionInterface::describesSingleValuedAssociation`, `FieldDescriptionInterface::describesCollectionValuedAssociation` to abstract the association mapping types.
- Added `AbstractFormContractor` base class to centralize association form option validation & defaults. …
```
=> Add AbstractFormContractor and field description methods

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
Remove code duplication to improve performance.
```markdown
- Optimize performance of checking is can access object in `AbstractAdmin::configureActionButtons()`
```
=> Optimize performance of checking is can access object

UPGRADE-3.x.md, src/DependencyInjection/Compiler/AddAuditReadersCompilerPass.php, src/DependencyInjection/SonataAdminExtension.php, src/Model/AuditManager.php, src/Resources/config/core.php, tests/DependencyInjection/Compiler/AddAuditReadersCompilerPassTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php, tests/Fixtures/Model/AuditReader.php, tests/Model/AuditManagerTest.php
Audit readers MUST be tagged with this tag so we can use a service locator instead of injecting the whole container in the next major version.
Ref: https://github.com/sonata-project/SonataAdminBundle/issues/6963
```markdown
- Added `sonata.admin.audit_reader` tag for Audit readers.
- Deprecated not tagging an audit reader with the tag `sonata.admin.audit_reader`.
```
=> Add tag for audit readers

UPGRADE-3.x.md, composer.json, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/Resources/config/core.php, src/Route/AdminPoolLoader.php, tests/Route/AdminPoolLoaderTest.php
The container was added in https://github.com/sonata-project/SonataAdminBundle/commit/eefe79cca5774b612ba8ab32e7bbdf4ec014411f to solve https://github.com/sonata-project/SonataAdminBundle/issues/128, I've marked this PR as draft, as I'm not sure if it is not needed anymore, I'll try to search about this or if someone has some knowledge about this, would be appreciated.
Ref: https://github.com/sonata-project/SonataAdminBundle/issues/6963
```markdown
- Deprecated constructing `AdminPoolLoader` passing more than one argument. 
- Deprecated `AdminPoolLoader` service alias.
```
=> Deprecate constructing AdminPoolLoader with more than one argument

src/SonataAdminBundle.php, tests/SonataAdminBundleTest.php
Merging `3.x` with `master` I've realised I've missed registering the compiler pass in the bundle in https://github.com/sonata-project/SonataAdminBundle/pull/6983.
```markdown
- Fixed removing deprecations having audit readers tagged.
```
=> Register AddAuditReadersCompilerPass in the bundle

src/Search/SearchHandler.php, tests/Search/SearchHandlerTest.php
Set "or_group" filter option at `SearchHandler::search()`
Related to #2850, #3368, #5569, sonata-project/SonataDoctrineORMAdminBundle#1373.
```markdown
- "or_group" filter option at `SearchHandler::search()`.
```
=> Set "or_group" filter option at `SearchHandler::search()`

src/Twig/Extension/RenderElementExtension.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Twig/Extension/RenderElementExtensionTest.php
Looking at 
https://github.com/sonata-project/SonataAdminBundle/blob/7f07a8e25b90451125a9820d391747e49dd1f485/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L395-L407
seems like we could change this code:
```php
$serviceId = $adminCode.'.template_registry';
$templateRegistry = $this->templateRegistries->get($serviceId);
if ($templateRegistry instanceof TemplateRegistryInterface) {
return $templateRegistry;
}
```
And use `AdminInterface::getTemplateRegistry()` method instead, so there is no need of injecting the container to the `RenderElementExtension` service.
=> Use `AdminInterface::getTemplateRegistry` instead of fetching the service from the container

src/Admin/AbstractAdmin.php
`DatagridManagerInterface::getDefaultSortValues()` was deprecated in `3.79` and the implementations of this method in the persistence bundles where also deprecated. 
The problem is that in `3.x` we have to still use it, so we need a way to not trigger that deprecation, adding the `'sonata_deprecation_mute'` argument allows the persistence bundles to not trigger a deprecation when the call is from this bundle.
I am targeting this branch, because this change is BC.
```markdown
- Fixed allowing avoid deprecation using `DatagridManagerInterface::getDefaultSortValues()`.
```
=> Allow silence deprecation in persistence bundles

UPGRADE-3.x.md, src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php, src/Resources/config/commands.php, src/Resources/config/core.php, src/Resources/config/event_listener.php, tests/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPassTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php
Following https://symfony.com/doc/current/bundles/best_practices.html#services, service names in bundles shouldn't be the FQCN, so I've changes these FQCN with strings prefixed with the bundle alias `sonata.admin`.
The aliases deprecated are based on implementations and some of them shouldn't be part of the public API.
Ref: https://github.com/sonata-project/SonataAdminBundle/issues/7000
Closes #7000.
```markdown
- Deprecated `Sonata\AdminBundle\Command\ExplainAdminCommand` service alias.
- Deprecated `Sonata\AdminBundle\Command\GenerateObjectAclCommand` service alias.
- Deprecated `Sonata\AdminBundle\Command\ListAdminCommand` service alias.
- Deprecated `Sonata\AdminBundle\Command\SetupAclCommand` service alias.
- Deprecated …
```
=> Deprecate class-based aliases

src/Admin/LifecycleHookProviderInterface.php, src/Filter/FilterInterface.php
Pedantic
We're try-catch-ing the method of LifecycleHookProviderInterface, so adding the `@throws` tag to the method  seems nice.
We're always using `int` for the filter type, so I think we can restrict the type.
It avoid some static analysis errors in the persistence bundle.
```
Parameter #1 $type of method Sonata\DoctrineORMAdminBundle\Filter\ClassFilter::getOperator() expects int, int|string given.
```
=> Improve php doc

UPGRADE-3.x.md, src/DependencyInjection/Compiler/AddAuditReadersCompilerPass.php, src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php, src/DependencyInjection/Compiler/AdminMakerCompilerPass.php, src/DependencyInjection/Compiler/AdminSearchCompilerPass.php, src/DependencyInjection/Compiler/ExtensionCompilerPass.php, src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php, src/DependencyInjection/Compiler/ModelManagerCompilerPass.php, src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php, src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php
This could be another step in our quest of closing public API, IMO Compiler passes are not meant to be directly used by users of the bundle, so we could mark them as internal so we don't have to keep BC on these classes (in `4.x`).
```markdown
- Compiler Pass classes have been marked as `@internal`.
```
=> Make compiler passes internal

UPGRADE-3.x.md, src/Resources/config/core.php
It should have been included in https://github.com/sonata-project/SonataAdminBundle/pull/7001
```markdown
- Deprecated `Sonata\AdminBundle\Admin\AdminHelper` service alias.
- Deprecated `Sonata\AdminBundle\SonataConfiguration` service alias.
```
=> Deprecate more service aliases

src/Resources/skeleton/Admin.tpl.php
In the `AbstractAdmin` class there are methods with parameters:  
```
protected function configureDatagridFilters(DatagridMapper $filter)
protected function configureListFields(ListMapper $list)
protected function configureFormFields(FormMapper $form)
protected function configureShowFields(ShowMapper $show)
```
The IDE prompts you to replace the names of the variables generated by the generator with those in the AbstractAdmin. 
```markdown
- Names of variables in the skeleton
```
=> Changing the names of variables in the skeleton

src/Form/Type/Filter/DateRangeType.php, src/Form/Type/Filter/DateTimeRangeType.php, src/Form/Type/Filter/DateType.php, tests/Form/Type/Filter/BaseTypeTest.php, tests/Form/Type/Filter/ChoiceTypeTest.php, tests/Form/Type/Filter/DateRangeTypeTest.php, tests/Form/Type/Filter/DateTimeRangeTypeTest.php, tests/Form/Type/Filter/DateTimeTypeTest.php, tests/Form/Type/Filter/DateTypeTest.php, tests/Form/Type/Filter/DefaultTypeTest.php, tests/Form/Type/Filter/NumberTypeTest.php
I wanted to work a bit with filters, but before starting, better to have some tests.
Adding them showed that:
- `format` is not valid for `DateTimeRangeType` because this Type adds two `DateTimeType` that have that configuration (not `DateTimeRangeType` itself), so I've added the `format` option in the `field_options` option so is passed to those `DateTimeType` and changed from `DateType::HTML5_FORMAT` to `DateTimeType::HTML5_FORMAT`.
- `date_format` is not valid for `DateType`, so I've changed it to `format`.
Another interesting part I was thinking was... why has it worked so far? Because having:
```php
public function configureOptions(OptionsResolver $resolver)
{
$resolver->setDefaults([
'field_type' => FormDateType::class,
'field_options' => ['date_format' => …
```
=> Add tests to filter types and fix options

src/Route/RouteCollection.php, tests/Route/RouteCollectionTest.php
I am targeting this branch, because this is where the deprecation happens.
```
2x: Since symfony/http-kernel 5.1: Referencing controllers with a single colon is deprecated. Use "sonata.admin.controller.crud::listAction" instead.
1x in CRUDControllerTest::testList from Sonata\AdminBundle\Tests\Functional\Controller
1x in CRUDControllerTest::testUrlIsSuccessful from Sonata\AdminBundle\Tests\Functional\Controller
```
```markdown
- Remove usage of single colon on actions referenced to service controllers
```
=> Remove deprecations with symfony/http-kernel ^5.1

src/Block/AdminSearchBlockService.php, src/Resources/public/css/layout.css, src/Resources/views/Block/block_search_result.html.twig
Show matching filters in search results.
The search results are using the `Admin::toString()` method to show a representation of the model matching the search criteria, but in cases where the value of the field matching a filter is not present on that string, is hard to understand why that result is presented as a match.
These changes add the name of the filters that produced the model match in each search result.
Here is an example:
```markdown
- Information about the matching filters in the search results.
```
If someone with good CSS skills wants to get rid of the required work to provide a better UI, please be free to suggest any change.
=> Show matching filters in search results

src/Resources/views/CRUD/base_list.html.twig
Use `FilterInterface::getOption()` from views.
`Filter::getOptions()` is not declared in the interface.
```markdown
- Calls to `Filter::getOptions()` by `FilterInterface::getOption()` in views.
```
=> Use `FilterInterface::getOption()` from views

docs/cookbook/recipe_customizing_a_mosaic_list.rst, docs/reference/advanced_configuration.rst, src/Admin/AbstractAdmin.php, src/Admin/BreadcrumbsBuilder.php, src/Resources/views/CRUD/Association/edit_many_script.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/CRUD/base_acl_macro.html.twig, src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/list_outer_rows_mosaic.html.twig, src/Resources/views/Form/form_admin_fields.html.twig, tests/Admin/BreadcrumbsBuilderTest.php, tests/Twig/Extension/RenderElementExtensionTest.php, tests/Twig/Extension/SonataAdminExtensionTest.php
As suggested by @phansys for `SonataPageBundle`, this PR removes the hardcode `id` parameter in favor of `AdminInterface::getIdParameter()` method. 
Also replaces the use of `AdminInterface::id()` when generating URLs by `AdminInterface::getUrlSafeIdentifier()`.
```markdown
- Fixed using the hardcode `id` parameter instead of calling `AdminInterface::getIdParameter()` method.
```
=> Leverage `AdminInterface::getIdParameter()` and `AdminInterface::getUrlSafeIdentifier()`

src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php
I am targeting this branch, because it's a minor.
Fixed an error on SonataDoctrineORMAdminBundle:
```
ERROR: InvalidArgument - src/Builder/DatagridBuilder.php:150:71 - Argument 3 of Sonata\AdminBundle\Datagrid\Datagrid::__construct expects Sonata\AdminBundle\Datagrid\PagerInterface<Sonata\AdminBundle\Datagrid\ProxyQueryInterface>, Sonata\AdminBundle\Datagrid\PagerInterface<Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQueryInterface> provided (see https://psalm.dev/004)
return new Datagrid($admin->createQuery(), $admin->getList(), $pager, $formBuilder, $values);
```
```markdown
- Generics for Datagrid and DatagridInterface
```
=> Add template for datagrid

phpstan-baseline.neon, src/Datagrid/DatagridMapper.php, src/Datagrid/ListMapper.php, src/Event/ConfigureEvent.php, src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, src/Mapper/BaseMapper.php, src/Mapper/MapperInterface.php, src/Show/ShowMapper.php, tests/Event/ConfigureEventTest.php, tests/Fixtures/Admin/AbstractDummyGroupedMapper.php, tests/Mapper/BaseGroupedMapperTest.php, tests/Mapper/BaseMapperTest.php
We're using `BaseMapper` as a typehint somewhere, which is an abstract class.
Isn't better to use an interface instead ?
```markdown
- Added `MapperInterface`
```
=> Introduce MapperInterface

src/DependencyInjection/Compiler/AddFilterTypeCompilerPass.php, src/Filter/FilterFactory.php, src/Filter/FilterFactoryInterface.php, src/Resources/config/core.php, tests/DependencyInjection/Compiler/AddFilterTypeCompilerPassTest.php, tests/Filter/FilterFactoryTest.php
I think this cannot be done with BC because we are injecting to `FilterFactory` the whole container and this service locator will have only the filter services registered by class name.
Last task of https://github.com/sonata-project/SonataAdminBundle/issues/6963.
I am targeting this branch, because this is not BC.
=> Use a service locator for FilterFactory

src/Resources/config/twig.php, src/Twig/Extension/XEditableExtension.php, tests/Twig/Extension/RenderElementExtensionTest.php, tests/Twig/Extension/XEditableExtensionTest.php
```markdown
- Added `XEditableExtension::FIELD_DESCRIPTION_MAPPING` to expose mapping between FieldDescription types and xEditable types
```
=> Use field description constants

docs/reference/field_types.rst, docs/reference/security.rst
When building Sonata docs with the new Symfony Docs Builder, we found some issues related to tables (see https://github.com/weaverryan/docs-builder/issues/89).
Strictly speaking, it's not a mistake of your docs, so I'll understand if you prefer to not change this ... but making these minor changes would make your doc publishable again on symfony.com. Thanks!
=> [Docs] Minor tweaks in RST syntax

src/Admin/AdminInterface.php, src/DependencyInjection/Admin/AbstractTaggedAdmin.php, src/DependencyInjection/Admin/TaggedAdminInterface.php, src/Form/DataTransformer/ArrayToModelTransformer.php, src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Form/DataTransformer/ModelToIdTransformer.php, src/Form/DataTransformer/ModelsToArrayTransformer.php, src/Model/ModelManagerInterface.php
@franmomu You proposed this change https://github.com/sonata-project/SonataAdminBundle/pull/6721, and I didn't fully understand if it was a good change or not. Now I think I agree with your proposal.
If the modelManager is generic, `ModelManager<object>` or `ModelManager<T>` could be used.
If the modelManager works only for some objects, like https://github.com/sonata-project/SonataAdminBundle/blob/3.x/tests/App/Model/ModelManager.php#L22, it could be `ModelManager<Foo>`.
It could fixed https://github.com/sonata-project/SonataAdminBundle/blob/master/tests/App/Model/ModelManager.php#L56-L60
See https://phpstan.org/r/ab8c0e82-a65c-4b98-9662-18e07a73ce07 Vs https://phpstan.org/r/adc525ad-dadf-4912-af8e-7087ac6b1344
```markdown
- Added generic for …
```
=> Move template param of the ModelManager to the class

src/Resources/views/Form/form_admin_fields.html.twig, tests/Fixtures/StubTranslator.php, tests/Form/AbstractLayoutTestCase.php, tests/Form/AdminLayoutTest.php
This PR add some tests for `form_label` and `form_help` blocks, this will be helpful also for fixing https://github.com/sonata-project/SonataAdminBundle/issues/7014.
It failed for `form_label` when using the admin translation domain because `admin.translationDomain` does not exist in:
https://github.com/sonata-project/SonataAdminBundle/blob/db09b03adee7ae24379d0462af329467b4a83e29/src/Resources/views/Form/form_admin_fields.html.twig#L163
to solve this I added a `|default` filter (to not break anything) just in case this `admin` variable is defined somewhere (I haven't found it).
I've also replaced `StubTranslator` to our own to add this `domain` value.
=> Add tests for label and help blocks

src/Resources/config/twig.php, src/Twig/Extension/TemplateRegistryExtension.php
I missed this on in https://github.com/sonata-project/SonataAdminBundle/issues/6963
After this and merging with `4.x` (resolving the comment) I think we won't have more `service_container` dependencies.
```markdown
- Changed `TemplateRegistryExtension` constructor to `@internal`.
```
=> Prepare to remove usages of service_container in version 4

src/Form/Extension/Field/Type/FormTypeFieldExtension.php, src/Resources/views/Form/form_admin_fields.html.twig, tests/Form/AdminLayoutTest.php
I'll add tests after https://github.com/sonata-project/SonataAdminBundle/pull/7020
Closes #7014.
```markdown
- Fixed using the admin translation domain as default for `form_help` twig block.
```
I think we can use the same approach for `form_label` and do not override the entire block, just setting variables, I'll try to have a look.
=> Use translation domain of admin as default for form_help

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php
Allow `AbstractAdmin::getListMode()` to return the default value if the request hasn't a session.
Triggered by https://github.com/sonata-project/SonataAdminBundle/pull/7033#discussion_r615244036.
```markdown
- Using a non existing `Session` instance from the `Request` object at `AbstractAdmin::getListMode()`.
```
=> Allow `AbstractAdmin::getListMode()` to return the default value if the request hasn't a session

docs/cookbook/recipe_sortable_listing.rst, docs/reference/action_list.rst, src/Action/RetrieveAutocompleteItemsAction.php, src/Admin/AbstractAdmin.php, src/Block/AdminStatsBlockService.php, src/Datagrid/Datagrid.php, src/Datagrid/DatagridInterface.php, src/Form/Type/ModelAutocompleteType.php, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/Pager/base_results.html.twig, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Admin/AdminTest.php, tests/Controller/HelperControllerTest.php, tests/Datagrid/DatagridTest.php, tests/Filter/Persister/SessionFilterPersisterTest.php, tests/Form/Type/ModelAutocompleteTypeTest.php, tests/Twig/Extension/PaginationExtensionTest.php, tests/Util/ParametersManipulatorTest.php
Some polishing, there are multiples places where these strings are used, this replaces the scalar strings by constants.
Since they seem related to `Datagrid`, I've created them in `DatagridInterface`. ~I've chosen `KEY_` prefix, but any other name is welcome.~
```markdown
- Added `DatagridInterface::SORT_ORDER` constant to use it instead of `_sort_order` string.
- Added `DatagridInterface::SORT_BY` constant to use it instead of `_sort_by` string.
- Added `DatagridInterface::PAGE` constant to use it instead of `_page` string.
- Added `DatagridInterface::PER_PAGE` constant to use it instead of `_per_page` string.
```
=> Extract strings to constants

src/Form/DataTransformer/ModelToIdPropertyTransformer.php, src/Model/ModelManagerInterface.php
In the persistence bundle, an empty array isn't allowed.
In this bundle we're doing a empty check before calling this method.
```markdown
- addIdentifierToQuery phpdoc to reflect the fact that it shouldn't be called with an empty array of identifier
```
=> Update addIdentifierToQuery phpdoc

UPGRADE-3.x.md, src/Resources/views/standard_layout.html.twig
I am targeting this branch, because this is a bug fix.
```markdown
- Fixed main sidebar toggling
```
The upgrade to admin lte v4: https://github.com/sonata-project/SonataAdminBundle/pull/7032 broke the sidebar menu, we are unable to toggle (open/close) it.
It is kind of bc break on their side: https://github.com/ColorlibHQ/AdminLTE/issues/1666
This change fixes it.
=> Sidebar menu toggle with admin-lte 2.4

src/Resources/public/css/layout.css, src/Resources/views/Block/block_search_result.html.twig
Fix matching filters links in search results
Related to #7005.
```markdown
- URLs generated at global search results for the list filtering, which were missing the `value` dimension;
- Layout for the filter links generated at global search results.
```
=> Fix matching filter links in search results

UPGRADE-3.x.md, src/Action/DashboardAction.php, src/Action/SearchAction.php, src/Controller/CRUDController.php, src/Resources/config/actions.php, src/Resources/config/twig.php, src/Resources/views/Breadcrumb/breadcrumb.html.twig, src/Resources/views/Breadcrumb/breadcrumb_title.html.twig, src/Resources/views/standard_layout.html.twig, src/Twig/Extension/BreadcrumbsExtension.php, tests/Action/SearchActionTest.php, tests/Twig/Extension/BreadcrumbsExtensionTest.php
Instead of passing `breadcrumbs_builder` parameter to all templates, the new `render_breadcrumbs` and `render_breadcrumbs_for_title` Twig functions will render the breadcrumbs.
For keeping BC, these functions accept the breadcrumbs builder from Twig as last argument.
Closes #6832.
```markdown
- Added `render_breadcrumbs` and `render_breadcrumbs_for_title` Twig functions to render breadcrumbs.
- Deprecated overriding the `breadcrumbs_builder` variable passed to Twig templates.
```
=> Add render_breadcrumbs and render_breadcrumbs_for_title twig functions

src/Admin/AbstractAdmin.php
This also restores the defaults values from `3.x` for `4.x`.
=> Extract magic numbers

src/Admin/AbstractAdmin.php
The preValidate method was deprecated in 3.82 version, but I recently had the need to update the data before the form validation. I tried using this method and it works fine. 
In the PR: https://github.com/sonata-project/SonataAdminBundle/commit/eddec2648cc1d3bb15f3343a2dc0e1156885244c, we deprecated (and remove in master) all the validation related method. IMHO it's a good thing to remove our own validator, but it should be allowed to add an event in order to do things before the symfony form validators.
WDYT @sonata-project/contributors ?
```markdown
- Remove deprecation for `AbstractAdmin::preValidate()` method
```
=> RFC: Remove deprecation for preValidate method

UPGRADE-4.0.md, docs/reference/action_list.rst, phpstan-baseline.neon, psalm.xml, src/Filter/FilterInterface.php, src/Filter/Model/FilterData.php, src/Form/DataTransformer/FilterDataTransformer.php, src/Form/Type/Filter/ChoiceType.php, src/Form/Type/Filter/DateRangeType.php, src/Form/Type/Filter/DateTimeRangeType.php, src/Form/Type/Filter/DateTimeType.php, src/Form/Type/Filter/DateType.php, src/Form/Type/Filter/DefaultType.php, src/Form/Type/Filter/FilterDataType.php, src/Form/Type/Filter/NumberType.php, tests/Datagrid/DatagridTest.php, tests/Filter/Model/FilterDataTest.php, tests/Fixtures/Filter/BarFilter.php, tests/Fixtures/Filter/FooFilter.php, tests/Form/DataTransformer/FilterDataTransformerTest.php, tests/Form/Type/Filter/DateTimeRangeTypeTest.php
I have doubts on where to do this, the easy way is to do it in `4.x`, I thought about adding `FilterDataType` in `3.x`, but removing `buildForm` from types is BC break, so not sure if is worth it to do it in `3.x`.
My idea with filters was:
This type will be used as a base of filter types, it contains `type` and `value` fields and it defines `operator_type`, `field_type`, `operator_options` and `field_options` options.
The idea is that other types will override `getParent()` method returning `FilterDataType`, so there is no need for them to override `buildForm` with `type` and `value` and only have to configure the `operator_type` and `field_type` options (and other options if they have).
The datatransform transforms from `array` to `FilterData` (I'll extract the `CallbackTransformer` to …
=> Add FilterData

src/Datagrid/ProxyQueryInterface.php, src/Datagrid/SimplePager.php, src/Form/ChoiceList/ModelChoiceLoader.php, src/Form/DataTransformer/ModelsToArrayTransformer.php, src/Model/ModelManagerInterface.php, src/Util/TraversableToCollection.php, tests/Datagrid/SimplePagerTest.php
We're using `ProxyQuery::execute()` method as if it alway return an array|Traversable.
Indeed, we're sometimes using `TraversableToCollection::transform()` on it.
So I think we can update the phpdoc. Same for `ModelManager::executeQuery()`.
I also used `TraversableToCollection` in the `SimplePager`.
```markdown
- Restrict return type of `ProxyQuery::execute()` method to `array<object>|(\Traversable<object>&\Countable)`
```
=> Restrict return type of execute method

src/Builder/DatagridBuilderInterface.php, src/Builder/FormContractorInterface.php, src/Datagrid/DatagridMapper.php, src/Model/LockInterface.php, src/Model/ModelManagerInterface.php
BC
Fix 
```
ArgumentTypeCoercion - src/Builder/DatagridBuilder.php:135:78 - Argument 2 of Sonata\AdminBundle\Filter\FilterFactoryInterface::create expects class-string, parent type string provided (see https://psalm.dev/193)
$filter = $this->filterFactory->create($fieldDescription->getName(), $type, $fieldDescription->getOptions());
```
And
```
Method Sonata\DoctrineORMAdminBundle\Builder\DatagridBuilder::getBaseDatagrid() should return Sonata\AdminBundle\Datagrid\DatagridInterface<Sonata\AdminBundle\Datagrid\ProxyQueryInterface> but returns  
Sonata\AdminBundle\Datagrid\Datagrid<Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQueryInterface>.
```
And I'm trying to solve other issue in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1421
```markdown
- Generic template for …
```
=> Restrict datagridBuilder type to class-string and add Template

src/Filter/Model/FilterData.php, tests/Filter/Model/FilterDataTest.php
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/7022#issuecomment-826994705
Adding this VO introduced in next major version allows us to add forward compatibility for callback filter functions.
```markdown
- Added `FilterData` to use it for forward compatibility with `4.0`.
```
=> [RFC] Add FilterData

src/Form/DataTransformer/ModelToIdPropertyTransformer.php
Backport of https://github.com/sonata-project/SonataAdminBundle/pull/7119/commits/f5b96041ff10f1d008f72e86824f3eb9dd6f042b
```markdown
- Calling foreach on `ArrayAccess` in ModelToIdPropertyTransformer
```
=> Stop trying to foreach on ArrayAccess

src/FieldDescription/BaseFieldDescription.php, src/FieldDescription/FieldDescriptionInterface.php, src/Resources/views/CRUD/Association/edit_many_script.html.twig, src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/Form/form_admin_fields.html.twig
Follow up of the discussion
https://github.com/sonata-project/SonataAdminBundle/pull/7101
This type is currently not describing correctly the possible options ATM.
Since @franmomu is not agreeing with this, I prefer to wait for his approval before any merge.
```markdown
- FieldDescriptions options phpdoc to keep only common options.
```
=> Keep only common option in FieldDescriptionOptions type

src/Resources/views/CRUD/display_url.html.twig, tests/Twig/Extension/SonataAdminExtensionTest.php
Bugfix
```markdown
- Fix `display_url.html.twig` template
```
=> Do not try to find a route for `show` and `edit`

src/Controller/CRUDController.php
I am targeting this branch, because it's failing in 3.x version.
Closes #7134.
```markdown
- Remove `do-not-use` alias for exporter service.
```
=> Bug - Removed do-not-use alias for exporter service

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, src/DependencyInjection/Compiler/AdminAddInitializeCallCompilerPass.php, src/SonataAdminBundle.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php, tests/DependencyInjection/Compiler/AdminAddInitializeCallCompilerPassTest.php, tests/SonataAdminBundleTest.php
I am targeting this branch, because its BC and part of fixing https://github.com/sonata-project/SonataAdminBundle/issues/7104
```markdown
- `AdminInterface::initialize()` is the last method called
- `admin_services.templates.form` is correctly set
- `admin_services.templates.filter` is correctly set
- default service setter calls on `AdminInterface` are only added if there are no calls defined yet
```
=> add "setFormTheme" and "setFilterTheme" calls + change "initialize" priority

assets/js/app.js, assets/scss/app.scss, package.json, yarn.lock
I am targeting this branch, because this is only applies to master.
Part of #7049 
I tried to remove jquery-slimScroll and jquery-scrollTo but found that they are used outside this bundle:
jquery-slimScroll is kind of used for admin-lte
jquery-scrollTo is used by other sonata bundles
I just added some explanations to the javascript, just in case someone tries to remove them. Ideally the dependencies should be placed where the usage is done, but for now this is better than nothing.
I also added postcss, it was a missing dependency
=> Avoid accidental removal of some frontend dependencies

src/Admin/AbstractAdmin.php, src/Admin/AbstractAdminExtension.php, src/Admin/AdminExtensionInterface.php
Allow admin to be configured by extensions at initialize time.
I am targeting this branch, because code is backwards compatible.
Closes #6890.
```markdown
- Added `AdminExtensionInterface::configure` method
- Added `AbstractAdminExtension::configure` method with no content
- Changed `AbstractAdmin::initialize` and call `AdminExtensionInterface::configure` on each extension
```
=> Allow admin extension to configure admin at initialize time

src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php, tests/DependencyInjection/Compiler/AddDependencyCallsCompilerPassTest.php
The Phpcr bundle is not abandonned.
There is no Sonata-4 compatibility.
IMHO we shouldn't add code for a specific persistence-bundle.
It should be the persistence bundle to adapt his code instead.
=> Drop support for phpcr

src/Builder/AbstractFormContractor.php, src/Datagrid/Pager.php, src/Datagrid/SimplePager.php, src/FieldDescription/BaseFieldDescription.php, src/Filter/Filter.php, src/Mapper/BaseGroupedMapper.php, src/Templating/AbstractTemplateRegistry.php, src/Util/ObjectAclManipulator.php
Closes #5791. (I think)
```markdown
- `final` for method of every abstract classes.
```
=> Add final for every method of abstract classes

src/Datagrid/ProxyQueryInterface.php, src/Model/ModelManagerInterface.php
Patch
If I understand correctly https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/585, the `execute` return type is not Countable. (cc @franmomu)
In the SonataAdmin we don't call count directly since we're using `TraversableToCollection`.
```markdown
- `ProxyQuery::execute()` return type ; it doesn't require to be a Countable.
```
=> Remove Countable from execute return type

composer.json, docs/cookbook/recipe_decouple_crud_controller.rst, docs/index.rst, src/DependencyInjection/SonataAdminExtension.php, src/Request/AdminFetcher.php, src/Request/AdminFetcherInterface.php, src/Request/ParamConverter/AdminParamConverter.php, src/Resources/config/core.php, src/Resources/config/param_converter.php, tests/App/Admin/TestingParamConverterAdmin.php, tests/App/AppKernel.php, tests/App/Controller/InvokableController.php, tests/App/Controller/ParamConverterController.php, tests/App/config/services.yml, tests/DependencyInjection/SonataAdminExtensionTest.php, tests/Functional/Controller/ParamConverterControllerTest.php, tests/Request/AdminFetcherTest.php, tests/Request/ParamConverter/AdminParamConverterTest.php
This is something I had half way done (and it's not finished), just for comments if you think it's interesting or just to not continue.
The idea with this is that someone using `sensio/framework-extra-bundle` can create a controller like this:
```php
final class MyCustomController
{
public function myCustomAction(MyAdmin $admin)
{
// ...
}
}
```
Previously the admin has to be configured to use `MyCustomController` and add the `myCustom` route.
This could be a way to not force the user to extend `CRUDController` if we use an approach like https://github.com/sonata-project/SonataAdminBundle/pull/6796#issuecomment-764880016
Also the `AdminFetcher` (or another name) could be reuse for fetching the `Admin` in `CRUDController`. …
=> Add ParamConverter for Admins

docs/reference/action_list.rst
This PR enhances the list documentation for non-model fields.
Right now only two ways to handle those are covered, additional getters and added select expressions.
You can however also mark list fields as virtual, as documented here by Sonata itself:
https://symfony.com/doc/current/bundles/SonataAdminBundle/cookbook/recipe_virtual_field.html
It may seem like a pointless use case to always have a list field display null as a value, but it becomes quite important when overriding the template that facilitates the FieldDescription to render a value.
In one of my apps, I enhanced the template to execute an anonymous callback function on the object instead of just rendering the value of the FieldDescription's associated property. That's incredibly powerful if data has needs to be enhanced …
=> enhance list documentation for virtual fields

src/Datagrid/SimplePager.php, tests/Datagrid/SimplePagerTest.php
The recent change I made broke the pagination of the SimplePager.
This is because the SimplePager is now using a check `countResults > maxPerPage`.
But the `SimplePager::countResults` was returning the the maxPerPage so the pagination wasn't triggered.
Previously, this was the behavior.
Let's say you wanted to display 25 results per page and you have 30 in database.
The simple pager look for 26 results.
It then display
> page 1/?: at least 25 results.
And page 2,
> page 2/?: at least 30 results.
I change this behavior to 
> page 1/?: at least 26 results.
> page 2/?: at least 30 results.
This fix the pagination, and give a more precise information about the result number.
```markdown
- Fix SimplePager pagination
```
=> Fix countResult of SimplePager

docs/reference/configuration.rst
Fix option `show_empty_boxes` to `empty_boxes` under **global_search**
=> Fix "show_empty_boxes" option in the documentation

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
- Fixed error `Uncaught TypeError: autocompleteInput.select2(...).append is not a function` after adding a new item to **ModelAutocompleteType** fields.
- Fixed error on save, id was missing from the hidden input (value attribute).
Closes #4022.
```markdown
- Changed .select2() to .attr()
- Set id in the value attribute of hidden input after save
```
=> Fixed select2 ModelAutocompleteType

src/Action/AppendFormFieldElementAction.php, src/Action/GetShortObjectDescriptionAction.php, src/Action/RetrieveAutocompleteItemsAction.php, src/Action/RetrieveFormFieldElementAction.php, src/Action/SetObjectFieldValueAction.php, src/Resources/config/actions.php, src/Resources/views/CRUD/Association/edit_many_script.html.twig, src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, src/Resources/views/CRUD/Association/edit_one_script.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/Core/search.html.twig, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig, src/Resources/views/Form/form_admin_fields.html.twig, tests/Action/AppendFormFieldElementActionTest.php, tests/Action/GetShortObjectDescriptionActionTest.php, tests/Action/RetrieveAutocompleteItemsActionTest.php, tests/Action/RetrieveFormFieldElementActionTest.php, tests/Action/SetObjectFieldValueActionTest.php, tests/Controller/HelperControllerTest.php
Follow #7188
Closes #7185.
```markdown
- Passing a `code` value in the request of AppendFormFieldElementAction, GetShortObjectDescriptionAction, RetrieveAutocompleteItemsAction, RetrieveFormFieldElementAction and SetObjectFieldValueAction. Pass `_sonata_admin` instead.
- Passing a `Pool` argument to the constructor of AppendFormFieldElementAction, GetShortObjectDescriptionAction, RetrieveAutocompleteItemsAction, RetrieveFormFieldElementAction and SetObjectFieldValueAction. Pass an AdminFetcher instead.
- AppendFormFieldElementAction, GetShortObjectDescriptionAction, RetrieveAutocompleteItemsAction, RetrieveFormFieldElementAction and SetObjectFieldValueAction now set the childAdmin subjects to the childAdmin.
```
=> Use adminFetcher in Actions

src/FieldDescription/FieldDescriptionInterface.php
It is used as `string` for specify the field name for example in:
https://github.com/sonata-project/SonataAdminBundle/blob/33d99daf74d3fdeb760dbec60e16856b34fd3ef3/src/Datagrid/Datagrid.php#L386
```markdown
- Fixed type of `sortable` option in `FieldDescriptionOptions`
```
=> Allow sortable option as string

src/FieldDescription/BaseFieldDescription.php, src/FieldDescription/FieldDescriptionInterface.php
The mapping type is not set in the constructor so it can be nullable.
Also the mapping type is only used if the field is linked to an entity so it can be null.
```markdown
- `FieldDescriptionInterface::getMappingType()` return type
```
=> Allow null mappingType

src/Resources/views/CRUD/Association/edit_many_script.html.twig, src/Resources/views/CRUD/Association/edit_many_to_one.html.twig, src/Resources/views/CRUD/Association/edit_one_script.html.twig, src/Resources/views/CRUD/Association/edit_one_to_one.html.twig, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/Form/form_admin_fields.html.twig
This is an attempt to fix https://github.com/sonata-project/SonataAdminBundle/issues/7185
```markdown
- childId are not lost anymore when using multiple times the appendFormFieldAction and similar actions.
```
=> Do not lose _route_params

src/Resources/views/CRUD/Association/edit_modal.html.twig, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig, src/Resources/views/Form/form_admin_fields.html.twig
Closes #7222
```markdown
- Focus on Select2 or CKEditor in modal dialog 
```
=> Fix for no focus on Select2 or CKEditor in modal dialog

.idea/.gitignore, src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
I am targeting this branch, because it's BC.
Closes #7210 
```markdown
Reverted the changes of #7196, because they only work for Select2 version 4, that is used on the Master branche. Branche 3.x uses Select2 version 3.
```
=> Fix for ModelAutocompleteType does not display the previously selected value when editing an entity

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, src/Admin/Extension/LockExtension.php, tests/Admin/AdminTest.php, tests/Admin/Extension/LockExtensionTest.php, tests/Controller/CRUDControllerTest.php, tests/Request/AdminFetcherTest.php, tests/Route/DefaultRouteGeneratorTest.php
I let as protected all the property without setter.
The property I changed has a setter (which is final), so we should promote the setter instead.
Also, we were mixing `$uniqId` and `$uniqid`. In the last psalm patch I used `uniqId` so I follow the changes here.
I think the method call are not case sensitive so it's not a BC break.
```markdown
- All the protected property of the AsbtractAdmin with a specific setter are now private.
```
=> Restrict visibility of some AbstractAdmin property and rename uniqid to uniqId

src/Resources/views/CRUD/history_revision_timestamp.html.twig
Patch
Closes #7217.
```markdown
- Display of `history_revision_timestamp.html.twig`
```
=> Fix display of history_revision_timestamp

src/Filter/Persister/SessionFilterPersister.php, src/Menu/Matcher/Voter/AdminVoter.php, src/Resources/config/core.php, tests/Filter/Persister/SessionFilterPersisterTest.php
`session` service has been deprecated in favor of fetching the session from the `request_stack` and `RequestStack::getMasterRequest` in favor of getMainRequest.
Ref: https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.3.md#frameworkbundle and https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.3.md#httpkernel
I am targeting this branch, because is where support of symfony 5 is.
```markdown
- Changed argument 1 of `SessionFilterPersister::__construct()` from `SessionInterface` to `RequestStack`
```
=> Remove deprecations with Symfony 5.3

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
As discussed here https://github.com/sonata-project/SonataAdminBundle/pull/7228#discussion_r642943408 we could remove the `getRequest` method in favor of passing the request as an argument of the method which require it.
I added the `request` as first argument to all the method in order to have some consistency.
Related to this consistency, the only one method with `request` as second argument is the `batchActions`.
We're doing `$this->$finalAction($query, $forwardedRequest);`. Should we swap the argument ?
```markdown
- `renderWithExtraParams()`, `isXmlHttpRequest()`, `getBaseTemplate()`, `redirectTo()`, `isPreviewApproved()`, `isInPreviewMode()`, `isPreviewDeclined()`, `validateCsrfToken()` signatures. They now require to pass the request as first argument.
- …
```
=> RFC: Remove CRUDController::getRequest method

src/Controller/CRUDController.php, tests/Controller/CRUDControllerTest.php
```markdown
- `strict` param to `CRUDController::assertObjectExist` in order to check for the existence of the id in the request.
```
=> Also check for id in assertObjectExists

src/Controller/CRUDController.php
I let as non final
- The actions
- `addRenderExtraParams` introduced here: https://github.com/sonata-project/SonataAdminBundle/pull/5965 ; but I'm considering removing this method the day we've solved https://github.com/sonata-project/SonataAdminBundle/issues/7242
- `getLogger` but I'm not sure about this one.
- `getBaseTemplate`
- `handleModelManagerException`
- all the `preCreate` and similar methods.
- `handleXmlHttpRequestErrorResponse` and `handleXmlHttpRequestSuccessResponse` introduced here: https://github.com/sonata-project/SonataAdminBundle/pull/6214
```markdown
- Add final to multiple method of CRUDController
```
=> Make some method of the CRUDController final

src/Resources/public/Admin.js
Replace usages of `$` with `jQuery` in `Admin.js`.
```markdown
- Conflicts with other libraries using the `$` variable.
```
=> Replace usages of `$` with `jQuery` in `Admin.js`

src/Controller/CRUDController.php
Related to https://github.com/sonata-project/SonataAdminBundle/pull/7252
```markdown
- Overriding renderWithExtraParams(), renderJson, isXmlHttpRequest(), isPreviewRequested(), isPreviewApproved(), isInPreviewMode(), isPreviewDeclined(), validateCsrfToken(), escapeHtml(), getCsrfToken() methods in the CRUDController.
```
=> Add final annotation for crud methods

src/FieldDescription/BaseFieldDescription.php, src/Form/FormMapper.php, src/Mapper/BaseGroupedMapper.php, tests/FieldDescription/BaseFieldDescriptionTest.php, tests/Form/FormMapperTest.php
Two things here:
- When using the group `default`, I added the `translation_domain` in order to avoid error when accessing `$group['translation_domain']`. @jordisala1991 got this error recently.
- I also added `?? null`.
- Previously the check was "If the field description has no translation domain, but the group has one, use it, but if the group has `false` just use the default translation domain". I wonder why we propagate the group `translation_domain` but not the false value, so I considered to propagate in both situation.
With the following code
```
->with('foo', ['translation_domain' => 'foo'])
->add('bar')
```
bar will use the `foo` translation_domain.
With the following code
```
->with('foo', ['translation_domain' => false])
->add('bar')
```
Do you think `bar` should use the …
=> [RFC] Propagate group translation domain to field description

src/Admin/AbstractAdmin.php, tests/Admin/AdminTest.php, tests/Fixtures/Admin/PostCategoryAdmin.php, tests/Fixtures/Admin/TagAdmin.php
```markdown
- Overriding `AbstractAdmin::getDataSourceIterator()`
- Overriding `AbstractAdmin::create()`
- Overriding `AbstractAdmin::delete()`
- Overriding `AbstractAdmin::getFilterParameters()`
- Overriding `AbstractAdmin::getParentAssociationMapping()`
- Overriding `AbstractAdmin::getBaseRoutePattern()`
- Overriding `AbstractAdmin::getBaseRouteName()`
- Overriding `AbstractAdmin::getClass()`
- Overriding `AbstractAdmin::getSubClasses()`
- Overriding `AbstractAdmin::setSubClasses()`
- Overriding `AbstractAdmin::hasSubClass()`
- Overriding `AbstractAdmin::hasActiveSubClass()`
- Overriding `AbstractAdmin::getActiveSubClass()`
- Overriding `AbstractAdmin::getActiveSubclassCode()`
- Overriding `AbstractAdmin::getBatchActions()`
- Overriding `AbstractAdmin::getRoutes()`
- Overriding …
```
=> Add final annotation for AbstractAdmin method final in master

src/Resources/views/Block/block_admin_preview.html.twig, src/Resources/views/CRUD/base_edit_form_macro.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_list_field.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/CRUD/base_show_field.html.twig, src/Resources/views/CRUD/base_show_macro.html.twig
```markdown
- Do not try to translate fieldDescription label when false is provided as translation domain.
```
=> Respect false as translation domain

src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/Pager/base_results.html.twig, tests/App/Datagrid/Datagrid.php
Right fix of https://github.com/sonata-project/SonataAdminBundle/pull/7231 IMHO.
Closes #7231.
Closes #7230.
```markdown
- `Max_per_page` drowpdown propagate correctly the `sort_by` filter value
```
=> Correctly pass pagination parameters

UPGRADE-3.x.md, src/Form/FormMapper.php
This is old code from where we allowed to pass form names instead of FQCN.
We could maybe deprecate also [`CollectionType`](https://github.com/sonata-project/SonataAdminBundle/blob/343256a2d7e679038b1fa6da9aea110fd5927673/src/Form/Type/CollectionType.php) since it's just adding a block prefix and we could override in twig the one from Symfony and remove completely this "if".
I am targeting this branch, because this change is BC.
```markdown
- Deprecated passing `collection` as argument 2 of `FormMapper::add()` method
```
=> Deprecate passing `collection` to `FormMapper::add()`

src/Resources/views/Block/block_admin_preview.html.twig, src/Resources/views/Block/block_search_result.html.twig, src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig, src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_edit_form_macro.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/CRUD/base_show_macro.html.twig, src/Resources/views/CRUD/dashboard__action.html.twig, src/Resources/views/CRUD/dashboard__action_create.html.twig, src/Resources/views/Form/form_admin_fields.html.twig
Similar to https://github.com/sonata-project/SonataAdminBundle/pull/7271
```markdown
- Respect `false` as translation_domain for tab and action buttons.
```
=> Respect false translationd domain

UPGRADE-3.x.md, docs/cookbook/recipe_knp_menu.rst, docs/reference/configuration.rst, docs/reference/dashboard.rst, src/Admin/AbstractAdmin.php, src/Block/AdminSearchBlockService.php, src/Block/AdminStatsBlockService.php, src/DependencyInjection/Configuration.php, src/Resources/config/twig.php, src/Resources/views/Block/block_admin_preview.html.twig, src/Resources/views/Block/block_search_result.html.twig, src/Resources/views/Block/block_stats.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/dashboard__action.html.twig, src/Resources/views/CRUD/dashboard__action_create.html.twig, src/Resources/views/Core/add_block.html.twig, src/Resources/views/Core/tab_menu_template.html.twig, src/Resources/views/Menu/sonata_menu.html.twig, src/Twig/Extension/IconExtension.php, tests/Block/AdminSearchBlockServiceTest.php, tests/Block/AdminStatsBlockServiceTest.php, tests/Block/DeprecatedAdminSearchBlockServiceTest.php, tests/Block/DeprecatedAdminStatsBlockServiceTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/Menu/Integration/BaseMenuTest.php, tests/Twig/Extension/IconExtensionTest.php
Closes #7137
Closes #7174
```markdown
- Added `IconExtension` twig extension.
- Added `parse_icon` filter.
- Passing an `icon` option with the format `fa-plus` or `plus`, use the format `fa fa-plus` or pass directly the `<i>` html instead.
```
=> Introduce parse_icon method.

phpstan-baseline.neon, psalm-baseline.xml, src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, tests/Admin/AdminTest.php, tests/Fixtures/Admin/CommentAdmin.php
Closes https://github.com/sonata-project/SonataAdminBundle/pull/6007
I rebased and reacting to this comment: https://github.com/sonata-project/SonataAdminBundle/pull/6007#discussion_r560753114, I added an exception is we're calling `getParentAssociationMapping` for an admin without Parent. The check `isChild()` must be used.
```markdown
- `AbstractAdmin::addParentAssociationMapping()` method.
- Calling `AdminInterface::setParent()` without second argument.
- Calling `AdminInterface::getParentAssociationMapping()` for a non parent admin.
```
=> Make setParent consistent with addChild

src/Resources/public/Admin.js
I am targeting this branch, because patch.
Closes #7250.
```markdown
- Filters are correctly updated if only default values are submitted.
```
=> Simulate a reset of filters if no values are different from the default ones

src/Admin/AbstractAdmin.php
I'd like to add a deprecated annotation to the `AbstractAdmin` `validate()` method. This method was already planned to be removed in 4.0, but the code/comments do not point the developer into  the right direction. Today was the second time I started a Google search to the correct way and ended up on outdated documentation pages and old/outdated GH issues and had to continue searching for the right solution. I know this very small change will help future me a lot 😄 
I am targeting this branch, because this is the branch where the `validate()` method was set to be removed.
```markdown
- Added deprecated annotation to AbstractAdmin validate() method.
```
=> Add deprecated annotation to AbstractAdmin validate() method

docs/reference/action_list.rst, docs/reference/search.rst, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataAdminExtension.php, src/Resources/config/core.php, src/Search/SearchHandler.php, src/Search/SearchableFilterInterface.php, tests/Search/SearchHandlerTest.php
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1467
Introducing this interface could allow to configure directly in the filter if he should be used for the global search or not.
We need to discuss about the issue https://github.com/sonata-project/SonataAdminBundle/issues/7274 now ; since if wanted we might add a method to the interface in order to change the line 
```
$filter->setOption('case_sensitive', $this->caseSensitive); 
```
to 
```
$filter->setCaseSensitive($this->caseSensitive); 
```
This way we do not need to know the name of the case_sensitive option.
But I'm not sure we want to keep an half-working case_sensitive option, already renamed to force_case_insensitivity by @phansys in one persistence bundle (and I don't know if a case_sensitive option …
=> Use a SearchableFilterInterface instead of a global_search option.

src/Datagrid/Datagrid.php, src/FieldDescription/FieldDescriptionCollection.php, tests/Datagrid/DatagridTest.php, tests/FieldDescription/FieldDescriptionCollectionTest.php
I consider as BC the exception added because the code were already failing somewhere if an extra key were added.
Also, if I already have three fields `foo`, `bar`, `baz` and I call reorder(['baz', 'bar']), the current behavior is setting `foo` last. Do you agree with this or should we throw an exception if all the keys are not passed ? @sonata-project/contributors 
```markdown
- `FieldCollection::reorder()` and `Datagrid::reorderFilter()` methods.
```
=> Improve reorder methods.

docs/reference/security.rst
Fix some minor issues related to RST syntax.
These errors showed when building Sonata docs. It's because RST is very strict with links/references, which use the `_` (e.g. `ROLE_APP_ADMIN_FOO_{PERMISSION}` is considered like a link `ROLE_APP_ADMIN_FOO_` followed by some text `{PERMISSION}`)
```
/!\ Found invalid reference "ROLE_APP_ADMIN_FOO" in file "reference/security"
/!\ Found invalid reference "ROLE_MY_BLOG_ADMIN_FOO_BAR" in file "reference/security"
```
=> [Doc] Fix minor RST syntax issue

src/Builder/AbstractFormContractor.php, tests/Admin/AdminTest.php, tests/App/config/services.yml, tests/Builder/AbstractFormContractorTest.php
This fixes issue https://github.com/sonata-project/SonataAdminBundle/issues/7268 by resolving parent form types 
Closes https://github.com/sonata-project/SonataAdminBundle/issues/7268
```markdown
- not passing argument 2 of `Symfony\Component\Form\FormRegistryInterface` to `AbstractFormContractor::__construct`
- default options are added correctly to form types that use the Symfony way of extending Sonata's default types
```
=> fix issue 7268 by checking Symfony form type inheritance

src/Resources/views/CRUD/base_edit_form.html.twig
When you want to override a button label, or changing some design, you currently have to override the whole form actions, and copy paste all the logic.
With these new blocks, you can now override only one button without taking care bout the logic behind.
WDYT ?
```markdown
- New `block` twig in order to override the button display by the admin in the base_edit_form.
```
=> Easier way to override button

src/Security/Handler/RoleSecurityHandler.php, tests/Security/Handler/RoleSecurityHandlerTest.php
Closes #5992
Prior to this, when using isGranted with something like `ROLE_USER` it was transformed to `ROLE_FOOADMIN_ROLE_USER`, which feel really unnatural and buggy.
Now,
- if we pass the full role, no prefix is added
- if we pass a string not starting by `ROLE`, the prefix is added.
```markdown
- Added support for non admin prefixed `ROLE_*` roles by the RoleSecurityHandler.
```
=> Support custom role with RoleSecurityHandler

docs/reference/form_types.rst, src/Action/RetrieveAutocompleteItemsAction.php, tests/Action/RetrieveAutocompleteItemsActionTest.php
I am targeting this branch, because it's a BC-break but since it can't work like this, we can consider this as a bugfix.
Closes #7298.
```markdown
- `response_item_callback` callback signature.
- `response_item_callback` option of ModelAutocompleteFilter.
```
=> Stop using response_item_callback param 3 as reference

src/Action/SearchAction.php, src/Resources/config/actions.php, tests/Action/SearchActionTest.php
BC
Closes: #7168
```markdown
- Passing `admin` in the request of search action.
```
=> Deprecate ajax call to search action

src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig, src/Resources/views/CRUD/base_edit_form.html.twig, src/Resources/views/CRUD/base_edit_form_macro.html.twig, src/Resources/views/CRUD/base_list.html.twig, src/Resources/views/CRUD/base_show.html.twig, src/Resources/views/CRUD/base_show_macro.html.twig, src/Resources/views/CRUD/dashboard__action.html.twig, src/Resources/views/CRUD/dashboard__action_create.html.twig
I added the `is defined` check every time it's not a getter, (and we have a `??` check in the next line).
Close #7324
Close #7318
```markdown
- Accessing on non existent array keys `translation_domain`
```
=> Add defined check for translation_domain property

src/Action/SetObjectFieldValueAction.php
Because of the weak comparison, if we try to update a choice list field
with a value of 0, it is considered as a violation.
I am targeting this branch, because: https://github.com/sonata-project/SonataAdminBundle/pull/7289#issuecomment-882569519.
Closes #5231.
```markdown
- Crash on choice field inline edition with a 0 value
```
=> fix(x-editable): choice value update crash with 0 value

src/Command/QuestionableCommand.php
When running phpstan-strict on master, I have an issue because we're using the `askConfirmation` return value as a boolean.
The phpdoc is saying string but I think it's a boolean instead.
Pedantic I would say.
=> Fix phpdoc

src/FieldDescription/FieldDescriptionInterface.php, tests/Menu/Provider/GroupMenuProviderTest.php
phpstan doesn't support `array{foo: bar}&array<string, mixed>`
=> Fix static analysis

src/Filter/Filter.php, src/Search/ChainableFilterInterface.php
This is consistent with all the getter with hasser of the admin.
And solve static analysis issue from https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1483
=> Make getPreviousFilter non nullable to be consistent

src/Controller/CRUDController.php, src/Resources/views/CRUD/delete.html.twig, tests/Controller/CRUDControllerTest.php
The `redirectTo` method rely on the name of the button, so I did the same for the deleteAction.
For the check on the request method, I added `POST` to support project without `http_override_method`.
Closes #7346.
```markdown
- Support for POST request to deleteAction.
```
=> Make DeleteAction compatible with POST action

src/Resources/views/Form/form_admin_fields.html.twig
I'm testing v4/master on one of my apps and I noticed that https://github.com/sonata-project/SonataAdminBundle/pull/7330 broke some select2 choice fields for me.
For example I have this field:
```php
->add('planDiscount', ChoiceType::class, [
'label' => 'Discount',
'choices' => [
'10% (for two packages purchased)' => 10,
'15% (for three packages purchased)' => 15,
],
'required' => false,
'placeholder' => 'no discount',
])
```
Without this fix the empty option is not available and on page load always the first value is selected although on the persisted model its an empty value. 
I tested it and for me it works fine now.
On page load with empty value on model:
On page load with 10% persisted on model:
ping @willemverspyck does this look good to you?
I am targeting this branch, because its …
=> fix select2 placeholder html

src/Admin/AbstractAdmin.php, src/Admin/AdminInterface.php, tests/Admin/AdminTest.php
This way the signature is more similar to the request.
```markdown
- Added second parameter to `AdminInterface::getPersistentParameter()`
```
=> Add `default` parameter to getPersistentParameter

phpstan-baseline.neon, src/Action/RetrieveAutocompleteItemsAction.php, tests/Action/RetrieveAutocompleteItemsActionTest.php
Closes #7359.
```markdown
- `RetrieveAutocompleItemsAction` when used with an array of property
```
=> Fix RetrieveAutocompleteItemsAction for multiple properties

UPGRADE-3.x.md, docs/cookbook/recipe_decouple_crud_controller.rst, src/ArgumentResolver/AdminValueResolver.php, src/DependencyInjection/SonataAdminExtension.php, src/Request/ParamConverter/AdminParamConverter.php, src/Resources/config/core.php, src/Resources/config/param_converter.php, tests/App/Admin/AdminAsParameterAdmin.php, tests/App/AppKernel.php, tests/App/Controller/AdminAsParameterController.php, tests/App/Controller/InvokableController.php, tests/App/config/services.yml, tests/ArgumentResolver/AdminValueResolverTest.php, tests/DependencyInjection/SonataAdminExtensionTest.php, tests/Functional/Controller/AdminAsParameterControllerTest.php, tests/Request/ParamConverter/AdminParamConverterTest.php
Instead of relying on `SensioFrameworkExtraBundle` `ParamConverter` feature, we can do the same thanks to value resolvers: https://symfony.com/doc/4.4/controller/argument_value_resolver.html and remove the dependency of that bundle.
This would only affect to people using `@ParamConverter` annotation, for those type-hinting with the admin classes should work as it was.
```markdown
- Deprecated using `@ParamConverter` annotation for injecting admin services
```
=> Deprecate the use of ParamConverter in favor of argument resolver

src/ArgumentResolver/AdminValueResolver.php, src/Request/AdminFetcherInterface.php, tests/ArgumentResolver/AdminValueResolverTest.php
I am targeting this branch, because bugFix.
When the admin fetcher has no sonata_code it throws an exception so does the valueResolver.
The value resolver should catch everything instead.
```markdown
- Do not throw error when trying to inject an admin as a service in an action.
```
=> Do not throw error on invalidArgument

src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
Select 2 is was not using the selected locale on the ModelAutocomplete
I am targeting this branch, because it is a bug fix.
```markdown
- Make Select2 use the locale.
```
=> Use locale for Select2

docs/cookbook/recipe_sortable_listing.rst, docs/getting_started/installation.rst, docs/reference/action_list.rst, docs/reference/advanced_configuration.rst, docs/reference/dashboard.rst, docs/reference/events.rst, docs/reference/form_types.rst, docs/reference/security.rst
Link need to be updated when merging into 4.x
=> Update doc url

src/Resources/views/CRUD/base_show_compare.html.twig
I am targeting this branch, because the bug was introduced on this branch.
```markdown
- Display of the `base_show_compare` template 
```
=> Fix variable name

src/Block/AdminSearchBlockService.php, src/Resources/public/css/layout.css, src/Resources/views/Block/block_search_result.html.twig
This is a hotfix to make the search useable again if you have cascaded search filters.
```php
protected function configureDatagridFilters(DatagridMapper $filter): void
{
$filter
->add('addresses.city')
;
}
```
The following code needs some rework to make the feature useable again:
```twig
{% set match = name|split('.')|reduce((carry, v) => carry ? attribute(carry, v) : null, result) %}
```
I am targeting this branch, because #7005 break the search result.
```markdown
- Information about the matching filters in the search results, because it does not work for cascaded oneToMany filters.
```
=> Revert: Show matching filters in search results

src/Model/AuditReaderInterface.php, src/Model/Revision.php, tests/Fixtures/Model/AuditReader.php
I am targeting this branch, because the return type from `findRevision` is the only BC-break and 
- not a lot of people will implement `AuditReaderInterface`, it's already implemented in DoctrineORMAdmin
- the return type still need to be added from 3.x to 4.x
We might improve the getter `getRev` to `getId`, but I keep it like that for now in order to make the upgrade easier.
Closes #6279.
```markdown
- `Revision` class
- `AuditReaderInterface::findRevision()` return type
```
=> Add Revision class

src/Admin/AbstractAdmin.php, src/Admin/AdminHelper.php, src/Admin/AdminInterface.php, src/Form/FormMapper.php, src/Show/ShowMapper.php, tests/Admin/AdminHelperTest.php, tests/Form/FormMapperTest.php
I just encounter this bug, it was introduced in 4.x.
The Admin keep a reference of FieldDescriptions using the name as key for every Mapper, also the FormMapper since 4.x. 
In 3.x it was using the formBuilder field name, so the sanitize name. So now, when a field `foo.bar` is added
- The fieldDescription is named `foo.bar`
- The fieldDescription is added to the admin with the key `foo.bar`
- The formBuilder is added with the name `foo__bar`
- The group is added with a reference to both value.
But the AdminHelper, try to find the fieldDescription from the admin with the name of the formBuilder, which is not possible anymore. Since the formBuilder has an option `sonata_field_description`, it should be prefer instead, it avoid to compute back the name of the field description.
Also, for the …
=> Fix collection type with nested field 

src/DependencyInjection/SonataAdminExtension.php
Closes #7097
```markdown
- Fail fast when using ACL as security handler without security.acl.provider service
```
=> Fail fast if using ACL and the service security.acl.provider is missing

src/Form/Type/Filter/FilterDataType.php, src/Resources/views/CRUD/batch_confirmation.html.twig
I am targeting this branch, because bug fix.
When we render FilterDataType in the datagrid we only use form_widget, so the label is not needed.
When we render it in the batch confirmation page we render everything in display none, so the label are translated.
This PR solve this.
This solve half of the issue #4069, I don't know if we want to do more for this issue.
In order to use `HiddenType` in the batch confirmation we need to change
```
foreach ($this->getFilters() as $filter) {
[$type, $options] = $filter->getRenderSettings();
$this->formBuilder->add($filter->getFormName(), $type, $options);
}
```
to
```
foreach ($this->getFilters() as $filter) {
$this->formBuilder->add($filter->getFormName(), HiddenType::class);
}
```
This means we need a different method to get the Form, and to get …
=> Avoid missing translation on batch confirmation

src/Security/Handler/AclSecurityHandler.php, src/Security/Handler/AclSecurityHandlerInterface.php, src/Util/AdminAclManipulator.php, src/Util/AdminAclManipulatorInterface.php, src/Util/ObjectAclManipulator.php, tests/Util/ObjectAclManipulatorTest.php
I take a look at https://github.com/sonata-project/SonataAdminBundle/issues/4925, and saw that multiple method were passing both the securityHandler and the `securityInformation` from this securityHander. This seems wrong to me
- The method could have the need to access to the Admin (don't know if it will be needed for the bugFix, but if it does and we discover it after the stable release, the BC-break won't be possible).
- Those method could been call with a securityHandler and securityInformation from another securityHandler ; which makes no sens.
```markdown
- `AclSecurityHandlerInterface::addObjectClassAces()` signature
- `AclSecurityHandler::addObjectClassAces()` signature
- `AdminAclManipulator::addAdminClassAces()` signature
- `AdminAclManipulatorInterface::addAdminClassAces()` …
```
=> Improve signature of method using securityInformation

UPGRADE-4.0.md, docs/reference/configuration.rst, docs/reference/security.rst, src/Admin/AbstractAdmin.php, src/Admin/AccessRegistryInterface.php, src/DependencyInjection/Configuration.php, src/Security/Acl/Permission/AdminPermissionMap.php, src/Security/Acl/Permission/MaskBuilder.php, tests/Controller/CRUDControllerTest.php, tests/Security/Acl/Permission/AdminPermissionMapTest.php, tests/Util/AdminObjectAclDataTest.php
I am targeting this branch, because there is no real BC way to do it.
It will be a BC-break only for revisions users (with EntityAuditBundle).
Closes #7444.
```markdown
- New role `ROLE_MYADMIN_HISTORY` to access to the history actions
- `AbstractAdmin::getAccessMapping` visibility
- Access to the history actions with the role `ROLE_MYADMIN_EDIT` 
- `AdminInterface::getAccessMapping` method
```
=> Introduce HISTORY role

src/FieldDescription/BaseFieldDescription.php, tests/FieldDescription/BaseFieldDescriptionTest.php
Pedantic.
When using the `foo.bar` field on the `BazAdmin`, the message is 
"Cannot access 'foo.bar' on `Bar`", instead of "Cannot access 'foo.bar' on `Baz`"
=> Fix error message

src/Admin/AbstractAdmin.php, src/Controller/CRUDController.php, tests/App/AppKernel.php, tests/Fixtures/StubFilesystemLoader.php, tests/Functional/Controller/AdminAsParameterControllerTest.php, tests/Functional/Controller/CRUDControllerTest.php
Fixes some of the deprecations shown in https://github.com/sonata-project/SonataAdminBundle/pull/7486
```markdown
- Deprecations triggered with Symfony 5.4
```
=> Fix some Symfony 5.4 deprecations

src/Admin/AbstractAdmin.php
This PR fixes an issue where `configureActionButtons` are not called in custom actions.
```markdown
- Issue where `configureActionButtons()` is not being called in custom actions.
```
=> Allow configured action buttons
